### ISSUE TITLE
multiple via doesn't populate array properly

### ISSUE THREAD

**Issue by kiuka** [yiisoft/yii2#13092] opened 2016-11-29 13:34 UTC
### What steps will reproduce the problem?
table structure:
`        $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';

        $this->createTable('category', [
            'id' => $this->primaryKey(),
        ], $tableOptions);

        $this->createTable('tag', [
            'id' => $this->primaryKey(),
            'category_id' => $this->integer()->notNull(),
        ], $tableOptions);

        $this->createTable('case_study', [
            'id' => $this->primaryKey(),
        ], $tableOptions);

        $this->createTable('case_study_tag', [
            'case_study_id' => $this->integer()->unsigned()->notNull(),
            'tag_id' => $this->integer()->unsigned()->notNull(),

            'PRIMARY KEY(case_study_id, tag_id)'
        ], $tableOptions);
`

models\Category

`
    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['category_id' => 'id']);
    }

    public function getCaseStudies()
    {
        return $this->hasMany(CaseStudy::class, ['id' => 'case_study_id'])
            ->via('caseStudyTags');
    }

    public function getCaseStudyTags()
    {
        return $this->hasMany(CaseStudyTag::class, ['tag_id' => 'id'])
            ->via('tags');
    }

   // request categories with case studies
  $items = Category::find()->with('caseStudies');
`

### What is the expected result?
it should populate case studies

### What do you get instead?
return an empty array or only the first matched item

### Additional info
it query the items from the database, but the active model doesn't populate the array properly.

I found out that the problem is somewhere here (I guess it should hit the if case, not the else - but this statement isn't statisfied: is_array($keys = $primaryModel[reset($link)])):
https://github.com/yiisoft/yii2/blob/master/framework/db/ActiveRelationTrait.php#L270

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.24
| Operating system | Windows

**Comment by cebe** [comment] 2016-11-29 13:39
on a quick look this looks like a duplicate of #5341.

**Comment by samdark** [comment] 2016-11-29 13:40
Indeed.

**Closed by samdark** 2016-11-29 13:40 UTC
Labels: feature:db

**Comment by kiuka** [comment] 2016-11-29 13:41
yeah, it seems the same, thanks:)
