### ISSUE TITLE
ActiveQuery and Aliases

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#14166] opened 2017-05-16 12:27 UTC
1 The alias **must** previous to all assoc columns if Alias is set; 
2 In the joinWith the alias **must** be set too (default is a key of array)

### What steps will reproduce the problem?
```php
class Duration extends \yii\db\ActiveRecord {
...
    public function getUnit()
    {
        return $this->hasOne(DurationUnit::className(), ['id' => 'unitId'])->inverseOf('durations');
    }
...
}
```
```php
        echo Duration::find()
            ->joinWith([
                'unit as unitAlias' => function (DurationUnitQuery $query) {
                    $query->andWhere(['id' => [5, 3, 2, 1]]);
                }
            ])
            ->andWhere(['id' => [4, 5, 9]])
            ->alias('durationAlias')
            ->createCommand()->getRawSql();
```
### What is the expected result?
```SQL
SELECT `durationAlias`.* FROM `duration` `durationAlias` LEFT JOIN `duration_unit` `unitAlias` ON `durationAlias`.`unitId` = `unitAlias`.`id` WHERE (`durationAlias`.`id` IN (4, 5, 9)) AND (`unitAlias`.`id` IN (5, 3, 2, 1))
```
### What do you get instead?
```SQL
SELECT `durationAlias`.* FROM `duration` `durationAlias` LEFT JOIN `duration_unit` `unitAlias` ON `durationAlias`.`unitId` = `unitAlias`.`id` WHERE (`id` IN (4, 5, 9)) AND (`id` IN (5, 3, 2, 1))

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 44fa97f1d66ecc8c8851cc3787f4432f1e8eb0ad
| PHP version      | 7.15
| Operating system |Debian/Alpine/other

**Comment by bscheshirwork** [comment] 2017-05-16 12:34
`Where` `condition` must be processed with this function;

https://github.com/bscheshirwork/yii2/blob/184f6d385bd1a7eb3e5216774a3a9783978b3760/framework/db/ActiveQuery.php#L800-L814

**Comment by cebe** [comment] 2017-05-16 12:37
duplicate of #7263

**Closed by cebe** 2017-05-16 12:37 UTC
