### ISSUE TITLE
Different database connection used in the application and in Codeception functional tests

### ISSUE THREAD

**Issue by ivokund** [yiisoft/yii2#9852] opened 2015-10-08 05:32 UTC
Hi,

I have about 60 functional Cest test files that test various REST API endpoints, sometimes creating new data, sometimes updating existing fixtures etc. Everyting is fine, except I noticed that the tests have started affecting each other. The success of test A depends on test B being run before it. So it would really help if I could clear/rollback my database after each test to make the tests truly independent.

I'm trying to use the `cleanup: true` attribute in Codeception Yii2 module configuration, but it seems that the rollback in Yii2 Codeception module is done on a different connection (`SELECT CONNECTION_ID()` is different) than the one used inside the application. So basically the rollback in Codeception Yii2 module has no effect on the changes done in my REST actions. 

Is this behaviour correct? And if yes, then is there a way to rollback database changes (done in the app) after each Cest file?

Using Yii2 v2.0.3, Codeception v2.0.11, yii2-codeception v2.0.3

Thanks a lot!

**Comment by samdark** [comment] 2015-10-08 09:36
Try updating first.

**Comment by ivokund** [comment] 2015-10-09 07:05
Confirmed with Codeception 2.1.x-dev, Yii2 dev-master (e6d4667), Yii2-codeception dev-master (d2c91b5a).

`SELECT CONNECTION_ID()` returns a different ID inside `\Codeception\Module\Yii2::_after` (before rollback is done) and in my Action. Thus, the transaction being rolled back (in the module) is not the one that really contained anything. Everything done inside my actions gets still written in the database and stays there right until the fixtures get unloaded in the end. 

Perhaps things get more complicated because I use Codeception REST module with Yii2 connector?

**Comment by ivokund** [comment] 2015-10-12 09:38
I noticed that during the running of my tests, several calls were made to `\yii\db\Connection::initConnection` resulting in in different connections and connection ID-s used throughout my tests. I have pasted traces of the first 3 calls here:

https://gist.github.com/ivokund/e8dbb1c94675cd33fe82
https://gist.github.com/ivokund/e18f49ccaaa58e47cd4c
https://gist.github.com/ivokund/cf1b864cfe828b7437da

Perhaps this is of some help.

**Comment by ivokund** [comment] 2015-10-13 07:53
The only way I've found for achieving this is to modify the Yii2 Codeception connector (`\Codeception\Lib\Connector\Yii2`) like this

```php
    public static $db; // remember the db instance

    public function startApp()
    {
        $config = require($this->configFile);
        if (!isset($config['class'])) {
            $config['class'] = 'yii\web\Application';
        }
        /** @var \yii\web\Application $app */
        $app = Yii::createObject($config);
        if (isset(static::$db)) { // if db instance is set, use it
            $app->set('db', static::$db);
        } else {
            static::$db = $app->get('db'); // create the singleton db instance
        }
        return $app;
    }
```
Is there a better way of doing this without modifying codeception code?

@samdark @qiangxue can you please comment on this? Is what I'm trying to achieve sensible and is this a bug or not? Thanks

**Comment by samdark** [comment] 2015-10-13 09:06
Modifying codeception code is OK. You can make a pull request and I'll merge it. The question is about if it's connector issue or normal REST module behavior.

**Comment by ivokund** [comment] 2015-10-13 11:36
@samdark is there anyone who knows and could confirm this? :)

**Comment by samdark** [comment] 2015-10-13 11:43
Probably @Ragazzo or @DavertMik (if it's Codeception REST module expected behavior).

**Comment by Ragazzo** [comment] 2015-10-13 11:49
how you do rollback / delete fixtures? you can see example in `yii2-advanced` with `User::deleteAll` method, works fine

**Comment by ivokund** [comment] 2015-10-13 11:56
@Ragazzo I use global fixtures in FixtureHelper. But fixtures are not the problem. The problem is that if my test adds some data to the database (via functional tests and REST actions), then this data is not cleaned up before the next test (Cest file). 

The problem is that the "cleanup" flag does not work as expected. Nothing wrong with fixtures. 
I cannot imagine using an approach similar to `User::deleteAll`, since the changes done in actions are extensive and I cannot undo them manually. Besides, is this not what the `cleanup` flag is meant for (to undo everything in a rollback)?

**Comment by Ragazzo** [comment] 2015-10-13 12:02
The problem here that `cleanup` flag is for `Codeception` `DB` module that is not used as you can see, since it was rejected in flavor of `Yii2` fixtures since you can do everything with them, or even with `Yii::app()->db` connection.

**Comment by ivokund** [comment] 2015-10-13 12:08
But I don't even use the Db module. I mean the "cleanup" flag in the Yii2 module: https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Yii2.php#L80

Or is this not used when I use the REST module?

**Comment by Ragazzo** [comment] 2015-10-13 12:20
there is a note that if you have some operations, they can be not rollbacked depending on what RDBMS you are using, you can google this, but afaik some of them like drop, insert cant be undo for mysql, check if you have them causing your issues

**Comment by ivokund** [comment] 2015-10-13 12:31
@Ragazzo Nope, already checked. This is not caused by MySQL implicit commit. The problem is that every time `\Codeception\Lib\Connector\Yii2::startApp` is called, a new application and a new database connection is created. Every instance of `\yii\db\Connection` keeps track of its own transactions and uses a different PDO instance. 

So we have (at least) two instances of the application and the db connection:

* One is created in `\Codeception\Module\Yii2::_before` and the cleanup rollback is done on this instance
* The other is created in `\Codeception\Lib\Connector\Yii2::doRequest` (for each test). The REST module uses this connector and all the actions being run in functional tests use this application (and connection). 

This means that doing a rollback in `\Codeception\Module\Yii2` does not affect another db instance used by the connector.

**Comment by Ragazzo** [comment] 2015-10-13 12:42
Ok, can you submit patch to `Codeception`, you only need to modify client so it will hold instance of app `getApplication() if null create`, and `Yii2` module will be calling client `getApplication()` and rollback transaction on correct connection. Simple fix as you can see, will you do this?

**Comment by ivokund** [comment] 2015-10-13 13:45
I noticed that it does not work unless I call `$app->response->clear()` for each application usage (otherwise the `isSent` flag remains true in `Request` and nothing gets output). 

Is there anything else that may break and needs special handline when using the same application instance for multiple requests (e.g. sessions, DI container) ?

**Comment by Ragazzo** [comment] 2015-10-13 13:50
> I noticed that it does not work unless I call

what does not work?

> s there anything else that may break and needs special handline when using the same application instance for multiple requests (e.g. sessions, DI container) ?

application is re-created from given config each time, not sure there is anything like this, only some custom components like redis, memcached and other where similar problem can occur, if so let the developer handle it in similar way. 
@samdark your thoughts on this one?

**Comment by ivokund** [comment] 2015-10-13 13:55
> what does not work?

I meant the approach you described in https://github.com/yiisoft/yii2/issues/9852#issuecomment-147704010

I haven't pinpointed the problem yet, but it seems that the Request object needs clearing somehow as well. The first request handled is fine, but the next one has the same parameters than the first one.

**Comment by Ragazzo** [comment] 2015-10-13 14:06
> The first request handled is fine, but the next one has the same parameters than the first one.

you re-create application each time dont you? before return you can resetApplication to null and then when you call getApplication it will return new instance that will be used correctly in module too

**Comment by ivokund** [comment] 2015-10-13 14:19
This is what I did to get to where I am

```php

    private static $app; // added this to store the application instance between tests

    public function startApp()
    {
        if (!isset(static::$app)) { // added this check to NOT re-create the application again
            $config = require($this->configFile);
            if (!isset($config['class'])) {
                $config['class'] = 'yii\web\Application';
            }
            /** @var \yii\web\Application $app */
            static::$app = Yii::createObject($config);
        }
        static::$app->response->clear(); // added this to be able to send response again
        return static::$app;
    }
```

What do you mean by `resetApplication` and `getApplication` exactly?

**Comment by Ragazzo** [comment] 2015-10-13 14:30
Yii2Connector::getApplication() // if (!$this->app) {$this->app = $this->startApp()}

call `getApplication` in [line](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/Yii2.php#L78) and [line](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Yii2.php#L70)

Yii2Connector::resetApplication() // $this->app = null;

call `resetApplication` in [line](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Yii2.php#L108) and [line](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Lib/Connector/Yii2.php#L96)

This is brief scratch ofcourse, feel free to modify it correctly

**Comment by ivokund** [comment] 2015-10-13 14:44
@Ragazzo What do you mean by `resetApplication` exactly? There so such method in the Yii2 connector (`Call to undefined method Codeception\\Lib\\Connector\\Yii2::resetApplication()`).

Also, there's nothing like it in the whole Codeception repository: https://github.com/Codeception/Codeception/search?utf8=%E2%9C%93&q=resetApplication

Same with `getApplication`.

**Comment by Ragazzo** [comment] 2015-10-13 14:53
as you can see after `//` i proposed their implementation, as was said those method could be a part of the patch to solve this problem, we only need to ensure that module and connector operate via same application instance during request, this patch helps to do it. Add those methods as i described, will see if it helps

**Comment by ivokund** [comment] 2015-10-13 16:13
Ok :) Although I cannot see right now how setting the app to null after each `doRequest` could help, since the initial problem with this issue was that the database connection gets reset and it shouldn't. 

But I'll try and get back to you!

**Comment by Ragazzo** [comment] 2015-10-14 06:49
the initial problem is that in `doRequest` application is recreated and differs from one that holds in `Yii2` module, by saving it in `Yii2` connector we will be sure that it is the same instance, after each doRequest it will be reset, and in `_before` it will be created, thus it will be the same connection

**Comment by ivokund** [comment] 2015-10-14 07:44
I've currently run out of time dealing with this. 

On a related matter: it seems that PUT requests end up empty in `Request::getBodyParams()` unless `$yiiRequest->setBodyParams($_POST);` is called in Yii2 connector (right after `$yiiRequest->setRawBody($request->getContent());`)

 I'll get back to it when I can.

**Comment by Ragazzo** [comment] 2015-10-14 08:01
Ok

**Comment by ivokund** [comment] 2015-10-15 13:11
@Ragazzo @samdark Ok, I think I got everhything to work, but I had to also make changes to Yii code, and change a lot more than what we talked about. If you can confirm that that's the correct way of doing this, I'll make pull requests to the official Yii2 and Codeception repositories.

**Changes in Codeception**
You can see the propsed changes in my fork: https://github.com/ivokund/Codeception/pull/1/files

**Changes in `yii\web\Request`**
Did not make a pull request yet, but this is what needs to be changed

* Changed `setPathInfo` from [this](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L675) to this. Otherwise we cannot set the pathInfo to null. 

```php
    public function setPathInfo($value)
    {
        $this->_pathInfo = $value !== null ? ltrim($value, '/') : null;
    }
```
* Added this method to be able to reset headers
```php
    /**
     * @param array|HeaderCollection|null $headers
     */
    public function setHeaders($headers)
    {
        if (is_array($headers)) {
            $this->getHeaders()->fromArray($headers);
        } else {
            $this->_headers = $headers;
        }
    }
```

If you have a better way of reusing or re-creating the Request object without all this reset functionality, I'm all ears :)

**Comment by Ragazzo** [comment] 2015-10-15 14:36
you do not reset application [here](https://github.com/ivokund/Codeception/blob/bugfix/yii2-problems/src/Codeception/Lib/Connector/Yii2.php#L138) it is needed, thus clearing some params is not needed

**Comment by ivokund** [comment] 2015-10-15 17:58
But we cannot reset the application after each request. After every reset we create a new database connection (with the next application instance), but all the requests (sendPOST, sendPUT, etc) have to be made on the same database connection (meaning also on the same application instance). Otherwise the rollback in Yii2 module's application will not work. This is the main problem I started with (see comment https://github.com/yiisoft/yii2/issues/9852#issuecomment-146774038)

If we reset the application after each request, this would happen: 

* Module creates the first application A (returned from connector)
* Module starts a transaction on connection A ("db" instance from application A)
* Yii2 Connector is used to execute a sendPOST request. Application A already exists, so data is inserted over connection A 
* Say we reset the connection now. Reference to application A is deleted from connector, but stays there in the module
* Another request is made within the same test. Connector creates application B and a new database connection B
* Data is inserted over connection B
* Test ends and module rolls back connection A. This does nothing to the data inserted over connection B in application B

I guess an alternative would be just to cache the database connection instance like explained here - https://github.com/yiisoft/yii2/issues/9852#issuecomment-147634881 - but there could be other problems waiting with this approach.

**Comment by Ragazzo** [comment] 2015-10-15 18:02
i think we can reset application in module `_after` instead of before `return`

**Comment by ivokund** [comment] 2015-10-15 18:06
What would this accomplish? We would still need all the hacking around with the Request object I have done,

**Comment by Ragazzo** [comment] 2015-10-15 18:08
Ok, lets stop for a while, i will take a close look on this one on weekend

**Comment by ivokund** [comment] 2015-10-16 07:11
I figured out one other possible solution that requires much less work and no changes in Yii2 code. It's a hybrid of my initial solution https://github.com/yiisoft/yii2/issues/9852#issuecomment-147634881 and yours https://github.com/yiisoft/yii2/issues/9852#issuecomment-147732535. 

Basically we do the getApplication and resetApplication approach plus we cache the DB instance so the connection isn't created again for each request.  

See commit: https://github.com/ivokund/Codeception/commit/36e637f6c6723c431ad604da9ea00436d76e3114

But take your time and let me know what you think. I'm OK with continuing next week. Thanks!

**Comment by ivokund** [comment] 2015-10-23 05:58
@Ragazzo have you had any chance to look at this?

**Comment by Ragazzo** [comment] 2015-10-23 06:22
sorry, did not, can we postpone it to saturday? i think i will have free time tomorrow

**Comment by ivokund** [comment] 2015-10-23 06:47
Sure, tomorrow would be great, thanks!

**Comment by Ragazzo** [comment] 2015-10-25 14:28
Ok, i looked through this one, yes, if fixes initial issue and can be merged, but i think we can come up with better design,  yet dont have time to propose / fix. 

@samdark please also take a look if you have any concernes

**Comment by samdark** [comment] 2015-10-26 07:10
@ivokund is the change to Codeception enough to fix the issue?

**Comment by ivokund** [comment] 2015-10-26 07:55
Yes, no changes required in Yii2. See the pull request referenced

**Comment by samdark** [comment] 2015-10-26 13:37
Can you resolve conflicts in the pull request or start off actual state of the branch?

**Comment by ivokund** [comment] 2015-10-26 13:53
Yep, sorry, my bad. Done
Any idea why AppVeyor build is failing? Seems unrelated to the issue.

**Comment by samdark** [comment] 2015-10-26 14:25
Seems to pass connector tests. Should be good. Will merge it soon.

**Comment by ivokund** [comment] 2015-10-26 14:29
Great, thanks!

**Comment by samdark** [comment] 2015-10-26 17:59
https://github.com/Codeception/Codeception/commit/c90ace2b69ee2332740018ff0489399ed7c89ada

**Comment by samdark** [comment] 2015-10-26 17:59
Thanks!

**Closed by samdark** 2015-10-26 17:59 UTC
Labels: feature:codeception
