### ISSUE TITLE
UNIQUE INDEX (upper(name))

### ISSUE THREAD

**Issue by pkirill99** [yiisoft/yii2#8545] opened 2015-05-25 16:18 UTC
Hi all

I updated the yii to 2.0.4

created table and index (pgsql):
```
CREATE TABLE table (
id BIGSERIAL PRIMARY KEY
, name character varying(32) NOT NULL
);

CREATE UNIQUE INDEX ON table USING BTREE (upper(name));
```

going in gii -> model generator
```
Use Table Prefix
Generate Relations
Generate Labels from DB Comments
```

```
...
public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 32],
            [['upper(name::text)'], 'unique']
        ];
    }
...
```

test:
```
Getting unknown property: common\models\Table::upper(name::text)
```

**Comment by nineinchnick** [comment] 2015-09-28 22:06
Duplicate of #8239.

**Closed** 2015-09-29 06:04 UTC
Labels: feature:gii, status:to be verified, type:bug
