### ISSUE TITLE
Mocking new application on tests does not clear yii\base\Event::$_events

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#12440] opened 2016-09-02 14:22 UTC
### What steps will reproduce the problem?
Mock application on tests that registers some event listeners
Tear this application down
Mock a new application that registers some event listeners that does not register event listeners(or registers new ones)
Observe ```yii\base\Event::$_events```
### What is the expected result?
When old test tears down old application, it should somehow clear event listeners
### What do you get instead?
When old test tears down old application, it doesnt clear event listeners

### My thoughts
Maybe event listeners should be added to Application?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 7.0.10
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment] 2016-09-02 14:26
How do you mock it?

**Comment by klimov-paul** [comment] 2016-09-02 14:27
> it should somehow clear event listeners

No it should not.

> When old test tears down old application, it doesnt clear event listeners

This is expected behavior for any class static fields.

However, since `Event::$_events` isprivate there should be a static method allowing to clear it.

**Comment by mikk150** [comment] 2016-09-02 14:37
@klimov-paul Right now I know it shouldn't do that, there is no code that does it
Yes it is expected behavior for any static classes but it limits writing unit tests, because when one test application that registers event listeners, tests that they are ok, and tears this application down with all of its components and another test application that registers different event listeners with other components test that those other events work, but because first tests event listeners are on Event class still, they fail.
I wouldn't want to register dummy components just for those tests to pass

@samdark with ```yii\codeception\TestCase```

**Comment by klimov-paul** [comment] 2016-09-05 09:47
Resolved by commit 48b0b962b877a05420e0d88b963a322c309bd05d

**Closed by klimov-paul** 2016-09-05 09:47 UTC
Labels: type:enhancement
