### ISSUE TITLE
data-method throw exception "Uncaught expected string value for 'container' option; got object"

### ISSUE THREAD

**Issue by mirkhamidov** [yiisoft/yii2#14912] opened 2017-10-04 13:00 UTC
There is not new code, it was working like a charm, but when we updated all packages in composer it becomes with errors.
Other pjax works well, but with a link data-method we got error.

I found out, if I add `'pjax-container' => '#' . $_pjaxId,` to my link, it works well. Is its compatibility were broken and we have to add everywhere this param?

In composer `"minimum-stability": "stable",`

### What steps will reproduce the problem?
```php
<?php Pjax::begin([
    'enablePushState' => false,
    'options' => [
        'class' => 'book_action',
    ],
    'scrollTo' => false,
    'id' => $_pjaxId,
])?>
<!-- another html -->
<?= Html::a(
    UserBook::STATUS_LIST[UserBook::STATUS_FINISHED],
    ['set-book-status', 'id' => $model->primaryKey, 'status' => UserBook::STATUS_FINISHED],
    [
        'class' => 'pull-right btn-xs btn btn-bg-status-' . UserBook::STATUS_FINISHED,
        'data' => [
            'method' => 'post',
            'pjax' => true,
        ],
    ]
)?>
<!-- another html -->
<?php Pjax::end() ?>
```

### What is the expected result?
correctly sended POST request using ajax

### What do you get instead?
"Uncaught expected string value for 'container' option; got object" in console section of browser

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.0.24
| Operating system | Ubuntu 14.04.5

**Comment by samdark** [comment] 2017-10-04 14:48
Duplicate of https://github.com/yiisoft/yii2/pull/14906

**Closed by samdark** 2017-10-04 14:48 UTC
Labels: feature:pjax
