### ISSUE TITLE
cant install or update project (bower/jquerry missing)

### ISSUE THREAD

**Issue by earlcherry** [yiisoft/yii2#13454] opened 2017-01-27 07:54 UTC
Hello. Now again cant install or update  project.
`
yiisoft/yii2 2.0.10 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -no matching package found.
`
fxp/composer-asset-plugin version is 1.2.2

**Comment by cebe** [comment] 2017-01-27 08:44
what is the command you are running and what is the complete output?

**Comment by earlcherry** [comment] 2017-01-27 09:01
composer create-project --prefer-dist yiisoft/yii2-app-basic delete_me3
You are running Composer with SSL/TLS protection disabled.
Warning: Accessing packagist.org over http which is an insecure protocol.
Installing yiisoft/yii2-app-basic (2.0.10)
  - Installing yiisoft/yii2-app-basic (2.0.10) Loading from cache
Created project in delete_me3
Loading composer repositories with package information
Warning: Accessing packagist.org over http which is an insecure protocol.
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.9 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.10 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 ~2.0.5 -> satisfiable by yiisoft/yii2[2.0.10, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by rob006** [comment] 2017-01-27 10:45
Show result of `composer global show`.

**Comment by earlcherry** [comment] 2017-01-27 11:06
composer global show
Changed current directory to C:/Users/myzajtse/AppData/Roaming/Composer
You are running Composer with SSL/TLS protection disabled.
fxp/composer-asset-plugin v1.2.2 NPM/Bower Dependency Manager for Composer

**Comment by vistart** [comment] 2017-01-28 16:29
Maybe the network of bower/npm or it's CDN service is unstable, please wait for a while and try again.

**Comment by samdark** [comment] 2017-01-28 17:08
Closing since it's not reproducible so we can't fix it.

**Closed by samdark** 2017-01-28 17:08 UTC
Labels: status:need more info

**Comment by davidjeddy** [comment] 2017-06-07 15:01
@earlcherry Did you run the `composer global require "fxp/composer-asset-plugin"` to install client assets?

**Comment by pasha-pivo** [comment] 2017-06-09 07:22
Hey, guys! I am having the same issue right now. Nothing helps. I tried to remove the executable itself with the root and config folders and reinstall the composer. Tried to remove the project I want to deploy and wipe out everything relative to the composer. Still no luck.
The project was successfully deployed on another machine earlier.
Globally only `fxp/composer-asset-plugin` installed.

**Comment by pasha-pivo** [comment] 2017-06-09 07:26
Hey, guys! I am having the same issue right now. Nothing helps. I tried to remove the executable itself with the root and config folders and reinstall the composer. Tried to remove the project I want to deploy and wipe out everything relative to the composer. Still no luck.
The project was successfully deployed on another machine earlier.
Globally only fxp/composer-asset-plugin installed.

**Comment by bitsnaps** [comment] 2017-07-03 10:20
I guess the reason is there was an old version of composer, you need to update it or fix the old one by adding the missing plugin: "fxp/composer-asset-plugin" as @davidjeddy says.

**Comment by pasha-pivo** [comment] 2017-07-03 12:05
No, that was because of broken dependencies. It was quickly fixed.
Here is the thread about this issue #14275

**Comment by vercotux** [comment] 2017-08-14 13:52
So where are bower assets supposed to be now? `vendor/bower-asset` or `vendor/bower`?

**Comment by davidjeddy** [comment] 2017-08-14 15:52
@vercotux Yii 2.0.12 has them in `./vendor/bower`  by default.

**Comment by vercotux** [comment] 2017-08-14 17:04
@davidjeddy I'm using 2.0.12 and it puts them in `vendor/bower-asset`.

**Comment by cebe** [comment] 2017-08-14 17:21
that does not depend on the Yii version but on the configuration in application template.

**Comment by vercotux** [comment] 2017-08-15 03:25
@cebe I thought so. I assume it mostly depends on the `fxp/composer-asset-plugin` version which configures your project when you run `composer create-project`. I reckon it calls some composer-triggered scripts? Is there any way to re-do that step once we've already created the project?

**Comment by cebe** [comment] 2017-08-17 13:59
Make sure composer config and application aliases match:

- https://github.com/yiisoft/yii2-app-basic/blob/2f2e2506c68080a60dc3f7d488ba30938aefbbc3/composer.json#L31-L39
- https://github.com/yiisoft/yii2-app-basic/blob/2f2e2506c68080a60dc3f7d488ba30938aefbbc3/config/web.php#L10-L13
