### ISSUE TITLE
Unexpected behavior on ajaxValidation when prettyUrl = false

### ISSUE THREAD

**Issue by nevermnd** [yiisoft/yii2#11727] opened 2016-06-08 15:13 UTC
### What steps will reproduce the problem?
Create an ActiveForm with `ajaxValidation` set to true, method `GET` and a custom `validationUrl`.

### What is the expected result?
ActiveForm should call the custom `validationUrl` uppon ajax validation.

### What do you get instead?
ActiveForm triggers an an ajax validation request to the form url.

### Additional info
The hidden field with the current route added to the form overrides the `validationUrl`.

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      |  5.6.22
| Operating system | Fedora 23

**Comment by cebe** [comment] 2016-06-08 16:38
can you post the code that calls ActiveForm::begin()?

**Comment by nevermnd** [comment] 2016-06-08 16:44
Sure.

```php
$form = ActiveForm::begin([
    'action' => ['create'],
    'successCssClass' => '',
    'method' => 'get',
    'enableAjaxValidation' => true,
    'validationUrl' => ['validate'],
    'validateOnChange' => false,
    'validateOnBlur' => false
]);
```

**Comment by nevermnd** [comment] 2016-06-08 17:38
Probably related to #11691.

**Comment by lynicidn** [comment] 2016-06-10 15:27
https://github.com/yiisoft/yii2/issues/10681#issuecomment-223753843

**Comment by lynicidn** [comment] 2016-06-10 15:28
https://github.com/yiisoft/yii2/issues/9535

**Comment by lynicidn** [comment] 2016-06-10 15:28
validation in 2.0.7. will break

**Comment by lynicidn** [comment] 2016-06-11 14:04
check this code https://github.com/yiisoft/yii2/pull/11743

**Comment by nevermnd** [comment] 2016-06-14 00:17
#11743 Is not enough to solve this issue.

**Comment by nevermnd** [comment] 2016-06-14 01:02
I manage to get around this problem by deleting the `routeParam` from the serialized form data before triggering the ajax request. 

```js
// yii.activeForm.js

var dataToSubmit = $form.serializeArray();
$.each(dataToSubmit, function (index, object) {
    // delete route param
    if (object.name == 'r') delete dataToSubmit[index];
});
dataToSubmit.push({name: data.settings.ajaxParam, value: $form.attr('id')});
// do ajax request ...
```
Couldn't think of a better solution.

**Comment by samdark** [comment] 2016-07-01 23:00
Please check if the issue is solved by https://github.com/yiisoft/yii2/commit/e8bcb93507a7859f2a5115ec2179182353e9cc04

**Comment by lynicidn** [comment] 2016-07-02 00:31
@samdark здесь проблема в скрытом филде формы, она зачемто роут тоже делает скрытым
т.е. если выключен чпу, то роут "?r=test" попадает скрытым филдом в форму, и соответственно при сериализации он перекрывает установленный validationUrl
подробнее описал тут https://github.com/yiisoft/yii2/issues/11691

@nevermnd you can use prettyUrl - it solve problem with hidden field "r" of form (from request url)

**Comment by samdark** [comment] 2016-07-02 16:10
Duplicate of #11691

**Closed by samdark** 2016-07-02 16:10 UTC
Labels: severity:important, status:to be verified
