### ISSUE TITLE
Yii::$app->db->getLastInsertID() throw error when using PostgreSQL DB

### ISSUE THREAD

**Issue by fproject** [yiisoft/yii2#9087] opened 2015-07-13 04:18 UTC
This error is found in Yii 2.0.4

I have a table warning_register_id_seq sequence in schema sys.
The following code throw an PDOException:

`Yii::$app->db->getLastInsertID("sys.warning_register_id_seq");`

In this case, the method `quoteSimpleTableName` of `yii\db\Schema` class add a quote around the sequence name, which causes the error. The command `Yii::$app->db->pdo->lastInsertId("sys.warning_register_id_seq")` is run without any error.

The PDOException stack trace is:

```
exception 'PDOException' with message 'SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "sys.warning_register_id_seq" does not exist' in F:\GitRepo\apom-api\vendor\yiisoft\yii2\db\Schema.php:351
Stack trace:
#0 F:\GitRepo\apom-api\vendor\yiisoft\yii2\db\Schema.php(351): PDO->lastInsertId('"sys.warning_re...')
#1 F:\GitRepo\apom-api\vendor\yiisoft\yii2\db\Connection.php(720): yii\db\Schema->getLastInsertID('sys.warning_reg...')
#2 F:\GitRepo\apom-api\vendor\fproject\yii2-restx\fproject\components\DbHelper.php(135): yii\db\Connection->getLastInsertID('sys.warning_reg...')
#3 F:\GitRepo\apom-api\vendor\fproject\yii2-restx\fproject\rest\BatchSaveAction.php(65): fproject\components\DbHelper::batchSave(Array, Array)
#4 [internal function]: fproject\rest\BatchSaveAction->run()
#5 F:\GitRepo\apom-api\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array)
#6 F:\GitRepo\apom-api\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array)
#7 F:\GitRepo\apom-api\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('batch-save', Array)
#8 F:\GitRepo\apom-api\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('warning-registe...', Array)
#9 F:\GitRepo\apom-api\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#10 F:\GitRepo\apom-api\web\index.php(12): yii\base\Application->run()
#11 {main}
```

**Comment by nineinchnick** [comment] 2015-07-13 04:54
Duplicate of #8483 which has already been fixed but waits for next realease.

**Closed** 2015-07-13 06:26 UTC
