### ISSUE TITLE
Markup bug at yii\helpers\BaseHtml page

### ISSUE THREAD

**Issue by alexstulov** [yiisoft/yii2#17842] opened 2020-01-31 10:38 UTC
### What steps will reproduce the problem?

1. Go to https://www.yiiframework.com/doc/api/2.0/yii-helpers-basehtml#activeCheckboxList()-detail
2. Scroll a bit down

### What is the expected result?
Normal markup

### What do you get instead?
http://joxi.net/1A55xk7FDxZj4A

### Additional info

| Q                | A
| ---------------- | ---
| Operating system | Ubuntu 18
| Browsers | Chrome 79, Firefox 72

**Comment by rob006** [comment] 2020-02-01 19:53
Duplicate of https://github.com/yiisoft-contrib/yiiframework.com/issues/338

**Closed by rob006** 2020-02-01 19:53 UTC
