### ISSUE TITLE
problem with UrlManager rules behavior

### ISSUE THREAD

**Issue by hesna** [yiisoft/yii2#8060] opened 2015-04-13 06:51 UTC
Hi,
I have this rule in my url manager configurations:
```php
        'urlManager' => [
            'enablePrettyUrl' => true,
            'rules' => [
                '<language:\w{2}>/news'=>'news/front/index',
            ]
        ],
```
it works fine for a URL like `mysite/index.php/en/news`. but the problem occurs when the URL is `mysite/index.php/en/news/`, that last `/` seems to broke the link and a 404 exception is thrown.
I added the following rule to rules array but it didn't solve it:
```php
     '<language:\w{2}>/news/'=>'news/front/index',
```
I've used similar rules in Yii 1.1 and it's working just fine, and it's the first time I'm working with rules in Yii 2.0 and this is happening, am I missing something?

**Comment by samdark** [comment] 2015-04-13 11:00
Duplicate of https://github.com/yiisoft/yii2/issues/7670

**Closed by samdark** 2015-04-13 11:00 UTC

**Comment by hesna** [comment] 2015-04-13 12:48
Thanks couldn't find it :+1:
