### ISSUE TITLE
Captcha: Could not load the image.

### ISSUE THREAD

**Issue by shi-yang** [yiisoft/yii2#11872] opened 2016-07-02 19:02 UTC
### What steps will reproduce the problem?

Controller

```
class SiteController extends Controller
{
    ...
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    ...
}
```

Model

```
class SignupForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $captcha;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
	    ...
            ['captcha', 'captcha']
	    ...
        ];
    }
}
```

View

```
<?= $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::classname(), [
    // configure additional widget properties here
]) ?>
```

### What is the expected result?
Load the image.
### What do you get instead?
In my program, Captcha can be displayed properly on some computers, but there are some computers can not be loaded properly, and the browser will appear "Could not load the image".

![screenshot from 2016-07-03 02-48-53](https://cloud.githubusercontent.com/assets/5102567/16541993/c797ae74-40c8-11e6-9e10-09f54b14d15f.png)

The same computer, download and install "Yii 2 Basic Application Template"  can be displayed, but not in my program.
### Additional info
I searched the Internet. If  the output buffer is not empty, you can not load the image.The solution is to empty the output buffer before output captcha.
For example, in [[\yii\captcha\CaptchaAction::run()]]
```php
        } else {
            ob_clean();  //Add this line, can solve this problem. Or add in other suitable places
            $this->setHttpHeaders();
            Yii::$app->response->format = Response::FORMAT_RAW;
            return $this->renderImage($this->getVerifyCode());
        }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.x
| PHP version      | 7.0.4-7ubuntu2.1
| Operating system | ubuntu 16.04

_Is it a bug?_

**Comment by samdark** [comment] 2016-07-02 21:24
Do you know how to reproduce the issue?

**Comment by ivanmota** [comment] 2016-07-03 05:33
On those machine that you can't load the image, please check if the user that is runnig the php have the right permission on the directory sessions.save_path or try to save the session on database

**Comment by zeevy** [comment] 2016-07-04 09:53
some times may be due to "enableStrictParsing" is set to true and you don't have any url rule for captcha

**Comment by samdark** [comment] 2016-07-04 10:04
I see no way to reproduce it so we can't fix it. Closing.

**Closed by samdark** 2016-07-04 10:04 UTC
Labels: status:need more info

**Comment by samatic** [comment] 2016-08-29 09:31
I had same issue and ob_clean() solved it.

**Comment by shannlove** [comment] 2017-04-05 06:40
I had same issue and ob_clean() solved it. Thanks @shi-yang.

**Comment by samdark** [comment] 2017-04-05 07:30
@shannlove any idea how to reproduce it?

**Comment by nageennayak11** [comment] 2017-12-29 11:21
Very good @shi-yang, its working for me.
i was tired but now relax.
thank you again.

**Comment by daliha** [comment] 2018-02-06 08:29
@samatic  @nageennayak11 
Where did you put ob_clean() to solve the problem?

**Comment by samatic** [comment] 2018-02-06 08:41
@daliha look at @shi-yang comment above

**Comment by daliha** [comment] 2018-02-06 08:58
@nageennayak11 Thank you

**Comment by neoacevedo** [comment] 2018-03-11 18:00
It was working for a long time to me, but suddenly it let to work, and the solution given here is not working in my case.

I set _ob_clean()_ in CaptchaAction and not worked.

It happened just after run composer update. 

I run both in my own PC and in AWS Elastic Beanstalk. In both was working, but just today it failed.

**Comment by OmgDef** [comment] 2018-10-12 02:42
Super weird, but I faced the same issue on one of my servers on PHP 7.1. Adding ```ob_clean()``` to the CaptchaAction class solved the issue. Yii version is 2.0.14. Checked all the permissions for sessions. PHP-FPM can write session files. No errors and warnings in the logs too.

**Comment by shi-yang** [comment] 2018-10-19 03:33
@samdark the issue can be reproduce by follwing step:

1. run `composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic` to install yii2-app-basic project.

2. add a blank line on `config/db.php` as below:
```

<?php
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname=test',
    'username' => 'root',
    'password' => '123456',
    'charset' => 'utf8'
];
```
**Note: There is a blank line at the beginning of the file**

3. Access the application through the following URL:
```
http://localhost/basic/web/index.php?r=site/contact
```

**Comment by samdark** [comment] 2018-10-19 07:19
Well, that is expected. PHP files should never start with blank lines or BOM else you'll have broken HTTP headers and unexpected input.

**Comment by 751836594** [comment] 2019-05-29 09:23
I had same issue  but I set ob_clean() in CaptchaAction and not worked.
because i don't have permission to write  session file

**Comment by johnbosco91** [comment] 2023-03-05 13:28
> I had same issue and ob_clean() solved it. Thanks @shi-yang.

I just extended the class and add ob_clean() works fine
