### ISSUE TITLE
Need to update MaskedInput

### ISSUE THREAD

**Issue by Sepaka22** [yiisoft/yii2#9866] opened 2015-10-09 10:08 UTC
https://github.com/RobinHerbots/jquery.inputmask/issues/1069
it was some fixes for escaping chars in version 3.2 in Jquery.inputmask

**Comment by samdark** [comment] 2015-10-09 11:00
Duplicate of https://github.com/yiisoft/yii2/issues/9783

**Closed by samdark** 2015-10-09 11:00 UTC
