### ISSUE TITLE
Proposal: start using asset-packagist

### ISSUE THREAD

**Issue by and800** [yiisoft/yii2#13759] opened 2017-03-12 22:24 UTC
**Reason:** installing Bower/NPM deps with Asset Plugin makes Composer slow, requires users to deal with Github API keys, makes Composer stateful because of that (which leads to awkward deploy scripts both on local machines and production). Let the people from Asset Packagist team deal with those problems for us!

**Possible caveats:**
for reasons that I cannot know, Yii has a hardcoded dependency on asset directories, `@vendor/bower` and `@vendor/npm`. But in Asset-Packagist they are located in `bower-asset` and `npm-asset` directories.
Even if we set aliases `@bower` and `@npm` explicitly, there might be a possibility that Yii will be requested for these aliases before alias configuration process, (maybe during bootstrap?)

**Steps to complete:**
+ Alter official app templates' `composer.json`s: https://asset-packagist.org/site/about
+ remove requirements to install asset-plugin from docs

no need to change the framework itself (only if there will be real issues with the path problem stated above)

**Comment by cebe** [comment] 2017-03-13 01:02
duplicate of #13064

**Closed by cebe** 2017-03-13 01:02 UTC
