### ISSUE TITLE
Undocumented use of {{tablename}} in create table in migrations

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2#14945] opened 2017-10-09 07:03 UTC
Looking into the yii2 user module: https://github.com/dektrium/yii2-user/blob/master/migrations/m140209_132017_init.php I have found that the tablename for createTable is enclosed in double curly brackets,  but I have not found any documentation about that use.

**Comment by schmunk42** [comment] 2017-10-09 07:11
Duplicate of https://github.com/yiisoft/yii2/issues/14944

**Closed by schmunk42** 2017-10-09 07:11 UTC
