### ISSUE TITLE
Identity data stays in session if findIdentity() returns null

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#18646] opened 2021-05-12 09:29 UTC
### What steps will reproduce the problem?

1. Login a user
2. Make `findIdentity()` return `null` for that user (e.g. disable the user in the database)
3. Load any page that checks the login status (`getIsGuest()`)

### What is the expected result?

If `findIdentity()` returns `null` the user should be logged out properly and the identity information should be deleted from the session.

### What do you get instead?

The user *seems* to be logged out (i.e. `getIsGuest()` returns `true`) but the identity information is still present in the session. The user is redirected to the login page on next request.

If now the user record is re-enabled in the DB the user suddenly is logged in again.

This is an unexpected user experience and can also lead to weird errors on the login page.

### Additional info

This is related to #9718 but to me the issue here is more fundamental. It is unrelated to auth_key and the like.

I'm unsure about BC issues but wonder why this was implemented this way. I can't think of a situation where it would make sense to keep the `idParam` in session if the asssocitated identity is gone/no longer valid and `getIsGuest()` returns `true`.

The comment for `IdentityInterface::findIdentity()` also seems to suggest that this can be used to immediately un-authenticate (read: logout) a logged in user:

```
    /**
     * ...
     * @return IdentityInterface|null the identity object that matches the given ID.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentity($id);
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.41
| PHP version      |  7.4.15
| Operating system | Debian

**Comment by mikehaertl** [comment] 2021-05-12 09:53
My workaround is to use my custom `User` class and override `renewAuthStatus()` like this:

```php
    /**
     * @see \yii\web\User
     */
    protected function renewAuthStatus()
    {
        parent::renewAuthStatus();
        if ($this->getIdentity() === null) {
            $this->switchIdentity(null);
        }
    }
```

I suggest to add this to the implementation of `yii\web\User`.

**Comment by bizley** [comment] 2021-05-12 10:07
This sounds good, at least without digging more into the problem. @samdark ?

**Comment by bizley** [comment] 2021-05-12 11:35
Hmm, I can see that [renewAuthStatus](https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L712) is setting identity to `null` when this is returned by `findIdentity`, and since `isGuest` is checking for that all should be good, right? What am I missing?

**Comment by mikehaertl** [comment] 2021-05-12 11:39
Right, setting `identity` to `null` is the one part. But like I said: the identity params are not removed from the session (e.g. you still see `__id` with the correct user id there). So the user is suddenly logged in again if `findIdentity()` returns the user record again.

I can't see, why it would make sense to have the id params kept in session if the user is actually seen as guest.

**Comment by bizley** [comment] 2021-05-12 11:46
So the problem is more with that and enabling auto login, right? Is setting it to `false` fixing that use-case?

**Comment by mikehaertl** [comment] 2021-05-12 11:51
It has nothing to do with auto login. It's really about proper cleanup if a user if the `identity` ist not valid anymore. The implementation of `getIsGuest()` shows, that `findIdentity()` is the single source of truth, whether a user is authenticated or not.

If the return value of `findIdentity()` changes to `null` all authentication data should be completely removed:

 1. Remove identity params from session
 2. Delete auto login cookie, if enabled

Point 2) already happens, but I think this is rather by accident: 

 * After `findIdentity()` returns null, on the next request, it will try to login by cookie
 * `loginByCookie()` will call `getIdentityAndDurationFromCookie()`
 * There the cookie is deleted if `findIdentity()` returns `null`

Point 1) remains open.

**Comment by bizley** [comment] 2021-05-12 12:06
Ok, I agree with what you are saying here. Would it work if the line I pointed previously was changed to `$this->switchIdentity($identity);`? There might be a wee overhead with the lines underneath it.

**Comment by samdark** [comment] 2021-05-12 12:22
Yes, doing a cleanup is a good idea.

**Comment by mikehaertl** [comment] 2021-05-12 12:24
@bizley I think it must be done after the call to `loginByCookie()`  because `switchIdentity(null)` would delete that cookie and thus break auto login. So probably the end of `renewAuthStatus()` is a good place to do the check.

@samdark Sure, I can provide a PR and we can discuss things further there.

**Comment by bizley** [comment] 2021-08-11 08:35
Closed via https://github.com/yiisoft/yii2/commit/c94d7049c51343c1512772b321005cfeb83e1746

**Closed by bizley** 2021-08-11 08:35 UTC
Labels: type:bug
