### ISSUE TITLE
ip address behind load balancer

### ISSUE THREAD

**Issue by nikunjtrapasiya** [yiisoft/yii2#8746] opened 2015-06-11 01:09 UTC
function getUserIP() returns local ip address if the servers are behind load balancer (i am using aws)

```
    public function getUserIP()
    {
        return isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : null;
    }
```

i need to change it to each time i upgrade my framework

```
return (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['HTTP_X_FORWARDED_FOR']) ? $_SERVER['HTTP_X_FORWARDED_FOR'] : null;
```

is there any way i can override the function in my config file or somewhere so i can still use it for logging purpose.

**Comment by samdark** [comment] 2015-06-11 08:45
Yes.

1. Create your own class that extends from `\yii\web\Request`.
2. Override `getUserIP()`.
3. In the config, specify new class as `request` component.

**Comment by cebe** [comment] 2015-06-11 10:36
or overwrite `$_SERVER['REMOTE_ADDR']` in index.php

**Comment by dizews** [comment] 2015-10-15 07:51
hello, what do you think if we implement this functionality like in [symphony](https://github.com/symfony/symfony/blob/v2.2.0/src/Symfony/Component/HttpFoundation/Request.php#L708) ?

**Comment by samdark** [comment] 2015-10-15 09:34
Via separate method? Yes, that's OK.

**Comment by dizews** [comment] 2015-10-15 14:14
@samdark I suggest to reimplement ```getUserIP``` which should use trustedHeaders property of request object and make docs how it influence to security.

**Comment by cebe** [comment] 2016-11-27 00:44
related to #10854 and #13050

**Comment by cebe** [comment] 2016-12-16 02:02
closing as duplicate of #10854

**Closed by cebe** 2016-12-16 02:02 UTC
Labels: type:enhancement
