### ISSUE TITLE
unsupported use of WITH clause

### ISSUE THREAD

**Issue by jonny7** [yiisoft/yii2#10312] opened 2015-12-02 18:21 UTC
What is the accepted method to retrieve a DataProvder when using WITH() statements? 

My approach is like so:

      $q = "WITH DISTINCT_ATTENDING(ATTENDING) AS
     ...
     rest of with statement";

         $data = Yii::$app->db->createCommand($q)->queryAll();
        $count = Yii::$app->db->createCommand($q)->queryScalar();
        $provider = new SqlDataProvider([
          'sql' => $q,
          //'params' => [':status' => 1],
          'totalCount' => $count,
          'pagination' => [
              'pageSize' => 50,
          ],
          'sort' => [
              'attributes' => [
                'ATTENDING',
                ....
               rest of attributes

              ],
          ],
        ]);
        return $provider;

This results in an error `WITH USER_SQL AS (WITH DISTINCT_ATTENDING(ATTENDING) AS`. Im guessing because my statement seems to be wrapped within a with() statement too?

So, what would be the correct way to obtain a DataProvider for use with GridView? I could just return the raw data not as a dataprovider and build a grid manually, but it would be quicker and nicer I'm sure if there was a way to do it within Yii? (Apologies for posting loads of obscure Oracle questions)

**Comment by klimov-paul** [comment] 2015-12-02 18:24
https://github.com/yiisoft/yii2/blob/master/framework/data/SqlDataProvider.php

**Comment by jonny7** [comment] 2015-12-02 18:26
I am using SqlDataProvider

**Comment by klimov-paul** [comment] 2015-12-02 18:31
> This results in an error

What error? Can you provide a full stack trace?

> So, what would be the correct way to obtain a DataProvider for use with GridView? 

Are you sure your SQL executed correctly in the environment which does not involve Yii, like SQL console or something?

**Comment by jonny7** [comment] 2015-12-02 19:00
My SQL statement in the variable $q works. I have just returned it from the model and ran it in TOAD.

http://pasted.co/3ee39d38

I had some trouble with pasting it in here as some of disappeared.

**Comment by klimov-paul** [comment] 2016-08-30 12:07
There is nothing I can do with such fuzzy report.

> This results in an error WITH USER_SQL AS (WITH DISTINCT_ATTENDING(ATTENDING) AS. Im guessing because my statement seems to be wrapped within a with() statement too?

`yii\db\Command` does not processes given SQL searching for the `with` occurances. There must be something else involved.

Closing, since there is no way to reproduce.

**Closed by klimov-paul** 2016-08-30 12:07 UTC
Labels: feature:db
