### ISSUE TITLE
Error when configuring UrlManager::$ruleConfig with custom UrlRule

### ISSUE THREAD

**Issue by Locustv2** [yiisoft/yii2#13893] opened 2017-03-30 18:00 UTC
I extended `yii\web\UrlRule` and modified `[[parseRequest()]]` and `[[createUrl()]]`.
I also added 2 public properties.

In my config, i add the following:
```php
'ruleConfig' => [
    'class' => 'my\custom\UrlRule',
    'propertyX' => 'abc',
    'propertyY' =>'xyz',
],
```

When i run the my application with the following, i get the following:
```
Unknown Property – yii\base\UnknownPropertyException

Setting unknown property: yii\web\UrlRule::propertyX
```

The cause is related to `yii\debug\Module` and `yii\gii\Module`. When i disable both, it works.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.10

**Comment by samdark** [comment] 2017-03-30 19:21
Both Gii and Debug do the following at bootstrap stage:

```php
Yii::$app->getUrlManager()->addRules([
            [
                'class' => 'yii\web\UrlRule',
                'route' => 'x',
                'pattern' => 'x',
            ],
], false);
```

**Comment by samdark** [comment] 2017-03-30 19:29
And the issue is about `UrlManager::buildRules()`:

```php
$rule = Yii::createObject(array_merge($this->ruleConfig, $rule));
```

Resulting array in your case is:

```php
'ruleConfig' => [
    'class' => 'yii\web\UrlRule',
    'route' => 'x',
    'pattern' => 'x',
    'propertyX' => 'abc',
    'propertyY' =>'xyz',
],
```

**Comment by samdark** [comment] 2017-03-30 20:31
It works as described:

> Individual rule configurations specified via [[rules]] will take precedence when the same property of the rule is configured.

**Comment by samdark** [comment] 2017-03-30 20:32
So we can fix that in Gii and Debug extensions.

**Comment by samdark** [comment] 2017-03-30 20:51
https://github.com/yiisoft/yii2-debug/issues/103

**Comment by samdark** [comment] 2017-03-30 20:56
https://github.com/yiisoft/yii2-gii/issues/264

**Comment by Locustv2** [comment] 2017-03-31 15:18
I was reading about: 

> Individual rule configurations specified via [[rules]] will take precedence when the same property of the rule is configured.

In the docs as well then realised it should be in gii and debug issues.

Thanks for referencing them.

**Comment by samdark** [comment] 2017-04-01 13:40
Closing the issue here since core is correct.

**Closed by samdark** 2017-04-01 13:40 UTC
Labels: type:bug

**Comment by dezmound** [comment] 2017-07-07 08:07
I get a similar problem then i changing `ruleConfig` in `yii\web\UrlRule` and set custom class for `Rule` still get old rules with different class from cache. `UrlManager` calculated hash only for rules but nothing with they configuration.
```php
if (is_string($this->cache)) {
    $this->cache = Yii::$app->get($this->cache, false);
}
if ($this->cache instanceof CacheInterface) {
    $cacheKey = $this->cacheKey;
    $hash = md5(json_encode($this->rules));
    if (($data = $this->cache->get($cacheKey)) !== false && isset($data[1]) && $data[1] === $hash) {
        $this->rules = $data[0];
    } else {
        $this->rules = $this->buildRules($this->rules);
        $this->cache->set($cacheKey, [$this->rules, $hash]);
    }
} else {
    $this->rules = $this->buildRules($this->rules);
}
```

**Comment by rob006** [comment] 2017-07-07 08:50
@dezmound You should open new issue for your problem, it is completely unrelated to this issue.
