### ISSUE TITLE
Old version of Imagine

### ISSUE THREAD

**Issue by esindger** [yiisoft/yii2#6869] opened 2015-01-15 00:57 UTC
Hello,

I have the following error:

> PHP Fatal Error "yii\base\ErrorException" with message "Call to undefined method Imagine\Gd\Image::metadata()"

The reason is that extensions 'yii2-imagine' dependence ``"imagine/imagine": "0.5.*"`` ([https://github.com/yiisoft/yii2-imagine/blob/master/composer.json])

Please replace to ``"imagine/imagine": "0.6.*"``

**Comment by qiangxue** [comment] 2015-01-15 01:57
Duplicate of https://github.com/yiisoft/yii2/issues/6014

**Closed by qiangxue** 2015-01-15 01:57 UTC
