### ISSUE TITLE
Yii:t not working in 'plural' mode

### ISSUE THREAD

**Issue by r-novikov** [yiisoft/yii2#9170] opened 2015-07-21 12:31 UTC
```php
echo \Yii::t(
    'app', 
    'Здесь {n, plural, =0{котов нет} =1{есть один кот} one{# кот} few{# кота} many{# котов} other{# кота}}!', 
    ['n' => $n]
);
```

Not working as expected in case of ```$n = 21```
Output:
```Здесь 21 кота!```

**Comment by unclead** [comment] 2015-07-21 12:43
duplicate of #7430

**Closed** 2015-07-21 20:22 UTC
