### ISSUE TITLE
Using not selected data in filters (v2.0.46)

### ISSUE THREAD

**Issue by DesRodman** [yiisoft/yii2#19519] opened 2022-08-23 08:03 UTC
Hello team

In search filter I have the next structure
```
<?php  $clientsList = [0 => 'Client1', 1 => 'Client2', ....]
           echo $form->field($model, 'id_client')->
                listBox($clientsList, ['multiple' => 'true'])->
                label(Yii::t('app', 'Clients'));
?>
```
So even, if I didnt use this filter and click - Search, after page reload - in select data of this ListBox I can see "Client1", means data with ID - 0

But Client1 (with ID 0) should be there - just if I selected it before click button Search

I saw such issue in ListBox, Select2, etc... so its not some foreign extension.. its last version of Yii2

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46 (last version for now)
| PHP version      |  7.4
| Operating system | Ubuntu 21.10+

I made downgrade to 2.0.45, and it works without any issue

Kindly advice, how can I fix it, or its a bug?

Thanks

**Comment by bizley** [comment] 2022-08-23 08:29
Duplicate of #19508

**Closed by bizley** 2022-08-23 08:29 UTC
