### ISSUE TITLE
set emulatePrepare is false, get TableSchema error

### ISSUE THREAD

**Issue by huijiewei** [yiisoft/yii2#11296] opened 2016-04-06 13:23 UTC

**Comment by samdark** [comment] 2016-04-06 14:42
Could you post a stack trace and full error message?

**Comment by huijiewei** [comment] 2016-04-06 15:02
2016-04-06 21:14:25 [127.0.0.1][-][-][error][yii\db\Exception] exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number' in /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Command.php:840
Stack trace:
#0 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Command.php(840): PDOStatement->execute()
#1 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('<span class="st...', '<span class="ke...')
#2 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/mysql/Schema.php(268): yii\db\Command->queryAll()
#3 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/mysql/Schema.php(98): yii\db\mysql\Schema->findConstraints(Object(yii\db\TableSchema))
#4 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Schema.php(146): yii\db\mysql\Schema->loadTableSchema('<span class="st...')
#5 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveRecord.php(296): yii\db\Schema->getTableSchema('<span class="st...')
#6 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveRecord.php(370): yii\db\ActiveRecord::getTableSchema()
#7 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(133): yii\db\ActiveRecord::populateRecord(Object(common\models\AppVersion), '[<span class="s...')
#8 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveQuery.php(210): yii\db\ActiveQuery->createModels('[[<span class="...')
#9 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Query.php(211): yii\db\ActiveQuery->populate('[[<span class="...')
#10 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all('<span class="ke...')
#11 /Users/huijiewei/Documents/Develop/Yuncars/Website/yuncars.restful/controllers/open/AppVersionAction.php(24): yii\db\ActiveQuery->all()
#12 [internal function]: app\restful\controllers\open\AppVersionAction->run('<span class="st...')
#13 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array('[<span class="t...', '[<span class="s...')
#14 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams('[<span class="s...')
#15 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('<span class="st...', '[<span class="s...')
#16 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('<span class="st...', '[<span class="s...')
#17 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(app\restful\components\Request))
#18 /Users/huijiewei/Documents/Develop/Yuncars/Website/yuncars.restful/web/index.php(19): yii\base\Application->run()
#19 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[HY093]: Invalid parameter number
The SQL being executed was: SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'yc_app_version' AND kcu.table_name = 'yc_app_version'' in /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Schema.php:628
Stack trace:
#0 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Command.php(855): yii\db\Schema->convertException(Object(PDOException), 'SELECT\n    kcu....')
#1 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Command.php(362): yii\db\Command->queryInternal('<span class="st...', '<span class="ke...')
#2 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/mysql/Schema.php(268): yii\db\Command->queryAll()
#3 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/mysql/Schema.php(98): yii\db\mysql\Schema->findConstraints(Object(yii\db\TableSchema))
#4 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Schema.php(146): yii\db\mysql\Schema->loadTableSchema('<span class="st...')
#5 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveRecord.php(296): yii\db\Schema->getTableSchema('<span class="st...')
#6 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveRecord.php(370): yii\db\ActiveRecord::getTableSchema()
#7 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveQueryTrait.php(133): yii\db\ActiveRecord::populateRecord(Object(common\models\AppVersion), '[<span class="s...')
#8 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveQuery.php(210): yii\db\ActiveQuery->createModels('[[<span class="...')
#9 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/Query.php(211): yii\db\ActiveQuery->populate('[[<span class="...')
#10 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all('<span class="ke...')
#11 /Users/huijiewei/Documents/Develop/Yuncars/Website/yuncars.restful/controllers/open/AppVersionAction.php(24): yii\db\ActiveQuery->all()
#12 [internal function]: app\restful\controllers\open\AppVersionAction->run('<span class="st...')
#13 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Action.php(92): call_user_func_array('[<span class="t...', '[<span class="s...')
#14 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\Action->runWithParams('[<span class="s...')
#15 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('<span class="st...', '[<span class="s...')
#16 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('<span class="st...', '[<span class="s...')
#17 /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(app\restful\components\Request))
#18 /Users/huijiewei/Documents/Develop/Yuncars/Website/yuncars.restful/web/index.php(19): yii\base\Application->run()
#19 {main}
Additional Information:
Array
(
    [0] => HY093
)

**Comment by cebe** [comment] 2016-04-06 16:19
please also show the code at /Users/huijiewei/Documents/Develop/Yuncars/Website/yuncars.restful/controllers/open/AppVersionAction.php, that generates the query.

**Comment by cebe** [comment] 2016-04-06 16:24
> /Users/huijiewei/Documents/Develop/Yuncars/Website/vendor/yiisoft/yii2/db/mysql/Schema.php(98): yii\db\**mysql**\Schema->findConstraints(Object(yii\db\TableSchema))

You are using a MSSQL constant on a MySQL connection? seems you messed up your config somehow. which DBMS are you using and how did you configure yii?

**Comment by huijiewei** [comment] 2016-04-06 17:06
AppVersion::find()
            ->where(['type' => $type])
            ->orderBy(['id' => SORT_DESC])
            ->limit(1)
            ->all();

i use 
'dsn'        => 'mysql:host=host;dbname=db',

**Comment by huijiewei** [comment] 2016-04-06 17:07
I use aliyun rds mysql

**Comment by cebe** [comment] 2016-04-06 17:10
duplicate of #10946, which is fixed in master and will be in release of version 2.0.8.

**Closed by cebe** 2016-04-06 17:10 UTC
