### ISSUE TITLE
[Feature request] Model::attributeHints method

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#7162] opened 2015-02-04 09:22 UTC
An `ActiveField` allows to set a hint when filling a form using the `hint()` method. I propose to have a method to set the hints for an attribute from the model

```php
public function attributeHints()
{
    return [
        'telephone' => 'include area code, eg: 5551234567',
        'shipping_address' => 'if left blank the package will be sent to your registered address',
    ];
}
```
We might also require an `BaseHtml::activeHint($model, $attribute, $options)` method to render it more easily.

**Comment by petrabarus** [comment] 2015-02-16 09:47
+1

**Comment by Faryshta** [comment] 2015-02-16 22:03
@samdark what do you think about the `BaseHtml::activeHint` method?

**Comment by samdark** [comment] 2015-02-16 22:16
I think it's a duplicate of #1468

**Closed by samdark** 2015-02-16 22:16 UTC
Labels: status:under discussion, type:enhancement
