### ISSUE TITLE
Native Url and PrettyUrl run both at the same time bi-directional way

### ISSUE THREAD

**Issue by konapaz** [yiisoft/yii2#13076] opened 2016-11-25 20:34 UTC
Urls should be works  bi-directional, in native Yii generated url and after of enablePrettyUrl set to true in UrlManager

For example both of the below url should be work in the same time, or broken-links will exist for a long time by search engines

mydmomain.com/index.php?r=gallery/default/index/&uid=52  

After enablePrettyUrl =true
mydmomain.com/gallery/52

See also here
http://www.yiiframework.com/forum/index.php/topic/73198-native-url-and-prettyurl-run-both-at-the-same-time/page__p__305362__fromsearch__1#entry305362

Does UrlManager manipulates both of two type of link ?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.?
| Operating system | LINUX, Windows

**Comment by cebe** [comment] 2016-11-25 20:37
how does your .htaccess file look like?

**Comment by konapaz** [comment] 2016-11-25 20:39
RewriteEngine On
RewriteRule ^(frontend|backend)/web/ - [L]
RewriteRule ^admin(/(.*))?$ backend/web/$2 [L]
RewriteRule ^sitemap.xml - [L]
RewriteRule ^robots.txt - [L]
RewriteRule .* frontend/web/$0

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^([^/]+/web)/.*$ $1/index.php

**Comment by konapaz** [comment] 2016-11-27 10:48
What more info is needed to solve this problem ?

**Comment by SilverFire** [comment] 2016-11-28 22:12
Your `.htaccess` looks a bit customized. We need some time to verify it. Most probably we will take care about on your issue after current release

**Comment by cebe** [comment] 2016-11-29 09:14
@konapaz could you test whether the issue is reproduceable with the [recommended .htaccess file from the docs](http://www.yiiframework.com/doc-2.0/guide-tutorial-shared-hosting.html#add-extras-for-webserver):

```apache
RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php
```

**Comment by konapaz** [comment] 2016-11-29 15:47
In this way nothing work

I reproduce this on localhost with below results

Not Found
The requested URL /folder_of_webapp/index.php was not found on this server.
Apache/2.4.23 (Win64) PHP/5.6.25 Server at localhost Port 80

or in best case an yii error is raised on
/folder_of_webapp/frontend/web/
with Yii/php error Not Found (#404)

My frontend/config/main-local.php is

 'components' => [
        'request' => [
            'baseUrl' => '/folder_of_webapp',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'scriptUrl' => '/folder_of_webapp/index.php',
        ],
...

**Comment by dynasource** [comment] 2016-11-29 15:57
where have you put this .htaccess?

**Comment by dynasource** [comment] 2016-11-29 16:00
is the index.php in the same folder as the .htaccess?

**Comment by konapaz** [comment] 2016-11-29 16:05
As I use the advanced yii2 template no, So index.php files are inside the frontend/web and backend/web folders

**Comment by dynasource** [comment] 2016-11-29 16:27
well, you should test the htaccess in these folders like @cebe asked you  https://github.com/yiisoft/yii2/issues/13076#issuecomment-263516507

**Comment by konapaz** [comment] 2016-11-29 16:29
@dynasource 
This is not work for me

https://github.com/yiisoft/yii2/issues/13076#issuecomment-263607518

**Comment by dynasource** [comment] 2016-11-29 17:02
what source code of Yii2 should be altered to get what you want?

**Comment by cebe** [comment] 2016-11-29 17:15
> 'baseUrl' => '/folder_of_webapp',

this looks wrong to me. if the final URL does not contain this path, yii does not know how to parse the URL. `baseUrl` should refer to the real base from where application urls are starting.

**Comment by konapaz** [comment] 2016-11-30 00:18
@cebe 

for localhost
'baseUrl' => '/folder_of_webapp', is useful to find css, images, and js in the right folder, without this 
browser try to get files like that

localhost/assets/4b0b56a3/jquery.js
instead of
localhost/folder_of_webapp/assets/4b0b56a3/jquery.js

for online server  'baseUrl' => '',  is ok!

**Comment by cebe** [comment] 2017-04-25 23:04
I am unable to reproduce the issue. It looks like an environment or configuration specific problem to me. As long as we do not have any information on how to reproduce it we can not fix anything. I am closing this issue for now.

**Closed by cebe** 2017-04-25 23:04 UTC
Labels: status:to be verified
