### ISSUE TITLE
\yii\log\Target::getContextMessage not filtered over filterMessages

### ISSUE THREAD

**Issue by ekaragodin** [yiisoft/yii2#6399] opened 2014-12-07 08:24 UTC
My log targets configuration for console application:

        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                    'except' => ['mycategory*'],
                ],
                [
                    'class' => 'yii\log\FileTarget',
                    'categories' => ['mycategory*'],
                    'logFile' => '@runtime/logs/mycategory.log',
                ]
            ],
        ],

Write to log:

        \Yii::info('Hello', 'mycategory');

See mycategory.log:

2014-12-07 09:19:02 [-][-][-][info][mycategory] Hello
2014-12-07 09:19:01 [-][-][-][info][**application**] $_SERVER = [
    'PATH' => '/usr/local/php5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/ekaragodin/bin'
    'TMPDIR' => '/var/folders/yd/cy4s0m450lbcdjmlcc4c3kcr0000gn/T/'
    'LOGNAME' => 'ekaragodin'
    ....

**Comment by cebe** [comment] 2015-01-10 19:09
the "context message" is always logged in category application and severty info, regardless of which filters you use: https://github.com/yiisoft/yii2/blob/master/framework/log/Target.php#L106 So the output is expected.

**Comment by qiangxue** [comment] 2015-01-11 02:00
Duplicate of https://github.com/yiisoft/yii2/issues/6470

**Closed by qiangxue** 2015-01-11 02:00 UTC
Labels: status:under discussion
