### ISSUE TITLE
When download utf8 filename via  Response::sendfile()  , filename is not correct in IE11

### ISSUE THREAD

**Issue by pigochu** [yiisoft/yii2#11953] opened 2016-07-14 08:24 UTC
Example Code

~~~php
return Yii::$app->getResponse()->sendFile($filepath, $attachment->filename);
~~~

if $attachment->filename is "中文.txt"  <== this is chinese filename with utf8 encoded.

When I download 
- Chome & Firefox save correct filename
- IE 11 is not correct

In http://php.net/manual/en/function.header.php , yjf_victor wrote :
![image](https://cloud.githubusercontent.com/assets/1013744/16832701/0de4414e-49de-11e6-89c4-ac25a1107317.png)

So I change my code looks like:

~~~php
$response = Yii::$app->getResponse()->sendFile($filepath, $attachment->filename);
$response->headers['Content-Disposition'] = 'attachment; '
        . sprintf('filename="%s"; ', rawurlencode($attachment->filename))
        . sprintf("filename*=utf-8''%s", rawurlencode($attachment->filename));
        return $response;
~~~

IE11 & Chrome & Filefox can download file with correct filename.

**Comment by cebe** [comment] 2016-07-18 19:33
I remember a similar issue report but I could not find it.

**Comment by samdark** [comment] 2016-07-18 19:56
https://github.com/yiisoft/yii2/issues/10563 ?

**Comment by cebe** [comment] 2016-07-20 20:03
Yes, thanks.

**Comment by samdark** [comment] 2016-08-23 23:19
Closed as duplicate of #10563.

**Closed by samdark** 2016-08-23 23:19 UTC
Labels: type:bug
