### ISSUE TITLE
Database query logging at info level is very spammy.

### ISSUE THREAD

**Issue by Orteko** [yiisoft/yii2#8906] opened 2015-06-26 01:56 UTC
Currently database queries have the full raw sql logged at level info.

Given that most production sites will be running logging at info this can result in extremely spammy log files and makes it hard to find relevant information.

I propose that these log commands be set to trace level rather than info as they are really only relevant for a dev environment.

**Comment by cebe** [comment] 2015-06-26 12:22
duplicate of #1662

**Closed by cebe** 2015-06-26 12:22 UTC
