### ISSUE TITLE
Provide a Formatter for time interval

### ISSUE THREAD

**Issue by cbhp** [yiisoft/yii2#9704] opened 2015-09-16 22:00 UTC
Please provide a formatter for time intervals, e.g. given a value in seconds:
2050 -> 34 minutes, 10 seconds
26967 -> 7 hours, 29 minutes

**Comment by samdark** [comment] 2015-09-16 22:08
Message formatter is able to do it already: http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html#duration. Not sure it worth creating separate formatter for it.

**Comment by nineinchnick** [comment] 2015-09-17 06:04
Duplicate of #9671

**Comment by nineinchnick** [comment] 2015-09-17 06:08
@samdark some arguments:

* intl doesn't work for all locales, like pl_PL
* a formatter would be easier to use in a grid or detail view widget
* it's easy

How about I'll make a PR to discuss it?

**Comment by samdark** [comment] 2015-09-17 10:17
> intl doesn't work for all locales, like pl_PL

Contribute to CLDR and it will in future.

**Comment by cbhp** [comment] 2015-09-17 18:23
Especially I need it in a DetailView::widget. A formatter would make it easy to use.

**Comment by SilverFire** [comment] 2015-10-02 09:30
I faced the same problem. I18n `duration,%with-words` (for example `Yii::t('app', '{0, duration,%with-words}', (int)$model->spent_seconds)`) is not supported with ru_RU locale. Another thing is that you can not set your own format with i18n duration.
I needed the date rounded to minutes, but with i18n duration, integer `3900` seconds will be formatted as `1 hour, 5 minutes, 0 seconds`, but I don't want that `0 seconds`.

I had no time to fight with it, so I wrote `Yii::t('app', '{0, time, HH:mm}', (int)$model->spent_seconds)` and that's all.

As for me, @nineinchnick suggested useful formatter. It intersects with my needs and I want it :) I will post some enhancement ideas to PR #9710 and will ask for merge.

@samdark CLDR contribution will take much more time to get it usable in PHP. I vote for `Formatter::asInterval`

**Comment by samdark** [comment] 2015-10-02 10:45
Agree that CLDR contribution is long term thing but it's a good thing to do anyway.

**Comment by SilverFire** [comment] 2015-10-02 10:49
@samdark I'm not experienced with CLDR contributing. We can do PHP `asDuration` and somebody will contribute to CLDR. When it will be ready in PHP, we will get rid of our implementation

**Closed** 2015-10-27 09:45 UTC
Labels: status:under discussion, type:enhancement
