### ISSUE TITLE
Rest controller(behaviors)

### ISSUE THREAD

**Issue by gud3** [yiisoft/yii2#14754] opened 2017-09-02 13:36 UTC
I use the behavior in the rest controller: the cors and the authenticator. When the query comes into action, where the "HttpBearerAuth" is and does not pass the token validation, the "handleFailure" method is called in which the exception
` throw new UnauthorizedHttpException ('Your request was made with invalid credentials.');`
 The exception is thrown, and headers of the cors are not set.

Q | A
------------ | -------------
Yii version | 2.0.13-dev
PHP version | 7.1
Operating system | Windows10

**Comment by russianlagman** [comment] 2017-09-05 02:05
@gud3 what is the question? Attach your authenticator behavior after the cors. 

```
/**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        unset($behaviors['authenticator']);

        $behaviors['corsFilter'] = [
            'class' => Cors::class,
            'cors' => [
                'Origin' => ArrayHelper::getValue(\Yii::$app->params, 'cors.origin', ['*']),
                'Access-Control-Request-Headers' => ['Authorization', 'X-Pagination-Total-Count', 'X-Pagination-Page-Count', 'X-Pagination-Current-Page', 'X-Pagination-Per-Page'],
                'Access-Control-Expose-Headers' => ['Authorization', 'X-Pagination-Total-Count', 'X-Pagination-Page-Count', 'X-Pagination-Current-Page', 'X-Pagination-Per-Page'],
            ]
        ];

        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
        ];
        $behaviors['authenticator']['except'] = ['options'];

        return $behaviors;
    }
```

**Comment by gud3** [comment] 2017-09-05 09:42
Yes, I set the cors before authentication. But when the request fails, the headers are not set. When you check, do not forget that the option query remembers the corset headers for the time specified by the "Access-Control-Max-Age"

**Comment by gud3** [comment] 2017-09-13 15:12
It was all because I forgot to add a line `unset($behaviors['authenticator']);`. Only I do not understand how it affected if I overwrote an array?

**Comment by leopripos** [comment] 2019-06-19 09:16
I don't know whether this has been resolved or not.

But only to state the main points that I found here.

we must call `unset($behaviors['authenticator'])` before resetting the `behaviors['authenticator']`. This is important to make the right order becase the `parent::behaviors()` already has the `authenticator` index.

**Comment by samdark** [comment] 2019-06-19 22:28
The issue is open so it was not.

**Comment by bizley** [comment] 2021-01-01 15:47
I'm not sure if handling of that changed since Yii 2.0.13 but I've just tested it on 2.0.40 and CORS headers are preserved after `UnauthorizedHttpException` is thrown so I'm closing this. Feel free to comment if it requires reopening.

**Closed by bizley** 2021-01-01 15:47 UTC
Labels: feature:rest, type:bug
