### ISSUE TITLE
The file or directory to be published does not exist: `bower/jquery/dist`

### ISSUE THREAD

**Issue by petrabarus** [yiisoft/yii2#10198] opened 2015-11-20 10:25 UTC
I suddenly got this error few hours ago.

```
The file or directory to be published does not exist: `bower/jquery/dist`
```

Turns out the there is one more level under directory `vendor/bower`, 

```
$ ls vendor/bower
bower-asset
$ ls vendor/bower/bower-asset
ace-builds              bootstrap                 handlebars          jquery-slimscroll       magnific-popup  seiyria-bootstrap-slider  zeroclipboard
angular                 bootstrap-hover-dropdown  jquery              jquery.sparkline.build  moment          slick-carousel
```
while in 

https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php#L456

```
       Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
```

I'm using `"fxp/composer-asset-plugin:~1.0.3"`

**Comment by petrabarus** [comment] 2015-11-20 10:26
To reproduce

```
$ git clone git@github.com:yiisoft/yii2-app-basic.git
$ composer update --prefer-dist
$ ls vendor/
autoload.php  bin/          bower/        cebe/         composer/     ezyang/       fzaninotto/   phpspec/      swiftmailer/  yiisoft/
$ ls vendor/bower/
bower-asset
$ ls vendor/bower/bower-asset
bootstrap  jquery  jquery.inputmask  punycode  typeahead.js  yii2-pjax
```

**Comment by petrabarus** [comment] 2015-11-20 10:28
````
$sed -n '456'p vendor/yiisoft/yii2/base/Application.php 
        Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
````

**Comment by SilverFire** [comment] 2015-11-20 10:28
The problem recently occurred and we are trying to figure out what happens.

**Comment by petrabarus** [comment] 2015-11-20 10:29
Simple solution is by
```
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower/bower-asset');
```

**Comment by SilverFire** [comment] 2015-11-20 10:30
It seems that the problem is in composer.

### Temporary solution:

Use stable composer 1.0.0-alpha11: ://getcomposer.org/download/1.0.0-alpha11/composer.phar

**Comment by samdark** [comment] 2015-11-20 10:30
Composer master is broken.

```
composer self-update 1.0.0-alpha11
composer clear-cache
```

Then repeat.

**Comment by petrabarus** [comment] 2015-11-20 10:36
@samdark's solution is working

```
composer self-update 1.0.0-alpha11
composer clear-cache
```

thanks!

**Comment by samdark** [comment] 2015-11-20 10:49
https://github.com/francoispluchino/composer-asset-plugin/issues/164

**Comment by samdark** [comment] 2015-11-20 17:39
This is now fixed and fxp plugin is tagged.

**Closed by samdark** 2015-11-20 17:39 UTC
Labels: severity:critical, type:bug

**Comment by Bahmad92** [comment] 2017-04-17 08:16
go to the  directory C:\wamp64\www\yii2-advanced-api\vendor and change **bower-asset** into **bower**. this helped me

**Comment by SG5** [comment] 2017-05-24 08:08
Have same issue, bower located on `vendor/bower-asset`

**Comment by php5developer** [comment] 2017-07-03 10:54
I've same problem in 2017 (CARL !). The solution is

1. rm -r vendor/bower-assets
2. Open composer.json
3. **config** array has following lines:
`
"asset-installer-paths": {
  "npm-asset-library": "vendor/npm",
  "bower-asset-library": "vendor/bower"
}
`
4. Move these lines in **extra** array
5. composer update. At termenal you will see "Installing in bowe-assets/jquery...", but in real bower files will be installed in **bower** directory.
6. Enjoy

**Comment by yasiralijaved** [comment] 2017-07-30 12:06
Just rename the folder "bower-asset" to "bower" in /vender directory. And make sure the directory "bower-asset" has all of its content

**Comment by baltechies** [comment] 2017-10-26 10:21
Still facing the issue with latest composer version 1.5.2 2017

**Comment by cebe** [comment] 2017-10-26 10:57
make sure you have the latest version of the composer-asset-plugin and the config in composer.json:

https://github.com/yiisoft/yii2-app-basic/blob/0c87fab0c3c9d0ada04a85f4982aeffc08b76cc7/composer.json#L33

**Comment by darkdubdeep** [comment] 2018-05-07 13:08
What an crazy bug

**Comment by fugafree** [comment] 2018-07-31 09:03
I had the same issue when I updated to the latest `composer.json`.
The solution: update the `config/web.php` too. Add
```
'aliases' => [
  '@bower' => '@vendor/bower-asset',
  '@npm'   => '@vendor/npm-asset',
],
```
to `$config`. Like in the `config/web.php` on `master` now.

**Comment by eramudeep** [comment] 2019-02-15 10:16
Hey there i am still facing this issue. i tried:
1). 'aliases' => [
        '@bower' => '@vendor/bower',
        '@npm'   => '@vendor/npm-asset',
    ],
2. Rename Folder bower-asset to bower and vice versa.
3. Giving proper read write permissions 

Need Help.

**Comment by polishExperiment** [comment] 2020-04-07 23:49
2020 - this issue still seems to exist and bother me;)

**Comment by soofani** [comment] 2020-06-15 15:51
> I had the same issue when I updated to the latest `composer.json`.
> The solution: update the `config/web.php` too. Add
> 
> ```
> 'aliases' => [
>   '@bower' => '@vendor/bower-asset',
>   '@npm'   => '@vendor/npm-asset',
> ],
> ```
> 
> to `$config`. Like in the `config/web.php` on `master` now.

This worked for me.

**Comment by eramudeep** [comment] 2020-12-29 05:40
Still getting this error in 2020 :(

**Comment by sunnyphp** [comment] 2021-05-20 17:18
Some packages, like `kriss/yii2-calendar-schedule` has `provide` key in `composer.json`:
```config
  "provide": {
    "bower-asset/jquery": "*",
    "bower-asset/bootstrap": "*",
    "bower-asset/inputmask": "*",
    "bower-asset/jquery.inputmask": "*",
    "bower-asset/punycode": "*",
    "bower-asset/yii2-pjax": "*",
    "npm-asset/fullcalendar": "*"
  },
```
and this can affect the installation.

**Comment by jjoselon** [comment] 2022-01-28 15:38
Please read README.md of this https://packagist.org/packages/yidas/yii2-bower-asset
