### ISSUE TITLE
 InvalidArgumentException in AttributeTypecastBehavior

### ISSUE THREAD

**Issue by m8nknight** [yiisoft/yii2#19851] opened 2023-05-27 05:05 UTC
Hi, all. I have an issue in version 2.0.48. It does not happening in2.0.47. The behaviour AttributeTypecastBehavior throws an error 
yii\base\InvalidArgumentException for attributes witch not present on this model from database. 
On example I have these two behawiours with this settings in my model:

```php
public function behaviors()
    {
        return [
           [
                'class' => ManyToManyBehavior::class,
                'relations' => [
                    'category_ids' => 'categories',
                    'image_ids' => [
                        'logos',
                        'viaTableValues' => [
                            'file_type' => FileToProduct::FILE_TYPE_LOGO,
                            'sort' => function($model, $relationName, $attributeName, $relatedPk) {
                                return $this->oldFileSorting[FileToProduct::FILE_TYPE_LOGO][$relatedPk] ?? 0;
                            }
                        ],
                        'customDeleteCondition' => [
                            'file_type' => FileToProduct::FILE_TYPE_LOGO,
                        ],
                    ],
                ]
            ],
            [
                'class' => AttributeTypecastBehavior::class,
                'attributeTypes' => [
                    'category_ids' => function ($value) {
                        if (is_array($value)) {
                            return array_map(function ($item) {
                                return (int) $item;
                            }, $value);
                        }
                        return null;
                    },
                    'image_ids' => function ($value) {
                        if (is_array($value)) {
                            return array_map(function ($item) {
                                return (int) $item;
                            }, $value);
                        }
                        return null;
                    },
                    'is_exclude_from_search' => AttributeTypecastBehavior::TYPE_BOOLEAN,
                ],
                'typecastBeforeSave' => true,
                'typecastAfterFind'  => true,
                'skipOnNull' => false,
            ],
     ]
}
```

Please take a look on category_ids attribute. It does not present in database but it became available because ManyToManyBehavior(\voskobovich\behaviors\ManyToManyBehavior) is filling it by some data from related table. (On this case ids but i think it does not matters)
With this settings every find() operation will throw an error yii\base\InvalidArgumentException.
My PHP version 8.2 but I also tested it on 8.0 and 8.1 - both the same

I have fixed this issue but I have no access to create branches and make pull requests on this repo. So I'll provide my solution here and may be I will help somebody to solve this.
On file framework/behaviors/AttributeTypecastBehavior.php we need to change this function:
```php
private function resetOldAttributes()
    {
        if ($this->attributeTypes === null) {
            return;
        }

        $attributes = array_keys($this->attributeTypes);

        foreach ($attributes as $attribute) {
            if ($this->owner->hasAttribute($attribute)) {
                $this->owner->setOldAttribute($attribute, $this->owner->{$attribute});
            }
        }
    }
```
and it will work. Sorry for maybe some misunderstanding from my side and maybe not too match correct solution )))

Have a good day to all.

Q | A
-- | --
Yii version | 2.0.48
PHP version | 8.1
Operating system | Ubuntu 22.04

**Comment by notaidea** [comment] 2023-05-29 05:52
It works fine in my app,I also use php 8.1 and yii2.0.48.

**Comment by m8nknight** [comment] 2023-05-29 05:59
> It works fine in my app,I also use php 8.1 and yii2.0.48.

Yes. Without \voskobovich\behaviors\ManyToManyBehavior it works. But with him I have this issue. Before my update of yii version all was ok. I think its something connected only to fields not from database but created automatically by onother behaviors .

**Comment by acceleratemedia** [comment] 2023-05-31 17:38
I have this same issue. For my context, the issue is this commit / update ( https://github.com/yiisoft/yii2/commit/819b7cf701dbf259fd4554f9cb2ab9d787145f85 ).

A simplifed description of our case is:
We have a model that extends \yii\db\ActiveRecord called MyModel.
MyModel uses AttributeTypeCastBehavior, set up so that it uses the validation rules are what are used for the typecasting.
MyModel has a property called $myProperty. This is a member property, not a database attribute. 
In rules() we add a rule for $myProperty to be a string.
AttributeTypeCastBehavior typecasts this and sets it as a string.

In the updates to the typecast behavior here ( https://github.com/yiisoft/yii2/commit/819b7cf701dbf259fd4554f9cb2ab9d787145f85#diff-a24903cf67c3f36b600123be576c5cdba667e6e78d449dc6e346bf8662a3efe5 ) it forces a reset of the old attributes which is causing this error.

\yii\db\BaseActiveRecord::setOldAttribute() does a check for whether the property is set in the \yii\db\BaseActiveRecord::$_oldAttributes or \yii\db\BaseActiveRecord::hasAttribute(). BaseActiveRecord::hasAttribute() is checking strictly against  attributes in the database. So, this update breaks this functionality on models that are typecasting with member variables.

To fix it, in that commit, resetOldAttribute() should check if the variable is a member property and if it is, ignore it.

**Comment by samdark** [comment] 2023-05-31 18:22
@acceleratemedia seems you have a fix 50% ready. Do you have time for a pull request?

**Comment by BrianVB** [comment] 2023-07-14 02:07
Just got all set up to write a fix for this and it looks like someone has already taken care of it here ( https://github.com/yiisoft/yii2/pull/19857 ). I'm not sure if the status of this issue should be changed or how this is handled.

**Comment by samdark** [comment] 2023-07-14 14:47
Thanks for noticing, @BrianVB

**Closed** 2023-07-14 14:47 UTC
Labels: type:bug
