### ISSUE TITLE
make activeField display custom error massage

### ISSUE THREAD

**Issue by yanggs07** [yiisoft/yii2#15100] opened 2017-11-06 03:10 UTC
### What steps will reproduce the problem?
When I use activeField widgets to display custom errors,
the \yii\helpers\Html::error() method would always get error from model by
```php
$error = $model->getFirstError($attribute);
```
and when I want to custom the error display, the only way is to override the getFirstError method of the model class, which might cause more unwanted effects
### What is the expected result?
the error() method can choose a public method of the model to display errors
### What do you get instead?
use a key in $options named errorMethod to call the $model method to display errors

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11
| PHP version      | 7.1.29
| Operating system | centos 7.1

**Comment by Alex-Code** [comment] 2017-11-06 08:39
What are you wanting to change?
Styling the error can be done via [`ActiveField::$errorOptions`](http://www.yiiframework.com/doc-2.0/yii-widgets-activefield.html#$errorOptions-detail)

If it's the message itself you can change it in the model rules.
http://www.yiiframework.com/doc-2.0/guide-input-validation.html#customizing-error-messages

**Comment by yanggs07** [comment] 2017-11-06 09:02
@Alex-Code 
thank you for reply my issue.
I am considering that nether $errorOptions nor customizing error messages would solve my problem.

firstly, i want to customize the error message itself instead of its css styling.
secondly, although the model rules can be set customize message, it is about a single error.

So let's think about the scene creating password.

Some password rules require a length of 12, with letters, numerics and symbols.
and the model applied several rules to follow that.

One user want '123456' to be his password.
And then the model tells the user, the password must be at least 12 digits.
the user changed the password to 123456123456
And the model tells 'need alphabetical letters'
and, and the user tries 123456qwerty
then the model tells that symbols is required.

why cannot the model show the error message at the {error} section at once with the information given by the properties existed...

if we use activeField as the input, the {error} placeholder can only display the getFirstError to replace the error message and no other way instead.

I am so appreciating you to consider my issue, thank you.

**Comment by cebe** [comment] 2017-11-06 15:17
duplicate of https://github.com/yiisoft/yii2/issues/3087

**Closed by cebe** 2017-11-06 15:17 UTC
