### ISSUE TITLE
DbSession concurrency issue

### ISSUE THREAD

**Issue by vikram0207** [yiisoft/yii2#11401] opened 2016-04-22 09:21 UTC
### What steps will reproduce the problem?

It worked well with http but with https its making multiple call of writeSession
### What is the expected result?

It should work with https as well
### What do you get instead?

Integrity constraint violation: SQLSTATE[23000]: 
Integrity constraint violation: 1062 Duplicate entry 'h6g8mp45arddisfppio96jj5akkjg9alg8k9kk5f' for key 'PRIMARY'
The SQL being executed was: 
INSERT INTO `session` (`data`, `id`, `expire`) VALUES ('__flash|a:0:{}loginDetailPri|a:1:{s:12:\"permanentKey\";s:64:\"cefbf813b2cf35e9203c53bd24e71b250c74201e5844338b97b7d69af5b127d0\";}loginDetail|a:9:{s:12:\"permanentKey\";s:64:\"0cda4174274e6ca13ec37dd86013dac70779a48210fadce0f40350a4b03b1b1c\";s:7:\"is_bind\";i:1;s:6:\"mobile\";s:12:\"919899195914\";s:5:\"email\";s:0:\"\";s:4:\"name\";s:6:\"Vikram\";s:9:\"last_name\";s:5:\"Singh\";s:3:\"dob\";s:10:\"1981-06-02\";s:7:\"balance\";s:7:\"2575.59\";s:14:\"balance_status\";s:5:\"false\";}otpVerified|s:1:\"0\";otpDetail|a:2:{s:6:\"mobile\";s:10:\"9899195914\";s:8:\"otpValue\";s:1:\"2\";}', 'h6g8mp45arddisfppio96jj5akkjg9alg8k9kk5f1fv9v2qqoef1', 1461308275)

Integrity constraint violation: SQLSTATE[23000]: 
Integrity constraint violation: 1062 Duplicate entry 'h6g8mp45arddisfppio96jj5akkjg9alg8k9kk5f' for key 'PRIMARY'
The SQL being executed was: 

INSERT INTO `session` (`data`, `id`, `expire`) VALUES ('__flash|a:0:{}', 'h6g8mp45arddisfppio96jj5akkjg9alg8k9kk5f1fv9v2qqoef1', 1461308275)
### Additional info

| Q | A |
| --- | --- |
| Yii 2 |  |
| php 5.6.10 |  |
| ubuntu |  |

**Comment by klimov-paul** [comment] 2016-04-22 10:00
`DbSession` always check for the existance of the session row:
https://github.com/yiisoft/yii2/blob/master/framework/web/DbSession.php

Multiple calls of `writeSession()` should not cause such problems.

Such issue may be caused by race conditions if several scripts are running for the same session ID simultaneously. Or it could be some troubles with the session table, which prevents correct existance query execution.

**Comment by SilverFire** [comment] 2016-04-23 06:14
Failed to reproduce. Could you describe a way to get this kind of error on clean Yii basic application installation?



> may be caused by race conditions

most probably

**Comment by vikram0207** [comment] 2016-04-26 16:59
Happing on Safari (mac) every time working fine on mozilla firefox and chrome

main.php
<?php
return [
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],       'session' => [
            'class' => 'yii\web\DbSession',
            'sessionTable' => 'session',
       ],
    ],
    
];

**Comment by motzy** [comment] 2016-07-20 10:48
Hello,
We just encountered the same issue while running a multi-website app. It clearly seems to be a racing condition, but it's the first time we witness it in months of use.
Our problem isn't so much that it happened, but that it plan echoes the error. Even throwing the error would be more acceptable, or suppressing the echo in production environments.

 Another option would be to add an `ON DUPLICATE KEY` condition.

Hope this input helps.

**Comment by SilverFire** [comment] 2016-12-11 19:13
Failed to reproduce. Most probably, it's a race condition the happens under high concurrency.

`ON DUPLICATE KEY` syntax is not cross-DBMS to use it in `DbSession`.

I see the only bulletproof solution - to obtain a mutex lock in `writeSession()` method. However, it could be unacceptable because mutexes will (most probably) slow down sessions handling a lot.

I'd like to hear more @yiisoft/core-developers opinions.

**Comment by cebe** [comment] 2016-12-11 20:25
In which situation would the php session handler write a session with the same ID, that has just been created from within another process?
@vikram0207 @motzy could you give more information about the database connection config and the DBMS you are using? It could also be that there is some query caching involved, do you have set up any options in this direction?

**Comment by cebe** [comment] 2016-12-11 20:27
> but that it plan echoes the error

This should only happen in debug mode... https://github.com/yiisoft/yii2/blob/75b98c6b7ebe712097207f1e3a4af38fc20909db/framework/web/DbSession.php#L184-L186

**Comment by acs-ferreira** [comment] 2017-03-29 07:13
I'm having the same issue here on multi-master MariaDB Galera cluster.

`Exception (Integrity constraint violation) 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'a94fe4ca775bf4bd6d41a2aeb6cf071b' for key 'PRIMARY'`

**Comment by samdark** [comment] 2017-03-29 11:05
@acs-ferreira is it from logs? Would your please give more information about the database connection config and the DBMS you are using? Do you have query caching set up?

**Comment by acs-ferreira** [comment] 2017-03-29 11:46
@samdark i'm using HumHub and as i'm not sure if the problem comes from Yii or HumHub, i've also posted an issue on their Git here: https://github.com/humhub/humhub/issues/2402

Issue comes from Yii logs _(not from DBMS logs)_ and the connection to the database config is:

```
'db' => [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=10.99.0.14;dbname=yii2',
    'username' => 'yii2',
    'password' => '*********',
    'charset' => 'utf8',
    'enableSchemaCache' => true,
 ],
```

**Comment by samdark** [comment] 2017-03-29 21:53
> Server setup (DBMS) is 3x dedicated (8 cores, 32Gb RAM) MariaDB 10.1.22 configured in a Galera Cluster (multi-master) backed up by a MaxScale dedicated server (4 cores, 16Gb RAM)
> (=> DBMS is not dedicated to HumHub, perhaps, this issue is only related to this software).
> 
> I'm also using Phabricator with this setup, no DB issues.
> 
> Clients are between 2.000 and 5.000 (peak hours).
> 
> All tables are InnoDB.

**Comment by andreasanta** [comment] 2017-10-04 11:02
I've noticed the same behavior if the Load Balancer is set with no persistence. That means that Yii2 receives two subsequent very fast requests and both try to insert the same session ID.

Resolved by increasing the persistence timeout of the server to 60 seconds. I think it can be lower as well.

**Comment by cebe** [comment] 2017-10-13 23:19
> That means that Yii2 receives two subsequent very fast requests, on two or more different servers, and all of them try to insert the same session ID.

I wonder why this should happen, when creating a new session, the session ID should be generated randomly.

**Comment by andreasanta** [comment] 2017-10-14 15:51
> I wonder why this should happen, when creating a new session, the session ID should be generated randomly

I know it’s a bit hard to reason about, but I think the following occurs:

1. New Client makes request to one server and the server generates session ID and stores it in DB
2. Second request is issued by the client with the newly generated session ID while the DB server hasn’t completed the write operation (this is also worsened by my setup, because I use a read replica that lags behind 1 sec approx from the master).
3. Server checks if session exists on DB, it doesn’t find it and tries the insert
4. The first insert completes and replicates successfully
5. The second insert fails with dup key

I would solve it with:

1. INSERT IGNORE on session creation, although it’s MariaDB only jargon
2. Transactional insert on session creation, with error checking and graceful recover

Best,
A.

**Comment by cebe** [comment] 2017-10-14 21:55
> Server checks if session exists on DB, it doesn’t find it and tries the insert

this check should be made against the master db, not the replica. So adding a `useMaster()` wrapper around the queries should help.

**Comment by andreasanta** [comment] 2017-10-15 11:49
Roger that. Opened PR #14972, please merge if ok.

**Closed** 2018-02-09 00:14 UTC
Labels: feature:db, type:bug
