### ISSUE TITLE
Problem while injecting dependencies in ActiveRecord model

### ISSUE THREAD

**Issue by akireikin** [yiisoft/yii2#8639] opened 2015-06-03 09:13 UTC
Given ActiveRecord class.

```php
class Place extends ActiveRecord
{
    /**
     * @var \app\core\helpers\GeoTransformerInterface
     */
    private $geoTransformer;

    /**
     * @param \app\core\helpers\GeoTransformerInterface $geoTransformer
     * @param array                                     $config
     */
    public function __construct(GeoTransformerInterface $geoTransformer, $config = [])
    {
        $this->geoTransformer = $geoTransformer;

        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'place';
    }

    /**
     * @return array
     */
    public function getLocation()
    {
        return $this->geoTransformer->decode($this->location_polygon);
    }

    /**
     * @param array $value
     */
    public function setLocation(array $value)
    {
        $this->location_polygon = $this->geoTransformer->encode($value);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])->viaTable('place_has_category', ['place_id' => 'id']);
    }
}
```

# Problem 1

```php
$place = Place::find()->one();
```

This code raises an Exception.

`Argument 1 passed to app\\modules\\places\\ar\\Place::__construct() must be an instance of app\\core\\helpers\\GeoTransformerInterface, none given`

## Possible solution

Overwrite `BaseActiveRecord::instantiate()` with:

```php
    public static function instantiate($row)
    {
        return \Yii::$container->get(static::class);
    }
```

# Problem 2

```
$place = Place::find()->with('categories')->asArray()->all();
```

This code also raises an Exception.

`Argument 1 passed to app\\modules\\places\\ar\\Place::__construct() must be an instance of app\\core\\helpers\\GeoTransformerInterface,  none given`

The problem is located in `ActiveQueryTrait::findWith()`, line 162.

```php
    public function findWith($with, &$models)
    {
        $primaryModel = new $this->modelClass;
        $relations = $this->normalizeRelations($primaryModel, $with);
        /* @var $relation ActiveQuery */
        foreach ($relations as $name => $relation) {
            if ($relation->asArray === null) {
                // inherit asArray from primary query
                $relation->asArray($this->asArray);
            }
            $relation->populateRelation($name, $models);
        }
    }
```

## Possible solution

Unfortunately, it is hard to overwrite `ActiveQueryTrait::findWith()` method. The problem is that `ActiveQueryTrait::nomalizeRelations()` is private.

Maybe it will be better to get rid of any sort of `new $modelClass` calls in ActiveRecord's core classes?

**Comment by akireikin** [comment] 2015-06-03 09:16
Problem 1 related to #6808

**Comment by cebe** [comment] 2015-06-03 11:10
Problem 1 should be solved in application code like you did, need to check if we can solve the second one somehow...

**Comment by SamMousa** [comment] 2015-12-08 15:41
Problem 2 at the moment is an implicit contract problem.
The only thing you truly know about the model class is that it implements `ActiveRecordInterface`,`ActiveRecordInterface` does not define a constructor, so blindly calling `new $modelClass` is bad practice in any case.

**Comment by adamdry** [comment] 2016-02-11 21:20
@SamMousa agreed. Also if it used \Yii::createObject() we could use dependency injection/container to setup dependencies.

@cebe thanks for the duplicate detection.

**Comment by cebe** [comment] 2016-02-25 17:31
I have checked in some fixes that reduce the problem to the use of `asArray()` and `joinWith()`. Will address these later but in general using DI and custom constructor should work now.

**Comment by cebe** [comment] 2016-02-26 15:19
there is another place :-/ https://github.com/yiisoft/yii2/blob/ded158ed43cfb0a9551d692b569ef85e91f0b4e5/framework/data/ActiveDataProvider.php#L176

**Comment by cebe** [comment] 2016-03-04 01:30
another one: https://github.com/yiisoft/yii2/blob/e0b0679f3a31753098e6de03e9a5fe9409c00719/framework/grid/DataColumn.php#L125

**Comment by cebe** [comment] 2016-03-04 01:32
seems like this is a duplicate of #5786

**Closed** 2016-03-04 01:32 UTC
Labels: type:enhancement

**Comment by zharnikov** [comment] 2017-01-06 13:02
I think injecting dependencies into ARs is a bad pactice. We should consider AR as an Entity in terms of DDD. Entities shouldn't have any dependencies in their constructors as they aren't a part of their state. If you implement it in yii it will create a possibility for God AR classes (code smell).

**Comment by SamMousa** [comment] 2017-01-06 13:11
Interesting point hadn't considered that..

On Jan 6, 2017 2:02 PM, "Antony Z" <notifications@github.com> wrote:

I think injecting dependencies into ARs is a bad pactice. We should
consider AR as an Entity in terms of DDD. Entities shouldn't have any
dependencies in their constructors as they aren't a part of their state. If
you implement it in yii it will create a possibility for God AR classes
(code smell).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yiisoft/yii2/issues/8639#issuecomment-270899397>, or mute
the thread

**Comment by vercotux** [comment] 2017-07-09 05:35
>I think injecting dependencies into ARs is a bad pactice. We should consider AR as an Entity in terms of DDD. Entities shouldn't have any dependencies in their constructors as they aren't a part of their state. If you implement it in yii it will create a possibility for God AR classes (code smell).

You are not thinking this through. What about modules? How is an AR inside a module supposed to have a relation to the main application (typically you need *at least* a `getUser()` relation to the main application's Identity class). Are modules supposed to maintain their own table of users? How do you envision this?
