### ISSUE TITLE
does yii2 restful support batch operate in one request?

### ISSUE THREAD

**Issue by cstabor** [yiisoft/yii2#11988] opened 2016-07-20 03:14 UTC
### What steps will reproduce the problem?

I need batch operation, such as batch update order status to enable status. 
At present, only one order can be update in one request. 
for example:
> PUT   http://www.name.com/order/1234
it just update order_id=1234 record.

In my project, I need update more than one order in one request.

Anyone knows it, thank you

### What is the expected result?

operate a amount of record status in one http request.

### What do you get instead?

some reference:
https://developers.google.com/drive/v3/web/batch
https://developers.facebook.com/docs/graph-api/making-multiple-requests

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | Yii2
| PHP version      | php-5.6.16
| Operating system | centos7.0

**Comment by tunecino** [comment] 2016-07-20 09:16
nope it doesn't. 

ActiveController introduces those [actions](https://github.com/yiisoft/yii2/blob/master/framework/rest/ActiveController.php#L70) by default and [this](https://github.com/yiisoft/yii2/blob/master/framework/rest/UpdateAction.php) is what does the UpdateAction. ActiveController dosen't cover all cases as REST implementations differs from an app to another it just introduce the common basic onces. In your case you'll need to introduce a new one or override the built-in update action and maybe make use of the[ActiveRecord::updateAll](http://www.yiiframework.com/doc-2.0/yii-db-activerecord.html#updateAll()-detail) method. this is how you can extend your controller class:

http://www.yiiframework.com/doc-2.0/guide-rest-controllers.html#extending-active-controller

**Comment by fernandezekiel** [comment] 2016-09-18 15:31
Duplicate of https://github.com/yiisoft/yii2/issues/4478

**Comment by SilverFire** [comment] 2016-09-18 17:19
Thank

**Closed by SilverFire** 2016-09-18 17:19 UTC
Labels: feature:rest, status:under discussion, type:enhancement
