### ISSUE TITLE
Problem with displaying error stack items

### ISSUE THREAD

**Issue by bookin** [yiisoft/yii2#8159] opened 2015-04-22 15:22 UTC
I see it:
![image](https://cloud.githubusercontent.com/assets/537882/7277781/9948e2b0-e91a-11e4-8851-fa0ab98e9dc4.png)

i suggest change code in "\yii2\views\errorHandler\callStackItem.php" : 
with 
```php
<div class="element">
	<span class="item-number"><?= (int) $index ?>.</span>
	<span class="text"><?php if ($file !== null) echo 'in ' . $handler->htmlEncode($file); ?></span>
	<?php if ($method !== null): ?>
		<span class="call">
			<?php if ($file !== null) echo '&ndash;'; ?>
			<?= ($class !== null ? $handler->addTypeLinks("$class::$method") : $handler->htmlEncode($method)) . '(' . $handler->argumentsToString($args) . ')' ?>
		</span>
	<?php endif; ?>
	<span class="at"><?php if ($line !== null) echo 'at line'; ?></span>
	<span class="line"><?php if ($line !== null) echo (int) $line + 1; ?></span>
</div>
```
to
```php
<div class="element">
	<span class="item-number"><?= (int) $index ?>.</span>
	<span class="text"><?php if ($file !== null) echo 'in ' . $handler->htmlEncode($file); ?></span>
	<span class="at"><?php if ($line !== null) echo 'at line'; ?></span>
	<span class="line"><?php if ($line !== null) echo (int) $line + 1; ?></span>
	<?php if ($method !== null): ?>
		<div class="call">
			<?php if ($file !== null) echo '&ndash;'; ?>
			<?= ($class !== null ? $handler->addTypeLinks("$class::$method") : $handler->htmlEncode($method)) . '(' . $handler->argumentsToString($args) . ')' ?>
		</div>
	<?php endif; ?>
</div>
```

and add add CSS code to "\yii2\views\errorHandler\exception.php"
```css
.call-stack ul li div.call{
    margin: 5px 0 0 50px;
}
```

And we will get:
![image](https://cloud.githubusercontent.com/assets/537882/7277964/7043188a-e91b-11e4-80ba-25a1c30da7b7.png)

And why I have question marks instead of values ​​?
Thanks.

**Comment by cebe** [comment] 2015-04-22 16:07
related to #4763

**Comment by cebe** [comment] 2015-07-25 23:12
duplicate of #4763 which is now fixed.

**Closed by cebe** 2015-07-25 23:12 UTC
Labels: status:to be verified
