### ISSUE TITLE
Set dependencies in application config

### ISSUE THREAD

**Issue by hiqsol** [yiisoft/yii2#11758] opened 2016-06-14 13:31 UTC
What do you think about adding function to yii\base\Application:

``` php
public function setDependencies(array $dependencies)
{
    foreach ($dependencies as $class => $definition) {
        Yii::$container->set($class, $definition);
    }
}
```

This will allow setup dependencies in main application config in the same way as aliases are set now:

``` php
$config = [
    ...
    'aliases' => [
         '@foo' => '@runtime/foo',
    ],
    'dependencies' => [
        'yii\mail\MailInterface' => 'yii\swiftmailer\Mailer',
        'yii\widgets\LinkPager' => [
            'maxButtonCount' => 5,
        ],
    ],
    ...
];
```

**Comment by samdark** [comment] 2016-06-14 13:41
Sounds good to me. I was asked about it multiple times.

**Comment by samdark** [comment] 2016-06-14 13:41
@yiisoft/core-developers any objections?

**Comment by SilverFire** [comment] 2016-06-14 14:28
Could be implemented

**Comment by hiqsol** [comment] 2016-06-14 14:36
Ok, if no objections I will do PR.

**Comment by cebe** [comment] 2016-06-14 21:58
what does it do? configure Yii::$container?

**Comment by hiqsol** [comment] 2016-06-15 06:06
It's the same story as with aliases.
What does Application::setAliases() do? configure Yii::$aliases.
And you have it because it allows to setup aliases with **configuration** not code.
According guide:
> This property is provided so that you can define aliases in terms of application configurations instead of by calling the Yii::setAlias() method.

Application config looks good place to put dependencies config. There is no other global config.

**Comment by lynicidn** [comment] 2016-06-15 12:01
if change
$application = new yii\web\Application($config);
to
$application = Yii::createObject(yii\web\Application::class, $config);
than this solution not work for app

app can not resolve dependencies, example `_bootstrap.php:
```php
Yii::$container->set('yii\web\Application', 'MyApplication');
Yii::$container->set('MyAppInject', 'MyDep');
class MyApplication
{
    public function __construct($config, MyAppInject) {}
}
```
по русски - ваше решение ограничивает использование контейнера для самого приложения

**Comment by SilverFire** [comment] 2016-06-15 12:28
> what does it do? configure Yii::$container? that is not the job of the application class imo.

It was my first question when we had a discussion with @hiqsol offline.

This suggest might look awkward in terms of design, but since we don't have a better way to manage DI in declarative way, it might be implemented.

@lynicidn Thank you for your idea of a possibly unexpected behavior. The suggested example will not work just because the code that puts your dependencies' config to the DI container is being executed after creation of the target object. The code bellow should work as expected:

```php
class MyApplication extendex \yii\web\Application 
{
    public function __construct($config, MyAppInject) {}
}

Yii::$container->set('MyAppInject', '\app\ApplicationDependency');

$application = Yii::createObject([
    'class' => MyAppliction::class,
    'dependencies' => [
        'SuperComponent' => ['class' => ...]
    ]
]);
```

**Comment by cebe** [comment] 2016-06-15 16:24
> This suggest might look awkward in terms of design, but since we don't have a better way to manage DI in declarative way, it might be implemented.

How about creating an extra config file for that, which will be included in index.php?

**Comment by hiqsol** [comment] 2016-06-15 17:13
> How about creating an extra config file for that, which will be included in index.php?

It's more about **how** then **where**.

Ok, to sum it up: the proposal is to allow dependency injection configuration be: 

- declarative
- located in the standard place
- made in the same way as quite similar construction (aliases)

But I agree that everything can be just left as it is :)

**Comment by hiqsol** [comment] 2016-10-18 09:43
Maybe any new ideas how to configure dependency injection in a nice way?

**Comment by dynasource** [comment] 2016-10-18 09:59
I dont see the problem in terms of design. DI containers are used in an implementation of Application so why not letting it be configured by Application. Its feels more awkward/hacky to do this in a bootstrap file than to do this in the Application config.

If you do this in Application config, you have way more flexibility and control. You can override DI configuration and have different settings in different Application tiers. This is consistent with the way you are configuring other components of your app. 

It also adds flexibility to the way you are configuring your app. If you think about configuring your Application through a database interface, it would be very comfortable to has DI container config inside your Application config files. Arrays add flexibility.

**Comment by cebe** [comment] 2016-11-29 11:59
I'd still prefer to add something like the following to the application templates to resolve this:

https://github.com/yiisoft/yii2-app-basic/pull/98/files

**Comment by SilverFire** [comment] 2016-11-29 12:02
It does not solve problem of config merging

**Comment by cebe** [comment] 2016-11-29 12:03
good point.

**Comment by dynasource** [comment] 2016-11-29 12:07
have you actually read my post https://github.com/yiisoft/yii2/issues/11758#issuecomment-254462498 ;)

**Comment by cebe** [comment] 2016-11-29 13:13
well, I had read that before but not today, sorry :)

**Closed** 2016-12-02 13:09 UTC
Labels: status:under discussion, type:enhancement
