### ISSUE TITLE
Very complex method used to disable single checkbox in ActiveField::checkboxList()

### ISSUE THREAD

**Issue by yapi68** [yiisoft/yii2#7453] opened 2015-02-25 18:33 UTC
In Yii 1.x to disable single checkbox in checkboxList we did following:

```
$form->checkBoxList($model, 'items', $selected, array(
  'options' => array(
       'value1'=>array('disabled'=>true),
   ),
));
```

In Yii 2.x we must use Closures to override checkbox rendering:

```
$form->field($model, 'items')->checkboxList($options, [
    'item' => function($index, $label, $name, $checked, $value){
        $disable = false;
        if ($value == 'value1') {
            $disable = true;
        }

        $checkbox = Html::checkbox($name, $checked, ['value' => $value, 'disabled' => $disable]);
        return Html::tag('div', Html::label($checkbox . $label), ['class' => 'checkbox']);
    }
]);
```

I think its very complicated to customize checkboxList now. Maybe we need back to Yii 1.x style in this case?

**Comment by sidtj** [comment] 2015-02-25 23:01
Maybe an specific item could be customized by specifying its name prefixed by `:` (or something else). This way:
~~~[php]
$form->field($model, 'items')->checkboxList($options, [
    ':myValue' => ['disabled' => true],
    'item' => function(){...},
    ...
]);
~~~
So this could be implemented in Html::activeCheckBoxList() (internally used by the mentioned method);

**Comment by sidtj** [comment] 2015-02-25 23:38
EDIT:
For simplification of the framework code development, so that we dont need iterate over every item looking for `:` prefix but only over 'customItems', it could be:
~~~[php]
$form->field($model, 'items')->checkboxList($options, [
    'customItems' => [
        'myValue' => ['disabled' => true],
    ],
    'item' => function(){...},
    ...
]);
~~~

**Comment by sidtj** [comment] 2015-02-26 00:35
I have implemented that for checkBoxList. After I implement it for radioList I will PR.

**Comment by sidtj** [comment] 2015-02-26 01:49
Done for radioList too. Tests updated too. I will make a PR now.

**Comment by sidtj** [comment] 2015-02-26 02:16
Waiting the PR to be discussed. No problem if it is not accepted. Every time learning more! ;-)

**Comment by SDKiller** [comment] 2015-02-26 11:11
:+1: for simplifying such things
now it is easier and faster to build it in pure `html` with a few `php` injections

Not sure about `customItems` - the rules apply to `options` rendering

**Comment by sidtj** [comment] 2015-02-26 11:56
Hi @SDKiller 
I cant see how the solution for this problem could be 'easier' and 'faster' than using 'customItems' (or a similar solution). Can you give an example to achieve this...
~~~[php]
$form->field($model, 'items')->checkboxList($options, [
    'customItems' => [
        'myValue' => ['disabled' => true],
    ],
]);
~~~
... using "pure `html` with a few `php` injections"?
:v:

**Comment by SDKiller** [comment] 2015-02-26 12:14
@sidtj 

> I cant see how the solution for this problem could be 'easier' and 'faster' than using 'customItems' 

I was talking not about your proposal but about "closure" syntax 
(I've also dropped using constructs like `GridView` if they consist more than of 3-4 columns ;) )

> Not sure about `customItems`...

Here I was talking about naming and placement of rules array.

**Comment by sidtj** [comment] 2015-02-26 12:44
@SDKiller 

Yeah, but using the closure has been complex as @yapi68 examplified. It is a long signature and, no rarely, we have to put (so) many conditions to achieve our objective. I agree with him. Yii should be easy (like 1 was in this case).

About customItems, anything can be changed. Do you have some idea?

(I am going to work now. See u later :v:)

**Comment by creocoder** [comment] 2015-02-27 03:58
Vote against, at least concrette implementation. Introducing new properties like `customItems` make framework inconsistent and its really hard to maintence it several years after changes like this. There is already feature which make so rare case possible. Yes, its implemented as anonymous function, but **it's already implemented*. Introducting new properties to make same job is sign of very very bad design. There is already LOT of mistakes with V layer inside Yii 2, no need to aggravate situation. Yii 2.1 will come and its better in that version to fix everything that was wrong.

**Comment by creocoder** [comment] 2015-02-27 04:15
> In Yii 2.x we must use Closures to override checkbox rendering

Let's look at your example:

```php
$form->field($model, 'items')->checkboxList($options, [
    'item' => function($index, $label, $name, $checked, $value){
        $disable = false;
        if ($value == 'value1') {
            $disable = true;
        }

        $checkbox = Html::checkbox($name, $checked, ['value' => $value, 'disabled' => $disable]);
        return Html::tag('div', Html::label($checkbox . $label), ['class' => 'checkbox']);
    }
]);
```

Don't you think to render simple `<div class="checkbox">` its better to use `<div class="checkbox">` instead if `Html::tag('div', ..., ['class' => 'checkbox'])`? You do not have dynamically generated classes, etc. Its absoluttely meaningless to write html by using php in such cases. Same for other cases like that. Moreover you can make helper which can be used with `items` and return anonymous. You can return partial. There is 100th variations how to make this without introducing new property.

P.S. https://twitter.com/sam_dark/status/570748500109107201

**Comment by sidtj** [comment] 2015-02-27 04:57
Hi @creocoder

I agree with you about it to be already implemented. But, the entire point of this issue is about **the complexity** to get simple things done, things like to put a 'disabled' in a specific item.

This is a "simplified" version of the original code for this case (using your arguments):
~~~[php]
$form->field($model, 'items')->checkboxList($options, [
    'item' => function($index, $label, $name, $checked, $value){
        $disabled = in_array($value, ['val1', 'val3', 'valN']) ? 'disabled' : '';
        return "<div class='checkbox'><label><input type='checkbox' name='$name' value='$value' $disabled>My Label</label></div>";
    }
]);
~~~

Maybe you are right. But it stills smells like "why simplify if we can complicate"? 

My final thought is: `item` can be used for more complex templates, `customItems` (or something else) just for customize the item(s) I want. I really dont think it hurts.

Anyway, thank you so much for your thoughts. Made me open the mind and see that the problem is a bit smaller than I was thinking.

**Comment by creocoder** [comment] 2015-02-27 05:37
@sidtj Look for example at `Html::dropDownList` description. There is `options` property. Inside that property there is `options` array key which do job about attributes for concrette options. This is clean proof than introducing something like `customItems` will broke fw consistency at all. And this is proof why its very important to learn how similar troubles solved inside another methods. In case of `Html::checkBoxList` it can be solved that consistent way.

**Comment by lynicidn** [comment] 2015-02-27 05:41
ArrayHelper::map before configure widget ?

**Comment by creocoder** [comment] 2015-02-27 05:44
@sidtj So your feature can be implemented by using so called "special attributes". It will looks like:

```php
$form->checkBoxList($model, 'items', $selected, [
    'options' => [
        'options' => [
            'value1' => ['disabled' => true],
            'value2' => ['disabled' => true],
            'value3' => ['disabled' => true],
        ],
    ],
));
```

This is **consistent** with how that **already** done for `Html::dropDownList()` and other methods.

**Comment by creocoder** [comment] 2015-02-27 05:51
@sidtj If you'll create new consistent PR don't forget fact that `Html::checkboxList` and `Html::radioBoxList` has additional `itemOptions` property. This is difference between that methods and `Html::dropDownList`. This property mean **default** item options which make sence for those 2 methods. So don't forget merge **default** item options with **per-item** options.

**Comment by sidtj** [comment] 2015-02-27 12:42
@creocoder 
> Look for example at Html::dropDownList description. There is options property. Inside that property there is options array key which do job about attributes for concrette options. 

I saw that just few moments after I have made the pull request but I found that somehow 'unreusable/almost hardcoded' for this situation. I dont remember now what exactly was the point, but I even thought to propose a refactoring after the PR to be merged, so that the code could be used for the three methods (and others).

> So your feature can be implemented by using so called "special attributes"

I thought similarly about it too but I gave away after to think about similar situations like `'checked' => ['disabled' => true]`, but it did not include your idea about a new sub `options`, that eliminate the problem I thought! :+1: 

> If you'll create new consistent PR don't forget fact that Html::checkboxList and Html::radioBoxList has additional itemOptions property. This is difference between that methods and Html::dropDownList. This property mean default item options which make sence for those 2 methods. So don't forget merge default item options with per-item options. Thanks.

Ok, I will take that care!

Thank you for your clear insights!

[I just dont have more time now cause I am going to work]

**Comment by sidtj** [comment] 2015-02-27 12:47
Just one more [off, not entirely] question:

How does PR, new features, enhancements and others are picked? I mean, who have authority to pick or discard those? Does the core team chat internally even although just one member participate of the discussion?

I really would like to understand how it works, if possible. 
Thanks again!

**Comment by creocoder** [comment] 2015-02-27 13:48
> I mean, who have authority to pick or discard those?

Project Lead and Project Collaborators make decisions.

> Does the core team chat internally even although just one member participate of the discussion?

Its depends on PR and it effect on framwork. In simple situations Collaborators can make decisions by self, in complex situations other Collaborators opinions asked, in super complex situations internal discussions used.

This is usual workflow for open source projects.

**Comment by slinstj** [comment] 2015-03-19 00:24
@creocoder, news here?

**Comment by trejder** [comment] 2015-04-30 06:30
Let me throw my own vote to this discussion. While, I agree with @yapi68, that this could be a little bit complicated, especially for the beginners, I must disagree with proposed PR and support @creocoder. Yii2 is a modern framework and using closures, wherever it is possible is the way how entire PHP development ships in my opinion. Think about this like about Javascript / jQuery, where you do virtually anything in callbacks, closures, anonymous functions etc. In my personal opinion (you're all free to disagree with me), implementing this PR and going to some kind of string manipulation, is a step back. After all, closures and anonymous functions are solution to modify, whatever you don't like in base implementation of anything. That's their function, right?

**Comment by m00nk** [comment] 2016-06-06 14:36
How about this:

```
$form->checkBoxList($model, 'items', [
		'val1' => 'Title 1',
		'val2' => 'Title 2:disabled',
		'val3' => 'Title 3'
	]
);
```

It is very clean (imho) and simple to use. For example, in that way I can use the simples query to get the necessary data:

```
$items = MyMod::find()
    ->select("concat(full_name, if(enabled=0, ':disabled', '') as title, id")
    ->indexBy('id')->column();
```

**Comment by samdark** [comment] 2016-06-06 17:01
I don't like introducing special syntax in strings.

**Comment by mikehaertl** [comment] 2016-06-06 18:23
I agree to @samdark and can't really see what the problem is with a callback. The example shown in the top post is lengthy, because it also adds another `<div>`. That's unrelated to the actual problem. If you just need to disable a single item, this should do it:

```
'item' => function($index, $label, $name, $checked, $value) {
    return Html::checkbox($name, $checked, [
        'value' => $value,
        'disabled' => $value==='value1',
    ]);
},
```

It's very readable and no special syntax involved.

**Comment by m00nk** [comment] 2016-06-06 19:20
Another idea:

```
$form->checkBoxList($model, 'items', [
        'val1' => 'Title 1',
        'val2' => ['Title 2' => 'disabled'],    // or maybe 'val2' => ['Title 2' => false]
        'val3' => 'Title 3'
    ]
);
```

**Comment by m00nk** [comment] 2016-06-06 19:23
Last idea:

```php
$form->checkBoxList($model, 'attr', $items, [
    'options' => [
         'disabled' => [1, 4, 25], // the list of disabled values
         . . . 
    ] 
]);

**Closed** 2016-11-12 15:16 UTC
Labels: expired, status:under discussion
