### ISSUE TITLE
Stack trace is shown in exception in production mode

### ISSUE THREAD

**Issue by steve-obrien** [yiisoft/yii2#10291] opened 2015-11-30 17:51 UTC
When setting the Response format to \yii\web\Response::FORMAT_RAW exceptions thrown within the following controller action and subsequent models etc show the full stack trace. Revealing potentially sensitive information.

Line 107 of the ErrorHandler perhaps needs to use the $this->convertExceptionToString($exception)?
Which seems to resolve the issue.

**Comment by samdark** [comment] 2015-11-30 18:22
Duplicate of https://github.com/yiisoft/yii2/issues/9750

**Closed by samdark** 2015-11-30 18:22 UTC

**Comment by samdark** [comment] 2015-11-30 18:28
Already fixed by #9874
