### ISSUE TITLE
Make \yii\base\ArrayableTrait::toArray truly recursive.

### ISSUE THREAD

**Issue by mcd-php** [yiisoft/yii2#7179] opened 2015-02-05 13:38 UTC
Or how can i make it myself and stay with framework guidelines and future plans ?

Example:

``` php
class SevereDisasterController extends \yii\rest\Controller {

    public function actionGetAllHands($customerId) {
        $allHands = Customer::find($customerId)
            ->with([
                'arContract',
                'arContract.obDepartment',
                'arContract.obDepartment.arJobPosition',
                'arContract.obDepartment.arJobPosition.obWorker',
                'arContract.obDepartment.arJobPosition.obWorker.arNotifyChannel',
            ])
            ->one();
        return $allHands->toArrayRecursive(); // Hypothetic
    }

} 
```

Expected: sheer tree of objects, all with limitations and renames defined in `fields()` and `extra_fields()`.

Observed: no more than one level of nesting if called like `->toArray([],$arWith,true)`. This level is given w/o limitations in `fields()`.

**Comment by mcd-php** [comment] 2015-02-05 15:12
Here it is - not covered with tests, maybe buggy, but works in my narrow case:

https://gist.github.com/mcd-php/e5236dd6150ea144b1da

**Comment by dynasource** [comment] 2016-11-04 17:54
if this is a bug, shouldnt this be fixed in BaseArrayHelper::toArray()?

**Comment by cebe** [comment] 2016-11-11 00:21
duplicate of #6844?

**Closed** 2016-11-11 00:22 UTC
Labels: status:to be verified
