### ISSUE TITLE
[Gii ] [PHP 8.1.9] error when generating model via GII

### ISSUE THREAD

**Issue by atmanegara** [yiisoft/yii2#19533] opened 2022-09-02 03:01 UTC
I tried to generate a model via Gii, an error occurred as shown in the picture, the database structure only has 2 fields, ID (int / AI) , Name (Varchar)

| Q                | A
| ---------------- | ---
| Yii version      |2.0.46
| PHP version      | 8.1.9
| Operating system | Windows 10
| Database   | Mariadb
| Apache | 2.4.47

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/9096711/188048226-b29db667-ba00-4277-974b-f4bb7b2ba757.png">

**Comment by samdark** [comment] 2022-09-04 19:20
Please check if the pull request https://github.com/yiisoft/yii2/pull/19539 fixes your issue.

**Comment by atmanegara** [comment] 2022-09-05 02:14
sorry sir, still the same problem

![image](https://user-images.githubusercontent.com/9096711/188346850-741d9825-fe35-47f0-a63c-b80dd6b80418.png)

**Comment by atmanegara** [comment] 2022-09-05 02:48
wait, after choose Generate ActiveQuery [solved]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/9096711/188351177-a6a18cf1-a5d4-46fb-9c8c-e3601fde723d.png">

**Comment by rob006** [comment] 2022-09-05 14:44
Looks like duplicate of https://github.com/yiisoft/yii2-gii/issues/505

**Comment by samdark** [comment] 2022-09-06 06:43
Will be fixed in Gii.

**Closed by samdark** 2022-09-06 06:43 UTC
Labels: type:bug
