### ISSUE TITLE
Only JS assets stopped loading

### ISSUE THREAD

**Issue by alexandernst** [yiisoft/yii2#8650] opened 2015-06-04 10:23 UTC
I was working on a project and suddenly all the JS files stopped loading in one and only one of my views. The CSS files from all the registered assets in that same view are loading fine.

I thought maybe some syntax error in some asset was causing that so I tried disabling one by one all the assets in my view, but none is causing the bug.

I tried deleting the `cache` folder and everything in the `runtime` folder, but the bug is still there.

I also can't reproduce that in none of my other views. I'm out of ideas, so I'm open to any suggestions/ideas about how to isolate that bug.

PS: Changing the `$basePath` of one of the assets registered in the view to something non-existent triggers the typical "Can't load file" error in Chrome's dev tools, but then, if I fix back the `$basePath` path, the error disappears, but my JS files don't load. (I can't see any JS files loaded in Chrome's network tab).

**Comment by samdark** [comment] 2015-06-04 10:49
Closing since there's no way to reproduce it.

**Comment by alexandernst** [comment] 2015-06-04 10:49
Found it. Funny how something as silly as a missing `-` in a closing HTML comment (`-->`) can cause so much trouble. I guess Yii kept loading all the CSS files as they are at the top of the document, while all scripts are at the bottom (which got commented because of the missing `-`).

**Closed by samdark** 2015-06-04 10:49 UTC
