### ISSUE TITLE
Model->validate  have  a bug  !!!!

### ISSUE THREAD

**Issue by huaiguoguo** [yiisoft/yii2#17414] opened 2019-07-06 10:23 UTC
### What steps will reproduce the problem?

当我没有输入任何参数的时候，竟然没有报错，我的Model里面定义了必填的

![image](https://user-images.githubusercontent.com/1888094/60754905-c9fe7080-a01a-11e9-8a39-b92dff39a8ee.png)

![image](https://user-images.githubusercontent.com/1888094/60754896-a9361b00-a01a-11e9-8ff4-e6d54d539622.png)

this is  login()
![image](https://user-images.githubusercontent.com/1888094/60755137-cb7d6800-a01d-11e9-9248-85c47ad2d2ed.png)

### What is the expected result?
![image](https://user-images.githubusercontent.com/1888094/60754896-a9361b00-a01a-11e9-8ff4-e6d54d539622.png)

![image](https://user-images.githubusercontent.com/1888094/60754965-79d3de00-a01b-11e9-9456-d6a60d348304.png)

![image](https://user-images.githubusercontent.com/1888094/60754924-016d1d00-a01b-11e9-9a67-fce6fdfef28f.png)

### What do you get instead?
只好手写代码验证是否为空了

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.22
| PHP version      |  7.3.6-nts
| Operating system | win10 1903 x64

**Comment by samdark** [comment] 2019-07-06 10:34
What is the code of your `login()` method?

**Comment by huaiguoguo** [comment] 2019-07-06 10:44
@samdark 
![image](https://user-images.githubusercontent.com/1888094/60755150-113a3080-a01e-11e9-92eb-0ec3c1721fb5.png)

**Comment by huaiguoguo** [comment] 2019-07-06 10:48
> What is the code of your `login()` method?

![image](https://user-images.githubusercontent.com/1888094/60755183-94f41d00-a01e-11e9-849f-54020ec32189.png)

**Comment by huaiguoguo** [comment] 2019-07-06 12:15
@samdark 
that is great，  With pleasure，  thank you  !!

**Comment by alex-code** [comment] 2019-07-06 13:50
Did you mean to set the `formName` param of `load` to an empty string?
It could be returning false here so it never gets to the `$model->login()` condition.

```php
if ($model->load(Yii::$app->request->post()) && $model->login()) {
  // ...
}
```

**Comment by samdark** [comment] 2019-07-06 15:08
Yes, that is likely what happens.

**Comment by huaiguoguo** [comment] 2019-07-07 10:31
> Did you mean to set the `formName` param of `load` to an empty string?
> It could be returning false here so it never gets to the `$model->login()` condition.
> 
> ```
> if ($model->load(Yii::$app->request->post()) && $model->login()) {
>   // ...
> }
> ```

@samdark 

###  catch a empty when no paramer was filled in 
![image](https://user-images.githubusercontent.com/1888094/60767048-912ace00-a0e4-11e9-824f-f94e41d9ef76.png)

![image](https://user-images.githubusercontent.com/1888094/60767041-72c4d280-a0e4-11e9-88b1-0a351b847af1.png)


### catch a errors   when fill  only one paramer  
![image](https://user-images.githubusercontent.com/1888094/60767064-c46d5d00-a0e4-11e9-98f4-2b917568140f.png)

**Comment by alex-code** [comment] 2019-07-07 11:52
Could you try
```php
var_dump($model->load(Yii::$app->request->post()));
var_dump($model->login());
```
So we can determine if something fails here?

**Comment by alex-code** [comment] 2019-07-09 14:41
Thinking about this more if you don't provide any `POST` data `load()` will return false and never reach the validate method.

If you only provide one value in the `POST` it will load and reach the validate method hence the odd issue you're having.

If the `POST` was from a `<form/>` it would have empty values which would be loaded.

Is this for a `REST` API? If so you could ignore the result of `load()` and just run `login()`.
```php
$model->load(Yii::$app->request->post());
if ($model->login()) {
  // ...
}
```

**Comment by samdark** [comment] 2019-07-16 14:32
Need a test set to reproduce the issue. Then we'll be able to fix it in case it's not designed behavior.

**Comment by alex-code** [comment] 2019-07-16 15:24
@samdark I think it's working as expected. It's just the way their `actionLogin` works.

If there's no `POST` data `load()` will return false and it won't get to the `login()` method hence no validation.
If only one value is provided `load` will succeed and it'll get to the `login()` method and perform validation.

**Comment by samdark** [comment] 2019-07-16 16:58
Looks like so. Closing issue for now. @huaiguoguo if you'll get a test case I'll reopen it / verify validity of the issue.

**Closed by samdark** 2019-07-16 16:58 UTC
Labels: status:need more info
