### ISSUE TITLE
Flash Messages Not Persisting in Firefox

### ISSUE THREAD

**Issue by cozumel424** [yiisoft/yii2#11879] opened 2016-07-03 21:41 UTC
### What steps will reproduce the problem?

```
Yii::$app->session->setFlash('success', 'msg.');
return $this->redirect(Yii::$app->urlManager->createUrl(['some/url']));
```

If the redirect is a 302 (ajax posting a form, then redirecting) in Firefox the session is emptied before displaying it. In Chrome it works ok, no idea why!

Maybe relevant http://oi68.tinypic.com/2zyx7rm.jpg PHP session settings.

### What's causing it?
It looks like `updateFlashCounters()` in` /vendor/yiisoft/yii2/web/Session.php` is getting called twice. Determined by putting an `echo 'here';` in it. But only in Firefox?

I upgraded to PHP 7 the other day and am pretty sure I didn't have this issue before, but I don't have PHP 5 to test it on anymore, it could be something to do with session handling in PHP 7 but I'm not sure.

### Kludgy Fix

Just updated the counter to 1 from 0, so the session is still active on the second (actual) viewing.

`/vendor/yiisoft/yii2/web/Session.php`

```
protected function updateFlashCounters()
    {
        $counters = $this->get($this->flashParam, []);
        if (is_array($counters)) {
            foreach ($counters as $key => $count) {
                if ($count > 1) {
                    unset($counters[$key], $_SESSION[$key]);
                } elseif ($count <= 1) {
                    $counters[$key]++;
                }
            }
            $_SESSION[$this->flashParam] = $counters;
        } else {
            // fix the unexpected problem that flashParam doesn't return an array
            unset($_SESSION[$this->flashParam]);
        }
    }

public function getAllFlashes($delete = false)
    {
        $counters = $this->get($this->flashParam, []);
        $flashes = [];
        foreach (array_keys($counters) as $key) {
            if (array_key_exists($key, $_SESSION)) {
                $flashes[$key] = $_SESSION[$key];
                if ($delete) {
                    unset($counters[$key], $_SESSION[$key]);
                } elseif ($counters[$key] < 1) {
                    // mark for deletion in the next request
                    $counters[$key] = $counters[$key] + 1;
                }
            } else {
                unset($counters[$key]);
            }
        }

        $_SESSION[$this->flashParam] = $counters;

        return $flashes;
    }

public function getFlash($key, $defaultValue = null, $delete = false)
    {
        $counters = $this->get($this->flashParam, []);
        if (isset($counters[$key])) {
            $value = $this->get($key, $defaultValue);
            if ($delete) {
                $this->removeFlash($key);
            } elseif ($counters[$key] < 1) {
                // mark for deletion in the next request
                $counters[$key] = $counters[$key] + 1;
                $_SESSION[$this->flashParam] = $counters;
            }

            return $value;
        } else {
            return $defaultValue;
        }
    }
```

### Related Issues
[https://github.com/yiisoft/yii2/issues/3956](https://github.com/yiisoft/yii2/issues/3956)
[https://github.com/yiisoft/yii2/pull/3960](https://github.com/yiisoft/yii2/pull/3960)
[https://github.com/yiisoft/yii2/issues/4415](https://github.com/yiisoft/yii2/issues/4415)
[https://github.com/yiisoft/yii2/issues/9187](https://github.com/yiisoft/yii2/issues/9187)
[https://github.com/yiisoft/yii2/issues/11351](https://github.com/yiisoft/yii2/issues/11351)
[https://github.com/yiisoft/yii2/issues/5370](https://github.com/yiisoft/yii2/issues/5370)
[https://github.com/yiisoft/yii2/issues/2510](https://github.com/yiisoft/yii2/issues/2510)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.08
| PHP version      | 7.0.8
| Operating system | Ubuntu 14.04

**Comment by mikehaertl** [comment] 2016-07-04 06:44
Blind guess: Some content on your page (e.g. some asset with wrong URL) or some js code is causing another Yii request and that's where the flash message gets flushed. It may work in one browser due to minor differences in loading order or status caching of failed requests.

**Comment by samdark** [comment] 2016-07-04 07:18
I think @mikehaertl is right. I've checked it multiple times and I can say that if there are no duplicate requests made by application itself, Yii handles it well.

@cozumel424 if you'll be able to reproduce the issue using basic application template, let us know. Until then I'm closing the issue.

**Closed by samdark** 2016-07-04 07:18 UTC

**Comment by cozumel424** [comment] 2016-07-04 15:10
I can't duplicate the issue with a fresh install, I must have messed up somewhere. Thanks for the help and sorry for wasting your time!  I'll update when I find out what caused it, it might help someone.

**Comment by cozumel424** [comment] 2016-07-05 02:41
It fixed itself when I emptied the vendor folder and did a reinstall! /shrug

**Comment by karmrajzala** [comment] 2016-07-05 05:10
@cozumel424 : Yes i had faced this issue previously but it generate randomly.
