### ISSUE TITLE
Implicit conversion from data type char to varbinary(max) is not allowed

### ISSUE THREAD

**Issue by OkyTrilupito** [yiisoft/yii2#15068] opened 2017-11-02 06:21 UTC
### What steps will reproduce the problem?
i use yii2-admin with sql server, when i create role, assign role and etc, I always get an error. 
i look this problem just in rbac, cz in other CRUD still work.
![image](https://user-images.githubusercontent.com/9190451/32312503-bb45c66e-bfd0-11e7-89b5-612bd80148eb.png)

### What is the expected result?
how to solve this rbac problem?

### What do you get instead?
SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Implicit conversion from data type char to varbinary(max) is not allowed. Use the CONVERT function to run this query.
The SQL being executed was: INSERT INTO [auth_item] ([name], [type], [description], [rule_name], [data], [created_at], [updated_at]) VALUES ('test', 1, NULL, NULL, NULL, 1509601715, 1509601715)
Error Info: Array
(
    [0] => 42000
    [1] => 257
    [2] => [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Implicit conversion from data type char to varbinary(max) is not allowed.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.1
| Operating system | SQL Server

**Comment by samdark** [comment] 2017-11-02 08:36
Duplicate of https://github.com/yiisoft/yii2/issues/13436

**Closed by samdark** 2017-11-02 08:36 UTC
Labels: MSSQL

**Comment by OkyTrilupito** [comment] 2017-11-03 08:09
@samdark  this problem fixing in version 2.0.13? and this solution is, just waiting for the next version?

**Comment by samdark** [comment] 2017-11-03 08:36
Why waiting? http://www.yiiframework.com/news/149/yii-2-0-13-is-released/

**Comment by OkyTrilupito** [comment] 2017-11-03 09:47
thank you very much 💃 I am trying to upgrade now 👍
