### ISSUE TITLE
"Numbers" with leading and trailing spaces are passed by NumberValidator

### ISSUE THREAD

**Issue by karelvasicek** [yiisoft/yii2#18544] opened 2021-03-03 09:37 UTC
Possible duplicate of (unresponded) #15474

### What steps will reproduce the problem?

1. use f.ex. `[['amount'], 'number']` validation rule in model
2. validate any value with leading or trailing space

### What is the expected result?

Validation fails.

### What do you get instead?

Validation passes and a `A non well formed numeric value encountered in ...` error occurs in any calculation using _validated_ number.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.40
| PHP version      | 7.2.33
| Operating system | Fedora 30

**Comment by bizley** [comment] 2021-03-03 09:45
Confirmed. I think we should trim the value.

**Comment by karelvasicek** [comment] 2021-03-03 09:50
> I think we should trim the value.

I think that `NumberValidator ` should not manipulate the validated value. Trimming the value before it is used (or using custom patterns in validation rule) is a workaround for this. `$integerPattern` and `$numberPattern` should be changed IMO.

**Comment by bizley** [comment] 2021-03-03 10:06
Hmm, right. There is always filter validator for trimming.

**Comment by karelvasicek** [comment] 2021-03-03 10:20
@samdark - do I understand it correctly that numbers with leading and trailing spaces are considered valid numbers when they produce `A non well formed numeric value encountered in ...` errors?

**Comment by bizley** [comment] 2021-03-03 10:24
Ehm, @samdark why have you closed this?

**Comment by samdark** [comment] 2021-03-03 10:26
@bizley thought it's another issue :) Sorry.

**Comment by lubosdz** [comment] 2021-03-04 10:50
Value may not be manipulated in any way during evaluation. 
Thus only non-trivial regex adjustment or indirect evaluation of a value copy is possible e.g. 
```
if(floatval($value) != $value){
    ... add error message ...
}
```
Just of out curiosity - this very unlucky behaviour which is causing lots of pain since has been introduced in [PHP 7.1 - RFC](https://wiki.php.net/rfc/invalid_strings_in_arithmetic).

**Closed** 2021-03-10 21:40 UTC
Labels: type:bug
