### ISSUE TITLE
Allow using custom constructor with non-optional arguments in AR-based models

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#5786] opened 2014-10-27 16:08 UTC
This issue sums up #5771 by @Ragazzo.
### What's wrong

Currently it's not possible to use non-optional arguments in AR constructor:

``` php
class User extends ActiveRecord
{
    public function __construct($password, $config = []) {
        $this->password = $password;
        parent::__construct($config);
    }
}
```

When getting data from database you'll get:

```
Warning: Missing argument 1 for User::__construct()
```
### How to solve it

When records are retrieved from database instances are created using `instantiate` method. Default implementation is the following:

``` php
public static function instantiate($row)
{
    return new static;
}
```

In order to solve it we should avoid calling constructor. The way @Ragazzo proposed is [using unserialize](http://www.doctrine-project.org/2010/03/21/doctrine-2-give-me-my-constructor-back.html):

``` php
public function instantiate()
{
    if ($this->_prototype === null) {
        $className = get_called_class();
        $this->_prototype = unserialize(sprintf('O:%d:"%s":0:{}', strlen($className), $className));
    }
    $object = clone $this->_prototype;
    $object->init();
    return $object;
}
```

Another approach is [to use reflection](http://php.net/manual/ru/reflectionclass.newinstancewithoutconstructor.php).
### Is it backwards compatible

No.
### Is there performance implact

Should be tested but it should be OK because instance is unsertialized once then cloned. See code in "How to solve it".
### Problems?

When instantiating existing database rows constructor will not be called. While constructing new AR instance and existing AR instance are different it's could cause confusion. See https://github.com/yiisoft/yii2/issues/5771#issuecomment-60518517

**Comment by Faryshta** [comment] 2015-01-30 20:50
What is the point of forcing the constructor to ask for a param, then force php to not use that constructor?

A better approach IMHO would be

```php
class User extends ActiveRecord
{
    public function __construct($config = []) {
         $this->password = hash($password);
        parent::__construct($config);
    }

    public static function instantiate($row)
    {
         $password = $row['password'];
         return new static($password);
    }
```

It wouldn't have to change the core code, you can rewrite the `instantiate` method on your new ActiveRecord as the documentation encourages you to do it.

**Comment by lynicidn** [comment] 2015-01-30 21:09
remember by related records
am up it only via config https://github.com/yiisoft/yii2/issues/4270

**Comment by lynicidn** [comment] 2015-01-30 21:10
example pr for view bc https://github.com/yiisoft/yii2/commit/2b0c37c867f44e12e7b87873105e846c09cab754

**Comment by cebe** [comment] 2016-03-04 01:34
closed issue #8639 as duplicate of this one. Citing some relevant comments here:

>I have checked in some fixes that reduce the problem to the use of asArray() and joinWith(). Will address these later but in general using DI and custom constructor should work now.

> there is another place :-/ https://github.com/yiisoft/yii2/blob/ded158ed43cfb0a9551d692b569ef85e91f0b4e5/framework/data/ActiveDataProvider.php#L176

> another one: https://github.com/yiisoft/yii2/blob/e0b0679f3a31753098e6de03e9a5fe9409c00719/framework/grid/DataColumn.php#L125

**Comment by zharnikov** [comment] 2017-01-06 11:52
I think, injecting dependencies into ARs is a bad pactice. We should consider AR as an Entity in terms of DDD. Entities shouldn't have any dependencies in their constructors as they aren't a part of their state. If you implement it in yii it will become a possibility for creating God AR classes (code smell).

**Comment by samdark** [comment] 2017-01-06 11:55
It is mainly about constructing entities using constructor, not about injecting dependencies.

**Comment by zharnikov** [comment] 2017-01-06 13:02
I'm sorry. Will move it to the apropriate thread.

**Comment by samdark** [comment] 2017-02-23 21:57
https://github.com/samdark/hydrator is a standalone implementation of such object instantiation.

**Closed** 2017-08-29 12:14 UTC
Labels: complexity:medium, status:under discussion
