### ISSUE TITLE
Protected for $this->getTableNameAndAlias();

### ISSUE THREAD

**Issue by loveorigami** [yiisoft/yii2#13686] opened 2017-03-02 15:26 UTC
I have common MyActiveQuery with 
```php
namespace common\db;

use yii\db\ActiveQuery as YiiQuery;
/**
 * Class ActiveQuery
 * Common ActiveQuery with system scopes.
 */
class MyActiveQuery extends YiiQuery
{
...
    public function published($state = true)
    {
        $this->andWhere(["status" => $state]);
        return $this;
    }
...
}
```

this method not worked for 
```php
$posts = Post::find()
            ->innerJoinWith(['category c' => function($query){
                    $query->published()
            }])
            ->published()
            ->all();
```
because status in published() not have alias

I can get alias from $this->getTableNameAndAlias, but this method is private
https://github.com/yiisoft/yii2/blob/bfd0de3e42f79d9d401691c1d85061f025b1417f/framework/db/ActiveQuery.php#L559

If getTableNameAndAlias will be ```**protected**```, I can
```php
namespace common\db;

use yii\db\ActiveQuery as YiiQuery;
/**
 * Class ActiveQuery
 * Common ActiveQuery with system scopes.
 */
class MyActiveQuery extends YiiQuery
{
    /**
     * @param bool $state если true выбираем активные иначе не активные
     * @return $this
     */
    public function published($state = true)
    {
        $this->andWhere([$this->getAlias().".status" => $state]);
        return $this;
    }

    /**
     * @param $slug
     * @return $this
     */
    public function bySlug($slug)
    {
        $this->andWhere([$this->getAlias().".slug" => $slug]);
        return $this;
    }

    /**
     * alias for table
     * @return null|string
     */
    public function getAlias()
    {
       list(, $alias) = $this->getTableNameAndAlias();
       return $alias;
    }
}

```

and all queries will be worked good.

**Comment by rob006** [comment] 2017-03-02 15:35
Related: #11646

**Comment by loveorigami** [comment] 2017-03-03 06:43
@rob006 In my case it is not worked, if I do
```php
    /**
     * alias for table
     * @return null|string
     */
    public function getAlias()
    {
       return '@alias';
    }
```
It will be in future?

**Comment by rob006** [comment] 2017-03-03 08:17
@loveorigami It is not merged yet, so (obviously) it is not working right now. You could merge this PR to your fork and test if it work.

**Comment by cebe** [comment] 2017-03-03 10:17
this is a duplicate of #7263

**Closed by cebe** 2017-03-03 10:17 UTC
