### ISSUE TITLE
OnCondition error

### ISSUE THREAD

**Issue by master-7** [yiisoft/yii2#9543] opened 2015-08-28 13:22 UTC
My problem

```sql
CREATE TABLE user (
id int(11) NOT NULL AUTO_INCREMENT,
username varchar(128) NOT NULL,
surname varchar(50) NOT NULL,
name varchar(50) NOT NULL,
avatar varchar(255) DEFAULT NULL,
sex int(1) DEFAULT '0',
PRIMARY KEY (id,username,surname,name),
UNIQUE KEY email_UNIQUE (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE work (
id int(11) NOT NULL AUTO_INCREMENT,
logo varchar(255) NOT NULL,
title varchar(255) NOT NULL,
description mediumtext NOT NULL,
create_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE work_comment (
id int(11) NOT NULL AUTO_INCREMENT,
work_id int(11) NOT NULL,
author_id int(11) NOT NULL,
post_id int(11) DEFAULT NULL,
author_hidden int(1) NOT NULL,
comment text NOT NULL,
positive int(11) NOT NULL,
negative int(11) NOT NULL,
status int(1) NOT NULL DEFAULT '1',
create_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
KEY fk_work_comment_1_idx (work_id),
KEY fk_work_comment_2_idx (author_id),
KEY fk_work_comment_3 (post_id),
CONSTRAINT fk_work_comment_1 FOREIGN KEY (work_id) REFERENCES work (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT fk_work_comment_2 FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT fk_work_comment_3 FOREIGN KEY (post_id) REFERENCES work_comment (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

AR query

```php
$Work = Work::find()
->joinWith([
'WorkComments',
'WorkComments.author' => function ($query) {
$query->andOnCondition('author_hidden = 0');
},
'WorkComments.commentPost',
'WorkComments.commentPost.authorPost'
])
->asArray()
->one();
```

My Error

```
Database Exception – yii\db\Exception

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'author_hidden' in 'where clause'
The SQL being executed was: SELECT id, name, surname, avatar, status FROM prm_user author_comment WHERE (id='1') AND (author_hidden = 0)
Error Info: Array
(
[0] => 42S22
[1] => 1054
[2] => Unknown column 'author_hidden' in 'where clause'
)
↵
Caused by: PDOException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'author_hidden' in 'where clause'

in /vendor/yiisoft/yii2/db/Command.php at line 837
```

OnCondition copied in a subquery - this is a bug.

**Comment by samdark** [comment] 2015-08-28 14:51
Duplicate of #9535

**Closed by samdark** 2015-08-28 14:51 UTC
Labels: feature:db, status:to be verified, type:bug
