### ISSUE TITLE
Module::_viewPath and Module::_layoutPath as protected instead of private.

### ISSUE THREAD

**Issue by vova07** [yiisoft/yii2#7647] opened 2015-03-09 22:26 UTC
So here is the case:
My module class contain this code:
```php
/**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        if ($this->getIsBackend() === true) {
            $this->setViewPath('@vova07/module/views/backend');
        } else {
            $this->setViewPath('@vova07/module/views/frontend');
        }
    }
```
But in this case I can't use `viewPath` in my app config file.

I can't rewrite [`getViewPath`](https://github.com/yiisoft/yii2/blob/master/framework/base/Module.php#L244) method in module class because there is used `private` variable.

It's an easy change but it's really helpful.

**Comment by Rathil** [comment] 2015-03-09 22:39
And what you do not like the approach you described?

**Comment by vova07** [comment] 2015-03-09 22:41
I don't like that I can't have an flexible and modern module' view configuration.

**Comment by Rathil** [comment] 2015-03-09 22:45
If you look ideologically - You have been given the opportunity to change the value.

**Comment by vova07** [comment] 2015-03-09 22:45
There is: http://www.yiiframework.com/doc-2.0/yii-base-module.html#$viewPath-detail so it means that we have a possibility to configure our modules view by this param.
But in my case, because I need an different default view for my module, this option is impossible, and I can't use the `viewPath` as an alternative of view configuration.

**Comment by Rathil** [comment] 2015-03-09 22:46
+ You can always override this method and make their implementation.

**Comment by vova07** [comment] 2015-03-09 22:46
Are you sure?

**Comment by Rathil** [comment] 2015-03-09 22:47
Of Course

**Comment by vova07** [comment] 2015-03-09 22:51
Ok, then take a try to override this method with some different value by default, but save at the same time the possibility to set the view by config file:
```php
'modules' => [
  'module' => [
    ...
    'viewPath' => 'not/default/value'
    ...
  ]
]
```

**Comment by Rathil** [comment] 2015-03-09 22:58
I did not immediately understood you correctly.
You can not configure this setting in the configuration file...

**Comment by Rathil** [comment] 2015-03-09 22:59
Frankly, quite specific desire :)

**Comment by vova07** [comment] 2015-03-09 23:02
No, I can. See again: http://www.yiiframework.com/doc-2.0/yii-base-module.html#$viewPath-detail and this is why a create this issue.

**Comment by vova07** [comment] 2015-03-09 23:03
> Frankly, quite specific desire :)

I don't think so. Sorry!

**Comment by mikehaertl** [comment] 2015-03-10 08:04
In your class you could put something like:

```php
<?php
protected $_viewPathConfigured = false;

public function getViewPath()
{
    if ($this->_viewPathConfigured) {
        // no view path configured... your code goes here
    } else {
        return parent::getViewPath();
    }
}

public function setViewPath($value)
{
    $this->_viewPathConfigured = true;
    parent::setViewPath($value);
}
```

**Comment by vova07** [comment] 2015-03-10 09:44
@mikehaertl Yes you are right, and I know this method, but it is ugly. Why to not use the standard option, that is clear for all? I share my extension, so a lot of people use them, and I don't think that it is a good idea, to do double the config params. Some people may not understand why there is 2 options, and why the Yii 2 way doesn't work.
The temporary solution that I use is:
```php
if ($this->getViewPath() === $this->getBasePath() . DIRECTORY_SEPARATOR . 'views') {
            if ($this->getIsBackend() === true) {
                $this->setViewPath('@vova07/module/views/backend');
            } else {
                $this->setViewPath('@vova07/module/views/frontend');
            }
        }
```
But how I said it's ugly.

Hope somebody from Yii team will take a look to this issue.

**Comment by mikehaertl** [comment] 2015-03-10 10:07
Honestly I think, that your use case is too specific - and not really good by design either. You should not do too much auto magic with these config settings. If there's a difference between frontend and backend configuration, it should be clearly visible from your config files, not hidden somewhere in your classes.

But that's just my opinion.

**Comment by creocoder** [comment] 2015-03-10 11:44
Absolutte agree with @mikehaertl about design points, etc.

But on other side class designed to be extended and its rare case when private properties make sence. In case of issue its obvious that such properties should be protected.

**Comment by creocoder** [comment] 2015-03-10 11:48
@vova07 Try to make PR and if you'll do it, don't forget about remove `_` prefix from properties name since its BC.

**Comment by cebe** [comment] 2015-03-10 13:13
I do not get the problem, you can simply override getter and setter and you have a working class, can't you?

```php
    private $_viewPath;

   /**
     * Returns the directory that contains the view files for this module.
     * @return string the root directory of view files. Defaults to "[[basePath]]/views".
     */
    public function getViewPath()
    {
        if ($this->_viewPath !== null) {
            return $this->_viewPath;
        } else {
            return $this->_viewPath = /* your default value here */;
        }
    }

    /**
     * Sets the directory that contains the view files.
     * @param string $path the root directory of view files.
     * @throws InvalidParamException if the directory is invalid
     */
    public function setViewPath($path)
    {
        $this->_viewPath = Yii::getAlias($path);
    }
``` 

what am I missing?

**Comment by vova07** [comment] 2015-03-10 14:22
> it should be clearly visible from your config files, not hidden somewhere in your classes.

It not hidden somewhere. It's just a default value. Why do I need to complicate my module configuration with default values?! If you are not agree with me, then the default value `$this->getBasePath() . DIRECTORY_SEPARATOR . 'views'` also not make sense, and all Yii 2 users, need to configure the default value on each module setting up.

I just give an example, and the directory names are just for demo. Their name can be "red" and "blue" or "single" and "multiple", and the final user my not be really familiar with my extension, but just to run it, he will need to lear a lot of docs, just to do it right. I realy disagree we you, and I think it's not a specific way just for blog system, or for landing pages, but Yii it's not a framework that is used just for simple sites, there is a lot of more complicated things. (SAAS, CRM, etc.) This is why a lot of people choose framework and not CMS.

@cebe No, it will not work.

**Comment by creocoder** [comment] 2015-03-10 14:37
@vova07 

> @cebe No, it will not work.

Example shown by @cebe will work ofcourse. What you mean by saying this will not work?

**Comment by vova07** [comment] 2015-03-10 14:40
I was tried yesterday to do this hack, but it seams that somewhere deep in framework code is used parent' private var instead of current instance, and of corse because this one is null by default we get all the time the default value, and the configuration doesn't work.

**Comment by creocoder** [comment] 2015-03-10 14:45
@vova07 Its strange. Ok, can you show how you'll solve issue in case when property is protected?

**Comment by vova07** [comment] 2015-03-10 14:47
I'll just override the `getViewPath` method, and I'll return my own default value.

**Comment by creocoder** [comment] 2015-03-10 14:47
@vova07 Can you show concrette implementation?

**Comment by creocoder** [comment] 2015-03-10 14:48
@vova07 With your module class, with that method, etc...

**Comment by cebe** [comment] 2015-03-10 14:49
@vova07 the property is private so usage can only be in the Module class. getter and setter are the only methods using it. There should be no issues with the implementation I showed you. If there are, please state explicitly what is not working.

**Comment by vova07** [comment] 2015-03-10 14:50
```php
class MyModule extends \yii\base\Module
{
    ...
    public function getViewPath()
    {
        if ($this->viewPath !== null) {
            return $this->viewPath;
        } else {
            return $this->viewPath = '@vova07/mymodule/views/frontend';
        }
    }
    ...
}
```
This will work because `viewPath` will be protected and it will be available in `MyModule` class.

**Comment by creocoder** [comment] 2015-03-10 14:53
@vova07 

Ok, now look...

```php
class MyModule extends \yii\base\Module
{
    ...
    public function getViewPath()
    {
        if (parent::getViewPath() !== null) {
            return parent::getViewPath();
        } else {
            return '@vova07/mymodule/views/frontend';
        }
    }
    ...
}
```

**Comment by creocoder** [comment] 2015-03-10 14:55
@vova07 And slightly more...

> I was tried yesterday to do this hack

This is not hack, this OOP basics.

> code is used parent' private var instead of current instance

Term like "parent private var" is just nonsense ) ... and this is again OOP basics.

**Comment by mikehaertl** [comment] 2015-03-10 15:01
@vova07 did you maybe forget to add `private $_viewPath` to your class? Otherwhise you can't of course access the private member of the parent (if that's what you meant).

Apart from that cebe's solution should work fine for you.

**Comment by vova07** [comment] 2015-03-10 15:11
@creocoder How I already said, the problem is that `parent::getViewPath()` will never be null, because in `parent` class in case of null, it will return the default value.

**Comment by creocoder** [comment] 2015-03-10 15:14
@cebe Issue starter obviously wrong that `getViewPath()` can't be overriden without making property protected.

But there is absolluttely different point why it should be protected. From practical reasons classes which designed for extending should not contains private properties since it make extending harder. In that case having private give nothing. Having it propected will allow override only `getViewPath()` and not touch `setViewPath()` if its logic is fine. If private used here from incapsulation point of view. That this is wrong again in that case. Yii and SOLID is just fantastic... )

@vova07 As i said before you trouble can be solved without raise property visibility. @cebe shown correct example for that. But issue is still correct from different points (not first post points).

**Comment by vova07** [comment] 2015-03-10 15:20
@creocoder Yes, you are right, the @cebe solution work, there was my mistake because instead of `_viewPath` I added `viewPath` attribute. But however, I don't thinks that this solution is right, and it's really ugly. How you said:
> Having it propected will allow override only getViewPath() and not touch setViewPath()

I think protected will be really better. And I'm completely agree with you:
> From practical reasons classes which designed for extending should not contains private properties since it make extending harder.

**Comment by creocoder** [comment] 2015-03-10 15:24
@vova07 Yes from that point of view things dramatically changes. And here we have just wrong design decision inside framework. While overriding is still possible using private there give us nothing except pain. It involve us to override methods which we do not want override. And this is on background that `Module` is born to be extended.

Btw we have lot of places like that... and this is horrible. But this is usual inside Yii, it plays in "object oriented design" on wrong fields )

**Comment by creocoder** [comment] 2015-03-10 15:27
Good news that all those places can be easily fixed without breaking BC. The main problem is the awareness of why design decisions was wrong... )

**Comment by vova07** [comment] 2015-03-10 15:50
I'll do a PR soon. Thanks!

**Comment by mikehaertl** [comment] 2015-03-10 16:23
@vova07 Another approach would be:

```php
<?php
class MyModule extends \yii\base\Module
{
    public function __construct($id, $parent = null, $config = [])
    {
        if (!isset($config['viewPath'])) {
            $config['viewPath'] = // your code here
        }
        parent::__construct($id, $parent, $config);
    }
}
```

**Comment by qiangxue** [comment] 2015-03-10 16:55
The reason for using the private member here is because we don't want you to incorrectly access this member while it is null. The PR made by @vova07 will certainly break BC because if you have old code in a module that accesses `$this->viewPath`, you will be in trouble since `viewPath` now refers to the protected member (instead of the getter property) which is not initialized.

**Comment by qiangxue** [comment] 2015-03-10 16:56
In this particular issue because the requirement is a bit special (as it relies on the uninitialized state of a variable), you may use the solution proposed by @mikehaertl.

**Comment by vova07** [comment] 2015-03-10 18:30
ok, I got it, but if there is a problems with `viewPath` maybe we can leave this `protected $_viewPath` ?

**Comment by creocoder** [comment] 2015-03-10 19:40
@vova07 Its more ugly solution that live with current )

**Comment by klimov-paul** [comment] 2015-04-20 12:14
I agreed with @qiangxue. Issue is not generic and can be easily bypassed.

**Closed by klimov-paul** 2015-04-20 12:14 UTC
