### ISSUE TITLE
Relation "migration" already exists error while executing yii migrate/history

### ISSUE THREAD

**Issue by lourdas** [yiisoft/yii2#9344] opened 2015-08-07 07:59 UTC
I've created a migration, applied it successfully and when I run `yii.bat migrate/history` I get the error:

```
W:\app>yii.bat migrate/history
Yii Migration Tool (based on Yii v2.0.6)

Creating migration history table "migration"...Exception 'yii\db\Exception' with
 message 'SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "migration" alrea
dy exists
The SQL being executed was: CREATE TABLE "migration" (
        "version" varchar(180) NOT NULL PRIMARY KEY,
        "apply_time" integer
)'

in W:\app\vendor\yiisoft\yii2\db\Schema.php:628

Error Info:
Array
(
    [0] => 42P07
    [1] => 7
    [2] => ERROR:  relation "migration" already exists
)
```

While the table already exists (since the migration already succeeded in the first place). I'm using PostgreSQL 9.3.9 as a database backend.
This is for the latest stable version of Yii (2.0.6).

**Comment by lourdas** [comment] 2015-08-07 08:26
I pinned down the issue. While the migration table is successfully created in the schema I'm working, the next time it checks if it exists or not, it fails, because the default schema at that case is the `public` schema and not the schema I'm working. `resolveTableNames()` in `pgsql/Schema.php` returns `public` as the `$schemaName` in `$table` object.

I guess a workaround is to hard code the table name in application config file.

**Comment by lourdas** [comment] 2015-08-07 20:58
migrate/down also does not work. It seems that using migrations with postgresql could be an issue.

**Comment by cebe** [comment] 2015-08-09 21:06
can you give more details about the defined schemas and how you configured the yii database connection=

**Comment by lourdas** [comment] 2015-08-09 21:09
What kind of details do you need?

**Comment by cebe** [comment] 2015-08-09 21:15
wasn't that clear from my message? :) show how the different schemas are defined and how you configured the 'db' appication component.

**Comment by lourdas** [comment] 2015-08-09 21:28
The `db` component is defined as this:
```
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=localhost;dbname=mydb',
    'username' => 'ktin_mitrwo',
    'password' => 'ktin_mitrwo',
    'charset' => 'utf8',
    'emulatePrepare' => false,
];
```
I'm using a schema named `expmanager` and the database owner is a user with the same name. I have defined a `schema` application parameter in `params.php` as this:
```
return [
    'schema' => 'ktin_mitrwo',
];
```
And in each model, I have defined the `tableName()` function as this:
```
public static function tableName()
{
    return Yii::$app->params['schema'] . '.ekmetalleush';
}
```
So that in case I changed the schema name, it would only take to change the global application parameter. The `public` schema is not used at all.

The migration class is defined as this (part of it):
```
    public function safeUp()
    {
        $schema = Yii::$app->params['schema'];

        $this->execute('ALTER TABLE ' . $schema
            . '.ekmetalleush RENAME CONSTRAINT id_ekmetalleush_pk TO ekmetalleush_pk');

        $this->execute(<<<QUERY
CREATE TABLE $schema.sygkrothma
(
   id serial NOT NULL,
   CONSTRAINT sygkrothma_pk PRIMARY KEY (id)
)
WITH (
  OIDS = FALSE
)
QUERY
        );
        $this->execute('ALTER TABLE ' . $schema . '.sygkrothma OWNER TO ktin_mitrwo');

        $this->execute(<<<QUERY
CREATE TABLE $schema.systegasmenh_ekmetalleush
(
   id_sygkrothma integer NOT NULL,
   id_ekmetalleush integer NOT NULL,
   CONSTRAINT systegasmenh_ekmetalleush_pk PRIMARY KEY (id_sygkrothma, id_ekmetalleush),
   CONSTRAINT systegasmenh_ekmetalleush_sygkrothma_fk FOREIGN KEY (id_sygkrothma) REFERENCES $schema.sygkrothma (id) ON UPDATE CASCADE ON DELETE RESTRICT,
   CONSTRAINT systegasmenh_ekmetalleush_ekmetalleush_fk FOREIGN KEY (id_ekmetalleush) REFERENCES $schema.ekmetalleush (id) ON UPDATE CASCADE ON DELETE RESTRICT
)
WITH (
  OIDS = FALSE
)
QUERY
        );
        $this->execute('ALTER TABLE ' . $schema . '.systegasmenh_ekmetalleush OWNER TO ktin_mitrwo');
        $this->execute('CREATE UNIQUE INDEX ON ' . $schema . '.systegasmenh_ekmetalleush (id_ekmetalleush ASC NULLS LAST, id_sygkrothma ASC NULLS LAST)');
    }
```

**Comment by lourdas** [comment] 2015-08-11 08:18
Adding
```
'schemaMap' => [
    'pgsql' => [
        'class' => 'yii\db\pgsql\Schema',
        'defaultSchema' => 'ktin_mitrwo',
    ]
]
```
in db.php file, inside the yii\db\Connection component fixes the problem. Could this be considered the correct solution to this issue?

**Comment by klimov-paul** [comment] 2017-06-01 14:24
Unable to reproduce. Issue either already fixed by some changeset or environment specific.

**Closed by klimov-paul** 2017-06-01 14:24 UTC
Labels: feature:db, status:to be verified
