### ISSUE TITLE
inverseOf not working in most situations

### ISSUE THREAD

**Issue by tvdavid** [yiisoft/yii2#6347] opened 2014-12-02 12:05 UTC
The mechanism for inverseOf is implemented in ActiveRelationTrait::findFor(). This means that in `$customer->orders` the system works fine, because it's routed through the magic getter: `return $this->_related[$name] = $value->findFor($name, $this)`.

However, if you're customizing the query, like `$customer->getOrders()->with('status')->all()`, the inverseOf system is bypassed entirely.

Worse, because ActiveDataProvider calls `all()` directly (prepareModels: `return $query->all($this->db)`) inverseOf doesn't work at all when a DataProvider is involved.

On first sight, it looks like the inverseOf logic could safely be applied to all calls to `all()`. Is it indeed just a matter of moving some code around or am I missing something?

**Comment by VojtechH** [comment] 2016-01-31 00:18
Is there any prospect of resolving this bug in the near future or should I rather implements some workaround in my application?

It seems to me that the solution @laszlovl suggested makes sense.

If there is currently no time to implement the fix perhaps it could be useful to mention here some tried-tested workaround.

**Comment by VojtechH** [comment] 2016-01-31 00:23
Also if the solution is not expected in the near future I would suggest to add some note to the documentation. I spent some time figuring out where the problem is. If the documentation specifies that the inverseOf() is currently supported only for the queries made through magic getter it would be much clearer.

**Comment by davidhirtz** [comment] 2016-02-04 18:33
@laszlovl fix looks fine to me, why is this not merged since May 20, 2015?

**Comment by cebe** [comment] 2016-02-06 14:51
@davidhirtz every pull request needs review and testing before merge. We have limited time so we have to prioritize. This issue is tagged for the 2.0.8 release.

**Closed** 2016-07-04 13:13 UTC
Labels: type:bug

**Comment by cebe** [comment] 2016-07-04 13:18
the fix is merged and will be released with 2.0.9
