### ISSUE TITLE
symlink(): File exists

### ISSUE THREAD

**Issue by stepanselyuk** [yiisoft/yii2#6226] opened 2014-11-24 21:34 UTC
Hi,
I got that error sometimes after I've deleted symlinks from `web/assets` manual or in the code. I can run `clearstatcache( true )` but it worked per thread, so other theads will produce the error until `realpath_cache` will be reloaded. How to fix it? I'm talking about `\yii\web\AssetManager::publishFile` and `\yii\web\AssetManager::publishDirectory`. Maybe try to catch that error and make `clearstatcache( true )`, then try again? I've googled that problem, and it's common problem for PHP.

**Comment by dynasource** [comment] 2016-10-31 20:38
not able to reproduce

**Comment by Renkas** [comment] 2017-05-09 14:44
I'm getting the same error from time to time. And I can reproduce it easily when creating a bunch of request to servers. I have an admin tool that opens a URL for each product in a iframe on same page (10+ per page) and about 1/3 or 1/4 of these requests give me said error.

**Comment by dynasource** [comment] 2017-05-09 15:26
thanks for sharing your reproduction

**Comment by cebe** [comment] 2017-05-09 20:46
could be solved in a similar way as #9288

**Comment by dynasource** [comment] 2017-10-07 18:44
fixed by https://github.com/yiisoft/yii2/pull/14905

**Closed by dynasource** 2017-10-07 18:44 UTC
Labels: type:bug
