### ISSUE TITLE
CheckboxColumn calling grid JS which is not initialized yet

### ISSUE THREAD

**Issue by rootpd** [yiisoft/yii2#12760] opened 2016-10-17 17:50 UTC
### What steps will reproduce the problem?

Use `\yii\grid\GridView` with a column of class `\yii\grid\CheckboxColumn`

The issue was also indirectly described in issue of different repo: https://github.com/kartik-v/yii2-grid/issues/518.
### What is the expected result?

Grid is successfully initialized with a checkbox column
### What do you get instead?

JS console error: _Uncaught TypeError: Cannot set property 'selectionColumn' of undefined_ causing halt of further JS execution.

It's caused by following being rendered:

``` js
jQuery('#w2').yiiGridView('setSelectionColumn', {"name":"selection[]","class":null,"multiple":true,"checkAll":"selection_all"});
jQuery('#w2').yiiGridView({"filterUrl":"\/contact\/view?id=6","filterSelector":"#w2-filters input, #w2-filters select"});
```

Technically this is the flow:
- Columns get initialized within `GridView::init` and `CheckboxColumn` registers it JS first
- Grid gets to registering its JS in `GridView::run` which seems to be too late here.

It looks like it's either necessary to move `GridView` JS registering sooner or columns JS registering later.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 5.6.18 |
| Operating system | Ubuntu 14.04 |

**Comment by SG5** [comment] 2016-10-19 08:34
@rootpd I have save JS code, but without `TypeError` exception
```
jQuery('#w1').yiiGridView('setSelectionColumn', {"name":"selection[]","class":null,"multiple":true,"checkAll":"selection_all"});
jQuery('#w1').yiiGridView({"filterUrl":"\/video1","filterSelector":"#w1-filters input, #w1-filters select"});
```

**Comment by rootpd** [comment] 2016-10-20 06:18
Let me get back to you with full example view so it's easier to reproduce. Just to confirm, the code you pasted is the one generated by Yii and executed when page is rendered, nothing custom called, right?

**Comment by SG5** [comment] 2016-10-20 07:07
@rootpd yes, only `GridView` from gii and one custom field with `CheckboxColumn`

**Comment by samdark** [comment] 2018-02-03 16:37
Since no additional info on how to reproduce it was provided, closing.

**Closed by samdark** 2018-02-03 16:37 UTC
Labels: JS, status:to be verified, type:bug
