### ISSUE TITLE
yii\web\Response::send() is sending a raw response while data contains a warning 

### ISSUE THREAD

**Issue by rochdi80tn** [yiisoft/yii2#13619] opened 2017-02-19 13:17 UTC
### What steps will reproduce the problem?
I am using DomPDF to render a html viens to PDF.
The process is rendering the html into a local temperal pdf file send it and delete it
The delete is generating a warning so that `yii\web\Response` object  `format` attribute is raw but `data ` is not null which makes a non well formatted response.

### What is the expected result?
Display at least the warning message : 

`PHP Warning 'yii\base\ErrorException' with message 'unlink(/app/src/../runtime/html2pdf/html2pdf58a995cc65e524.85184459.pdf): Text file busy' in /app/vendor/yii2tech/html2pdf/TempFile.php:98 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'unlink(/app/src...', '/app/vendor/yii...', 98, Array) #1`

### What do you get instead?
Nothing, neither the PDF contents nor the warning message.
```
This site can’t be reached

The webpage at http://127.0.0.1/pdf?id=1 might be temporarily down or it may have moved
 permanently to a new web address.

ERR_INVALID_RESPONSE
```

### Additional info
Locally fixed this but updating the `yii\web\Response::send() ` by forcing `format `to be HTML is such scenario: 
```php
    /**
     * Sends the response to the client.
     */
    public function send()
    {
        if ($this->isSent) {
            return;
        }
        if ( $this->format == self::FORMAT_RAW  && $this->data != null ){
            $this->format = self::FORMAT_HTML;
        }
        ...        
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      |7.0.15-1+deb.sury.org~trusty+1
| Operating system | Ubuntu 14.04.5 LTS

**Comment by SilverFire** [comment] 2017-02-22 20:46
Could you explain, how to reproduce the problem from scratch?

**Comment by cebe** [comment] 2017-07-06 12:21
unable to reproduce, closing until more information is provided.

**Closed by cebe** 2017-07-06 12:21 UTC
Labels: status:to be verified, type:bug
