### ISSUE TITLE
Cannot use 'Object' as class name

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii2#14460] opened 2017-07-15 18:13 UTC
### What steps will reproduce the problem?
Install php 7.2 from ppa:ondrej/php

### What is the expected result?
working project
### What do you get instead?
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /home//vendor/yiisoft/yii2/base/Object.php on line 77

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.2.0alpha3
| Operating system |ubuntu 16.04

On php <=7.1 works ok

**Comment by samdark** [comment] 2017-07-15 19:36
Duplicate of https://github.com/yiisoft/yii2/issues/7936

**Closed by samdark** 2017-07-15 19:36 UTC
