### ISSUE TITLE
No ->signed() or ->unSigned() modifiers in ColumnSchemaBuilder

### ISSUE THREAD

**Issue by df2** [yiisoft/yii2#9567] opened 2015-09-02 03:10 UTC
Seem to be missing. This and #9562 would be nice to have in 2.0.7. Is it just a case of writing the code or are there other reasons these are missing?

**Comment by hesna** [comment] 2015-09-02 06:16
duplicate of #9443

**Closed** 2015-09-02 09:12 UTC
