### ISSUE TITLE
UrlRule "Defaults" not working

### ISSUE THREAD

**Issue by RSalo** [yiisoft/yii2#12658] opened 2016-10-04 03:39 UTC
I have a code:

```
class LanguageUrlRule extends UrlRule
{

    public function init()
    {

        if ($this->pattern !== null) {
            $this->pattern = '<language>/' . $this->pattern;
        }

        $this->defaults['language'] = Yii::$app->language; // <- this doesn't work

        parent::init();
    }
}

        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'enableStrictParsing' => false,

            'rules' => [             
            ],
            'ruleConfig' => [
                'class' => 'app\components\LanguageUrlRule'
            ],
        ],
```

I want to get url like this site.com/en or site.com/ru but i get just site.com. Language on my site changing normal.

**Comment by Julian-B90** [comment] 2016-10-04 05:49
Hi RSalo,

can you post your question to the [forum](http://www.yiiframework.com/forum/). Because the issues are for bugs.

**Comment by SilverFire** [comment] 2016-10-04 07:10
> $this->defaults['language'] = Yii::$app->language; // <- this doesn't work

Do you mean that PHP never reaches this line?

> I want to get url like this site.com/en or site.com/ru but i get just site.com

What do you do to get URL like that?

**Comment by rob006** [comment] 2016-10-04 07:18
You have no rules in you config, so your `ruleConfig` settings does not affect anything.

**Comment by RSalo** [comment] 2016-10-04 07:28
> Do you mean that PHP never reaches this line?

I mean that not appear GET parameters after this line

> What do you do to get URL like that?

I do like described this https://github.com/samdark/yii2-cookbook/blob/master/book/i18n-selecting-application-language.md#language-in-url--subdomain

> You have no rules in you config, so your ruleConfig settings does not affect anything.

I have its in config and it reached...

**Comment by Julian-B90** [comment] 2016-10-04 08:17
which version from yii du you use?

**Comment by SilverFire** [comment] 2016-10-16 14:00
Failed to reproduce
I'm closing the issue unless further information provided.

**Closed by SilverFire** 2016-10-16 14:00 UTC
Labels: status:need more info

**Comment by mohdqasim98** [comment] 2018-06-20 12:20
Having this same issue, with exactly the same code
It seems the `LanguageUrlRule::init()` function is not called

**Comment by koxu1996** [comment] 2022-03-26 19:23
I had the same problem, but finally found that it was caused by urlManager cache behavior. You should disable it when playing with URL rules, otherwise rule is cached and your changes in code will not be reflected.
