### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by TheHett** [yiisoft/yii2#13256] opened 2016-12-20 12:01 UTC
Hello,
I mistake that yii has a memory leak. Why my issue was closed?
https://github.com/yiisoft/yii2-mongodb/issues/175

UPD: how to reproduce https://github.com/TheHett/yii2-memory-leak-reproduce/blob/master/console/controllers/TestController.php

**Comment by klimov-paul** [comment] 2016-12-20 12:02
https://github.com/yiisoft/yii2-mongodb/issues/175#issuecomment-268220674

**Comment by TheHett** [comment] 2016-12-20 12:04
Maybe you provide more info?

**Comment by klimov-paul** [comment] 2016-12-20 13:18
#9129
#6943

**Comment by TheHett** [comment] 2016-12-20 15:41
>memory should be cleared after php garbage collector has run, this will not be on each unset call but when memory is needed to be freed.

GC does not clear the memory in this case and it very seriously architecture problem. I dont know, why you close all similar tickets.

**Comment by TheHett** [comment] 2016-12-21 05:21
PHP 5.6.29

``` 
    public function behaviors()
    {
        return [
            \yii\behaviors\TimestampBehavior::className(),
        ];
    }
```

Run script
```
        VarDumper::dump(['YII_DEBUG' => YII_DEBUG, 'YII_ENV' => YII_ENV]);
        echo PHP_EOL;
        Yii::getLogger()->flushInterval = 1;
        $count = 0;
        while (true) {
            $user = User::find()->one();
            unset($user);
            $count++;
            if($count % 10000 == 0) {
                Yii::getLogger()->flush();
                gc_collect_cycles();
                echo memory_get_usage(), PHP_EOL;
            }
        }
```

```
$ ./yii test/x
[
    'YII_DEBUG' => false
    'YII_ENV' => false
]
6641176
8563056
10487536
12451384
...
...
118422800
120408080
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in C:\www\FileStore\vendor\yiisoft\yii2\log\Target.php on line 210
Segmentation fault
```

**Comment by cebe** [comment] 2016-12-21 17:04
could you provide your logger config?

**Comment by TheHett** [comment] 2016-12-21 19:30
@cebe 
hi, thanks
I create test-app based on latest release yii-advanced application
https://github.com/TheHett/yii2-memory-leak-reproduce/blob/master/console/controllers/TestController.php
(only added TestCommand and changed User model parent class to yii\mongodb\ActiveRecord)

The problem is reproduced only with yii\mongodb\ActiveRecord
You can clone repo and test it (command ./yii test)

when disabled (removed) all behaviors, then memory leak not watched.

**Comment by TheHett** [comment] 2016-12-22 05:59
Besides, I watch one more strange thing:
If do not do unset variable, memory leak reproduced even without Behaviors()
it reproduced only on \yii\mongodb\ActiveRecord
```
        while (true) {
            $user = User::find()->one();
//            unset($user);
            $count++;
            if ($count % 10000 == 0) {
                Yii::getLogger()->flush();
                gc_collect_cycles();
                echo memory_get_usage(), PHP_EOL;
            }
        }
```

**Comment by imrel** [comment] 2016-12-31 00:43
@TheHett you probably are not reading the numbers correctly, can you try with:
```
        gc_disable(); // IMPORTANT FOR CONSISTENT NUMBERS
        while (true) {
            $user = User::find()->one();
//            unset($user);
            $count++;
            if ($count % 1000 == 0) {  // you probably want here number between 100 and 1000 (not 10k)
                Yii::getLogger()->flush();
                gc_collect_cycles();
                echo memory_get_usage(), PHP_EOL;
            }
        }
```

**Comment by TheHett** [comment] 2017-01-04 15:58
@imrel It does not matter

**Comment by TheHett** [comment] 2017-02-04 05:49
I test code under php7, and all work fine.

php7
```
Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php7/php.exe yii test
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
3200664
3200664
3200664
```

php 5.6
```
Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php5.6/php.exe yii test
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
6513392
8437512
10365512
```

**Comment by samdark** [comment] 2017-02-04 12:48
So... any idea what to do with it?

**Comment by rob006** [comment] 2017-02-04 13:30
Cannot reproduce on PHP 5.6.29 on FreeBSD.

**Comment by samdark** [comment] 2017-02-04 13:35
@TheHett which 6.5 is that?

**Comment by TheHett** [comment] 2017-02-04 13:48
@rob006 You run test into https://github.com/TheHett/yii2-memory-leak-reproduce/blob/master/console/controllers/TestController.php ? 

Model should be extended from yii\mongodb\ActiveRecord, this is true?
I test php 5.6 under Ubuntu 14.04 and Windows, on both reproduced.

**Comment by TheHett** [comment] 2017-02-04 13:53
@samdark 5.6 leaking (tested under windows with copyed config from php7)

```Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php56/php.exe yii test
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
6514744
8438256
10364648
```

**Comment by rob006** [comment] 2017-02-04 14:18
@TheHett I cloned your test project and run tests on it. 

I also run test on Ubuntu 16.04 on PHP 5.6.30 and confirm leak. I can confirm leak also in 7.0.15 and 7.1.1 on the same system (Ubuntu 16.04, PHP from `ondrej/php` ppa) . This may be bug in mongodb driver, since all these versions share the same mongodb extension:

```
mongodb

MongoDB support => enabled
MongoDB extension version => 1.2.3
MongoDB extension stability => stable
libbson bundled version => 1.5.3
libmongoc bundled version => 1.5.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled

Directive => Local Value => Master Value
mongodb.debug => no value => no value

``` 

On FreeBSD I have:
```
mongodb

mongodb support => enabled
mongodb version => 1.1.9
mongodb stability => stable
libmongoc version => 1.3.6
libbson version => 1.3.6

Directive => Local Value => Master Value
mongodb.debug => no value => no value
```

**Comment by TheHett** [comment] 2017-02-04 14:55
@rob006 Thanks,
i already tried to install mongodb driver 1.9 from pecl on php 7.1 - leak not reproduced

**Comment by rob006** [comment] 2017-02-04 14:58
There is one leak fixed in 1.2.4, you could try it.

**Comment by TheHett** [comment] 2017-02-04 15:09
@rob006 hm, you're right.
```
root@dev-03:~/yii2-memory-leak-reproduce# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mongodb.so' - /usr/lib/php/20151012/mongodb.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies

root@dev-03:~/yii2-memory-leak-reproduce# php -i | grep "mongodb version"
mongodb version => 1.2.2
root@dev-03:~/yii2-memory-leak-reproduce# ./yii test/index
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
3016136
3128248
3240360
3352472
^C
root@dev-03:~/yii2-memory-leak-reproduce# pecl uninstall mongodb
Unable to remove "extension=mongodb.so" from php.ini
uninstall ok: channel://pecl.php.net/mongodb-1.2.2

root@dev-03:~/yii2-memory-leak-reproduce# pecl install mongodb
...

root@dev-03:~/yii2-memory-leak-reproduce# php -i | grep MongoDB
MongoDB support => enabled
MongoDB extension version => 1.2.5
MongoDB extension stability => stable


root@dev-03:~/yii2-memory-leak-reproduce# ./yii test/index
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
2903672
2903672
2903672
2903672
```


I think issue should be closed. Its not a Yii problem, sorry.

**Comment by TheHett** [comment] 2017-02-04 15:19
hmm. stop
expect for this error in php56 has leak with behavior

```
Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php56/php.exe -i | grep mongo
mongodb
mongodb support => enabled
mongodb version => 1.2.2
mongodb stability => stable
libmongoc version => 1.5.0
mongodb.debug => no value => no value
PHP Warning:  Unknown: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Unknown on line 0

Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php56/php.exe yii test
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
6535128
8483480
```

Now I comment 
```php
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
```

And run

```
Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php56/php.exe yii test
[
    'YII_DEBUG' => false
    'YII_ENV' => 'prod'
]
4202944
4202944
4202944
```

In php7 behavior not leaked.

**Comment by rob006** [comment] 2017-02-04 16:29
I have leak without behaviors but with single `isset($user->username);` in test script. I think that behaviors are only one of things that triggers this bug, but this could be anything.

**Comment by TheHett** [comment] 2017-02-04 16:32
@rob006 Can you show full code?

**Comment by rob006** [comment] 2017-02-04 16:36
```php
<?php

namespace console\controllers;

use common\models\User;
use Yii;
use yii\console\Exception;
use yii\helpers\VarDumper;


class TestController extends \yii\console\Controller
{

    public function actionIndex()
    {
		
		echo PHP_VERSION  . "\n";
        $user = new User();
        $user->username = 'test';
        if(!$user->save(false)) {
            throw  new Exception("Test failed: user was not created.");
        }

        VarDumper::dump(['YII_DEBUG' => YII_DEBUG, 'YII_ENV' => YII_ENV]);
        echo PHP_EOL;
        Yii::getLogger()->flushInterval = 1;
        $count = 0;
        while (true) {
            $user = User::find()->one();
            isset($user->username);
            $count++;
            if ($count % 1000 == 0) {
                Yii::getLogger()->flush();
                gc_collect_cycles();
                echo memory_get_usage(), PHP_EOL;
            }
        }
    }
}

```

And
```php
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
 //           TimestampBehavior::className(),
        ];
    }
```
in `User` model.

**Comment by TheHett** [comment] 2017-02-04 16:48
Confirm, reproducig on php 5.6 w/o isset and behaviors...

```
    public function actionIndex()
    {
        echo PHP_VERSION  . "\n";
        $user = new User();
        $user->username = 'test';
        if(!$user->save(false)) {
            throw  new Exception("Test failed: user was not created.");
        }
        echo PHP_EOL;
        Yii::getLogger()->flushInterval = 1;
        $count = 0;
        while (true) {
            $user = User::find()->one();
            $count++;
            if ($count % 1000 == 0) {
                Yii::getLogger()->flush();
                gc_collect_cycles();
                echo memory_get_usage(), PHP_EOL;
            }
        }
    }
```


```bash

Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php56/php.exe yii test
5.6.30RC1

4135128
4135320
4135512
4135704
4135896
4136088
4136280
4136472
4136664
```

```bash
Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php7/php.exe yii test
7.1.2RC1

3000616
3000616
3000616
3000616
3000616
3000616
3000616
3000616
3000616
```

**Comment by TheHett** [comment] 2017-02-04 16:55
Work fine w/o behaviors:

```php
    public function actionIndex()
    {
        echo "PHP: ", PHP_VERSION, PHP_EOL;
        echo "Mongodb: ", phpversion("mongodb"), PHP_EOL;

        $user = new User();
        $user->username = 'test';
        if(!$user->save(false)) {
            throw  new Exception("Test failed: user was not created.");
        }
        echo PHP_EOL;

        Yii::getLogger()->flushInterval = 1;
        $count = 0;
        while (true) {
            $user = User::find()->one();
            $count++;
            if ($count % 1000 == 0) {
                Yii::getLogger()->flush();
                gc_collect_cycles();
                echo memory_get_usage(), PHP_EOL;
            }
        }
    }
```


```bash
Anton@storm MINGW64 /c/www/leak-test (master)
$ /c/Opt/php56/php.exe yii test
PHP: 5.6.30RC1
Mongodb: 1.2.5

4136200
4136200
4136200
4136200
4136200
4136200
```

**Comment by TheHett** [comment] 2017-02-04 16:59
And with behaviors work fine.
Apparently I'm confused.

Try latest code from https://github.com/TheHett/yii2-memory-leak-reproduce

Now i dont see any problem...

**Comment by imrel** [comment] 2017-02-04 19:45
This is not Yii problem and not much can be done because that would be too use case specific.
I would let them close this ticket for now. 

I did some tests without mongodb and got the "leaks" with bigger loop count between `gc_collect_cycles` but they disapeared when using smaller one. 

Note that if you are doing your tests without disabling GC then `memory_get_usage()` does probably not report the highest value because internal GC will run. 

http://php.net/manual/en/features.gc.collecting-cycles.php

> cycle-finding algorithm is executed whenever the root buffer runs full. The root buffer has a fixed size of **10,000** possible roots

> If the root buffer becomes full with possible roots while the garbage collection mechanism is turned off, further possible roots will simply not be recorded. Those possible roots that are not recorded will never be analyzed by the algorithm. If they were part of a circular reference cycle, they would never be cleaned up and would create a memory leak.

However the "leak" might not be tied to circular references at all.

**Comment by TheHett** [comment] 2017-02-05 05:38
@imrel we just observe memory grown, therefore run GC cycle before print memory usage.

**Comment by TheHett** [comment] 2017-02-06 10:16
As we have seen, the problem driver.

**Closed** 2017-02-06 10:15 UTC
Labels: status:need more info, status:to be verified
