### ISSUE TITLE
DbMessage in SQLite 3.8.6 error

### ISSUE THREAD

**Issue by hiscaler** [yiisoft/yii2#5495] opened 2014-10-12 06:35 UTC
Database Exception – yii\db\Exception

SQLSTATE[HY000]: General error: 1 near "(": syntax error
Failed to prepare SQL: (SELECT `t1`.`message` AS `message`, `t2`.`translation` AS `translation` FROM `www_language_source_message` `t1`, `www_language_message` `t2` WHERE t1.id = t2.id AND t1.category = :category AND t2.language = :language) UNION ALL ( SELECT `t1`.`message` AS `message`, `t2`.`translation` AS `translation` FROM `www_language_source_message` `t1`, `www_language_message` `t2` WHERE (t1.id = t2.id AND t1.category = :category AND t2.language = :fallbackLanguage) AND (t2.id NOT IN (SELECT id FROM `www_language_message` WHERE language = :language)) )

**Comment by samdark** [comment] 2015-03-03 23:27
Can't reproduce w/o additional info. Closing.

**Closed by samdark** 2015-03-03 23:27 UTC
Labels: status:need more info
