### ISSUE TITLE
Model attributes with non-word characters.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii2#13764] opened 2017-03-13 14:33 UTC
### What steps will reproduce the problem?
Create a database table with a column name like `A+`.

### What is the expected result?
Yii does the escaping so this should just work.

### What do you get instead?
In `BaseHtml::getInputName()`:
````
Invalid Parameter – yii\base\InvalidParamException

Attribute name must contain word characters only.
````

### Solution
Make the naming requirements less strict and implement proper quoting (I think quoting is already working properly everywhere).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.1
| Operating system | Alpine

**Comment by samdark** [comment] 2017-03-13 15:28
Is it a duplicate of https://github.com/yiisoft/yii2/issues/4408?

**Comment by samdark** [comment] 2017-03-13 15:29
Yes. It is.

**Closed by samdark** 2017-03-13 15:29 UTC
