### ISSUE TITLE
Feature request: Controller::renderJson()

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/yii2#13036] opened 2016-11-17 14:15 UTC
I think, returning a JSON response is such a common task that a simple convenience method in `yii\web\Controller` would make sense:

```php
    /**
     * Render a JSON response
     *
     * @param mixed $data the data to return as JSON response
     * @return the data to return as JSON response
     */
    public function renderJson($data = null)
    {
        Yii::$app->getResponse()->format = Response::FORMAT_JSON;
        return $data;
    }
```

In a controller action you could then write:

```php
return $this->renderJson($model->attributes);
```

**Comment by samdark** [comment] 2016-11-17 14:33
Isn't response formatting as JSON a bit better than that? http://www.yiiframework.com/doc-2.0/guide-rest-response-formatting.html

**Comment by mikehaertl** [comment] 2016-11-17 14:45
Hmm, but it again requires extra configuration, right? Unless you extend from `yii\rest\Controller` you manually have to configure the `ContentNegotiator` filter. It's really all about convenience.

**Comment by samdark** [comment] 2016-11-17 14:47
No. It's as simple as:


```php
$response->format = \yii\web\Response::FORMAT_JSON;
return $model->attributes;
```

**Comment by mikehaertl** [comment] 2016-11-17 14:49
:D But that's exactly what happens in my suggested `renderJson()`. The sole purpose is, not having to remember the exact syntax ("what was that Reponse property and the name of the constant again ...?") but having one simple method for JSON response.

**Comment by dynasource** [comment] 2016-11-17 15:03
@samdark, that example should be in the guide at http://www.yiiframework.com/doc-2.0/guide-structure-controllers.html

**Comment by samdark** [comment] 2016-11-17 15:09
@dynasource you can find it here: http://www.yiiframework.com/doc-2.0/guide-runtime-responses.html

**Comment by dynasource** [comment] 2016-11-17 15:15
I see. Well, I understand the reasoning of @mikehaertl very well. If his suggestion can be implemented in another way, we should be clear in the docs about it.

**Comment by dynasource** [comment] 2016-11-17 19:53
to continue this conversion. Currently we have the following render methods in Controller:
* `render($view, $params = [])`
* `renderContent($content)`
* `renderPartial($view, $params = [])`
* `renderFile($file, $params = [])`
* `renderAjax($view, $params = [])`

I don't think it's a bad idea to add such a generic function like renderJson(). Perhabs we can make it even more generic like:
* `renderData($data, $format = \yii\web\Response::FORMAT_JSON)`

**Comment by mikehaertl** [comment] 2016-11-18 07:09
@dynasource I think there are only 2 very common formats: JSON and XML. If you cover both with one generic method you again have to remember that JSON is the default. And you need to look up the `FORMAT_XML` constant in `Response` if you need XML instead. So why not having 2 dedicated methods instead:

* `renderJson()`
* `renderXml()`

Not sure about Jsonp and raw.

**Comment by nkostadinov** [comment] 2016-11-18 07:45
The framework itself should be as basic as possible. I dont see a problem to extend the base controller with these 2 methods and create your base controller to use in your projects. There are many cases you don't need to send json/xml from a controller.

Even better you could create a trait with these two methods and add them whenever you like.

**Comment by dynasource** [comment] 2016-11-18 08:20
@yiisoft/core-developers, is there is reason why there isn't a `render` function for usecases with JSON in the Controller?

**Comment by klimov-paul** [comment] 2016-11-18 08:28
Keyword `render` means there is some processing of some entity composing output.
Usage `render` for the view file processing is suitable, but for simple JSON compoision  it is confusing.

I do not think such shortcut method should be added, as there could be many response formatters - not only  JSON or XML, creating method for one of them seems to be inconsistent.

If you with to add it anyway better naming can be `returnData()` or `responseData()` in following signature:

```php
public function responseData($data, $format) {}
```

Then it can be used for `raw`, `json` or `xml`:

```
public function actionFoo()
{
    return $this->responseData($data, Response::FORMAT_JSON);
    //return $this->responseData(file_get_contents('/path/to/file.txt'), Response::FORMAT_RAW);
}
```

**Comment by dynasource** [comment] 2016-11-18 08:42
> Keyword render means there is some processing of some entity composing output.

If you look at the current render() methods, you are right that there is always some processing going on. 

However, most people consider the `render` functions as the solution to `render` something to a output. This is also supported by the translation of the term `render`:
* to give: give, deliver, impart, lend, render, afford
* to show: represent, reproduce, render, give voice to, describe

With this and consistency in mind, I would expect such a method to include the `render` terminology, whether it's doing some processing or not. As a new developer I surely would overlook a function like `responseData`

**Comment by nkostadinov** [comment] 2016-11-18 08:54
@klimov-paul the rendering itself has nothing to do with the format of the data being processed if you name it responseData should be very confusing. If I am returning an array or AR is it a JSON/XML or the "render" should decide how to format the function ?

**Comment by mikehaertl** [comment] 2016-11-18 08:54
> Keyword render means there is some processing of some entity composing output.

Actually converting a PHP data structure into a JSON string is exactly that. Similar to when you render a view you convert it to a HTML string.

> I do not think such shortcut method should be added, as there could be many response formatters 

JSON and XML are the most common data formats, and Yii already has built in formatters for them. Other formats are far less common and developers will have to configure their own formatters in those cases anyway.

Using just one method to render different formats (e.g. `renderData()`) defeats the idea of this feature request. `renderJson()` / `renderXml()` is far easier to remember than `yii\web\Response::FORMAT_XML`.

**Comment by klimov-paul** [comment] 2016-11-18 09:18
What about `renderRaw()` For `yii\web\Response::FORMAT_RAW` support then?

**Comment by klimov-paul** [comment] 2016-11-18 09:22
What about `jsonp` (`yii\web\Response::FORMAT_JSONP`) ? Should it be method `renderJsonP()`?
And what about `yii\web\Response::FORMAT_HTML` - method `renderHtml()` should exist as well - if we start this improvement.

**Comment by dynasource** [comment] 2016-11-18 09:26
> If you with to add it anyway better naming can be returnData() or responseData() https://github.com/yiisoft/yii2/issues/13036#issuecomment-261475529

what about the combination of your suggestion & the `render` terminology https://github.com/yiisoft/yii2/issues/13036#issuecomment-261477936:
* `renderResponseData()'

**Comment by nkostadinov** [comment] 2016-11-18 09:27
How about renderAs($data, $format) ?

**Comment by klimov-paul** [comment] 2016-11-18 09:30
For me obvious solution for the issue is using `\yii\web\Response::EVENT_BEFORE_SEND` event and return of plain array as controller action result:

```php
return [
    'components' => [
        'response' => [
            'on beforeSend' => function ($event) {
                $response = $event->sender;                
                if (is_array($response->data) && $response->format === \yii\web\Response::FORMAT_HTML) {
                   $response->format = \yii\web\Response::FORMAT_JSON
                }

            }
        ],
    ],
];

class FooController extends \yii\web\Controller
{
    public function actionFoo()
    {
        return [
           'text' => 'will be formatted as JSON automatically'
        ];
    }
}
```

**Comment by mikehaertl** [comment] 2016-11-18 09:35
Again: The main idea is: **Keep it simple!!**. I found myself looking up the `FORMAT_` constants again and again, if all I want is to send a simple JSON response. Each time I wonder, why is this so inconvenient?

If we now add a method that you have to call like `renderData($data, \yii\web\Response::FORMAT_JSON)` nothing is improved! It's even worse with @klimov-paul last suggestion where he proposes that I have to write a huge block of > 10 lines of very hard to remember configuration just to send one simple stupid JSON response.

**Comment by nkostadinov** [comment] 2016-11-18 09:37
@klimov-paul that's some ugly solution with assumption that array should always be returned as JSON. It's much better to set the reponse format and return the data. But we are looking for an easy and elegant solution to a common task.

**Comment by klimov-paul** [comment] 2016-11-18 09:39
> I have to write a huge block of > 10 lines of very hard to remember configuration just to send one simple stupid JSON response.

???
What is wrong to write a couple of lines in application config just once per project and use simple `return` statement wherever you need to return a JSON.

Creating separated method for each response format does not follows ` Keep it simple!!` paradigm.

> that's some ugly solution with assumption that array should always be returned as JSON. It's much better to set the reponse format and return the data. But we are looking for an easy and elegant solution to a common task.

This `ugly` solution assumes JSON will be used **by default** for each array data, if NO other appropriate formate explicitly specified. For example:

```
class FooController extends \yii\web\Controller
{
    public function actionFoo()
    {
        Yii::$app->response->format = Response::FORMAT_XML;
        return [
           'text' => 'will be formatted as XML despite the `beforeSend` reponse event'
        ];
    }
}
```

**Comment by mikehaertl** [comment] 2016-11-18 09:41
@klimov-paul What if I have a project where I need both, JSON and XML responses?

**Comment by klimov-paul** [comment] 2016-11-18 09:41
I have just posted you an example.

**Comment by klimov-paul** [comment] 2016-11-18 09:42
It seems, you do not even paying attention to my comments at all.

**Comment by nkostadinov** [comment] 2016-11-18 09:44
How does that "keep it simple" more than e.g.:
```
RenderTrait {
public function renderAs($data, $format = Response::FORMAT_JSON)
}
```
or a method in the web\controller.

**Comment by mikehaertl** [comment] 2016-11-18 09:45
I don't find this very convenient - and that's what this issue is all about.

Make developers live easy and painless. Also keep the code readable. With your suggestion we would have this in the controller:

```
return $data;
```

If I look at this some months later I would have no idea, that this is going to be sent in JSON format. Whereas with:

```
return $this->renderJson($data);
```

IMO it's as clear and simple as it can get.

**Comment by dynasource** [comment] 2016-11-18 10:01
> For me obvious solution for the issue is using \yii\web\Response::EVENT_BEFORE_SEND event

although it's ingenious, it's a disentanglement of logic, making it more complex. The use of events is also a workaround. There are many usecase thinkable for this issue to be fixed with a Controller method.

**Comment by klimov-paul** [comment] 2016-11-18 10:12
> it's a disentanglement of logic, making it more complex.

For me it is convinient: take a general JSON response creation:

```
class FooController extends \yii\web\Controller
{
    public function actionFoo()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return [
           'text' => 'will be formatted as JSON'
        ];
    }
}
```

My proposal simply eliminates the necessity to set format all the time, so code becomes to look like following:

```
class FooController extends \yii\web\Controller
{
    public function actionFoo()
    {
        // no format setup present
        return [
           'text' => 'will be formatted as JSON'
        ];
    }
}
```

Also this is exacly the same syntax we use at `yii\rest\*` - no one complains on it back there.

> The use of events is also a workaround.

Yes it is. But what the case for having event in framework if do not want to use them? Should we drop event support at `Response` class, because it exist for 'hacking only'?

> There are many usecases thinkable for this issue to be fixed with a Controller method.

Unless you can provide me the anwsers to the question I asked -I do not think so. We have 5 built-in formats at `yii\web\Response`. If we add a shortcut for one of them - we should add a shortcut for every one - otherwise change is inconsistent.

I understand that it can be overwhelming to format JSON response each time at the large project - that is why I provide you a walkaround is the same fasion, we created it at `yii\rest\*`.

I can see no reason for creating a batch of shortcut methods.

But as I always say - it is my opinion and I can not force the core team to accept it.
Lets wait for input from other core team members.

**Comment by dynasource** [comment] 2016-11-18 10:53
> The use of events is also a workaround.
> Yes it is. But what the case for having event in framework if do not want to use them? Should we drop event support at Response class, because it exist for 'hacking only'?

Why should someone use a site-wide event in a scenario where he/she has only 1 JSON action? Thats rather cumbersome.

> Should we drop event support at Response class, because it exist for 'hacking only'?

Events should be used for unique cases in which flexibility is necessary. This usecase is too common for that.

> There are many usecases thinkable for this issue to be fixed with a Controller method.
> Unless you can provide me the anwsers to the question I asked - I do not think so.

The usecases are:
* consistency: returning JSON is a form of `render` and therefore it is expected in Controller with the other methods
* simplicity: using a central event is complex
* performance: using a site wide event is not performant
* convenience: see the arguments in this topic by @mikehaertl , @nkostadinov

**Comment by cebe** [comment] 2016-11-18 13:40
> Actually converting a PHP data structure into a JSON string is exactly that. Similar to when you render a view you convert it to a HTML string.

@mikehaertl this is what render methods do but not what your proposed method does. It simply sets the response type. other render methods do not touch the response type at all. So calling this new method `renderJson` would be inconsistent. Also I do not see why we have `$data` as an argument if it is not used:

```php
  public function renderJson($data = null)
    {
        Yii::$app->getResponse()->format = Response::FORMAT_JSON;
        return $data;
    }
```

I guess you would use that method like this:

```php
return $this->renderJson($data);
```

but it is all about settings the response format, there is no rendering going on. So I would rather see something like this instead:

```php
$this->setJsonResponseType();
return $data;
```

which is just another syntax for `Yii::$app->response->format = Response::FORMAT_JSON;`.
I do not really think this improves anything as you would have to look up `$this->setJsonResponseType();` the same way you would have to look up `Yii::$app->response->format = Response::FORMAT_JSON;`.

**Comment by dynasource** [comment] 2016-11-18 13:50
> but it is all about settings the response format, there is no rendering going on

actually there is, otherwise people wouldn't call this method. They want to render (show/present https://github.com/yiisoft/yii2/issues/13036#issuecomment-261477936) a JSON response.

**Comment by mikehaertl** [comment] 2016-11-18 13:52
@cebe I see your point, even though there are other methods like `renderAjax()` which also do things under the hood, which you may not expect. To me `renderJson()` has proven to be very useful in my projects. IMO it's a matter of writing the correct documentation for such a method.

As an alternative, how about `sendJson()` then?

```
return $this->sendJson($data);
```

**Comment by dynasource** [comment] 2016-11-18 14:20
> As an alternative, how about sendJson() then?
> 
> return $this->sendJson($data);

I dont think this is consistent enough. Like you said, you have been looking for a `render` method. Adding another terminology like `send` would be confusing. This will could potentially lead to many other methods with the prefix 'send'.

In the end, there still is rendering going on, only postponed by Response::defaultFormatters(). 
Therefore I would expect a shortcut method with a clear reference to these formatters, such as:
* `renderDataResponse()`

**Comment by cebe** [comment] 2016-11-18 14:37
There are two places of rendering response data:

1. rendering a view file `render()` `renderPartial()`, `renderContent()`, `renderFile()` and `renderAjax()`. These all call out to the View component for rending.
2. response formatting in Response component.

The new method proposed is about controlling point 2, so I'd prefer a name different from `render`.
We could introduce new methods for creating a response object, which is similar to `redirect`.

```php
return $this->createJsonResponse($data);
return $this->createXmlResponse($data);
```

implementation would look like:

```php
    public function createJsonResponse($data)
    {
        $response = Yii::$app->getResponse();
        $response->format = Response::FORMAT_JSON;
        $response->data = $data;
        return $response;
    }
```

**Comment by dynasource** [comment] 2016-11-18 15:01
Room for improvement in my opinion. The term `render` is too tightly connected to the `view` component and in the end both 1. and 2. are about rendering.

**Comment by samdark** [comment] 2016-11-23 08:39
How about `return $this->asJson($data)`?

**Comment by cebe** [comment] 2016-11-23 10:30
```php
return $this->jsonResponse($data);
return $this->xmlResponse($data);
```

**Comment by samdark** [comment] 2016-11-23 10:38
@cebe it sounds like getting response object. Actually, from the user standpoint, I don't see any problems with `renderJson` and `renderXml`.

**Comment by samdark** [comment] 2016-11-23 10:39
@cebe sounds perfect to me.

**Comment by dynasource** [comment] 2016-11-23 11:06
not to me. It's inconsistent and the method name is missing its main objective,  the `verb` part.

**Comment by samdark** [comment] 2016-11-23 11:10
Because it's not formatting anything. It is creating a response object of a certain type.

**Comment by dynasource** [comment] 2016-11-23 11:16
I know. But I've said enough on this subject.

**Comment by rob006** [comment] 2016-11-23 11:18
I'd prefer `asJson()` - it is more readable and more practical - if in IDE you type `$this->as` you will get hints with all similar methods. It is also more consistent - we have `render()` not `renderResponse()`.

**Comment by samdark** [comment] 2016-11-23 11:32
@rob006 `render` actually returns rendered string which is not necessary returned. You can save it to database again, for example.

**Closed** 2016-12-01 09:33 UTC
Labels: type:enhancement

**Comment by brandonkelly** [comment] 2017-03-02 02:11
Just noticed the new `asJson()` and `asXml()` methods. Nice! We happened to have the exact [same](https://github.com/craftcms/cms/blob/7401dc11926d5a018e503d91fafef2f3373e33af/src/web/Controller.php#L258) [methods](https://github.com/craftcms/cms/blob/7401dc11926d5a018e503d91fafef2f3373e33af/src/web/Controller.php#L309) in Craft 3 (with the same names even :), so thanks for lightening our codebase even more!

We also have [`asJsonP()`](https://github.com/craftcms/cms/blob/7401dc11926d5a018e503d91fafef2f3373e33af/src/web/Controller.php#L275) and [`asRaw()`](https://github.com/craftcms/cms/blob/7401dc11926d5a018e503d91fafef2f3373e33af/src/web/Controller.php#L292), mapping to the like-named response output formatters. Any reason those were omitted in 081ee7c5b13ba3735e8376394b1f016eb30a68e5 @dynasource?

**Comment by dynasource** [comment] 2017-03-02 11:16
@brandonkelly, because is was not part of this feature request but from a consistency perspective these could be added.

**Comment by Kolyunya** [comment] 2017-03-02 12:31
@brandonkelly have you noticed that https://github.com/yiisoft/yii2/commit/081ee7c5b13ba3735e8376394b1f016eb30a68e5 and your implementation are incompatible? Default `[]` parameter was [rejected](https://github.com/yiisoft/yii2/issues/13620) for some reason.

**Comment by brandonkelly** [comment] 2017-03-02 13:04
@Kolyunya Do you mean incompatible from a PHP strict standards perspective? PHP does allow you to override a method and add default values to its params under strict standards. I ended up just removing our versions after seeing this anyway, though. We were never taking advantage of the default `[]` values in our own codebase.

And fwiw, I think I prefer it w/out the defaults, now that I think about it. If I was new to the codebase and saw `return $this->asJson()` in a controller action (with no explicit data value), I would probably assume it was trying to JSON-encode the entire controller class.

**Comment by dynasource** [comment] 2017-03-02 14:04
> now that I think about it. If I was new to the codebase and saw return $this->asJson() in a controller action (with no explicit data value), I would probably assume it was trying to JSON-encode the entire controller class.

Agree

**Comment by Kolyunya** [comment] 2017-03-02 14:28
Doesn't the fact that omitting method parameter makes it unclear what it does indicate that it was named poorly?
