### ISSUE TITLE
defaultSchema in PostgreSQL must match the username used in DbConnection for the table schema name resolve to work

### ISSUE THREAD

**Issue by lourdas** [yiisoft/yii2#11832] opened 2016-06-27 11:27 UTC
### What steps will reproduce the problem?
- Create a schema in PostgreSQL, eg. myschema. Create a couple of tables.
- Create the models that correspond to the database tables through Gii.
- Modify `db.php` like:

``` php
<?php
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=localhost;dbname=mydb',
    'username' => 'myschemauser',
    'password' => 'pass',
    'charset' => 'utf8',
    'emulatePrepare' => false,
    'schemaMap' => [
        'pgsql' => [
            'class' => 'yii\db\pgsql\Schema',
            'defaultSchema' => 'myschema',
        ]
    ],
];
```
- Create a new test controller and try to find some rows through the models, like

``` php
$rows = Mymodel::find()->all();
```
### What is the expected result?

The expected result is that `$rows` contains all the rows in the corresponding table.
### What do you get instead?

I get a database exception that the relation does not exist. The database username used in the database config (in this case `myschemauser`) must match the schema name (`myschema`) for this to work. If they match, all is fine.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 5.6.23 |
| Operating system | Windows 7 |

**Comment by schoradt** [comment] 2016-06-27 19:00
The Problem is the search path inside the postgresql database. The default schema is only used at schema analysis time. For queries no dedicated schema is used (I found no usage in the code). 

Your configuration should work if you set the search_path of the user with ALTER USER SET search_path TO myschema, public; or you can set the search path for the session with set search_path as first command.

Can you try this?

**Comment by lourdas** [comment] 2016-06-27 19:11
Now, I understand why the default schema must match the username used for the database connection. It's because the default search_path of a user is `"$user", public`. Still, I think the `defaultSchema` parameter should be used as I described in the issue description.

@schoradt Your suggestion would of course work.

**Comment by MKiselev** [comment] 2016-10-18 06:49
See temporary fix here: https://github.com/yiisoft/yii2/issues/12763#issuecomment-254421427

**Comment by cebe** [comment] 2017-04-26 09:18
duplicate of #12763, closing this as the other has a workaround and more information.

**Closed by cebe** 2017-04-26 09:18 UTC
Labels: PostgreSQL, status:to be verified
