### ISSUE TITLE
Version 2.0.46 brakes saving in DB

### ISSUE THREAD

**Issue by rsemenyshyn** [yiisoft/yii2#19531] opened 2022-08-31 20:37 UTC
I have updated Yii2 up to 2.0.46

My code was working well, but I started to get the following:
```
PHP Notice 'yii\base\ErrorException' with message 'Undefined index: Id' 

in .../vendor/yiisoft/yii2/db/BaseActiveRecord.php:1765

Stack trace:
#0 ...vendor/yiisoft/yii2/db/BaseActiveRecord.php(1765): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '...', 1765, Array)
#1 .../vendor/yiisoft/yii2/db/BaseActiveRecord.php(642): yii\db\BaseActiveRecord->isAttributeDirty('Id', 22813)

...

```

I have analyzed changes done between 2.0.45 and 2.0.46 and found the following:
https://github.com/yiisoft/yii2/commit/0f004db99b93e731b0e4cdbd35dcf78d86701f87
Here, 
```
 - if (isset($names[$name]) && (!array_key_exists($name, $this->_oldAttributes) || $value !== $this->_oldAttributes[$name])) {
 + if (isset($names[$name]) && (!array_key_exists($name, $this->_oldAttributes) || $this->isAttributeDirty($name, $value))) {
```
Where `isAttributeDirty` is a new function that looks like:
```
private function isAttributeDirty($attribute, $value)
    {
        $old_attribute = $this->oldAttributes[$attribute];
        if (is_array($value) && is_array($this->oldAttributes[$attribute])) {
            $value = ArrayHelper::recursiveSort($value);
            $old_attribute = ArrayHelper::recursiveSort($old_attribute);
        }

        return $value !== $old_attribute;
    }
```

For me, interesting is, why we used `$this->_oldAttributes` in the older versions, but `$this->oldAttributes` in the newest?

So I changed the code locally to:
```
private function isAttributeDirty($attribute, $value)
    {
        $old_attribute = $this->_oldAttributes[$attribute];
        if (is_array($value) && is_array($this->_oldAttributes[$attribute])) {
            $value = ArrayHelper::recursiveSort($value);
            $old_attribute = ArrayHelper::recursiveSort($old_attribute);
        }

        return $value !== $old_attribute;
    }
```

and that works back as it used to be before.

Is this a bug, or feature?

**Comment by KirDE** [comment] 2022-08-31 20:40
looks like typo for me

**Comment by bizley** [comment] 2022-09-01 06:41
Damn, indeed. I wonder why the tests didn't show anything. Could you prepare PR fixing this? With proper tests if possible?

**Comment by lesha724** [comment] 2022-09-01 11:46
@bizley, This isn`t type, see [this](https://github.com/yiisoft/yii2/blob/0f004db99b93e731b0e4cdbd35dcf78d86701f87/framework/db/BaseActiveRecord.php#L540)

**Comment by bizley** [comment] 2022-09-01 12:10
Hmm, right... Missed that getter. So what is going on here? This should not affect anything. @rsemenyshyn could you provide us with a minimal data to reproduce the problem?

**Comment by WinterSilence** [comment] 2022-09-10 02:28
> For me, interesting is, why we used $this->_oldAttributes in the older versions, but $this->oldAttributes in the newest?

because `$this->oldAttributes` calling `$this->getOldAttributes()`, by default, `$this->_oldAttributes` is null i.e. not array 
https://github.com/yiisoft/yii2/blob/27344557ea415011afda1d26be0df1496a1cc51a/framework/db/BaseActiveRecord.php#L93

**Comment by WinterSilence** [comment] 2022-09-10 02:38
~~~php
private function isAttributeDirty($attribute, $value)
{
    $oldAttributes = $this->getOldAttributes();
    if (!array_key_exists($attribute, $oldAttributes)) {
        return false;
    }
    if ($value === $oldAttributes[$attribute]) {
        return true;
    }
    if ($value != $oldAttributes[$attribute] && is_array($value) && is_array($oldAttributes[$attribute])) {
        $value = ArrayHelper::recursiveSort($value);
        $oldAttributes[$attribute] = ArrayHelper::recursiveSort($oldAttributes[$attribute]);
    }

    return \yii\helpers\Comparator::compare($value, $oldAttributes[$attribute]);
}
~~~
[Comparator](https://github.com/yiisoft/yii2/pull/19358)

**Comment by bizley** [comment] 2022-10-27 06:37
Since this change broke app and we have many reports about it I would say that we need to rollback it. @samdark ?

**Comment by markch123** [comment] 2022-11-02 06:24
Hi @samdark, was there some discussion/progress on @bizley  request to revert?

**Comment by schmunk42** [comment] 2022-11-02 09:37
> Hi @samdark, was there some discussion/progress on @bizley request to revert?

@markch123 see https://github.com/yiisoft/yii2/issues/19546

**Comment by samdark** [comment] 2022-11-03 11:10
Closing since it was reverted in master.

**Closed by samdark** 2022-11-03 11:10 UTC
Labels: type:bug
