### ISSUE TITLE
Feature request: ASCII Tables

### ISSUE THREAD

**Issue by tonykor** [yiisoft/yii2#13987] opened 2017-04-13 14:34 UTC
Hello,

please consider adding a function to Console helper, which will create an ANSII tables from array of data like in Zend https://framework.zend.com/manual/2.1/en/modules/zend.text.table.html

Thanks.

**Comment by pana1990** [comment] 2017-04-13 14:53
i am woriking this feature https://github.com/yiisoft/yii2/pull/11415#issue-150664421

duplicated https://github.com/yiisoft/yii2/issues/11412

Thanks for your link ;)

**Comment by arogachev** [comment] 2017-04-13 15:23
Closing as duplicate of #11412.

**Closed by arogachev** 2017-04-13 15:23 UTC
