### ISSUE TITLE
Disabled activeCheckbox doesn't disable the hidden checkbox pair so values are always reset

### ISSUE THREAD

**Issue by nagyt234** [yiisoft/yii2#16130] opened 2018-04-19 16:45 UTC
### What steps will reproduce the problem?
Use similar code:
```
$model->show_full_text = true;
Html::activeCheckbox($model, 'show_full_text', ['disabled' => true]);
```
This creates the following HTML:
```
<input type="hidden" name="Nutrient[show_full_text]" value="0">
<label style="margin-bottom:0">
    <input type="checkbox" id="nutrient-show_full_text" name="Nutrient[show_full_text]" value="1" checked disabled">
    Show full text
</label>
```

### What is the expected result?

The hidden input should be also disabled.

### What do you get instead?

The hidden input is not disabled. When the form is submitted, the disabled input is correctly ignored and the hidden value is submitted, i.e. the appropriate value will be always resetted.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.1
| Operating system | Ubuntu 16.04

**Comment by rob006** [comment] 2018-04-21 15:36
Duplicate of #10843

**Closed by rob006** 2018-04-21 15:36 UTC
Labels: status:ready for adoption, type:bug
