### ISSUE TITLE
Check FileCache

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#9104] opened 2015-07-14 11:32 UTC
https://github.com/yiisoft/yii2/commit/398caaf7fd75dd42bc2c485e09553663601d7eaf#commitcomment-12149643

**Comment by RomeroMsk** [comment] 2015-07-14 12:07
Can you reproduce this? I will check another guess, when will have more time. It may be not Yii problem.

**Comment by RomeroMsk** [comment] 2015-07-14 13:40
Finally found the reason! It was server configuration problem, not framework. Updating Yii2 to the latest version just helped to see this problem, thanks to [this commit](https://github.com/yiisoft/yii2/commit/1a7d9ac809d0b337d510ee805c4d7d57f8b38ab0).
Sorry for misinformation! Please, close the issue.

**Closed** 2015-07-14 16:27 UTC
Labels: severity:critical
