### ISSUE TITLE
Active form should not generate any excessive HTML for hidden inputs

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2#11418] opened 2016-04-25 11:39 UTC
### What steps will reproduce the problem?

``` php
<?=$form->field($model, 'format', ['options' => ['tag' => '']])->hiddenInput()->label(false)->error(false)?>
```
### What is the expected result?

Just HTML of the hidden input itself.
### What do you get instead?

Input is wrapped into DIV.
### Additional info

| Q | A |
| --- | --- |
| Yii version | master |
| PHP version | any |
| Operating system | any |

**Comment by Mirocow** [comment] 2016-04-25 12:05
Yii version:	master
PHP: 5.6
Operating system: MacOSX

```html
< class="field-pricesend-format required">
```

**Comment by im-kulikov** [comment] 2016-04-25 12:36
Q | A
------------ | -------------
Yii version | master
PHP version | 5.6.19-0+deb8u1
Operating system | Debian Jessie

## What do you get instead?
```html
&lt; class="field-productreview-name"&gt;
```

@Mirocow method must return expected value, not void.

fix, must be like this:

```php
public static function beginTag($name = '', $options = [])
{
    if (!$name){  
        return "";
    }
    return "<$name" . static::renderTagAttributes($options) . '>';
}
```

**Comment by im-kulikov** [comment] 2016-04-25 12:57
@samdark @Mirocow 

```php
public static function remove(&$array, $key, $default = null)
    {
        if (is_array($array) && (isset($array[$key]) || array_key_exists($key, $array))) {
            $value = $array[$key];
            unset($array[$key]);

            return $value;
        }

        return $default;
    }
```

this method not check if value is empty, and return empty string.

If need to fix that part, then you should be rewritten as follows:

```php
public static function remove(&$array, $key, $default = null)
    {
        if (is_array($array) && (isset($array[$key]) || array_key_exists($key, $array))) {
            $value = $array[$key];
            unset($array[$key]);

            return $value ?: $default;
        }

        return $default;
    }
```

If want to get rid of the `div`, then do the following:
```php
public static function beginTag($name = '', $options = [])
{
    if (!$name){  
        return "";
    }
    return "<$name" . static::renderTagAttributes($options) . '>';
}
```

**Comment by cebe** [comment] 2016-04-27 21:59
I remember there was a discussion that this was expected behavior, but I did not find it.

related: https://github.com/yiisoft/yii2/issues/735#issuecomment-26008916
duplicate of https://github.com/yiisoft/yii2/issues/2990#issuecomment-53729223 ?

**Comment by samdark** [comment] 2016-05-17 22:47
@cebe it's a bit different case. In this issue we're explicitly setting not to use any wrapper tag and render no label and no error.

**Comment by samdark** [comment] 2016-12-15 22:44
Added test that verifies that it works as expected already and no fix needed.

**Closed** 2016-12-15 22:44 UTC
