### ISSUE TITLE
Clarify what is M in MVC

### ISSUE THREAD

**Issue by rugabarbo** [yiisoft/yii2#15964] opened 2018-03-23 20:37 UTC
The «Model» is a very unsuitable name for the class [Model](https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php). Word «model» is associated with a whole layer (many classes) of MVC architecture. Concrete class shouldn't have such name. It's mess, chaos, anarchy... :D

I propose the name «Collector» (collect, load and validate data). ActiveRecords, forms and data filters – they all can be "collectors".

**Comment by berosoboy** [comment] 2018-03-23 21:01
> Word «model» is associated with a whole layer (many classes) of MVC architecture.

It implies to rename "Controller" and "View" classes too?

I think the names are suitable. Maybe changing these class to `abstract` should be enough.

**Comment by rugabarbo** [comment] 2018-03-23 21:16
> It implies to rename "Controller" and "View" classes too?

No. Model is a larger (more complex) layer in comparison with Controller/View layers.

**Comment by FabrizioCaldarelli** [comment] 2018-03-23 21:28
I think that "Model" word expresses all complexity related to data manipulation, that reflects effectively his rule in MVC pattern.

Then Collector make me think of a kind of helper classes to handle collections, or data aggregator, but not something to get and manipulate data from source.

**Comment by samdark** [comment] 2018-03-23 21:33
I think it will be too much for 2.1 but we may consider it for 2.2.

There are alternative terms for the same pattern such as http://pmjones.io/adr/

**Comment by berosoboy** [comment] 2018-03-23 21:48
Understood @rugabarbo . I was confused about model meaning.

If it will be changed, i propose something like DomainModel, Entity, DataModel, or ModelObject. It sounds more concrete to me.

**Comment by FabrizioCaldarelli** [comment] 2018-03-23 21:53
If I had to pickup a new name, I'd vote for Entity.

**Comment by samdark** [comment] 2018-03-23 23:18
Not as I'm aware of. There are surveys at Facebook and in Slack though.

**Comment by gagatust** [comment] 2018-03-24 03:29
Entity or Dao.

**Comment by schmasterz** [comment] 2018-03-24 21:45
It will be easier to rename the framework to Laravel. 
use Illuminate\Database\Eloquent\Model;

Sarcasm!

**Comment by samdark** [comment] 2018-03-29 22:52
We have these:

1. Active Record. Saves data to DB and loads it from DB.
2. Form. Validates data, performs an action on form submit.
3. Search.  Validates parameters, forms query or criteria from these.
4. API Resource. Defines how data is serialized, validates filters input, builds query based on filters input.

**Comment by githubjeka** [comment] 2018-03-30 05:17
We have these:
1. model ActiveRecord. Saves data to DB and loads it from DB. (extends of Model)
2. model *Request* -  validates data of requests by a scenario. (extends of Model)

I don't want to see in documentation:
We have there:
collector ActiveRecord
collector Request
entity ActiveRecord
dao ActiveRecord
datamodel ActiveRecord
model object ActiveRecord
...

Any way you will use `model` word when describe objects of requests or activerecords 
No need rename Model class

**Comment by SilverFire** [comment] 2018-04-01 09:09
Agreed to leave as is.

**Comment by SilverFire** [comment] 2018-04-01 09:10
Closing the issue at least until we find better reasons to rename Model

**Comment by samdark** [comment] 2018-04-01 09:39
We probably need to call these "model object" in the guide and mention that "model" itself consists of many model objects.

**Comment by Auramel** [comment] 2018-04-04 07:49
Hey, yo. Why this class should called something about Model? If we looking into code: here has: validations and attributes  (and something from base classes). I think it closer to Form or Validation name. 

So, can you divide this class to 2 classes - Validation and Form? For example, In form you have all attributes method. In validation - validate mehods. What do you think?

**Comment by twisted1919** [comment] 2018-04-04 09:32
All the ideas to change it to something else are plain stupid and without any reason.
We have other pressing matters than changing the model class to something else.
I don't even understand why this issue is still opened.

**Comment by darealfive** [comment] 2018-04-04 14:02
There are probably thousands of bugs in Yii and of course, they differ in having different priorities. Naming schema issue usually gets a lower priority than logic issues. The priority must control the time of bug fixing. That is why I understand why this issue is still opened.

**Comment by twisted1919** [comment] 2018-04-04 14:32
The problem is that someone, came up and said "Let's rename class Model to something else". Not only that they said 'to something else" meaning they had no clue what they want, but also to me it just sounds like "let's take a piece of perfect fundamental concept of Yii and screw it because i want 
 to do so, even if i have no reason, or if i do, i don't know it yet".

M in MVC says Model for a good reason, because it handles data modeling, regardles of it's source or destination. The name is perfectly fine people, let's move along and forget this non-sense of renaming a fundamental part of the framework.

Come one, this is going too far by now.

**Comment by samdark** [comment] 2018-04-04 14:48
https://github.com/yiisoft/yii2/issues/15964#issuecomment-377775076 is what I see as solution.

**Closed** 2019-04-23 21:56 UTC
Labels: type:docs
