### ISSUE TITLE
Authentication (login) not working on PHP 5.6

### ISSUE THREAD

**Issue by p4scu41** [yiisoft/yii2#13242] opened 2016-12-19 04:00 UTC
Hello everybody, I have used Yii2 for a while, recently I updated my local server, but unfortunaly the funcionality for authentication fail, when I send a user and valid password, it doesn't throw error but redirect with the user not authenticated, althow if i send a user with a wrong password, it send the error message correctly. I tryed with a fresh instalation and the result was same. It's really weird because If a check the option Remember Me the authentication works and I check the error logs for php and apache and it's clear.

I am using PHP 5.6.24, Apache 2.4.10 and MySQL 5.6.20 on Windows 8.1 x64.

Thanks for your help.

**Comment by SilverFire** [comment] 2016-12-19 10:11
Which Yii version do you use?

Can you find a commit that breaks behavior using [git bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search)?

**Comment by p4scu41** [comment] 2016-12-20 17:18
Thanks for yours soon anwers.

I am using Yii 2.0.10

composer info yiisoft/yii2

name     : yiisoft/yii2
descrip. : Yii PHP Framework Version 2
keywords : framework, yii2
versions : * 2.0.10
type     : library
license  : BSD 3-clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/yiisoft/yii2-framework.git 5bfcb7a6dfa9771e2248eb8c4448613330f343ff
dist     : [zip] https://api.github.com/repos/yiisoft/yii2-framework/zipball/5bfcb7a6dfa9771e2248eb8c4448613330f343ff 
names    : yiisoft/yii2

autoload
psr-4
yii\ => .

requires
bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable | 1.12.*@stable
bower-asset/jquery.inputmask ~3.2.2
bower-asset/punycode 1.3.*
bower-asset/yii2-pjax ~2.0.1
cebe/markdown ~1.0.0 | ~1.1.0
ext-ctype *
ext-mbstring *
ezyang/htmlpurifier ~4.6
lib-pcre *
php >=5.4.0
yiisoft/yii2-composer ~2.0.4

**Comment by SilverFire** [comment] 2016-12-24 09:30
Failed to reproduce on basic application template. Could you provide exact steps to reproduce an issue?

**Comment by klimov-paul** [comment] 2016-12-26 13:43
Unable to reproduce.

**Comment by klimov-paul** [comment] 2016-12-26 13:44
Can you check if seesion cookie is actually send to the client and session is successfully written up.

**Comment by klimov-paul** [comment] 2016-12-26 13:44
Are you able to save some value into session at all?

**Comment by samdark** [comment] 2017-01-15 19:31
Closing the issue since no feedback provided for a long time and we don't have enough data to deal with the issue.

**Closed by samdark** 2017-01-15 19:31 UTC
Labels: status:need more info
