### ISSUE TITLE
logVars of log target is not working

### ISSUE THREAD

**Issue by gvsandeep2647** [yiisoft/yii2#18335] opened 2020-10-16 04:10 UTC
### What steps will reproduce the problem?
I am not able to use the logvars property of logging properly.
With this config:
```
[
         'class' => 'common\components\log\ExceptionFileTarget',
         'levels' => ['exception'],
         'logVars' => ['_SERVER.LC_ALL'],
         'logFile' => '@runtime/logs/error.logstash.log',
         'exportInterval' => 1,
],
```
### What is the expected result?
```
{
"timestamp":"2020-10-15T12:46:54+00:00",
"ip":"-",
"userId":"-",
"sessionId":"-",
"level":"exception",
"category":"customException",
"text":"[],
"$_SERVER":"["LC_ALL" => "Some other value"]"
}
```

### What do you get instead?
```
{
"timestamp":"2020-10-15T12:46:54+00:00",
"ip":"-",
"userId":"-",
"sessionId":"-",
"level":"exception",
"category":"customException",
"text":"[],
}
```

### Additional info
Default Settings:
```
[
         'class' => 'common\components\log\ExceptionFileTarget',
         'levels' => ['exception'],
         'logFile' => '@runtime/logs/error.logstash.log',
         'exportInterval' => 1,
],
```

Log in that case:
```
{
"timestamp":"2020-10-15T12:46:54+00:00",
"ip":"-",
"userId":"-",
"sessionId":"-",
"level":"exception",
"category":"customException",
"text":"[],
"$_SERVER":"["LANG" => "Eng, "LC_ALL" => "Some other value"]"
}
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 5.6
| Operating system | docker image with `nginx:alpine`

**Comment by bizley** [comment] 2020-10-27 17:15
Does this happen as well with the latest version of Yii 2?

**Comment by gvsandeep2647** [comment] 2020-10-28 01:15
No idea

**Comment by bizley** [comment] 2020-10-28 09:18
Ok, could you check? If you are not willing to upgrade your Yii version eventual bugfix will be provided to the newest release anyway.

**Comment by gvsandeep2647** [comment] 2020-10-28 09:26
Would not be able to upgrade the Yii version. No issues, we have decided to drop the $_SERVER variable in its entirety and that's working for us now.

**Comment by samdark** [comment] 2020-10-29 10:17
Closing since we need an issue that is reproducible with latest Yii version in order to fix it.

**Closed by samdark** 2020-10-29 10:17 UTC
Labels: status:to be verified
