### ISSUE TITLE
Yii2 for REST applications

### ISSUE THREAD

**Issue by graphicmist** [yiisoft/yii2#8709] opened 2015-06-08 16:16 UTC
Yii2 has an excellent support for REST applications. I want to use Yii  just for creating an REST api. I will not be needing bower packages, but since it is required, i have to install them. Is there any way i can exclude them and still use composer for autoloading and installing packages?

**Comment by cebe** [comment] 2015-06-08 16:41
duplicate of https://github.com/yiisoft/yii2/issues/8452

you may add the required bower package names to your composer.json in `provide` section https://getcomposer.org/doc/04-schema.md#provide to  pretend they exist already and avoid the download.

**Closed by cebe** 2015-06-08 16:41 UTC

**Comment by graphicmist** [comment] 2015-06-08 16:44
Looks cool. Thanks
