### ISSUE TITLE
MS SQL Server charset

### ISSUE THREAD

**Issue by BakhtiyorRuziev** [yiisoft/yii2#5951] opened 2014-11-06 15:44 UTC
When working with MS SQL Server database have many problems with charset, When we need to enter Cyrillic symbols into the database records, we need to make the request like this:
```
    insert into table (id,name) values (1,N'Привет');
```
Is it possible to put the identifier N '' from Active Record in a query????

**Comment by samdark** [comment] 2015-03-03 23:27
Can't reproduce w/o additional info. Closing.

**Closed by samdark** 2015-03-03 23:27 UTC
Labels: status:need more info
