### ISSUE TITLE
JSON::encode for DateTime

### ISSUE THREAD

**Issue by snakedin** [yiisoft/yii2#17760] opened 2019-12-23 16:07 UTC
### What steps will reproduce the problem?
`echo \yii\helpers\Json::encode(['date' => new \DateTime()]);`

### What is the expected result?
`{"date":{"date":"2019-12-23 15:52:27.717576","timezone_type":3,"timezone":"UTC"}}`

### What do you get instead?
`{"date":{}}`

But when I run native php `json_encode`:
`echo json_encode(['date' => new \DateTime()]);`

Returns expected result:
`{"date":{"date":"2019-12-23 15:52:27.717576","timezone_type":3,"timezone":"UTC"}}`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.4.0 (cli)
| Operating system | Debian 10

**Comment by kamarton** [comment] 2019-12-24 04:33
For yii3, consider whether it makes sense to support the current php output format (`{"date":"2019-12-23 15:52:27.717576","timezone_type":3,"timezone":"UTC"}`). I prefer unix timestamp (eliminate timezone), or [RFC3339#5.6](https://tools.ietf.org/html/rfc3339#section-5.6) format [`Y-m-d\TH:i:s.vP`](https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.rfc3339_extended)

**Comment by simialbi** [comment] 2019-12-24 09:43
Can't verify this issue. I did the following:
I added 
```php
        // @see https://github.com/yiisoft/yii2/issues/17760
        $data = ['date' => new \DateTime('now')];
        $this->assertSame('{"date":{}}', Json::encode($data));
```
to [method testEncode()](https://github.com/yiisoft/yii2/blob/master/tests/framework/helpers/JsonTest.php#L30) and got following resut:
```
Failed asserting that two strings are identical.
Expected :{"date":{}}
Actual   :{"date":{"date":"2019-12-24 09:38:26.801064","timezone_type":3,"timezone":"UTC"}}
```
I used yii `2.0.31` with php `7.2`

**Comment by snakedin** [comment] 2019-12-24 11:11
Well, it works as expected on php `7.2` and `7.3` but I can stably reproduce issue on `7.4`. 

For checking this issue I used Docker and php tags `php:7.2-fpm`, `php:7.3-fpm`, `php:7.4-fpm`

**Comment by rob006** [comment] 2019-12-24 12:22
I can confirm this issue - it was changed in PHP 7.4. It seems that `DateTime` is somewhat hacky, since it should not contain public properties, and `json_encode()` is treated specially for BC reasons. It was already fixed for array cast: https://bugs.php.net/bug.php?id=78383

But foreach behavior is still inconsistent: https://3v4l.org/h99LLn

**Comment by alex-code** [comment] 2019-12-24 14:55
Could we cast to array in `foreach` [BaseJson.php#L162](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseJson.php#L162)?

**Comment by rob006** [comment] 2019-12-24 17:36
Cast to array exposes also private and protected properties - it would be easier to add special condition for `DateTime`. But I would try to report it as PHP bug, since current behavior for `DateTime` is weird and inconsistent.

**Comment by samdark** [comment] 2019-12-25 09:25
@rob006 would you please report a PHP bug?

**Comment by rob006** [comment] 2019-12-28 11:58
https://bugs.php.net/bug.php?id=79041

**Comment by samdark** [comment] 2020-01-09 14:21
Seems to unlikely being fixed on the PHP side.

**Closed** 2020-01-09 15:53 UTC
Labels: php7, type:bug
