### ISSUE TITLE
yii\helpers\BaseHtml trouble getting attribute label in model with array attribute

### ISSUE THREAD

**Issue by surgat** [yiisoft/yii2#9519] opened 2015-08-26 06:33 UTC
We have record with embedded model(or array)

``` php
class Project extends ActiveRecord
{
    /**
     * @return FeedModel
     */
    public function getFeed();

    /**
     * @param FeedModel $model
     */
    public function setFeed($model);

    public function attributeLabels()
    {
        return [
            'name'      => 'Name',
            'feed.url'  => 'Url'
        ];
    }
}

class FeedModel implements Model
{
    public $url;
}
```
# Then
## Firts. Access with [ ]

``` php
// return label name "Feed". Label feed.url not working
echo $form->field($model, 'feed[url]')->dropDownList(FeedModel::typeList());
```

To work here need copy the code from yii\helpers\BaseHtml::getAttributeValue

``` php
................................
        if ($matches[3] !== '') {
            foreach (explode('][', trim($matches[3], '[]')) as $id) {
                if ((is_array($value) || $value instanceof \ArrayAccess) && isset($value[$id])) {
                    $value = $value[$id];
                } else {
                    return null;
                }
            }
        }
................................
```

To yii\helpers\BaseHtml::getAttributeName and replace [] on .

``` php
    public static function getAttributeName($attribute)
    {
        if (preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
            $attribute = [$matches[2]];
            if ($matches[3] !== '') {    // Here
                $attribute = array_merge($attribute, explode('][', trim($matches[3], '[]')));
            }
            return implode('.', $attribute);
        } else {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
    }
```
## Second. Access with "."

``` php
// PHP User Error – yii\base\ErrorException 
echo $form->field($model, 'feed.url')->dropDownList(FeedModel::typeList());
```

Char "." allowed, but not dereferenced as array access in yii\grid\DataColumn

In yii\helpers\BaseHtml

``` php
    public static function getAttributeValue($model, $attribute)
    {
        if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
        $attribute = $matches[2];
        $value = $model->$attribute; // This
        ....................................
    }
```

Can replace

``` php
    public static function getAttributeValue($model, $attribute)
    {
        if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
        $value = ArrayHelper::getValue($model, $matches[2]);
        ....................................................
    }
```

But input name will be feed.type

``` php
    public static function getInputName($model, $attribute)
    {
        $formName = $model->formName();
        if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
        $prefix = $matches[1];
        $attribute = $matches[2];
        $suffix = $matches[3];
        if ($formName === '' && $prefix === '') {
            return $attribute . $suffix;
        } elseif ($formName !== '') {
            return $formName . $prefix . "[$attribute]" . $suffix;
        } else {
            throw new InvalidParamException(get_class($model) . '::formName() cannot be empty for tabular inputs.');
        }
    }
```

Can replace

``` php
    public static function getInputName($model, $attribute)
    {
        $formName = $model->formName();
        if (!preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
            throw new InvalidParamException('Attribute name must contain word characters only.');
        }
        $prefix = $matches[1];
        $attribute = $matches[2];
        $suffix = $matches[3];
        $secondAttributes = '';
        if (strpos($attribute, '.')) {
            $list = explode('.', $attribute);
            $attribute = array_shift($list);
            $secondAttributes = '[' . implode('][', $list) . ']';
        }
        if ($formName === '' && $prefix === '') {
            return $attribute . $secondAttributes . $suffix;
        } elseif ($formName !== '') {
            return $formName . $prefix . "[$attribute]" . $secondAttributes . $suffix;
        } else {
            throw new InvalidParamException(get_class($model) . '::formName() cannot be empty for tabular inputs.');
        }
    }
```

**Comment by cebe** [comment] 2015-08-27 11:47
what are you trying to do? you can not use related attributes in a form like that.

what could work is this:

```php
echo $form->field($model->feed, 'url')->dropDownList(FeedModel::typeList());
```

but it still depends on what you want to do. also need to change controller action to reflect the input properly.

**Comment by lynicidn** [comment] 2015-08-27 12:52
read it and how fix this https://github.com/yiisoft/yii2/pull/8963

**Comment by surgat** [comment] 2015-08-27 18:06
This workin if you use model and don't work if using array

Suppose that class Feed not Model and we work with array or class with ArrayAccess
```php
class Project extends ActiveRecord
{

    public function getFeed() {
        return unserialize($this->_feed);
    }
    public function setFeed($array) {
        $this->_feed = serialize($array);
    }

    public function attributeLabels()
    {
        return [
            'name'       => 'Name',
            'feed.url'    => 'Url'
            'feed.type'  => 'Тип'
        ];
    }
}
```
Model feed lives within the Project
_feed is column in DB

Then
```php
echo $form->field($model->feed, 'url');
```
Not working 

A nice way for me:
```php
1) $form->field($model, 'feed[url]');
2) $form->field($model, 'feed.url');
```
Not need change controller.
Not need add new class without logic.
I can expand "feed" without changing DB.
I change only one class (Project).
Even if I create a class for feed I do not change the controller.

## But 
### With []
attributeLabels not working

### With "." (I like this option because he looks like GridView)
"." is allow char but It causes a fatal error!
```php
if (preg_match('/(^|.*\])([\w\.]+)(\[.*|$)/', $attribute, $matches)) {
```
but It causes a fatal error!
In grid "." is working but not work in form. Felt inconsistency.

## What I want
It is necessary to accept one of the proposed options, and then I'll do patch.

**Comment by cebe** [comment] 2015-08-27 22:07
duplicate of #569

**Comment by surgat** [comment] 2015-08-28 11:19
My issue not duplicate of #569
Because I'm not use relations! My embedded class not ActiveRecord.
I'm use serialized lob pattern http://martinfowler.com/eaaCatalog/serializedLOB.html

**Comment by cebe** [comment] 2016-11-14 22:38
@surgat you should put you feed into a submodel replacing the array for that case. I do not think adding this feature is a good idea as it conflicts with the existing implementation of AR relations.

**Closed by cebe** 2016-11-14 22:38 UTC
Labels: type:feature
