### ISSUE TITLE
Support subqueries for values in QueryBuilder::insert()

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12758] opened 2016-10-17 16:32 UTC
Currently Yii2 supports specifying subqueries as `\yii\db\Query` objects in some places of query, for example:

``` PHP
Model::find()
    ->where(['country_id' => Country::find()->select('id')->where(['name' => 'USA'])])
    ->all();
```

The same should be allowed in other places (if allowed by SQL), in particular in `INSERT` statement, for ex.:

``` PHP
$model = new Model();
$model->country_id = Country::find()->select('id')->where(['name' => 'USA']);
$model->insert(false);
```

**Comment by cebe** [comment] 2016-12-16 00:16
duplicate of #8293

**Comment by PowerGamer1** [comment] 2016-12-16 07:54
@cebe 
My issue is NOT a dupe of https://github.com/yiisoft/yii2/issues/8293 at all. https://github.com/yiisoft/yii2/issues/8293 deals with queries like `INSERT INTO tbl SELECT a, b FROM tbl2` while my issue deals with queries like `INSERT INTO tbl(a,b) VALUES(123, (SELECT x FROM tbl2 WHERE id=456))` - completely different things! Please reopen.

**Comment by cebe** [comment] 2016-12-16 23:53
Oh right, sorry. Was not aware that this case is even possible :)

**Closed** 2017-01-28 21:55 UTC
Labels: type:enhancement
