### ISSUE TITLE
Console stdout method produce unnecessary background color for the nextline in the terminal 

### ISSUE THREAD

**Issue by dabagab** [yiisoft/yii2#14464] opened 2017-07-16 17:21 UTC
### What steps will reproduce the problem?
Running a console command in the terminal of an Ubuntu.
In the Action of an inherited Controller from Console Controller the following stdout code is used.
`$this->stdout("Finished." . PHP_EOL, Console::BG_GREEN);`

I have tried to add only `"\n"` or without endline, but still the same problem.

Or if I do something wrong, can you update the documentation with a correct example how to use the background color for only one command line?
### What is the expected result?
The expected result is **only** the **Finished** command line should have Green background color.
### What do you get instead?
Unfortunately the **Finished** and the **next command line** have the Green background color
![Image of Problem](https://image.ibb.co/mdPbea/Screenshot_from_2017_07_16_19_11_06.png)
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.0
| Operating system | Ubuntu Server 16.04 LTS

**Comment by cebe** [comment] 2017-07-16 20:37
unable to reproduce on debian 9. Could be that your prompt moves the cursor in a way that produces the output? Can you show the output of `echo $PS1`?

**Comment by dabagab** [comment] 2017-07-18 08:47
I use Ubuntu 16.04 LTS on my PC and on my Laptop too, however I use it in the Vagrant too. So this is a fresh installation in Vagrant and I have got this problem.
I did a fresh reinstall on my PC too yesterday, and I got this problem again there. However I do not use directly Debian. So I can close out that this some kind of user configuration problem of the terminal.

Result of `echo $PS1` is here:
```~$ echo $PS1
\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
```

**Comment by dabagab** [comment] 2017-07-18 08:49
However I use the `Codeception` for testing my application.
The colors of messages of `Codeception` is okay, it works fine. The problem seems with the `stdout` function.

**Comment by cebe** [comment] 2017-07-18 10:14
hm... unable to reproduce even with using your prompt. I have adjusted basic app HelloController like this:

```diff
diff --git a/commands/HelloController.php b/commands/HelloController.php
index 86ab8b8..a388ff0 100644
--- a/commands/HelloController.php
+++ b/commands/HelloController.php
@@ -8,6 +8,7 @@
 namespace app\commands;
 
 use yii\console\Controller;
+use yii\helpers\Console;
 
 /**
  * This command echoes the first argument that you have entered.
@@ -25,6 +26,6 @@ class HelloController extends Controller
      */
     public function actionIndex($message = 'hello world')
     {
-        echo $message . "\n";
+        $this->stdout($message . PHP_EOL, Console::BG_GREEN);
     }
 }
```

![bildschirmfoto von 2017-07-18 12-13-51](https://user-images.githubusercontent.com/189796/28312209-9d5d6d90-6bb2-11e7-85eb-a720bcaab79a.png)

**Comment by rob006** [comment] 2017-07-18 11:50
I can reproduce it on Ubuntu 16.04, but it depends on terminal size - it works fine on fullscreen, but with smaller terminal it sometimes looks like on @dabagab screenshot.

**Comment by samdark** [comment] 2017-07-18 12:52
What's the size when it is visible?

**Comment by rob006** [comment] 2017-07-18 13:06
There is no fixed size for which this bug occurs - I just resized terminal couple of times (and run some commands in it) and I get this bug. I'm not sure if it can be fixed in Yii - it looks more like terminal bug.

**Comment by cebe** [comment] 2017-07-18 15:05
unable to reproduce regardless of terminal size. Pretty sure its not a Yii bug.

**Closed by cebe** 2017-07-18 15:05 UTC
Labels: status:to be verified, type:bug
