### ISSUE TITLE
Active record condition: auto aliasing where() and other functions

### ISSUE THREAD

**Issue by mitch3182** [yiisoft/yii2#10882] opened 2016-02-17 11:32 UTC
Is it posible to add aliasing to something like
`$query = SomeActiveRecord::find()->where(['{alias must be here}.status' => 1]);`
?
Sometimes I need to put alias and sometimes I need to put table name here.
May we use it this way?
`->where(['status' => 1])` and program will replace status for {alias}.status for **current** table?
I can not find such query. Sorry if it exists.

Example where I have problems. I create relation:
`
public function getSubjects(){
        return $this->hasMany(Subject::className(), ['id' => 'subject_id'])->andOnCondition(['subject_type' => 'type1'])->via('personSubjects');
    }
`
I can not know what alias must be in "andOnCondition()"
and I use it here:
`$query->joinWith('subjects sb')->andWhere([ 'sb.id' => $_GET['subject'] ]);`
sb - is new alias.

sorry for english.

**Comment by cebe** [comment] 2016-02-17 13:40
You could set alias explicitly using `->alias('subjects')`.

otherwise it's a duplicate of #7263

**Closed by cebe** 2016-02-17 13:40 UTC
