### ISSUE TITLE
Error while creating the log directory

### ISSUE THREAD

**Issue by kasparsj** [yiisoft/yii2#5596] opened 2014-10-16 10:20 UTC
If the runtime directory is not writable, then the error message says:
Trying to get property of non-object in Dispatcher.php on line 181

Which is not helpful at all.
This is because the error happens while executing Dispatcher::init, hence the targets are not properly initialized.

**Comment by orderbynull** [comment] 2015-07-06 07:55
Was trying to reproduce but i got just `Permission denied` error which is ok.@kasparsj can you comment on it?

**Comment by samdark** [comment] 2015-08-13 18:33
No feedback for a long time and it doesn't seem to be reproduceable. Closing.

**Comment by herokiller** [comment] 2015-10-22 03:20
got the same error when runtime is not writable

**Comment by samdark** [comment] 2015-10-22 07:21
@herokiller what is the error exactly? How to reproduce it?

**Comment by herokiller** [comment] 2015-10-22 07:34
@samdark PHP Notice:  Trying to get property of non-object in /home/vladimir/lolmanga/vendor/yiisoft/yii2/log/Dispatcher.php on line 181
when both runtime and web/assets directories are not writable

**Comment by cebe** [comment] 2015-10-28 22:11
@herokiller can you give a stack trace?

**Comment by bazaglia** [comment] 2016-02-10 02:31
Same issue here. As @cebe requested the stack trace:

```
Stack trace:
#0 /vendor/yiisoft/yii2/filters/auth/AuthMethod.php(56): yii\filters\auth\AuthMethod->handleFailure(Object(yii\web\Response))
#1 /vendor/yiisoft/yii2/base/ActionFilter.php(71): yii\filters\auth\AuthMethod->beforeAction(Object(yii\web\ErrorAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#3 /vendor/yiisoft/yii2/base/Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))
#4 /vendor/yiisoft/yii2/base/Controller.php(263): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#5 /vendor/yiisoft/yii2/web/Controller.php(108): yii\base\Controller->beforeAction(Object(yii\web\Er" while reading upstream
```

**Comment by cebe** [comment] 2016-02-10 11:00
Unable to reproduce, need a stack trace to dig deeper into it.

**Comment by ezintz** [comment] 2016-03-08 02:15
Hello everyone,

I can confirm that an issue - more or less - but it seems that the problem is not related to creating the log directory. In my case I am trying to access a custom component which is throwing an exception because the configuration file does not exists. Below you can find the output from NGINX and the content from my the default logging component (yii\log\FileTarget).
```
[error] 24#24: *25 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property of non-object in /path/vendor/yiisoft/yii2/log/Dispatcher.php on line 181
PHP message: PHP Notice:  Trying to get property of non-object in /path/vendor/yiisoft/yii2/log/Dispatcher.php on line 181
PHP message: PHP Notice:  Trying to get property of non-object in /path/vendor/yiisoft/yii2/log/Dispatcher.php on line 181" while reading upstream, client: 192.168.99.1, server: my.domain.com, request: "GET /api/ HTTP/1.1", upstream: "fastcgi://172.17.0.4:9000", host: "my.domain.com"
```
```
[error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Config file /path/config/amqp/config.yml is not reachable! in /path/vendor/mylib/yii2-amqp/src/components/Amqp.php:118
Stack trace:
#0 /path/vendor/mylib/yii2-amqp/src/components/Amqp.php(150): mylib\components\Amqp->getConfigFile()
#1 /path/vendor/mylib/yii2-amqp/src/components/Amqp.php(164): mylib\components\Amqp->getAmqpConfig()
#2 /path/vendor/mylib/yii2-amqp/src/components/Amqp.php(135): mylib\components\Amqp->getAmqpConfigProcessor()
#3 /path/components/log/MonitoringTarget.php(40): mylib\components\Amqp->getBuilder()
#4 /path/vendor/yiisoft/yii2/base/Object.php(107): app\components\log\MonitoringTarget->init()
#5 [internal function]: yii\base\Object->__construct(Array)
#6 /path/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->newInstanceArgs(Array)
#7 /path/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('app\\components\\...', Array, Array)
#8 /path/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('app\\components\\...', Array, Array)
#9 /path/vendor/yiisoft/yii2/log/Dispatcher.php(101): yii\BaseYii::createObject(Array)
#10 /path/vendor/yiisoft/yii2/base/Object.php(107): yii\log\Dispatcher->init()
#11 /path/vendor/yiisoft/yii2/log/Dispatcher.php(89): yii\base\Object->__construct(Array)
#12 [internal function]: yii\log\Dispatcher->__construct(Array)
#13 /path/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->newInstanceArgs(Array)
#14 /path/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('yii\\log\\Dispatc...', Array, Array)
#15 /path/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yii\\log\\Dispatc...', Array, Array)
#16 /path/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#17 /path/vendor/yiisoft/yii2/base/Application.php(302): yii\di\ServiceLocator->get('log')
#18 /path/vendor/yiisoft/yii2/web/Application.php(63): yii\base\Application->bootstrap()
#19 /path/vendor/yiisoft/yii2/base/Application.php(267): yii\web\Application->bootstrap()
#20 /path/vendor/yiisoft/yii2/base/Object.php(107): yii\base\Application->init()
#21 /path/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#22 /path/web/index.php(11): yii\base\Application->__construct(Array)
#23 {main}
```
After going to the Dispatcher I checked the configured targets. Inspecting each one of them (FileTarget, MonitoringTarget) I discovered that MonitoringTarget does not have all member variables from the abstract yii\log\Target, but for the FileTarget component it seems to be working. The implementation for the MonitoringTarget looks like this:
```php
use Yii;
use yii\log\Target;
class MonitoringTarget extends Target
{
  public function init() { parent:init(); }
  public function export() { /* Handle the messages */ } 
}
```

This happens on Debian 8.3 with PHP 7.0.4.
```bash
PHP 7.0.4-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
and I just discovered this while porting the application to Docker. If you need more information let me know and I will try to gather it for you guys.

**Comment by diogopms** [comment] 2016-03-16 20:26
I Had this error and i fixed installing php5-curl:

`sudo apt-get install php5-curl`

This fixed my problem with this error

`2016/03/16 20:00:28 [error] 7983#0: *12 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property of non-object in yiisoft/yii2/log/Dispatcher.php on line 181" while reading upstream, `

**Comment by samdark** [comment] 2016-07-04 10:00
Can't do anything based on information provided. Closing.

**Closed by samdark** 2016-07-04 10:00 UTC
Labels: status:need more info
