### ISSUE TITLE
Number validator incorrectly handles values of some data types for models

### ISSUE THREAD

**Issue by vesmi** [yiisoft/yii2#11672] opened 2016-06-01 07:45 UTC
### What steps will reproduce the problem?

Given:
```
class User extends ActiveRecord
{
    ...
    public function rules()
    {
        return [
            ['user_id', 'required'],
            ['user_id', 'integer', 'integerOnly' => true],
            ...
        ];
    }
}
```

Case 1:
```
$model = new User();
$model->user_id = 12345;
echo $model->validate();
```

Case 2:
```
$model = new User();
$model->user_id = new \stdClass();
echo $model->validate();
```

### What is the expected result?
Case 1:
```
true
```
Case 1:
```
false
```
### What do you get instead?
Case 1: 
```
true
```
Case 2:
```
{
  "name": "PHP Recoverable Error",
  "message": "Object of class stdClass could not be converted to string",
  "code": 4096,
  "type": "yii\\base\\ErrorException",
  "file": "/var/www/favorites/vendor/yiisoft/yii2/validators/NumberValidator.php",
  "line": 88
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.0
| PHP version      | 5.5.9
| Operating system | Ubuntu 14.04

**Comment by AlexQwerty** [comment] 2016-06-01 20:14
also 
`
['user_id', 'string']
`
or 
`
$model->user_id = [];
`
so
`
<input type="text" name="User[user_id]**[]**">
`
throw an error
strcasecmp() expects parameter 2 to be string, array given

**Comment by samdark** [comment] 2016-06-06 17:41
Not critical but should be fixed.

**Comment by SamMousa** [comment] 2016-06-07 12:03
My PR is only about the first reported issue, not about the second post.

**Closed** 2016-06-23 20:34 UTC
Labels: status:ready for adoption, type:bug

**Comment by samdark** [comment] 2016-06-23 20:37
Can't reproduce what @AlexQwerty reported.

**Comment by cebe** [comment] 2016-06-25 17:16
@AlexQwerty  can you provide a stacktrace for that error?
