### ISSUE TITLE
Incomplete logger depedency

### ISSUE THREAD

**Issue by Yiivgeny** [yiisoft/yii2#12163] opened 2016-08-15 23:05 UTC
### What steps will reproduce the problem?
```php
\Yii::$app->getLog()->setLogger(\yii\log\Logger::class);
\Yii::$app->getLog()->setFlushInterval(123);

var_dump(\Yii::getLogger()->flushInterval); //missing: 123; actual: 1000
var_dump(\Yii::getLogger() === \Yii::$app->getLog()->getLogger()); //missing: true; actual: false
```

### Result
Configured any `Logger` via `$config['components']['log']['logger']` has no effect for `BaseYii` log methods (warning, info, etc).

### Internal
`\yii\log\Dispatcher::setLogger` don't sync `\yii\BaseYii::$_logger` property.

**Comment by samdark** [comment] 2016-08-16 07:40
Verified. The way it could be configured is via

```php
\Yii::setLogger(\Yii::createObject([
    'class' => \yii\log\Logger::class,
    'flushInterval' => 123,
]));
```

**Comment by samdark** [comment] 2016-08-16 07:40
@Yiivgeny any suggestions?

**Comment by Yiivgeny** [comment] 2016-08-16 08:28
`\Yii::$container->set('\yii\log\Logger', ...)` works better because your solution still problem:
```php
var_dump(\Yii::getLogger() === \Yii::$app->getLog()->getLogger()); //missing: true; actual: false
```
@samdark, мне кажется оба варианта неюзабельны, т.к. требуют дополнительных знаний и конфигурирований. К примеру, распространять расширение реализующее компонент log становится труднее, т.к. невозможно его инициализировать посредством конфига, т.к. класс \Yii еще не определен в этот момент.

**Comment by klimov-paul** [comment] 2016-08-16 08:41
@Yiivgeny, can you explain what are you trying to achive with your code?

Note that `yii\log\Logger` instance can not be configured at application level anyhow: its instantiation and usage predates the application creation itself.
`yii\log\Logger` instance can be configured or overridden properly only via `yii\BaseYii::setLogger()`!

Also note that each instance of `yii\log\Dispatcher` may use different `yii\log\Logger` instance. That is why `yii\log\Dispatcher::log` property exists.

> \yii\log\Dispatcher::setLogger don't sync \yii\BaseYii::$_logger property.

When you call:

```php
\Yii::$app->getLog()->setLogger(\yii\log\Logger::class);
```

You force your `Dispatcher` to work with another instance of `Logger`. So it works as expected.

**Comment by Yiivgeny** [comment] 2016-08-16 08:59
@klimov-paul, i want redeclare `Logger::log` method for implementation immidiate terminal output. I can't  change `flushInterval` to 1, bacause it's flooding other log targets and bad performance.

I use standard logging methods in my application to display and mailing run logs. 
https://yadi.sk/i/8EeEKcHsuFQUE

**Comment by klimov-paul** [comment] 2016-08-16 08:59
In particular your code should look like following:

```php
\Yii::setLogger(MyLogger::class); // use custom logger class

(new yii\web\Application($config))->run(); // create application

\Yii::$app->getLog()->setFlushInterval(123); // now you can configure your custom logger via shortcut methods

var_dump(\Yii::getLogger()->flushInterval); //output 123;
var_dump(\Yii::getLogger() === \Yii::$app->getLog()->getLogger()); //output: true;
```

**Comment by klimov-paul** [comment] 2016-08-16 09:04
> i want redeclare Logger::log method for implementation immidiate terminal output.

You should use code like following one:

```php
class MyLogger extends \yii\log\Logger
{
    public function log($message, $level, $category = 'application')
    {
        parent::log($message, $level, $category);

        echo $message . "\n"; // do your "immidiate terminal output" here
    }
}

\Yii::setLogger(MyLogger::class); // use custom logger class

(new yii\web\Application($config))->run(); // create application
```

**Comment by klimov-paul** [comment] 2016-08-16 09:06
I  consider this as duplicate of #7555

**Closed by klimov-paul** 2016-08-16 09:06 UTC
