### ISSUE TITLE
3 addForeignKey produced 2 fk 

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#13548] opened 2017-02-09 10:23 UTC
### What steps will reproduce the problem?
create migration with 3 line `addForeignKey` on the same table
```
        $this->createTable('{{%lead}}', [
            'id' => $this->primaryKey(),
            'leadTypeId' => $this->integer(),
            'projectId' => $this->integer(),
            'projectFormId' => $this->integer(),
        ], $options);
        $this->addForeignKey('{{%fk_project_form_lead}}', '{{%lead}}', 'projectFormId', '{{%project_form}}', 'id', 'SET NULL', 'CASCADE');
        $this->addForeignKey('{{%fk_lead_type_lead}}', '{{%lead}}', 'leadTypeId', '{{%lead_type}}', 'id', 'SET NULL', 'CASCADE');
        $this->addForeignKey('{{%fk_project_lead}}', '{{%lead}}', 'projectId', '{{%project}}', 'id', 'SET NULL', 'CASCADE');
```

### What is the expected result?
3 fk, 3 index on corresponding fields

### What do you get instead?
2 fk, 3 index
Depends on order, only 2 latest is fk, first call `addForeignKey` produced only the index
```
        $this->addForeignKey('{{%fk_project_form_lead}}', '{{%lead}}', 'projectFormId', '{{%project_form}}', 'id', 'SET NULL', 'CASCADE');
        $this->addForeignKey('{{%fk_lead_type_lead}}', '{{%lead}}', 'leadTypeId', '{{%lead_type}}', 'id', 'SET NULL', 'CASCADE');
        $this->addForeignKey('{{%fk_project_lead}}', '{{%lead}}', 'projectId', '{{%project}}', 'id', 'SET NULL', 'CASCADE');
``` =>
```
fk_lead_type_lead (leadTypeId) -> lead_type (id)
fk_project_lead (projectId) -> project (id)
fk_lead_type_lead
fk_project_form_lead
fk_project_lead
```
=============================
```
        $this->addForeignKey('{{%fk_lead_type_lead}}', '{{%lead}}', 'leadTypeId', '{{%lead_type}}', 'id', 'SET NULL', 'CASCADE');
        $this->addForeignKey('{{%fk_project_lead}}', '{{%lead}}', 'projectId', '{{%project}}', 'id', 'SET NULL', 'CASCADE');
        $this->addForeignKey('{{%fk_project_form_lead}}', '{{%lead}}', 'projectFormId', '{{%project_form}}', 'id', 'SET NULL', 'CASCADE');

```
=>
```
fk_project_form_lead (projectFormId) -> project_form (id)
fk_project_lead (projectId) -> project (id)
fk_lead_type_lead
fk_project_form_lead
fk_project_lead
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | d3f1298ce1d0c06355764ea7c6626407204234af
| PHP version      |7.1.1
| MYSQL version |8.0.0
| Operating system |(Docker image here https://github.com/bscheshirwork/docker-yii2-app-advanced/tree/master/docker-run)

**Comment by bscheshirwork** [comment] 2017-02-09 10:34
also DDL representation is correct
```
CREATE TABLE `lead` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `leadTypeId` int(11) DEFAULT NULL,
  `projectId` int(11) DEFAULT NULL,
  `projectFormId` int(11) DEFAULT NULL,
   PRIMARY KEY (`id`),
  KEY `fk_lead_type_lead` (`leadTypeId`),
  KEY `fk_project_lead` (`projectId`),
  KEY `fk_project_form_lead` (`projectFormId`),
  CONSTRAINT `fk_lead_type_lead` FOREIGN KEY (`leadTypeId`) REFERENCES `lead_type` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_project_form_lead` FOREIGN KEY (`projectFormId`) REFERENCES `project_form` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_project_lead` FOREIGN KEY (`projectId`) REFERENCES `project` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
but some strange happens
if run this script
only 1 fk produced
```
fk_lead_type_lead (leadTypeId) -> lead_type (id)
fk_lead_type_lead
fk_project_form_lead
fk_project_lead
```

**Comment by bscheshirwork** [comment] 2017-02-09 11:49
I think need execute
```
INSERT INTO information_schema.KEY_COLUMN_USAGE (CONSTRAINT_CATALOG, CONSTRAINT_SCHEMA, CONSTRAINT_NAME, TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, POSITION_IN_UNIQUE_CONSTRAINT, REFERENCED_TABLE_SCHEMA, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME) VALUES ('def', 'db', 'fk_lead_type_lead', 'def', 'db', 'lead', 'leadTypeId', 0, 1, 'db', 'lead_type', 'id');
```
any idea?

**Comment by SilverFire** [comment] 2017-02-11 09:54
Seems to be out of Yii scope.

**Comment by SilverFire** [comment] 2017-02-11 09:56
I'll close this issue for now. In case you find that the problem is related to Yii, feel free to ask for reopening. Thank you

**Closed by SilverFire** 2017-02-11 09:56 UTC
