### ISSUE TITLE
image validation not working after changing file extension 

### ISSUE THREAD

**Issue by m-wardany** [yiisoft/yii2#10237] opened 2015-11-24 14:40 UTC
I renamed file "example.zip" to "example.png"
in model "Gallery" I have attribute "photo" :  
`[['photo'], 'image','maxSize'=>2e+6,'skipOnEmpty'=>true, 'when'=>'update'],`
in browser inspector I changed input and removed "id" attribute  to be  :
`<input type="file" name="Gallery[photo]">`
in model "beforeSave"  :
```
$file = \yii\web\UploadedFile::getInstance($this, "photo");
$file->saveAs(\Yii::getAlias("@frontend/web/media/".$file->baseName . '.' . $file->extension));
```
and file uploaded successfully !

**Comment by m-wardany** [comment] 2015-11-24 14:49
@SilverFire  image validation not working after changing file extension !

**Comment by samdark** [comment] 2015-11-24 15:01
Could you show the controller code where you're assigning image and validating the model?

**Comment by m-wardany** [comment] 2015-11-24 15:08
no code in controller 
in model "beforesave"
```
$this->photo = $file->baseName . '.' . $file->extension;
```

**Comment by samdark** [comment] 2015-11-24 15:21
There should be something in controller where you call `->validate()` or `->save()` for the model in question.

**Comment by m-wardany** [comment] 2015-11-24 15:25
```
if ($this->validate()) {
           $file = \yii\web\UploadedFile::getInstance($this, "photo");
           if($file->saveAs(\Yii::getAlias("@frontend/web/media/".$file->baseName . '.' . $file->extension)))
                $this->photo = $file->baseName . '.' . $file->extension;;
            echo 'validate ';
           
        }
        var_dump($this->errors);
        die();
```
Output :
```
validate array(0) { } 
```

**Comment by samdark** [comment] 2015-11-24 15:28
The problem is that you're validating a model w/o file instance assigned to it. See http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html#wiring-up

1. Get instance of uploaded file.
2. Assign it to a model where validation rule is.
3. Validate.
4. Save.

**Closed by samdark** 2015-11-24 15:28 UTC
Labels: status:need more info

**Comment by amjadsarwar** [comment] 2016-03-04 11:43
vhvh
