### ISSUE TITLE
access rule filter check for ajax requests

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#8794] opened 2015-06-15 06:55 UTC
Currently to allow only ajax requests for an action there is the need to use an if statement like this

```php
if (!Yii::$app->request->isAjax) {
    throw new NotAllowedHttpException('This url can only be accesed by ajax');
}
// rest of your code
```

I propose to have an option on the `yii\filters\AcessRule` or `yii\filters\VerbFilter` to check if a request is ajax and use the `allow` property to determine if that action requires ajax or not.

**Comment by arogachev** [comment] 2015-06-15 07:16
:+1: for this feature.

**Comment by unclead** [comment] 2015-06-15 09:22
i think its a duplicate of #7823

**Closed** 2015-06-15 10:06 UTC

**Comment by Faryshta** [comment] 2015-06-15 21:07
Not a duplicate, that one is about a NEW filter, mine one is about extending functionality of an existing filter. @samdark can you open it again?

**Comment by cebe** [comment] 2015-06-15 21:32
@Faryshta an issue is about a certain problem. your problem is the same as in #7823. if this will be a separate filter or part of an existing one is to be decided.
