### ISSUE TITLE
rbac with UUID

### ISSUE THREAD

**Issue by buiduongthe** [yiisoft/yii2#18974] opened 2021-10-24 10:41 UTC
### What steps will reproduce the problem?
I have a problem when assigning user role as follows

1. Setup UUID 
I use alternate UUID for id auto increment sql. UUID is string

2. Function rbac
```php
/**
     * Assigns a role to a user.
     *
     * @param Role|Permission $role
     * @param string|int $userId the user ID (see [[\yii\web\User::id]])
     * @return Assignment the role assignment information.
     * @throws \Exception if the role has already been assigned to the user
     */
    public function assign($role, $userId);
```
2. My Code
```php
$this->id = "CtKoSjIiEeyrpgAJD/4AAQ";
$auth       = Yii::$app->authManager;
$authorRole = $auth->getRole($this->role);
if (isset($authorRole)) {
$auth->assign($authorRole, $this->id);
$this->save();
}
````

3. My problem

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null\nThe SQL being executed was: INSERT INTO `auth_assignment` (`user_id`, `item_name`, `created_at`) VALUES (NULL, 'STUDENT', 1635050886)

### What is the expected result?

I want to use UUID instead of id auto increment sql

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 2.0.44
| PHP version      | 7.4
| Operating system | Windows

Thanks support teams

**Comment by bizley** [comment] 2021-11-02 16:52
Can we get a double check on this? I cannot find anything in the code that could cause the problem here. Do you have the same problem when you call `$auth->assign($authorRole, 'CtKoSjIiEeyrpgAJD/4AAQ');` (so using the value directly instead)?

**Comment by bizley** [comment] 2021-11-08 18:05
@buiduongthe could you please answer my question?

**Comment by buiduongthe** [comment] 2021-11-09 05:05
> Can we get a double check on this? I cannot find anything in the code that could cause the problem here. Do you have the same problem when you call `$auth->assign($authorRole, 'CtKoSjIiEeyrpgAJD/4AAQ');` (so using the value directly instead)?

@bizley Thanks Support

My Code
`$this->id = "CtKoSjIiEeyrpgAJD/4AAQ";
$auth       = Yii::$app->authManager;
$authorRole = $auth->getRole($this->role);
if (isset($authorRole)) {
$auth->assign($authorRole, $this->id);
$this->save();
}`

I want to replace id (integer) with uuid (string)

Thanks

**Comment by bizley** [comment] 2021-11-09 09:24
The thing is that `assign()` does not check for argument type and allows strings for user ID, as well as `Assignment` class, and I cannot see the reason for suddenly having `null` there. It's either you have some custom AuthManager component or some other shenanigans are happening. Please provide the clean steps to reproduce it.

**Comment by WinterSilence** [comment] 2021-11-09 11:53
@bizley I'm think, he add role to undefined item/user

**Comment by WinterSilence** [comment] 2021-11-09 12:09
@bizley foreign key?

**Comment by bizley** [comment] 2021-11-09 12:16
Yes, but wouldn't the error be different then?

**Comment by WinterSilence** [comment] 2021-11-09 12:48
@buiduongthe `$this` is User model?

**Comment by buiduongthe** [comment] 2021-11-13 03:42
> @buiduongthe `$this` is User model?

My Model

LoginForm.php

`
class RegisterForm extends \common\models\User
{

    public function rules(): array
    {
        return [
           [['role','national_number','country_prefix'], 'trim'],
	   [['role','country_prefix','national_number'], 'required'],
           [['role'], 'in', 'range' => Constant::AppRole()],
        ];
    }

    /**
     * @throws \Exception
     */
    public function SignUp()
    {
        $this->setPassword("123456");
        $this->generateAuthKey();
        $this->save();
        $auth       = Yii::$app->authManager;
        $authorRole = $auth->getRole($this->role);
        if (isset($authorRole)) {
            $auth->assign($authorRole, $this->id);
            $this->save();
        }
    }
}
`
$this->id is Primary key

Thanks

**Comment by buiduongthe** [comment] 2021-11-13 03:44
> Hmm, not sure, the error tells that user ID is not passed at all...

$this->id is UUID, is string
ex: $this->id = "CtKoSjIiEeyrpgAJD/4AAQ";

**Comment by bizley** [comment] 2021-11-13 08:13
Ok, now your code shows that `$this->id` is not provided as a fixed value - is it correct? What I suspect is that the first `$this->save()` (saving the user) is returning `false` (btw you should really add `if`s there for `$this->save()` to check if saving is successful, you cannot really assume it just like that). I don't know how you generate that value for user's `id` but it looks like it's not filled because of failed save and thus it's not passed to the `assign()`.
I'm closing this issue but if what I wrote is not correct please state here so we'll reopen it for further investigating.

**Closed by bizley** 2021-11-13 08:13 UTC
Labels: status:to be verified, status:need more info, help wanted
