### ISSUE TITLE
Migration history is not migrationPath-aware

### ISSUE THREAD

**Issue by bethrezen** [yiisoft/yii2#8383] opened 2015-05-12 19:16 UTC
Migration history table stores only version and apply_time.
But there's a problem when we need to migrate down - we need to specify exact migrationPath for migrations we want to revert!

**Comment by cebe** [comment] 2015-05-12 19:20
The current implementation assumes that migrations are all located in one place. this will be solved when we support multiple paths. duplicate of #384.

**Closed by cebe** 2015-05-12 19:20 UTC

**Comment by bethrezen** [comment] 2015-05-13 06:34
Just for others who will meet the same problem.
I've used different migrationPath for installing CMS extensions migrations.
I have information on migrationPath and extension ID.
Therefore solution was to separate all extensions migrations to separate table - one table for one migration.
The better solution is expected from solving #384

**Comment by mdmunir** [comment] 2015-05-13 07:43
https://github.com/deesoft/yii2-console
Support multiple path and compatible with current migration table.
