### ISSUE TITLE
ambiguous error in unique validator

### ISSUE THREAD

**Issue by sepidemahmoodi** [yiisoft/yii2#14042] opened 2017-04-24 11:56 UTC
### What steps will reproduce the problem?
Hi,
I've `department` and `college` table with this structure :

```php
$this->createTable('department', [
            'id' => $this->primaryKey(),
            'code' => $this->string()->notNull(),
            'collegeId' => $this->integer()->notNull(),
            'createdAt' => $this->integer(),
            'updatedAt' => $this->integer(),
        ]);

$this->createTable('department_info', [
       'id' => $this->primaryKey(),
       'name' => $this->string(),
       'languageId' => $this->string(),
       'description' => $this->text(),
      'departmentId' => $this->integer()->notNull(),
 ]);

$this->createTable('college', [
            'id' => $this->primaryKey(),
            'code' => $this->string()->notNull(),
            'createdAt' => $this->integer(),
            'updatedAt' => $this->integer(),
        ]);

$this->createTable('college_info', [
            'id' => $this->primaryKey(),
            'name' => $this->string(),
            'languageId' => $this->string(),
            'description' => $this->text(),
            'collegeId' => $this->integer()->notNull(),
            'websiteId' => $this->integer(),
            'url' => $this->text(),
]);
```

in rules of Department model `code` attribute is unique :

```php
 public function rules()
    {
        return [
            [['code', 'collegeId'], 'required'],
            [['code'], 'unique'],
            [['code'], 'integer'],
        ];
    }
```
then this model use uniqueValidator.
In special condition in `Department::find()` method i'm trying to join that tables :

```php
public static function find()
    {
        $query = new ActiveQuery(get_called_class());
        if(Yii::$app->user->isSuperuser()){
            return $query;
        }
        $query->joinWith('college');
        return $query;
    } 
```
while update one record of department this error was occured :

```sql
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous
The SQL being executed was:
 SELECT `id` FROM `department` LEFT JOIN `college` ON `department`.`collegeId` = `college`.`id` WHERE (`code`='1') LIMIT 2
```
3 month ago i wrote #13704 issue and some changes in master branch was occured but seems uniqueValidator already has some problems.

in `UniqueValidator::modelExists($targetClass, $conditions, $model)` 
in this part :

```php
if ($query instanceof \yii\db\ActiveQuery) {
                // only select primary key to optimize query
                $query->select($targetClass::primaryKey());
    }
```
when die($query->createCommand()->getSql()) return this :
`'SELECT `id` FROM `department` LEFT JOIN `college` ON `department`.`collegeId` = `college`.`id` WHERE (`code`=:qp0)'`

but while commented  `$query->select($targetClass::primaryKey());` line return this:

```sql
SELECT `department`.* FROM `department` LEFT JOIN `college` ON `department`.`collegeId` = `college`.`id` WHERE (`code`=:qp0)
```

and i need this.
it seems with commented that line problem will solved.
other solution is adding tableName as prefix to `id` column.

**Comment by samdark** [comment] 2017-04-25 16:28
Duplicate of #13842

**Comment by sepidemahmoodi** [comment] 2017-05-07 05:16
this issue is different from #13842 : | 
please pay attention this.
thanks.

**Comment by cebe** [comment] 2017-05-07 11:53
right, it is different. Thanks for pointing that out.

**Comment by samdark** [comment] 2017-05-07 19:12
@sepidemahmoodi have you tried it with code from master branch?

**Closed** 2017-05-11 22:00 UTC
Labels: type:bug

**Comment by sepidemahmoodi** [comment] 2017-05-14 06:41
have changes been merged to master?

**Comment by cebe** [comment] 2017-05-14 20:02
yes, if you check out current master it should work. Please check and report back if your problem is solved.
