### ISSUE TITLE
problem updating multiple instance of a model

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#9449] opened 2015-08-18 00:48 UTC
hi, im trying update multiple instances of a model, for example a datetime, but i cant find any documentation and save every instance, increase the use of the mysql server

like this
Model::loadMultiple($models,$data)->save(); ?

and when i trying use Model::loadMultiple($model, ['attribute' => 'value']));

this not update the models for this new value setted :S

work using this
$ids = ['1','2','3','4'];
Yii::$app->db->createCommand()->update(Model::tableName(),['updated_at' => idate('U')],['id' => $ids])->execute();

but i think this is better if i can use this in the models no ?

**Comment by cebe** [comment] 2015-08-18 14:02
duplicate of #2070

**Closed by cebe** 2015-08-18 14:02 UTC
