### ISSUE TITLE
Handling of column aliases changed

### ISSUE THREAD

**Issue by nathansbraten** [yiisoft/yii2#15673] opened 2018-02-19 14:00 UTC
After updating from 2.0.13 to 2.0.14 i noticed some strange log entries telling me some array keys are missing. It looks like there is a change in column aliasing which does not allow to select a db column more than once. I don't know if this is intended but we do fetch the same column more than once on purpose sometimes and it broke small parts of our application. Easy to fix on developer site but maybe it should be mentioned somewhere.

I just created a new app with 2.0.13 and executed the given query in a console controller and the output was like expected. After updating to 2.0.14 the third column was missing.

### What steps will reproduce the problem?

```
CREATE TABLE `columnAliasProblem` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(32) NOT NULL,
  `description` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `columnAliasProblem` (`id`, `name`, `description`) VALUES
(1, 'foo', 'foo description'),
(2, 'bar', 'bar description'),
(3, 'baz', 'baz description');

$result = (new Query())
    ->select([
        'someAlias'    => 'name',
        'anotherAlias' => 'description',
        'thirdAlias'   => 'name',
    ])
    ->from(['columnAliasProblem'])
    ->where([
        'id' => 1
    ])
    ->one();

print_r($result);
```

### What is the expected result?
```
Array
(
    [someAlias] => foo
    [anotherAlias] => foo description
    [thirdAlias] => foo
)
```

### What do you get instead?
```
Array
(
    [someAlias] => foo
    [anotherAlias] => foo description
)
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.1.13
| Operating system | Linux (Debian)
| Database | Percona XtraDB Cluster for MySQL 5.7

**Comment by samdark** [comment] 2018-02-19 14:02
Need DB schema and concrete queries in order to reproduce it.

**Comment by makroxyz** [comment] 2018-02-19 14:17
Last update broke my app!

```php
$query = new Address();
$query->select(['lat', 'lng'])->createCommand()->query();
```
createCommand creates "SELECT * FROM address";

problem is in Query.php
protected function getUniqueColumns($columns)

**Comment by samdark** [comment] 2018-02-19 14:24
@makroxyz isn't that separate issue?

**Comment by makroxyz** [comment] 2018-02-19 14:27
Probably yes, sorry... I create another issue

**Comment by nathansbraten** [comment] 2018-02-19 14:36
Updated the issue with some more data.

**Comment by SilverFire** [comment] 2018-02-19 16:28
Seems to be duplicate of https://github.com/yiisoft/yii2/issues/15676 and has been fixed in https://github.com/yiisoft/yii2/commit/1b3526d8db208fbc834e98c8563993ec9c2c6f1a

**Closed by SilverFire** 2018-02-19 16:28 UTC
Labels: status:to be verified, type:bug
