### ISSUE TITLE
console migrate on second database not work

### ISSUE THREAD

**Issue by mnbk** [yiisoft/yii2#11265] opened 2016-04-04 03:36 UTC
When I want to migrate my second database in yii basic template, I get an error ('Class db_server does not exist!').

This is the command:
```php
yii migrate --migrationPath=@app/migrations --db=db_server
```

![image](https://cloud.githubusercontent.com/assets/7428683/14237552/ce8f07a2-fa25-11e5-8774-f771ad25f9ee.png)

I configured both web and console config, and when I check it with gii, the second database is working.

This is my console config:

```php
$params = require(__DIR__ . '/params.php');
$db = require(__DIR__ . '/db.php');
$db_server = require(__DIR__ . '/db_server.php');

return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'modules' => [
        'gii' => 'yii\gii\Module',
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
        'db_server' => $db_server,
    ],
    'params' => $params,
];
```

db_server.php:

```php
<?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=localhost;dbname=xxxxxx',
    'username' => 'postgres',
    'password' => 'xxxxx',
    'charset' => 'utf8',
];
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | PHP Version 5.5.9-1ubuntu4.14
| Operating system | Ubuntu 14.04

**Comment by pana1990** [comment] 2016-04-13 00:06
@mnbk @SilverFire it works for me, are you sure that this not work? can you check again?

**Comment by SilverFire** [comment] 2016-04-13 09:05
Same here. Failed to reproduce. Make sure `yii` executable includes the same config you have listed in the issue.

I'm closing the issue unless further information provided.

**Comment by SilverFire** [comment] 2016-04-13 09:05
@pana1990 thank you

**Closed by SilverFire** 2016-04-13 09:05 UTC
Labels: status:to be verified

**Comment by pana1990** [comment] 2016-04-13 13:31
@SilverFire you're welcome ;)
