### ISSUE TITLE
Console fixture/load command causing error on postgres database.

### ISSUE THREAD

**Issue by akaSStalkALEX** [yiisoft/yii2#10550] opened 2016-01-11 06:51 UTC
```
Fixtures namespace is:
        tests\unit\fixtures

Global fixtures will be used:

        1. yii\test\InitDb

Fixtures below will be loaded:

        1. Request

Load above fixtures? (yes|no) [no]:y

...
Next yii\db\Exception: SQLSTATE[42809]: Wrong object type: 7 ERROR:  "pg_stat_statements" is not a table or foreign table
The SQL being executed was:ALTER TABLE "public"."file" DISABLE TRIGGER ALL; ALTER TABLE "public"."html"
DISABLE TRIGGER ALL; ALTER TABLE "public"."language" DISABLE TRIGGER ALL; ALTER TABLE "public"."language_source" DISABLE TRIGGER ALL; ALTER TABLE "public"."language_translate" DISABLE TRIGGER ALL; ALTER TABLE "public"."less"
 DISABLE TRIGGER ALL; ALTER TABLE "public"."messages" DISABLE TRIGGER ALL; ALTER TABLE "public"."migration" DISABLE TRIGGER ALL; ALTER TABLE "public"."pg_stat_statements" DISABLE TRIGGER ALL; ALTER TABLE "public"."profile" D
ISABLE TRIGGER ALL; ALTER TABLE "public"."request" DISABLE TRIGGER ALL; ALTER TABLE "public"."settings" DISABLE TRIGGER ALL; ALTER TABLE "public"."social_account" DISABLE TRIGGER ALL; ALTER TABLE "public"."token" DISABLE TRI
GGER ALL; ALTER TABLE "public"."user" DISABLE TRIGGER ALL;  in /vagrant/vendor/yiisoft/yii2/db/Schema.php:628

```

So I tried ``` ALTER TABLE "public"."pg_stat_statements" DISABLE TRIGGER ALL ``` manually in psql, it says the same. ``` SELECT * FROM pg_stat_statements ``` executes successfully.  Pg_stat_statements is view, not table.

**Comment by cebe** [comment] 2016-01-14 11:13
duplicate of #8644

**Closed by cebe** 2016-01-14 11:13 UTC
Labels: PostgreSQL, status:to be verified, type:bug

**Comment by akaSStalkALEX** [comment] 2016-04-07 10:21
Hi guys, sorry for disturbing you. If it was removed from next milestone, what can be used as a fast-fix now?
