### ISSUE TITLE
ActiveDataProvider not returning expected records

### ISSUE THREAD

**Issue by nadeemse** [yiisoft/yii2#14884] opened 2017-09-28 11:35 UTC
ActiveDataProvider returning fewer records than actual query. When I remove Group by then it's working fine

### Query

```
SELECT 
    `pc`.`id` AS `id`,
    `pc`.`name` AS `Title`,
    `pc`.`code` AS `code`,
    `pc`.`amount` AS `Value`,
    `pc`.`type` AS `type`,
    SUM(price) revenue,
    SUM(total_sum) totalRevenue,
    COUNT(order.id) AS total_orders,
    SUM(discount) discount,
    `order`.`source` AS `source`
FROM
    `order`
        INNER JOIN
    `promo_to_customer` `ptc` ON order.id = ptc.order_id
        INNER JOIN
    `promo_codes` `pc` ON ptc.promo_code_id = pc.id
WHERE
    (`order`.`branch_id` = '1')
        AND (DATE(time) >= '2017-09-01')
        AND (DATE(time) <= '2017-09-27')
GROUP BY `order`.`source` , `ptc`.`promo_code_id`
ORDER BY `pc`.`id` DESC
```

### What do you get instead?
Active Data provider returning fewer records than actual query. When I'm running the same query in MySQL client it's returning more records.

### Additional info

Q | A
-- | --
Yii version | 2.0.4
PHP version | 5.6
Operating system | Mac

**Comment by rob006** [comment] 2017-09-28 12:55
Please upgrade your Yii first - 2.0.4 was released more than 2 years ago, a lot of bugs was fixes since then.

**Comment by nadeemse** [comment] 2017-09-28 13:04
I have upgraded to **YII 2.0.12** but still, the same results. When I get rawSql and run that in MYSQL client it's returning more records but ActiveDataProvider returning fewer records.

**Comment by FabrizioCaldarelli** [comment] 2017-09-28 13:06
Data provider output data are paginated. Could be that the reason?
To avoid pagination set pagination attribute to false.

**Comment by rob006** [comment] 2017-09-28 13:12
Probably duplicate of #13800. See https://github.com/yiisoft/yii2/issues/13800#issuecomment-287726753

**Comment by nadeemse** [comment] 2017-09-28 13:13
By the way, I have already set pagination to false. kindly find the code below. 

```
$query = self::find();
        $this->load($params);

        $groups = ['ptc.promo_code_id'];

        // check if today flag is enabled then search only today transaction.
        if ($this->isToday) {
            $this->from_date = $this->to_date = Yii::$app->dateTime->getDate();
        }

        // Default columns selections
        $columns = [
            'pc.id id',
            'pc.name Title',
            'pc.code code',
            'pc.amount Value',
            'pc.type type',
            'sum(order.price) revenue',
            'sum(order.total_sum) totalRevenue',
            'count(order.id) total_orders',
            'sum(order.discount) discount'
        ];

        /**
         * Make active dataprovider and set pagination false to return full result set. 
         */
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => false
        ]);

        // Add columns selection. 
        $query->select($columns);

        // Join on tables.
        $query->join('INNER JOIN', 'promo_to_customer ptc', 'order.id = ptc.order_id');
        $query->join('INNER JOIN', 'promo_codes pc', 'ptc.promo_code_id = pc.id');

        $query->andFilterWhere([
            'order.address_id' => $this->address_id,
            'order.branch_id' => $this->branch_id,
            'order.source' => $this->source,
            'pc.status' => $this->code_status,
        ]);

        //Check if params has from_date parameter, if yes then allow search on from_date
        if ($this->from_date) {
            $query->andFilterWhere(['>=', 'DATE(time)', $this->from_date]);
        }

        //Check if params has to_date parameter, if yes then allow search on to_date
        if ($this->to_date) {
            $query->andFilterWhere(['<=', 'DATE(time)', $this->to_date]);
        }

        // filter on time category
        if ($this->time_category) {
            $query = Yii::$app->setting->getTimeCategory($this->time_category, $query);
        }

        if ($this->groups && in_array('byBranch', $this->groups)) {
            $query->join('INNER JOIN', 'branch b', 'order.branch_id = b.id');
            $groups[] = 'order.branch_id';
            $query->addSelect(['b.name branchName']);
        }

        if ($this->groups && in_array('bySource', $this->groups)) {
            $groups[] = 'order.source';
            $query->addSelect(['order.source source']);
        }

        if ($this->groups && in_array('byArea', $this->groups)) {
            $groups[] = 'order.source';
            $query->addSelect(['order.source source']);
        }

        if ($this->groups && in_array('byTimeCategory', $this->groups)) {
            $query->addSelect(['(CASE
                WHEN TIME(time) BETWEEN \'11:00:00\' AND \'12:00:00\' OR TIME(time) BETWEEN \'14:00:00\' AND \'16:00:00\'
                  THEN \'LUNCH NON PEAK\'
                WHEN TIME(time) BETWEEN \'12:00:00\' AND \'14:00:00\'
                  THEN \'LUNCH PEAK\'
                WHEN TIME(time) BETWEEN \'16:00:00\' AND \'19:00:00\' OR TIME(time) BETWEEN \'22:00:00\' AND \'23:59:59\'
                  THEN \'DINNER PEAK\'
                WHEN TIME(time) BETWEEN \'19:00:00\' AND \'22:00:00\'
                  THEN \'DINNER NON PEAK\'
                END) AS timeCategory']);

            $groups[] = 'timeCategory';
        }

        $query->groupBy($groups);
        $query->orderBy(['pc.id' => SORT_DESC]);

       return $dataProvider;
```

**Comment by samdark** [comment] 2017-09-29 14:05
It is what @rob006 suggested.

**Closed by samdark** 2017-09-29 14:05 UTC

**Comment by nadeemse** [comment] 2017-10-01 09:26
Thanks, @samdark & @rob006.

It's sorted out with adding $query->indexBy;

I have added dynamic $query->indexBy based on group data and it's working fine. 

```
$query->indexBy(function($row) {

            $index = [];
            if( isset($row->id) ) {
                $index[] = $row->id;
            }

            if( isset($row->branchName) ) {
                $index[] = $row->branchName;
            }

            if( isset($row->source) ) {
                $index[] = $row->source;
            }

            if( isset($row->timeCategory) ) {
                $index[] = $row->timeCategory;
            }

            return implode('-', $index);
        });
```
