### ISSUE TITLE
Not correct host handling with multiple nginx

### ISSUE THREAD

**Issue by s1lver** [yiisoft/yii2#19391] opened 2022-05-11 15:57 UTC
If nginx is installed before nginx, then I will get an incorrect redirect. I don’t know the exact location of the problem yet, but it reproduces when updating to 2.0.46-dev

```
example.com -> example.com:8080
```

Playable when used k8s, openshift, docker

### What steps will reproduce the problem?
install 2.0.46-dev

### What is the expected result?
Get the original domain

### What do you get instead?
get a domain with a port

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46-dev
| PHP version      | 8.0.16
| Operating system | Debian

**Comment by samdark** [comment] 2022-05-19 15:35
Should be connected with #19290.

**Comment by samdark** [comment] 2022-05-19 15:35
@s1lver considering the change I've linked, any idea on why it fails?

**Comment by lesha724** [comment] 2022-05-22 19:47
@s1lver, maybe [this](https://github.com/yiisoft/yii2/commit/8046d3a50f207e1033e1b23ff571da5bced0c822#comments) help you

**Comment by s1lver** [comment] 2022-05-23 06:17
> @s1lver, maybe [this](https://github.com/yiisoft/yii2/commit/8046d3a50f207e1033e1b23ff571da5bced0c822#comments) help you

Ок, the`X-Forwarded-Host` ispassed and has the correct value.

**Comment by samdark** [comment] 2022-05-23 06:30
@s1lver so... anything to fix?

**Comment by bizley** [comment] 2022-06-15 07:51
Closing, if this needs to be re-opened please write here.

**Comment by s1lver** [comment] 2022-06-16 13:05
> Closing, if this needs to be re-opened please write here.

The issue is closed, but what is the solution to the problem?

**Comment by bizley** [comment] 2022-06-16 15:39
Well, samdark asked if there is anything to fix and there was no answer for 3 weeks...
Anyway, so X-Forwarded-Host contains `example.com` but you can see (?) `example.com:8080`, right? Please give us more info, your report is very vague.

**Comment by lesha724** [comment] 2022-06-16 20:17
@bizley, maybe the header is being ignored as untrusted, see this [test](https://github.com/yiisoft/yii2/blob/master/tests/framework/web/RequestTest.php#L365)

**Comment by bizley** [comment] 2022-06-20 07:17
@samdark should we rollback https://github.com/yiisoft/yii2/pull/19301 ?

**Comment by samdark** [comment] 2022-06-20 21:08
@bizley maybe.

@s1lver is it possible to put together a unit test that reproduces the issue with current master?

**Comment by Fullchaos** [comment] 2022-06-22 12:25
The problem is real, please fix i

**Comment by samdark** [comment] 2022-07-01 07:29
@s1lver reverted https://github.com/yiisoft/yii2/commit/827db6c90ea3fb623a0c480c6a4c8ae46c655cf8

**Comment by bizley** [comment] 2022-07-31 08:54
Closing. Thanks everyone for catching this before release.

**Closed by bizley** 2022-07-31 08:54 UTC
