### ISSUE TITLE
session_regenerate_id(): Session write failed. ID: user (path: )

### ISSUE THREAD

**Issue by Yarisrespect** [yiisoft/yii2#14173] opened 2017-05-17 16:31 UTC
Application session component:
```php
'session' => [
      'class' => '\yii\web\DbSession',
],
```
Sometimes I receive php warning:

PHP Warning – yii\base\ErrorException
session_regenerate_id(): Session write failed. ID: user (path: )

 in /home/main/public_html/vendor/yiisoft/yii2/web/Session.php at line 283

```php
    public function regenerateID($deleteOldSession = false)
    {
        if ($this->getIsActive()) {
            // add @ to inhibit possible warning due to race condition
            // https://github.com/yiisoft/yii2/pull/1812
            if (YII_DEBUG && !headers_sent()) {
283:         session_regenerate_id($deleteOldSession);
            } else {
                @session_regenerate_id($deleteOldSession);
            }
        }
    }
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2.
| PHP version      |  7.1.5
| Operating system | Centos 6.9

**Comment by cebe** [comment] 2017-05-17 19:33
related to or duplicate of #9438, do you have a way to reproduce the issue?

**Comment by alexeevdv** [comment] 2017-05-22 20:23
Looks like this one https://github.com/humhub/humhub/issues/2402

**Comment by cebe** [comment] 2017-08-24 13:57
duplicate of #9438

**Closed by cebe** 2017-08-24 13:57 UTC
Labels: status:to be verified
