### ISSUE TITLE
Bug: ActiveQuery::one 

### ISSUE THREAD

**Issue by grigorieff** [yiisoft/yii2#8484] opened 2015-05-19 20:01 UTC
PHP information:
PHP 5.4.38 (cli) (built: Feb 18 2015 16:46:56) with eAccelerator v1.0-dev, Copyright (c) 2004-2012 eAccelerator, by eAccelerator

In yii\db\ActiveQuery::one if $models is not empty array next code returned null

```php
return reset($models) ?: null;
```

if i replaced to
```php
return reset($models)? reset($models) : null;
```
This code returned first element of array. I think the cause of for this behavior is eAccelerator.

**Comment by klimov-paul** [comment] 2015-05-20 09:46
Ternary shortsyntax `?:` is widely used accross the framework - not only at `yii\db\ActiveQuery::one()`

**Comment by samdark** [comment] 2015-05-20 09:59
@grigorieff are you using latest eaccelerator version? It looks like the one you're using isn't fully compatible with PHP 5.4...

**Comment by klimov-paul** [comment] 2015-05-20 10:03
Description says `eAccelerator v1.0-dev`, although I can't find related one at https://github.com/eaccelerator/eaccelerator
`?:` syntax has been introduced at PHP 5.3. If eAccelerator has a problem with it, it should revealed itself long ago.

**Comment by samdark** [comment] 2015-05-20 10:14
Anyway, I don't think we should change short ternary into long one. It's definitely eaccelerator issue and it should be fixed there.

**Closed by samdark** 2015-05-20 10:14 UTC
Labels: status:to be verified, type:bug

**Comment by grigorieff** [comment] 2015-05-20 10:24
@samdark I think the same. Thanks! eAccelerator v. 0.9.6.1

**Comment by klimov-paul** [comment] 2015-05-20 10:26
@grigorieff, if you are able to reproduce this issue with plain PHP, please submit it to https://github.com/eaccelerator/eaccelerator/issues/new

**Comment by grigorieff** [comment] 2015-05-21 21:08
Installed OPCache instead of eAccelerator and ?: was working now is good ;)
