### ISSUE TITLE
RBAC -  Get Assinged User Id List of a Particular Role

### ISSUE THREAD

**Issue by MrAwanishKumar** [yiisoft/yii2#10206] opened 2015-11-21 09:36 UTC
Hi,
Using PhpManager. 
There is a requirement to handle only 10 to 20 users role access to a particular module, say "account", I have created a role say "account" and assigned to 10 users. Now I did not find any method to get the user id list of the role "account". I have gone through these documentation links 

http://www.yiiframework.com/doc-2.0/guide-security-authorization.html and 
http://www.yiiframework.com/doc-2.0/yii-rbac-phpmanager.html

but did not find the exact method. 
Need help .....

Thanks

**Comment by samdark** [comment] 2015-11-25 03:43
Duplicate of https://github.com/yiisoft/yii2/issues/9573

**Closed by samdark** 2015-11-25 03:43 UTC
Labels: feature:rbac
