### ISSUE TITLE
new feature: allow international attributes in DetailView

### ISSUE THREAD

**Issue by pasmanp** [yiisoft/yii2#6898] opened 2015-01-17 00:59 UTC
When name of an attribute contain unicode character, DetailView not accept it:

```php
    echo DetailView::widget([
        'model' => $model,
        'attributes' => ['kąt'],
    ]);
```

There is error:

```
Invalid Configuration – yii\base\InvalidConfigException
The attribute must be specified in the format of "attribute", "attribute:format" or "attribute:format:label"

...

if (!preg_match('/^([\w\.]+)(:(\w*))?(:(.*))?$/', $attribute, $matches)) {
    throw new InvalidConfigException('The attribute must be specified in the format of "attribute", "attribute:format" or "attribute:format:label"');
}

```

Is it possible to allow international words here ?

**Comment by qiangxue** [comment] 2015-01-17 01:55
Duplicate of https://github.com/yiisoft/yii2/pull/4446

**Closed by qiangxue** 2015-01-17 01:55 UTC
