### ISSUE TITLE
yii\helpers\BaseUrl::current is not merging multi associative array

### ISSUE THREAD

**Issue by mirrorps** [yiisoft/yii2#16743] opened 2018-09-26 09:53 UTC
### What steps will reproduce the problem?

Current $_GET:
```
Array
(
    [TestModel] => Array
        (
            [field1] => 1
        )
)
```
### What is the expected result?
```
var_dump(\yii\helpers\Url::current(
            [
                $this->formName() => ['field2' => 2, 'field3' => 3]
            ]
        ));


Array
(
    [TestModel] => Array
        (
            [field1] => 1
            [field2] => 2
            [field3] => 3
        )
)
```
### What do you get instead?
```
Array
(
    [TestModel] => Array
        (
            [field2] => 2
            [field3] => 3
        )
)
```

### What will fix the problem:
Using ```array_replace_recursive``` instead ```array_replace``` in \yii\helpers\Url::current() (BaseUrl.php::432)
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version    | 5.6.33
| Operating system  |MAC

**Comment by Alex-Code** [comment] 2018-09-26 10:11
This was fixed in 2.0.14
If possible always update to the latest version and see if the issue is fixed.

**Closed** 2018-09-26 10:12 UTC
