### ISSUE TITLE
destinationFormat and destinationAttribute in \yii\validators\DateValidator

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/yii2#7903] opened 2015-03-28 09:59 UTC
In form, everytime it is necessary to change format date, from user input and database date field.

In my case, i change from d/m/Y to Y-m-d.

Infact when i receive date fields from form, that are in 'd/m/Y' format. I can apply format to date validator to check 'd/m/Y', but before to write to db I have to change format in 'Y-m-d'.

So I think that could be useful to have two new attributes to attach to DateValidator, destinationFormat and destinationAttribute. As timestampAttribute, if validation is right, validator will fill destinationAttribute with representation of date with destinationFormat.

In this way I haven't to apply any change format to data, that i'll have in correct database format.

**Comment by cebe** [comment] 2015-03-28 11:03
duplicate of #5053

**Closed by cebe** 2015-03-28 11:03 UTC

**Comment by FabrizioCaldarelli** [comment] 2015-03-30 20:48
I've created this gist:

https://gist.github.com/FabrizioCaldarelli/eb376822f07c6832d76b

I've overwritten DateValidator class file, so changes to yii\validators\DateValidator should be simple.
