### ISSUE TITLE
How  to check user can access controller/action.

### ISSUE THREAD

**Issue by noppakun** [yiisoft/yii2#7233] opened 2015-02-11 10:01 UTC
I try to use Yii::app()->user->can() it work only for permission , not work for cortroller/action

**Comment by samdark** [comment] 2015-02-11 10:05
Duplicate of https://github.com/yiisoft/yii2/issues/7232

**Comment by samdark** [comment] 2015-02-11 10:05
Please use forums for questions.

**Closed by samdark** 2015-02-11 10:05 UTC
