### ISSUE TITLE
[Formatter] add support for asInterval

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii2#9671] opened 2015-09-12 11:30 UTC
Add support for asInterval.
When inputig /DateInterval to RelativeTime, it does exactly what it should(shows time relative to now, altough DateInterval consists of no DateTime information, that is needed for it, but let's keep that

What is needed is asInterval(\DateInterval) that outputs strings something like 23 years or 11 days 4 hours

**Comment by mdmunir** [comment] 2015-09-12 13:20
https://github.com/yiisoft/yii2/blob/master/framework/i18n/Formatter.php#L711

**Comment by mikk150** [comment] 2015-09-12 13:24
No, it outputs string like 23 years ago or 11 days ago, I'd like to have just interval(right now I just strip that ago part off and works, but that is not long term success plan)

**Comment by nineinchnick** [comment] 2015-09-17 06:31
Duplicate of #5146

**Comment by cebe** [comment] 2015-11-23 22:14
implemented by #10018

**Closed by cebe** 2015-11-23 22:14 UTC
Labels: type:enhancement
