### ISSUE TITLE
Custom Validators skipped while validating non DB attributes

### ISSUE THREAD

**Issue by avinashz** [yiisoft/yii2#10723] opened 2016-02-01 12:41 UTC
I am having a case when I have to define few fields which are not fields of DB I want those in my form. I need to create custom validator for those fields. 

But those custom validation is being skipped by Yii2, Surprisingly If I have used inbuilt validator like `required` it works fine. Here is the example of model I am having:

```php

namespace backend\models;

use Yii;

class Entity extends \yii\db\ActiveRecord
{
	
	public $entityList = '';
	
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%entity}}';
    }

    public function rules() {
    	return [
			[['entityType'], 'number'],
    		[['entityList'], 'required', 'when' => function($model){return ($model->entityType == '1' || $model->entityType == '2');}], // Working
			#[['entityList'], 'required'], // Working
    		#[['entityList'], 'customCheck'], // Not Working
    	];
    }
    
    public function attributeLabels() {
    	return [
    		'entityType' => Yii::t('app', 'Type'),
    		'entityList' => Yii::t('app', 'List')
    	];
    
    }
    
    public function customCheck($attr, $param) {
    	
    	$post = $_POST;
    	
    	if($post['Entity']['entityType'] == '1' || $post['Entity']['entityType'] == '2') {
    		
    		if($post['Entity']['entityList'] == '') {
    			$this->addError($attr, 'Please provide '.$this->attributeLabels()[$attr]);
    			return false;
    		}
    	}
    	
    	return true;
    }
    
}

```

**Other info:**

PHP: 5.5.12
Yii Version: 2.0.6

**Comment by klimov-paul** [comment] 2016-02-01 12:52
What do you mean "not working"? Does method `customCheck()` ever invoked or not?

**Comment by avinashz** [comment] 2016-02-01 12:54
Its not getting invoked.

**Comment by Alex-Code** [comment] 2016-02-01 12:56
Does `$post['Entity']['entityType']` ever equal `1` or `2`?

Can you try forcing an error without conditions to check it's getting invoked.

```php
public function customCheck($attr, $param) {
    $this->addError($attr, 'Add an error to test');
}
```

**Comment by avinashz** [comment] 2016-02-01 12:59
I have already tried this. Even simple `die` is also not making any effect

```php
public function customCheck($attr, $param) {
    die('I am in');
    $this->addError($attr, 'Add an error to test');
}
```

**Comment by klimov-paul** [comment] 2016-02-01 13:01
Unable to reproduce.
Most likely you are ommitting `safe` validator in case of usage your `customCheck`.
You must ensure your custom attribute is marked as 'safe' by some validator like 'reqiured' or 'safe' in order to further vaidation being performed.

**Comment by avinashz** [comment] 2016-02-01 13:04
My field was not in `safe` rule but even after adding that to `safe` rule validation skipped.

**Comment by Alex-Code** [comment] 2016-02-01 13:10
How are you trying to invoke validation?
Do you have ajax validation?

**Comment by cebe** [comment] 2016-02-01 13:38
@avinashz a validator has `$skipOnError = true` by default so if your first validation rule fails, the others are not triggered unless you add `'skipOnError' => false`.

**Comment by avinashz** [comment] 2016-02-01 16:58
@Alex-Code no its not AJAX validation. 
@cebe My all other rules are not having error, only this rule is having validation error. 

I guess there seems to be an issue with validation of non-db attribute with custom validator.

**Comment by avinashz** [comment] 2016-02-02 05:33
@cebe confirmed that adding `'skipOnError' => false` does not make any difference

**Comment by avinashz** [comment] 2016-02-02 06:16
@cebe @klimov-paul @Alex-Code  Ok so I am out of main project and testing things on blank yii2-advance template. Please check below use case here:

## Table Schema:

```sql
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 ;
```


## Model Code:


```php
namespace frontend\models;

use Yii;

/**
 * This is the model class for table "{{%users}}".
 *
 * @property integer $id
 * @property string $username
 * @property string $firstname
 * @property string $lastname
 */
class Users extends \yii\db\ActiveRecord
{

	 public $email; // Custom NON-DB Attribute

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%users}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['username', 'firstname', 'lastname'], 'required'],
			[['email'], 'safe'],
			[['email'], 'uniqueCheck','skipOnError'=>false],
            [['username', 'firstname', 'lastname'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'firstname' => 'Firstname',
            'lastname' => 'Lastname',
        ];
    }
	
	public function uniqueCheck($attribute, $params) {
       die('here');exit;
    }
}

```

Still having the same issue, validator is just being skipped.

**Comment by Alex-Code** [comment] 2016-02-02 14:53
Can you show your `Controller` and `View` code.

**Comment by avinashz** [comment] 2016-02-02 15:33
It is exactly same as generated by gii. Nothing changed in those files
which is generated by Gii.

**Comment by arogachev** [comment] 2016-02-03 04:12
@avinashz I just checked it, the validation is not applied because by default empty values are skipped.

You need to explicitly set `'skipOnEmpty' => false` or mark it as `required` instead of `safe`, so first it's checked for having a value, and then it it has, your custom validation will be applied. 

Can't see bug here.

**Comment by avinashz** [comment] 2016-02-03 05:45
@arogachev this seems to be a solution here. but `skipOnEmpty` seems confusing in such cases, don't you?

**Comment by arogachev** [comment] 2016-02-03 05:48
@avinashz Why? I think it's correct to skip empty values by default.

**Comment by avinashz** [comment] 2016-02-03 05:54
@arogachev have put some thoughts here and agree with you here :ok:

**Comment by arogachev** [comment] 2016-02-03 06:01
:+1:

**Closed** 2016-02-03 06:03 UTC
Labels: status:to be verified

**Comment by yokoshima1** [comment] 2017-05-02 12:08
hey so m having the same trouble however the above didn't work
using advanced yii2
did use safe and skiponerror false but the validation function is not invoked
