### ISSUE TITLE
codeception API test failed after upgrade to 2.0.14

### ISSUE THREAD

**Issue by farmani** [yiisoft/yii2#15682] opened 2018-02-19 17:14 UTC
for all my tests on sending request it failed
```console
Headers already sent in /home/ramin/.config/composer/vendor/phpunit/phpunit/src/Util/Printer.php on line 112.
 /www/project/backend/vendor/yiisoft/yii2/web/Response.php:366
 /www/project/backend/vendor/yiisoft/yii2/web/Response.php:339
 /www/project/backend/vendor/symfony/browser-kit/Client.php:312
 /www/project/backend/api/tests/_support/_generated/ApiTesterActions.php:370
/www/picontest/backend/api/tests/api/ChangePasswordCept.php:7
```
this is ChangePasswordCept.php
```php
<?php 
use api\tests\ApiTester;
$I = new ApiTester($scenario, true);
$I->wantTo('Change Password By Old Password.');
$I->haveHttpHeader('Accept', 'application/json; version=v1.0');
$I->sendPUT('/change-password', [
    'email' => 'email@gmail.com',
    'oldPassword'=>'password_0',
    'password'=>'password_1'
]);
$I->grabResponse();
$I->seeResponseCodeIs(\Codeception\Util\HttpCode::OK);
```

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14
| PHP version      | 7.2
| Operating system |Debian 9

**Comment by samdark** [comment] 2018-02-19 17:36
https://yii.slack.com/archives/C6H833X42/p1519061710000023

**Comment by samdark** [comment] 2018-02-19 17:46
@farmani please report if you'll find out what's wrong with it.

**Comment by SilverFire** [comment] 2018-02-19 17:49
Try to run test in IDE with runner option `--stderr`

**Comment by farmani** [comment] 2018-02-19 17:54
The "--stderr" option does not exist.  

https://codeception.com/docs/reference/Commands#Run

**Comment by SilverFire** [comment] 2018-02-19 18:00
Ehh, messed up with PHPUnit :)

**Comment by farmani** [comment] 2018-02-19 18:01
yes I have same idea dont know which one rise it

**Comment by SilverFire** [comment] 2018-02-19 18:09
We've overridden `ResultPrinter` for PHPUnit to make it work with PHP 7.2: https://github.com/yiisoft/yii2/blob/master/tests/ResultPrinter.php
The main idea is to prevent echoing and always print execution progress to STDOUT. Otherwise - errors about sent headers may appear.

But there is an issue with PHPStorm: it forces its own ResultPrinter, that helps to integrate tests with the native IDE UI, but it outputs to the buffer instead of STDOUT. As a workaround, I can pass `--stdout` to PHPUnit, but can't do the same with Codeception.

@DavertMik maybe you have something to suggest?

**Comment by bscheshirwork** [comment] 2018-02-20 11:36
@farmani try to rebuild phpstorm docker image from autogenerated with you own result printer:

for example 

copy src
```sh
rm ~/projects/.phpstorm_helpers/*
docker cp phpstorm_helpers_PS-173.4127.29:/opt/.phpstorm_helpers/ ~/projects/.phpstorm_helpers
```
change `codeception.php`
```php
...
/**
 * For avoid set headers before session start
 * Class PhpStorm_Codeception_ReportPrinter_Redefine
 */
class PhpStorm_Codeception_ReportPrinter_Redefine extends PHPUnit_TextUI_ResultPrinter
{
    /**
     * @inheritDoc
     */
    public function __construct(
        $out = null,
        $verbose = false,
        $colors = self::COLOR_DEFAULT,
        $debug = false,
        $numberOfColumns = 80,
        $reverse = false
    ) {
        parent::__construct(STDOUT, $verbose, $colors, $debug, $numberOfColumns, $reverse);
    }

    /**
     * Flush buffer and close output if it's not to a STDOUT stream
     */
    public function flush()
    {
        if ($this->out != STDOUT) {
            parent::flush();
        }
    }
}

class PhpStorm_Codeception_ReportPrinter extends PhpStorm_Codeception_ReportPrinter_Redefine
{
...
```
delete all of old docker containers, who add origin code to cache.

build image. Important: name is same to origin
```
cd ~/projects/.phpstorm_helpers/
docker build --no-cache --pull -t phpstorm_helpers:PS-173.4127.29 .
```

May be someone tell JetBrain about this?

**Comment by farmani** [comment] 2018-02-20 12:22
this is not a right way to resolve an issue and I don't know why close this bug?

**Comment by SilverFire** [comment] 2018-02-20 12:40
This bug is not closed

**Comment by bscheshirwork** [comment] 2018-02-20 13:01
so.... I try to run test on fresh phpstorm helper with redefine printer. I also get the error.

```
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /repo/vendor/phpunit/phpunit/src/Util/Printer.php on line 112. in /var/www/html/vendor/yiisoft/yii2/web/Response.php:366
```

**Comment by bscheshirwork** [comment] 2018-02-20 13:03
https://github.com/yiisoft/yii2/blob/313be2a5d75951e48273c6dae04eba2ab879fba9/framework/web/Response.php#L365-L367

**Comment by amkoro** [comment] 2018-02-23 20:59
+1
the issue exists when running from console as well
reverted to 2.0.13

**Comment by samdark** [comment] 2018-02-23 23:06
@amkoro how to reproduce it?

**Comment by frontbear** [comment] 2018-02-24 03:41
this issue `Headers already sent...` has been reproduced. see https://github.com/yiisoft/yii2/issues/15698#issuecomment-368193947

I suggest making commit https://github.com/yiisoft/yii2/commit/28e7f31a37866d899c77a80d15a8c2676aff0771 as BC breaking change

**Comment by zacksleo** [comment] 2018-06-20 02:52
same issue

**Comment by samdark** [comment] 2018-10-26 22:05
Closing since we cannot resolve original issue.

**Closed by samdark** 2018-10-26 22:05 UTC
Labels: Codeception

**Comment by ItsReddi** [comment] 2020-09-15 13:38
We discovered that issue today, just for reference
https://stackoverflow.com/a/55040543/2331543
is a workaround that works.

Or does anyone have a better solution for that case?

**Comment by aminkt** [comment] 2021-08-20 10:46
Add below code to end of `_bootstrap.php`

```
// File: tests/_bootstrap.php
ob_start();
```
