### ISSUE TITLE
Incorrect behavior of Compare validator

### ISSUE THREAD

**Issue by jhon100** [yiisoft/yii2#12864] opened 2016-10-27 20:45 UTC
I have 2 fields:
'cred_rendimentos' and 'cred_despesas'

My rules are:

> ['cred_rendimentos', 'compare', 'compareAttribute' => 'cred_despesas', 'operator' => '>='  ],
> ['cred_despesas', 'compare', 'compareAttribute' => 'cred_rendimentos', 'operator' => '<'  ],

I type 10 in cred_rendimentos
Type 100 in cred_despesas

I see the desired error. (cred_despesas must be less than cred_rendimentos)

I type 1000 in cred_rendimentos, the error in cred_despesas dont disappear. (I could understand as a developer but this is not the behavior the user expects)

I clear the 2 fields, type 10 in cred_despesas and see the error about it must be less than cred_rendimentos. 
cred_rendimentos is not filled, why the error? The inverse dont cause error (Enter 10 in cred_rendimentos with cred_despesas empty)

So, the issue is:
- If an atributte A has error and has compare validator with field B, changing the field B must update the error in field A.
- If I fill only A and dont get errors, so I dont should get error when I only fill B
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.11-dev |
| PHP version | 5.6.24 |
| Operating system | Windows 10 |

**Comment by jhon100** [comment] 2016-10-27 21:10
Other strange behavior:
Type 100 in cred_rendimentos

And type the following values in cred_despesas

value    | status
------------ | -------------
 1 | ok
2 | error in this field
 10 | ok
 11, 12, 15, 20, 40, 99 | error in this field

**Comment by jhon100** [comment] 2016-10-27 22:03
I found in the Framework Code (yii\validators\CompareValidator) an option 'type'. Changing the type to 'number' solved my comment above, with respect the unexpected errors. Would be good a mention about this argument in http://www.yiiframework.com/doc-2.0/guide-tutorial-core-validators.html#compare.

The behavior mentioned in my firt post remains the same.
- If an atributte A has error and has compare validator with field B, changing the field B must update the error in field A.
- If I fill only A and dont get errors, so I dont should get error when I only fill B

**Comment by cebe** [comment] 2016-10-28 08:18
Fixed the docs, thanks for reporting!

**Comment by jhon100** [comment] 2016-10-28 10:01
Thanks @cebe, maybe you can use the new constant in the doc example?

> // validates if age is greater than or equal to 30
>     ['age', 'compare', 'compareValue' => 30, 'operator' => '>=', 'type' => 'number'],

**Comment by cebe** [comment] 2016-10-28 11:25
@samdark the original issue is not about docs, it is this:

> So, the issue is:
>
 > If an atributte A has error and has compare validator with field B, changing the field B must update the error in field A.
>  If I fill only A and dont get errors, so I dont should get error when I only fill B

**Comment by cebe** [comment] 2016-10-28 11:25
@jhon100 I did not use the constant in the docs as it would be harder to understand and would need to include the validator namespace.

**Comment by jhon100** [comment] 2016-10-28 11:38
Ok @cebe you are right.

**Comment by cebe** [comment] 2017-04-25 22:47
this is a non-trivial issue in JS validation: https://github.com/yiisoft/yii2/issues/12864#issuecomment-256897271 removed the milestone for now.

**Comment by cebe** [comment] 2017-04-25 22:49
related to #12636

**Comment by cebe** [comment] 2017-04-25 22:49
duplicate of #13333

**Closed by cebe** 2017-04-25 22:49 UTC
Labels: feature:form, JS
