### ISSUE TITLE
QueryBuilder->bindParam fails in PHP7.2.9 on "count($params)" if $params is null

### ISSUE THREAD

**Issue by theOtherNir** [yiisoft/yii2#16682] opened 2018-09-04 10:11 UTC
### What steps will reproduce the problem?
```
// NOT setting $params ! it's by-reference so the function accepts it
$q = $connection->getQueryBuilder()->insert($table, $d, $params);
```
### What is the expected result?
query should run

### What do you get instead?
"Parameter must be an array or an object that implements Countable"

### Additional info
this seems to solve the issue : (QueryBuilder line 1715)
`
$phName = self::PARAM_PREFIX . (empty($params) ? 0 : count($params));
`

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.4 (but it's the same code in 2.0.15.1)
| PHP version      | PHP 7.2.9-1+ubuntu16.04.1
| Operating system | ubuntu 16.4 / mint 18.3

**Comment by SamMousa** [comment] 2018-09-04 12:28
@theOtherNir you are breaking the contract.
The PHPDOC says this:
```php
/**
 * @param array $params the binding parameters that will be generated by this method.
 * They should be bound to the DB command later.
```

Passing `null` is not valid.

**Comment by theOtherNir** [comment] 2018-09-04 13:03
I totally agree with you :+1: 
but on the other hand, code that worked in 5.x is failing in 7.x
this is PHP, where by-ref can also be used to return values.
IMHO the framework shouldn't break due such a little thing.
and if you don't think that way then feel free to close this issue :)

**Comment by theOtherNir** [comment] 2018-09-04 13:06
+ actually, reading the doc you've attached, it says that :
"the binding parameters that will be generated by this method"
so why are they not generated ?
maybe the problem is somewhere else in the chain, didn't dive too deep, I admit.

**Comment by SamMousa** [comment] 2018-09-04 13:06
> but on the other hand, code that worked in 5.x is failing in 7.x
this is PHP, where by-ref can also be used to return values.

That's true, but not relevant. We capture part(s) of these contracts in PHPDoc because PHP (at the time) could not support the constraint.
If we update that to use an array type hint your code would also break.

The goal is not to have your code not break, the goal is to have your incorrect code always break.
The correct fix would be to check if the parameter is an array and if not, throw an exception.

**Comment by theOtherNir** [comment] 2018-09-04 13:13
> The goal is not to have your code not break, the goal is to have your incorrect code always break.

you're 100% correct in that.
throwing an exception is also an option.
but better do it before it gets too deep in the stack, i.e., maybe throw it in the insert / update / delete commands already ?
otherwise it takes debugging to find the root issue
as in the current state of PHP, even xdebug is not that stable yet, on my machine it keeps crashing and it took >hr to locate the issue.

**Comment by rob006** [comment] 2018-09-06 10:33
> Passing `null` is not valid.

I disagree. `null` may be considered as "no value", and if no value was specified, it should be generated (same when you don't pass nothing). It is also more pragmatic, since you can do:

```php
$connection->getQueryBuilder()->insert($table, $d, $params);
```

Instead of:

```php
$params = [];
$connection->getQueryBuilder()->insert($table, $d, $params);
```

And it could be easly achieved in PHP 7.1, for eaxmple:

```php
public function buildExpression(ExpressionInterface $expression, ?array &$params = []) {
    $params = $params ?? [];
    // ...
}
```

**Comment by SamMousa** [comment] 2018-09-06 11:12
@rob006 this is not subjective...
The PHPDoc says `null` is not a valid value, you are making an argument that it should be a valid value. 
I don't necessarily disagree with that, but that's a feature not a bug.
The current behavior conforms with the docs and changing it to support `null` is adding a feature.

I propose closing this for 2.x as there is an easy workaround for @theOtherNir. 
For 3.0 it makes more sense to properly clean it up, passing an argument by reference so it can serve as an extra return value isn't a neat solution anyway.

**Closed** 2018-09-06 23:26 UTC
Labels: php7, type:bug
