### ISSUE TITLE
bug in ActiveDataProvider

### ISSUE THREAD

**Issue by annushara** [yiisoft/yii2#8313] opened 2015-05-07 08:47 UTC
by combining several queries by a single UNION stops working pagination. Instead of sampling necessary amount of records per page, she chooses to Example 5 records from the first request, all subsequent entries and repeat it on every page

``` php
            $query = new Query();
            $query2  = new Query();
            $query3 =  new Query();



            $query->select(['monitors.id',
                'name_monitors.name as name'])
                ->from('monitors')
                ->leftJoin( 'name_monitors',
                    'name_monitors.id=monitors.id_name_monitor')
                ->all();

            $query2->select(['printers.id',
                'name_printers.name as name'])
                ->from('printers')
                ->leftJoin( 'name_printers',
                    'name_printers.id=printers.id_name_printer')
                ->all();

            $query3->select(['system_unit.id',
                'name_system_unit.name as name'])
                ->from('system_unit')
                ->leftJoin( 'name_system_unit',
                    'name_system_unit.id=system_unit.id_name_system_unit')
                ->all();

           $query->union($query3, true);
            $query->union($query2, true);

 $dataProvider = new ActiveDataProvider([
                'query' => $query,
                'pagination' => [
                    'forcePageParam' => false,
                    'pageSizeParam' => false,
                    'pageSize' => 5,
                ]
            ]);
```

**Comment by cebe** [comment] 2015-05-07 09:47
1. you should remove the `all()` call from all the queries, these would run the query on the db and drop the result
2. your issue may be a duplicate of #7992, can you show the sql that is being executed?

**Comment by annushara** [comment] 2015-05-07 10:56
I removed all -> all. sql request looks
<code>(SELECT `monitors`.`id`, `name_monitors`.`name` AS `name` FROM `monitors` LEFT JOIN `name_monitors` ON name_monitors.id=monitors.id_name_monitor) UNION ( SELECT `system_unit`.`id`, `name_system_unit`.`name` AS `name` FROM `system_unit` LEFT JOIN `name_system_unit` ON name_system_unit.id=system_unit.id_name_system_unit ) UNION ( SELECT `printers`.`id`, `name_printers`.`name` AS `name` FROM `printers` LEFT JOIN `name_printers` ON name_printers.id=printers.id_name_printer )</code>

**Comment by cozumel424** [comment] 2015-08-30 03:38
I've got this too, it seems pagination just doesn't work with a union query (unless I'm doing something completely wrong) Simplest way to reproduce it:
```
$query = Test::find();
$query2 = Test::find();

$query->union($query2, false);

$dataProvider = new ActiveDataProvider([
	'query' => $query,
	'pagination' => [
		'pageSize' => 1,
	],
	
]);

```		
Table:
```
CREATE TABLE IF NOT EXISTS `test` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
Generated SQL:
```
SELECT COUNT(*) FROM ((SELECT * FROM `test`) UNION ( SELECT * FROM `test` )) `c`

select_type: PRIMARY
table: 
type: ALL
rows: 4

(SELECT * FROM `test` LIMIT 1) UNION ( SELECT * FROM `test` )

select_type: PRIMARY
table: test
type: index
key: PRIMARY
key_len: 4
rows: 2
Extra: Using index

```
It looks like the limit is in the wrong place, it looks similiar too (but not identical) to this issue https://github.com/yiisoft/yii2/issues/7992

**Comment by ibrarturi** [comment] 2015-09-11 14:55
Using the union with ActiveDataProvider, pagination is not properly working... By checking the queries in Yii Debugger, its adding LIMIT and OFFSET to the first query only, which is the main causing of the problem.

Following are the generated example of the queries for union:
```
(SELECT * FROM `test` LIMIT 20) UNION ( SELECT * FROM `test` )
```
and for second page:
```
SELECT * FROM `test` LIMIT 20 OFFSET 40) UNION ( SELECT * FROM `test` )
```
and I have checked, this issue is not the duplicate of #7992

**Comment by SamMousa** [comment] 2017-03-30 15:14
Related to #12968

**Closed** 2024-04-02 12:38 UTC
Labels: status:to be verified
