### ISSUE TITLE
RateLimiter produces unexpected result

### ISSUE THREAD

**Issue by retnek** [yiisoft/yii2#14733] opened 2017-08-29 06:55 UTC
Hello,

I've got an interesting issue with the RateLimiter today. The yii\filters\RateLimiter checkRateLimit function always throw a TooManyRequestsHttpException.

### What steps will reproduce the problem?
When I remove the (int) typecast, the issue is dissapear.

yii\filters\RateLimiter.php class line 114:
```php
$allowance += (float) (($current - $timestamp) * $limit / $window);
```
instead of this:
```php
$allowance += (int) (($current - $timestamp) * $limit / $window);
// it will produces an unexpected negative number. 
// The expression result above without typecast is correct,
// but after typecast the result will be a negative number.
```
### What is the expected result?
The API should run the correct action.
### What do you get instead?
I've got an unexpected TooManyRequestsHttpException.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      |  7.1.0
| Operating system | Windows 10

**Comment by retnek** [comment] 2017-08-29 11:01
**When does the issue occur?**
All of my API calls I've got a 426 Too Many Requests exception (except OPTIONS).

**What do you see?**
I see a 429 Too Many Requests error in my API response.
`{"name":"Too Many Requests","message":"Rate limit exceeded.","code":0,"status":429,"type":"yii\\web\\TooManyRequestsHttpException"}`

**What was the expected result?**
The API does the several actions instead of throw a 426 exception on my first request.

Stack trace:
0 ..\vendor\yiisoft\yii2\filters\RateLimiter.php(89): yii\filters\RateLimiter->checkRateLimit(Object(common\models\User), Object(yii\web\Request), Object(yii\web\Response), Object(yii\base\InlineAction))
1 ...\vendor\yiisoft\yii2\base\ActionFilter.php(75): yii\filters\RateLimiter->beforeAction(Object(yii\base\InlineAction))
2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
3 ...\vendor\yiisoft\yii2\base\Component.php(545): call_user_func(Array, Object(yii\base\ActionEvent))
4 ...\yiisoft\yii2\base\Controller.php(272): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
5 ...\vendor\yiisoft\yii2\web\Controller.php(164): yii\base\Controller->beforeAction(Object(yii\base\InlineAction))
6 ...\vendor\yiisoft\yii2\base\Controller.php(154): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
7 ...\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('create', Array)
8 ...\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('notetaking/job/...', Array)
9 ...\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
10 ...\backend\web\index-test.php(22): yii\base\Application->run()
11 {main}

**Comment by samdark** [comment] 2017-08-29 11:05
Any idea on how to reproduce it?

**Comment by retnek** [comment] 2017-08-29 11:25
I think the problem is the following expression result is bigger than the default PHP_INT_MAX:
yii\filters\RateLimiter.php class line 114:
```php 
$allowance += (float) (($current - $timestamp) * $limit / $window);
```
therefore the typecast produces a negative value and the 
```php 
if ($allowance < 1) { ...
``` 
condition will be true.

In my case the getRateLimit returns [50, 1] and the loadAllowance returns [1, 1];
$allowance += (int) ((1504005147 - 1) * 50 / 1;
The current timestamp value * 50 will be reaches the PHP_INT_MAX.

I'm sorry that I couldn't help more.

**Comment by samdark** [comment] 2018-01-21 19:44
Should be duplicate of #15432

**Closed by samdark** 2018-01-21 19:44 UTC
Labels: status:ready for adoption, type:bug
