### ISSUE TITLE
BC break in ArrayHelper on 2.0.36

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii2#18086] opened 2020-06-07 10:42 UTC
### What steps will reproduce the problem?
```php
$list = self::find()
    ->select(['lng', 'name' => 'name_' . Yii::$app->language])
    ->orderBy('sort, name')
    ->all();
$test = ArrayHelper::map($list, 'lng', 'name');
var_dump($test);
```

### What is the expected result?
2.0.35 result
```
array(9) {
  ["Icao"]=>
  string(27) "ICAO/NATO phonetic alphabet"
  ["Lapd"]=>
  string(19) "LAPD radio alphabet"
  ["NlBe"]=>
  string(15) "Dutch (Belgium)"
  ["NlNl"]=>
  string(23) "Dutch (The Netherlands)"
  ["Fr"]=>
  string(6) "French"
  ["De"]=>
  string(6) "German"
  ["It"]=>
  string(7) "Italian"
  ["Es"]=>
  string(7) "Spanish"
  ["Useless"]=>
  string(49) "The Non-Phonetic Alphabet (Use at your own risk!)"
}
```

### What do you get instead?
2.0.36-dev result
```
array(9) {
  ["Icao"]=>
  NULL
  ["Lapd"]=>
  NULL
  ["NlBe"]=>
  NULL
  ["NlNl"]=>
  NULL
  ["Fr"]=>
  NULL
  ["De"]=>
  NULL
  ["It"]=>
  NULL
  ["Es"]=>
  NULL
  ["Useless"]=>
  NULL
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.36-dev
| PHP version      | 7.4.6
| Operating system | Debian 9

**Comment by alex-code** [comment] 2020-06-07 11:34
What results does the query return?

**Comment by Thoulah** [comment] 2020-06-07 11:41
Both times the same return (diff returned nohing).

```
array(9) {
  [0]=>
  object(mister42\models\tools\PhoneticAlphabet)#103 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(27) "ICAO/NATO phonetic alphabet"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "Icao"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "Icao"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [1]=>
  object(mister42\models\tools\PhoneticAlphabet)#138 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(19) "LAPD radio alphabet"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "Lapd"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "Lapd"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [2]=>
  object(mister42\models\tools\PhoneticAlphabet)#139 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(15) "Dutch (Belgium)"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "NlBe"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "NlBe"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [3]=>
  object(mister42\models\tools\PhoneticAlphabet)#140 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(23) "Dutch (The Netherlands)"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "NlNl"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(4) "NlNl"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [4]=>
  object(mister42\models\tools\PhoneticAlphabet)#141 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(6) "French"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "Fr"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "Fr"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [5]=>
  object(mister42\models\tools\PhoneticAlphabet)#142 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(6) "German"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "De"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "De"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [6]=>
  object(mister42\models\tools\PhoneticAlphabet)#143 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(7) "Italian"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "It"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "It"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [7]=>
  object(mister42\models\tools\PhoneticAlphabet)#144 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(7) "Spanish"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "Es"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(2) "Es"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
  [8]=>
  object(mister42\models\tools\PhoneticAlphabet)#145 (14) {
    ["alphabet"]=>
    NULL
    ["name"]=>
    string(49) "The Non-Phonetic Alphabet (Use at your own risk!)"
    ["numeric"]=>
    bool(true)
    ["text"]=>
    NULL
    ["_attributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(7) "Useless"
    }
    ["_oldAttributes":"yii\db\BaseActiveRecord":private]=>
    array(1) {
      ["lng"]=>
      string(7) "Useless"
    }
    ["_related":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_relationsDependencies":"yii\db\BaseActiveRecord":private]=>
    array(0) {
    }
    ["_errors":"yii\base\Model":private]=>
    NULL
    ["_validators":"yii\base\Model":private]=>
    NULL
    ["_scenario":"yii\base\Model":private]=>
    string(7) "default"
    ["_events":"yii\base\Component":private]=>
    array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private]=>
    array(0) {
    }
    ["_behaviors":"yii\base\Component":private]=>
    array(0) {
    }
  }
}
```

**Comment by Thoulah** [comment] 2020-06-07 13:06
I suspect https://github.com/yiisoft/yii2/blob/35fb9c624893855317e5fe52e6a21f6518a9a31c/framework/helpers/BaseArrayHelper.php#L200 from commit 35fb9c624893855317e5fe52e6a21f6518a9a31c to be there reason, as it returns as if everything given to this function is an array. The correct return is never reached.
https://github.com/yiisoft/yii2/blob/35fb9c624893855317e5fe52e6a21f6518a9a31c/framework/helpers/BaseArrayHelper.php#L214

**Comment by alex-code** [comment] 2020-06-07 17:13
I think it could be this line https://github.com/yiisoft/yii2/blob/35fb9c624893855317e5fe52e6a21f6518a9a31c/framework/helpers/BaseArrayHelper.php#L209

If the key doesn't exist it shouldn't return `$default` and should continue.

**Comment by samdark** [comment] 2020-06-09 08:59
Is it possible to put together a unit test that fails with 2.0.36 but does not with 2.0.35?

**Comment by Thoulah** [comment] 2020-06-09 09:32
I can't test it right now, but this might do the trick:

```
    public function testGetValueArrayObjects()
    {
        $data = [
			new \ArrayObject(['foo1' => 'bar1']),
			new \ArrayObject(['foo2' => 'bar2']),
		];
        $this->assertEquals('bar2', ArrayHelper::getValue($data, 'foo2'));
    }
```

**Comment by samdark** [comment] 2020-06-09 11:58
First one fails. Second one pass.

**Comment by samdark** [comment] 2020-06-09 12:08
Seems the first one fails with 2.0.35 as well.

**Comment by samdark** [comment] 2020-06-09 12:10
It fails for any version from 2.0.0 to 2.0.36 so what's in the tests is not a regression.

**Comment by samdark** [comment] 2020-06-09 12:15
```php
public function testMapObjects()
{
    $data = [
        new DynamicModel(['name' => 'bar1', 'value' => 1]),
        new DynamicModel(['name' => 'bar2', 'value' => 2]),
    ];

    $expected = [
        'bar1' => 1,
        'bar2' => 2,
    ];

    $this->assertEquals($expected, ArrayHelper::map($data, 'name', 'value'));
}
```

Works as expected.

**Comment by Thoulah** [comment] 2020-06-09 12:17
Right. I will come back with a correct test this evening then :)

**Comment by Thoulah** [comment] 2020-06-09 12:42
The only difference I can find right now is that in my case `name` is not actually a column in my database.table, but declared as `public $name;` in the class. This causes it to be not listed under `_attributes` in the object.
If that did not help I will take a look this evening.

**Comment by alex-code** [comment] 2020-06-09 13:08
This works for me on .35
```php
$data = [
  new class(['value' => 1]) extends \yii\base\DynamicModel {
    public $name = 'bar1';
  },
  new class(['value' => 2]) extends \yii\base\DynamicModel {
    public $name = 'bar2';
  },
];
```

I just did some quick local code and removing the `return $default` from this line https://github.com/yiisoft/yii2/blob/35fb9c624893855317e5fe52e6a21f6518a9a31c/framework/helpers/BaseArrayHelper.php#L209 made it work on .36

I think lines 199-201 & 208-210 could be combined too.
```php
if (static::isArrayAccess($array) && static::keyExists($key, $array)) {
  return $array[$key];
}
```

**Comment by Thoulah** [comment] 2020-06-09 15:06
Thank you @alex-code, that is most helpful :)

```php
	public function testMapObjects()
	{
            $data = [
                new class(['foo' => 'val1', 'bar' => 1]) extends \yii\base\DynamicModel {
                    public $foo = 'value1';
                },
                new class(['foo' => 'val2', 'bar' => 2]) extends \yii\base\DynamicModel {},
            ];

	    $expected = [
		'val1' => 1,
		'val2' => 2,
	    ];

	    $this->assertEquals($expected, ArrayHelper::map($data, 'foo', 'bar'));
	}
```

```
1) yiiunit\framework\helpers\ArrayHelperTest::testMapObjects
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'val1' => 1
     'val2' => 2
+    'value1' => 1
 )
```

**Comment by samdark** [comment] 2020-06-10 07:10
@Thoulah it fails the same way in 2.0.0. There was no regression about it.

So... is there something that worked in 2.0.35 and doesn't work in master?

**Comment by Thoulah** [comment] 2020-06-10 07:40
I seem to be unable to make this into a phpUnit test, but the following code will reproduce the difference in results.

`TestController.php`:
```php
<?php

namespace app\controllers;

class TestController extends \yii\web\Controller
{
    public function actionTest()
    {
        $model = new \app\models\Test();
        $data = $model->getList();
        var_dump($data);exit;
    }
}
```

`Test.php`:
```php
<?php

namespace app\models;

use yii\helpers\ArrayHelper;

class Test extends \yii\db\ActiveRecord
{
    public $key;

    public static function tableName()
    {
        return '{{%test}}';
    }

    public static function getList(): array
    {
        $list = self::find()
            ->select(['key' => 'name', 'value'])
            ->all();
        $data = ArrayHelper::map($list, 'key', 'value');
        return $data;
    }
}
```

Mysql dump:
```sql
CREATE TABLE `tbl_test` (
  `id` int(11) NOT NULL,
  `name` varchar(5) NOT NULL,
  `value` varchar(15) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

INSERT INTO `tbl_test` (`id`, `name`, `value`) VALUES
(1, 'name1', 'Yii2 test'),
(2, 'name2', 'Another value'),
(3, 'name3', 'Last one');
```

And finally the results of this code:
2.0.35: `array(3) { ["name1"]=> string(9) "Yii2 test" ["name2"]=> string(13) "Another value" ["name3"]=> string(8) "Last one" }`
2.0.36-dev: `array(1) { [""]=> string(8) "Last one" }`

**Comment by alex-code** [comment] 2020-06-10 09:10
Ignore those commits, thought I had it but we get other issues.

The problem is if an object implements `ArrayAccess` you can't use `ArrayHelper::getValue` to access public properties anymore and still have `$default` return on non existent keys.

**Comment by Thoulah** [comment] 2020-06-10 09:30
Is that related to [my issue](https://forum.yiiframework.com/t/no-value-of-property-after-setting-visibility/129784/11) on the forum?

**Comment by alex-code** [comment] 2020-06-10 09:54
That's different, if you're trying to access a property that exists (as part of the object) that'll be used before deferring to magic methods.

```php
class Test
{
  public $foo = 'bar';

  public function __get($name)
  {
    if ($name === 'foo') {
      return "I'm also bar";
    }
  }
}

(new Test)->foo; // is 'bar'
```

**Comment by mikk150** [comment] 2020-06-25 10:34
mkay, so, issue is that since you want to get property off of `ActiveRecord` instance, and `ActiveRecord` instance implements `\ArrayAccess` interface(meaning I can ask stuff with `\ArrayAccess::offsetGet()`) that means pretty much, that public properties and getters cannot be accessed using `ArrayHelper::getValue()`

this Is a regression yes..

**Comment by mikk150** [comment] 2020-06-25 11:22
hmm, it is actually more interesting, as it should not matter, as `ActiveRecord::offsetGet()` is https://github.com/yiisoft/yii2/blob/master/framework/base/Model.php#L1024

**Comment by mikk150** [comment] 2020-06-25 13:16
@samdark maybe we should fix `BaseActiveRecord::__isset()` to check for public properties as well, but that might be Backwards breaking for some folks out there

**Comment by mikk150** [comment] 2020-06-25 13:23
![image](https://user-images.githubusercontent.com/4953629/85728010-30830f80-b700-11ea-88dd-e8ffeb0f4d26.png)
So `BaseActiveRecord::__isset()` sure does not work correctly

**Comment by alex-code** [comment] 2020-06-25 13:56
I don't think this issue is specific to `ActiveRecord`

Quick dirty example
```php
$data = new class(['value' => 123]) implements \ArrayAccess {
  private $attributes = [];
  public $name = 'bar1';
            
  public function __construct($attributes)
  {
    $this->attributes = $attributes;
  }

  public function offsetExists($offset) { return isset($this->attributes[$offset]); }
  public function offsetGet($offset) { return $this->attributes[$offset]; }
  public function offsetSet($offset, $value) {}
  public function offsetUnset($offset) {}
};

var_dump(ArrayHelper::getValue($data, 'value')); // dumps as `123`
var_dump(ArrayHelper::getValue($data, 'name')); // dumps as `NULL`
```

If a class implements `ArrayAccess` you can't use `ArrayHelper::getValue` to get object properties.

**Comment by mikk150** [comment] 2020-06-25 14:03
> I don't think this issue is specific to `ActiveRecord`
> 
> Quick dirty example
> 
> ```
> $data = new class(['value' => 123]) implements \ArrayAccess {
>   private $attributes = [];
>   public $name = 'bar1';
>             
>   public function __construct($attributes)
>   {
>     $this->attributes = $attributes;
>   }
> 
>   public function offsetExists($offset) { return isset($this->attributes[$offset]); }
>   public function offsetGet($offset) { return $this->attributes[$offset]; }
>   public function offsetSet($offset, $value) {}
>   public function offsetUnset($offset) {}
> };
> 
> var_dump(ArrayHelper::getValue($data, 'value')); // dumps as `123`
> var_dump(ArrayHelper::getValue($data, 'name')); // dumps as `NULL`
> ```
> 
> If a class implements `ArrayAccess` you can't use `ArrayHelper::getValue` to get object properties.

well, yes but if this PR wasn't merged you could not get ArrayAccess offset values

**Comment by samdark** [comment] 2020-06-29 23:44
@Thoulah is your issue https://github.com/yiisoft/yii2/issues/18086#issuecomment-649557239?

**Comment by Thoulah** [comment] 2020-06-30 07:19
These smart individuals came to that conclusion based on my report and code. I have never even looked at `ArrayAccess` to say anything useful in this matter.

**Comment by mikk150** [comment] 2020-06-30 11:14
I could fix it with checking first with `offsetExists`

**Comment by samdark** [comment] 2020-06-30 14:52
@mikk150 let's do it but I'd like to see a test that works on 2.0.35 but fails on 2.0.36 first.

**Comment by alex-code** [comment] 2020-06-30 15:29
With my example here, https://github.com/yiisoft/yii2/issues/18086#issuecomment-649557239
_| .35 | .36 
---|---|---
1st `var_dump` | Causes an exception, treated as a non existent object property | Result as expected
2nd `var_dump` | Result as expected | Result is always `NULL` (or whatever `$default` is) even though property exists

**Comment by samdark** [comment] 2020-07-03 14:59
Added a test. Looking for a way to fix it.

**Comment by samdark** [comment] 2020-07-03 16:29
@alex-code, @Thoulah, @mikk150 implemented a fix. Need someone to check me. Especially on better ways achieving it.

**Comment by Thoulah** [comment] 2020-07-03 20:25
Is it prefered to return `$default` from a catch?

The `static function isArrayAccess` is now unused.

**Comment by samdark** [comment] 2020-07-03 21:03
> Is it prefered to return $default from a catch?

In this case yes because we have no idea what's missing, an object property or ArrayAccess-accessible data. Since it's ArrayAccess object we assume that's data so it behaves according to this assumption.

**Comment by samdark** [comment] 2020-07-03 21:04
btw., was your original issue fixed with it?

**Comment by Thoulah** [comment] 2020-07-03 21:05
> btw., was your original issue fixed with it?

I will let you know soon, I am in the middle of a server migration (Plesk now support Debian 10). It won't take very long

**Comment by Thoulah** [comment] 2020-07-03 21:38
Looking good from my end!

**Comment by alex-code** [comment] 2020-07-04 08:52
> @alex-code, @Thoulah, @mikk150 implemented a fix. Need someone to check me. Especially on better ways achieving it.

Looks OK to me, I can't think of another way to do it either.

**Closed** 2020-07-05 15:27 UTC
Labels: type:bug

**Comment by Thoulah** [comment] 2020-07-05 15:32
Thank you all for your help in resolving this issue :+1:

**Comment by arkzverev** [comment] 2020-07-08 14:30
After update to 2.0.36 my script crashed with memory overflow.
You can replace this:


`if (static::keyExists($key, $array)) {`

to

`if (is_array($array) && static::keyExists($key, $array)) {`

My object with getter-property - catchs this section, instead of getting into the section:

`if (is_object($array)) {`

**Comment by samdark** [comment] 2020-07-08 15:13
How to reproduce it?

**Comment by arkzverev** [comment] 2020-07-09 11:28
> How to reproduce it?

wrote to email

**Comment by rikcage** [comment] 2020-11-16 09:29
Hi i found a bug in
public static function filter ($ array, $ filters)
yii2 / framework / helpers / BaseArrayHelper.php file
line 947 [if ($ filter [0] === '!')](https://github.com/yiisoft/yii2/blob/763a2b04eae79ce3cb4cc448ad179605c52bdec2/framework/helpers/BaseArrayHelper.php#L947) {https://github.com/yiisoft/yii2/blob/763a2b04eae79ce3cb4cc448ad179605c52bdec2/framework/helpers/BaseArrayHelper.php#L947}
if $ filters is one dimensional array i see
### PHP Notice - yii \ base \ ErrorException
**Trying to access array offset on value of type int**
1.in /var/www/test_dev/vendor/yiisoft/yii2/helpers/BaseArrayHelper.phpat line 947

     * @return array Filtered array
     * @since 2.0.9
     * /
    public static function filter ($ array, $ filters)
    {
        $ result = [];
        $ excludeFilters = [];
 
        foreach ($ filters as $ filter) {
            if ($ filter [0] === '!') {
                $ excludeFilters [] = substr ($ filter, 1);
                continue;
            }
 
            $ nodeValue = $ array; // set $ array as root node
            $ keys = explode ('.', $ filter);
            foreach ($ keys as $ key) {
                if (! array_key_exists ($ key, $ nodeValue)) {
                    continue 2; // Jump to next filter

In older versions it worked like this
$ array:
```
Array
(
    [0] => #
    [1] => Action Column
    [2] => User
    [3] => Subject
    [4] => Is Active
    [5] => Created At
    [6] => Updated At
)
```
$ filters:
```
Array
(
    [0] => 0
    [1] => 1
    [2] => 3
    [3] => 2
    [4] => 6
    [5] => 5
)
```
$ result:
```
Array
(
    [0] => #
    [1] => Action Column
    [3] => Subject
    [2] => User
    [6] => Updated At
    [5] => Created At
    [4] => Is Active
)

```
It was possible to use ArrayHelper :: filter to display the array in the desired order.
**I fixed it like this**

```
- 947 if ($ filter [0] === '!') {
+ 947 if (is_array ($ filter) && $ filter [0] === '!') {
```

**Maybe it should be included this in the repository?**

**Comment by samdark** [comment] 2020-11-16 12:53
@rikcage please create a separate issue. Thanks. It's easy to lose track of comment in a closed issue.
