### ISSUE TITLE
Multiple DB connections querying problem

### ISSUE THREAD

**Issue by yrssoft** [yiisoft/yii2#10879] opened 2016-02-17 09:30 UTC
$db1 = Yii::$app->getDb();  // Yii::$app->get('db')
$db2 = Yii::$app->get('dbtest');

There is no data table in $db1
$db2 contains a data table named "t_user".
colums: user_id(int pk),name(varchar)

The following code doesn't work with the error info: The table does not exist: t_user
User::find()->where(['user_id'=>1])->one($db2);

But when I create the table t_user on $db1 (same as $db2)
The code works.

Is this Bug?

**Comment by s-o-f** [comment] 2016-02-17 11:43
Did you override the getDb() method in User model?
http://www.yiiframework.com/doc-2.0/guide-db-active-record.html#db-connection

**Comment by nkostadinov** [comment] 2016-02-17 12:17
Do you have some sort of cache enabled ?

**Comment by Alex-Code** [comment] 2016-02-17 13:37
Can you post your config for the separate connections.

**Comment by yrssoft** [comment] 2016-02-17 16:20
@s-o-f 
the User model was generated by gii.

**Comment by yrssoft** [comment] 2016-02-18 01:35
@Alex-Code 
'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=127.0.0.1:3306;dbname=cn',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8',
            'tablePrefix' => 't_',
        ],
        'dbtest' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=127.0.0.1:3306;dbname=cntest',
            'username' => 'root',
            'password' => '',
            'charset' => 'utf8',
            'tablePrefix' => 't_',
        ],

**Comment by SilverFire** [comment] 2016-02-18 09:09
Well, the config seems to be correct, but I'm unable to reproduce the error.

Please, execute the following code and show the result:

```php
var_dump(Yii::$app->get('db'));
var_dump(Yii::$app->get('dbtest'));
```

**Comment by klimov-paul** [comment] 2016-02-18 09:19
Have you redeclared `getDb()` method in your `User` ActiveRecord class?

**Comment by SilverFire** [comment] 2016-04-06 21:55
I'm closing the issue unless further information provided.

**Closed by SilverFire** 2016-04-06 21:55 UTC
Labels: feature:db, status:need more info
