### ISSUE TITLE
Type error is triggered on model typed properties - php 7.4

### ISSUE THREAD

**Issue by launcherx** [yiisoft/yii2#18055] opened 2020-05-21 09:25 UTC
### What steps will reproduce the problem?

1. Create model 
```php
class Demo extends Model
{
    public ?int $demo_attribute = null;

    public function rules()
    {
        return [
            [['demo_attribute'], 'required'],
            [['demo_attribute'], 'integer', 'min' => 0, 'max' => 10],
        ];
    }
}
```
2. Create controller action

```php
public function actionDemo()
    {
        $model = new Demo();
        
        if ($model->load(\Yii::$app->request->post())) {
            if ($model->validate()) {
                print_r($model->attributes());
            }
        }
        
        return $this->render('index', ['model' => $model]);
    }
```
3. Create form and submit form

### What is the expected result?
$model->validate() to kick in and validate attributes

If form submitted with empty `$demo_attribute` :
`Form validation error: Field Demo attribute is required`

If form submitted with non integer value for `$demo_attribute` :
`Form validation error: Field Demo attribute must be integer`

### What do you get instead?
TypeError: Typed property app\models\Demo::$demo_attribute must be int or null, string used in /app/vendor/yiisoft/yii2/base/Model.php:742

### Additional info
I guess this is happening, because $model->load() is trying to assign attribute values to model and fails because of typed properties. $model->validate() never executes. Is there any work around for this issue. 

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.35
| PHP version      | 7.4
| Operating system | Windows 10

**Comment by thiagomeireless** [comment] 2020-05-23 00:10
Having the same problem, just updated to 7.4. Did you manage to do something to override this while we wait for a proper fix?

**Comment by samdark** [comment] 2020-05-23 11:39
That is because `$model->load()` assigns values as is and the values come from the request as strings.

**Comment by samdark** [comment] 2020-05-23 11:43
Either `setAttributes()` should be modified to automatically type-cast or you should do it before calling `load()`.

**Comment by samdark** [comment] 2020-05-23 11:51
There's AttributeTypecastBehavior but it won't work either cause it fails right when assigning raw data of the wrong type.

**Comment by rob006** [comment] 2020-05-23 13:28
I don't think that this is a bug, this is how validation works in Yii 2 - you fill object with data, and then check if this data is valid. By design you can have model with inconsistent data - this is used in forms, where model still keeps user input, but displays validation error for affected field. If your model will throw type error on `load()`, that means that it is not sufficient for validation of user input. You probably should just remove types from properties and rely on validation.

**Comment by samdark** [comment] 2020-06-06 19:37
After some thinking I still have no idea on how to handle it without breaking things and changing overall concept. Thus, closing the issue. Will happily re-open if there's a brilliant idea from someone.

**Closed by samdark** 2020-06-06 19:37 UTC
Labels: php7, status:under discussion
