### ISSUE TITLE
yii\rbac\DbManager Cache 

### ISSUE THREAD

**Issue by undefinedor** [yiisoft/yii2#11751] opened 2016-06-13 06:45 UTC
| Q                | A
| ---------------- | ---
| Yii version      |2.0.8 
| PHP version      | 7.0
| Operating system | Windows

yii\rbac\DbManager,line 119
```php
public function checkAccess($userId, $permissionName, $params = [])
    {
        $assignments = $this->getAssignments($userId);
        $this->loadFromCache();
        if ($this->items !== null) {
            return $this->checkAccessFromCache($userId, $permissionName, $params, $assignments);
        } else {
            return $this->checkAccessRecursive($userId, $permissionName, $params, $assignments);
        }
    }
```
When Yii::$app->user->can(xxx), checkAccess will be called.
$assignments = $this->getAssignments($userId) will be excuted and generate a sql statement to select form db.
How to cache it ? The authManager cache is already set. But  don't work.

main.php:
```php
'authManager' => [
  			'class'=>'yii\rbac\DbManager',
            'cache'=>'cache'
		],
'cache'=>[
            'class' => 'yii\caching\FileCache',
        ],
```

**Comment by samdark** [comment] 2016-06-13 11:24
Duplicate of https://github.com/yiisoft/yii2/issues/7743

**Closed by samdark** 2016-06-13 11:24 UTC
Labels: status:to be verified
