### ISSUE TITLE
Docs about REST authentication

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii2#4718] opened 2014-08-14 16:59 UTC
Would be great if someone will clarify in [REST](https://github.com/yiisoft/yii2/blob/master/docs/guide/rest-authentication.md) guide from where we actually get `access_token`. Yes it is field form database `user` table for example, but how it is generated first time or from where it is initial value is get? Or how to generate such token, similar to `auth_token` ?

**Comment by samdark** [comment] 2016-11-04 15:49
Duplicate of #3808

**Closed by samdark** 2016-11-04 15:49 UTC
Labels: feature:rest, type:docs
