### ISSUE TITLE
SoapFault exception cannot be caught when using SoapClient

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [yiisoft/yii2#11772] opened 2016-06-17 19:13 UTC
### What steps will reproduce the problem?
i want working with SoapClient in yii2 project. but i need manage error with try-catch. but that not work !

yii2 code example :
```
class SiteController extends Controller
{
    public function actionIndex()
    {
        try{
            new \SoapClient('a',['cache_wsdl' =>  WSDL_CACHE_MEMORY]);
        }catch(\SoapFault $e){
            echo '***************';
        }
    }
}
```

yii framework output :

> PHP Fatal Error – yii\base\ErrorException SOAP-ERROR: Parsing WSDL: Couldn't load from 'a' : failed to load external entity "a"

but in test.php(no yii framework) :

```
try{
    new SoapClient('a',['cache_wsdl' =>  WSDL_CACHE_MEMORY]);
}catch(SoapFault $e){
    echo '***************';
}
```
output

`***************`

[stackoverflow : Yii2 - fatal error , try-catch not working](http://stackoverflow.com/questions/37885866/yii2-fatal-error-try-catch-not-working)

### What is the expected result?
print ***************
### What do you get instead?
catch block not run !

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 5.6.3
| Operating system | win 8.1

**Comment by cebe** [comment] 2016-06-19 10:51
`new SoapClient('a',['cache_wsdl' =>  WSDL_CACHE_MEMORY]);` triggers a PHP fatal error and does not throw `SoapFault` exception, that's why you can not catch it.

**Comment by cebe** [comment] 2016-06-19 10:56
```php
<?php

echo "<pre>";
try{
    new SoapClient('a',['cache_wsdl' =>  WSDL_CACHE_MEMORY]);
    echo "client created\n";
}catch(SoapFault $e){
    echo "exception thrown\n";
}

echo "php error:\n";

print_r( error_get_last() );
```

this seems to be a bug in the SoapClient implementation. it throws exception AND sets the fatal error in PHP.

**Comment by cebe** [comment] 2016-06-19 11:00
in PHP 7 you could work around this issue by calling [`error_clear_last()`](http://php.net/manual/en/function.error-clear-last.php) in the catch clause but that function does not exist in php 5.x

**Comment by samdark** [comment] 2016-06-19 11:52
Should be reported to PHP it seems, right?

**Comment by cebe** [comment] 2016-06-19 23:07
yep.

**Comment by samdark** [comment] 2016-06-20 08:33
Seem to be already reported: https://bugs.php.net/bug.php?id=70469 @cebe, @abolfazl-ziaratban please vote on it.

Since we can't affect this behavior from within Yii, I'm closing the issue.

**Closed by samdark** 2016-06-20 08:33 UTC
Labels: severity:important, status:to be verified

**Comment by cebe** [comment] 2016-06-20 10:04
also a duplicate of #9650

**Comment by Ne-Ray** [comment] 2016-06-21 15:18
bug in php.net
https://bugs.php.net/bug.php?id=47584

**Comment by NKalacheva** [comment] 2017-05-25 16:34
In version php 5.4.16 in Yii2  i have solved so
     try {
            $this->soapClient          = new \SoapClient($wsdl, $options);
        //без exit не сработает, в данной версии php невозможно решить малой кровью
        } catch (Exception $e) {
            exit;
        }

**Comment by gonardfreeman** [comment] 2017-06-27 14:03
`try {
            $short_link = new \SoapClient('http://rdp.zd.ua/zd/ws/Landing/?wsdl', $options);
        }catch (\SoapFault $e){
            var_dump($e);
            throw new \yii\web\HttpException(500);
        }`

and still cant to handle with SOAP-ERROR: Parsing WSDL: Couldn't load from , any ideas?

**Comment by unlike777** [comment] 2018-08-17 14:40
Soap suck...

Simple solve problem:
`
try {
   $wsdl = 'http://test.com/test/ws/Landing/?wsdl';
   simplexml_load_file($wsdl);
   $short_link = new \SoapClient($wsdl, $options);
} catch (\Exception $e) {
   var_dump($e);
}
`
If $wsdl is empty or not available simplexml_load_file throw an ErrorException
