### ISSUE TITLE
Problem with callable `indexBy` on relation query

### ISSUE THREAD

**Issue by vuongminh** [yiisoft/yii2#15183] opened 2017-11-17 18:41 UTC
### What steps will reproduce the problem?
Execute query:

```
<?php
$downloadPages = Guest::invoke()->getDownloadPages(DownloadPage::class)->joinWith([
     'linkInfo' => function ($query) use ($linkInfo) {
          $query->andOnCondition([
              '{{link_info}}.[[id]]' => ArrayHelper::getColumn($linkInfo, 'id')
          ]);
      }])->indexBy(function (DownloadPage $model) {
      // it is a lazy loading not eager
     return $model->linkInfo->link_code;
})->all();
```

In callable use relation `linkInfo` with N queries.

### What is the expected result?

Get `linkInfo` relation with `eager loading`

### What do you get instead?

Get `linkInfo` relation with `lazy loading`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13

**Comment by Alex-Code** [comment] 2017-11-20 14:23
Tricky one.
Indexing is done before relations are found so the relation in the callable is treated as lazy.

Only way I can see is to index it yourself after you have all records.

**Comment by cebe** [comment] 2017-11-21 07:34
duplicate of https://github.com/yiisoft/yii2/issues/9342

**Closed by cebe** 2017-11-21 07:34 UTC
Labels: status:to be verified
