### ISSUE TITLE
New Yii Migration 2.0.6 add additional values such as `AFTER`

### ISSUE THREAD

**Issue by bryglen** [yiisoft/yii2#9584] opened 2015-09-03 02:19 UTC
I'm using MySQL as my RDBMS, I want to have custom property but it doesn't available to the ColumnBuilder, I want to add `AFTER`. I think we should have a capability to add custom property to make it flexible to different RDBMS as well

**Comment by arogachev** [comment] 2015-09-03 03:35
Possible duplicate of #9455.

**Closed** 2015-09-03 06:14 UTC
