### ISSUE TITLE
Relations update and delete

### ISSUE THREAD

**Issue by Alex-Bond** [yiisoft/yii2#8230] opened 2015-04-30 03:38 UTC
Hi!

I found out that we don't have any functionality to simplify cascade updating and deleting of models.

For example:
I have product table `Products`.
I have table with images for this product `ProductImages`.

When i remove product i need to remove all associated images.

Guys in Gitter offer me to use database level relations, but in this case images associates with `ProductImages` will not be removed because removing configured in `afterDelete()` method.

Im offering to create something like this (part of `Products` model):
```
   public function getImages()
    {
        return $this->hasMany( ProductsImages::className(), [ 'product_id' => 'id' ] )->cascadeOnDelete();
    }
```

What core developer think about this?

**Comment by lucianobaraglia** [comment] 2015-04-30 05:00
Maybe a behaviour?

Desde el celular.

-----Mensaje original-----
De: "Alex" <notifications@github.com>
Enviado el: ‎30/‎04/‎2015 00:38
Para: "yiisoft/yii2" <yii2@noreply.github.com>
Asunto: [yii2] Relations update and delete (#8230)

Hi!
I found out that we don't any functionality to simplify cascade updating and deleting of models.
For example:
I have product table Products.
I have table with images for this product ProductImages.
When i remove product i need to remove all associated images.
Guys in Gitter offer me to use database level relations, but in this case images associates with ProductImages will not be removed because removing configured in afterDelete() method.
Im offering to create something like this (part of Products model):
   public function getImages()
    {
        return $this->hasMany( ProductsImages::className(), [ 'product' => 'id' ] )->cascadeOnDelete();
    }
What core developer think about this?

**Comment by Alex-Bond** [comment] 2015-04-30 05:32
Too much code for simple thing. I think we need to add this option inside framework as i show..

**Comment by cebe** [comment] 2015-04-30 08:26
duplicate of #569

**Comment by cebe** [comment] 2015-04-30 08:28
or maybe not, but for this:

> When i remove product i need to remove all associated images.

you can use foreign key definitions in your database: `ON DELETE CASCADE`

**Comment by Alex-Bond** [comment] 2015-05-01 06:42
When i use DB relations YII will not call `afterDelete()`.

**Comment by cebe** [comment] 2015-05-01 11:34
okay no, but you can achieve this by implementing afterDelete() in the parent model and related model.

**Comment by Alex-Bond** [comment] 2015-05-02 00:33
But we can simplify it... Right now im doing it using `afterDelete()` in `Products` model...

**Comment by cebe** [comment] 2015-05-02 21:11
place show how you would add this. adding it inside the relation definition is not possible because relation returns a query.

**Comment by Alex-Bond** [comment] 2015-05-03 05:08
Than lets return some new object, lets say `ActiveRelation` which extends ActiveQuery with few new methods.
Also this object subscribing to events of related models.

**Comment by usualdesigner** [comment] 2015-05-03 11:19
Agree with @Alex-Bond 
Ability to cascade delete via delete() method would be great.

**Comment by TerraSkye** [comment] 2015-05-04 07:49
And how would you do that with shared relation? IE i have a phonenumber. and i have 10 contacts that use that number. I delete 1 contact it should keep the number. Do i delete the other 9. De phonenber should also be removed.

**Comment by Alex-Bond** [comment] 2015-05-05 02:14
Just dont add `cascadeOnDelete()` in model.

**Comment by klimov-paul** [comment] 2015-05-05 08:42
There are several problems with this feature:

In order to make cascade deleting really(!) cascade, we need to use `ActiveRecord::delete()` method for this, which means each time you delete a 'Product' all(!) related 'orders ' should be loaded using `Order::find()->all()`, iterated and deleted one by one, which will trigger deleting 'order payments', which are related to the 'order'.
This will produce a huge perfromance impact.

If we use `ActiveRecord::deleteAll()`, the perfromance will be acceptable. But only one-level related records can be deleted this way, If you delete a 'Product' only its orders will be removed, but 'payments' linked to the orders will be intact.
Also some NOSQL solutions may lack the support of `deleteAll()`.

**Comment by Alex-Bond** [comment] 2015-05-05 10:31
@klimov-paul you still can use DB relations, but as i told before - we still need to clean all relatives for models and if model removed in DB than this trash will be not removed.

**Comment by Alex-Bond** [comment] 2016-06-05 00:33
Its been a year after last message... Any news from core team?

**Comment by samdark** [comment] 2016-06-06 17:19
I tend to think we should not implement it. The clean-up logic could vary a lot:

- Delete all relation models.
- Set all relation keys to nulls.
- Leave relations as is.
- Set status for all relation models.
- ...

**Closed by samdark** 2016-06-06 17:19 UTC
Labels: status:under discussion
