### ISSUE TITLE
Query for eager loading is inefficient

### ISSUE THREAD

**Issue by adamwinn** [yiisoft/yii2#17541] opened 2019-09-04 05:46 UTC
### What steps will reproduce the problem?
Run a query that uses eager loading.

ie.  
```
EventItemStore::find()
            ->innerJoinWith(['eventItem'])
            ->where(['event_item_store.event_id'=>$event_model->event_id])
            ->all()
```
The query produced to grab the data from the event_item table uses an `IN` clause and is not efficient.  

```SELECT * FROM event_item WHERE (event_item_id, event_id) IN ((35781233, 41285), (35781233, 41285)) ..... ```

I have an index of `KEY eventitemid-eventid (event_item_id,event_id)` and it scans the entire table and doesn't use the index.  I've read that mysql is not optimized at all for queries like this.

### What is the expected result?
A query that will use a table index and be fast

### What do you get instead?
An unoptimized query that scans the entire table.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.26
| PHP version      | 7.3
| Operating system | macOS

**Comment by rob006** [comment] 2019-09-04 07:34
What is your MySQL version?

There was similar discussion at https://github.com/yiisoft/yii2/pull/17125 and I was unable to reproduce this issue (indexes were used in my case).

**Comment by adamwinn** [comment] 2019-09-04 07:40
I'm on `5.6.10a` and it's Amazon RDS Aurora MySQL

**Comment by adamwinn** [comment] 2019-09-04 07:52
The table has 2.5M rows and when I use `force index` it still doesn't use the index

**Comment by adamwinn** [comment] 2019-09-04 07:57
This query uses the index:
`explain SELECT * FROM event_item WHERE (event_item_id, event_id) IN ((35781233, 41285))`
```
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	event_item	const	PRIMARY,event_id,event_id_index,eventitemid-eventid	PRIMARY	4	const	1	NULL
```

but this one doesn't
`explain SELECT * FROM event_item WHERE (event_item_id, event_id) IN ((35781233, 41285), (35781233, 41285))`
```
id	select_type	table	type	possible_keys	key	key_len	ref	rows	Extra
1	SIMPLE	event_item	ALL	NULL	NULL	NULL	NULL	2515122	Using where
```

**Comment by rob006** [comment] 2019-09-04 08:01
It could be an issue specific to RDS Aurora - it is not a real MySQL, it is different implementation with several limitations.

Do you have a chance to test it with 5.7?

**Comment by adamwinn** [comment] 2019-09-04 08:04
Ya, I can spin up a 5.7 instance tomorrow and give it a try

**Comment by adamwinn** [comment] 2019-09-04 17:45
mysql 5.7 worked

version: `5.7.26-log`

query: `explain SELECT * FROM event_item WHERE (event_item_id, event_id) IN ((35781233, 41285), (35781233, 41285))`

```
id	select_type	table	partitions	type	possible_keys	key	key_len	ref	rows	filtered	Extra
1	SIMPLE	event_item	NULL	range	PRIMARY,event_id,event_id_index,eventitemid-eventid	PRIMARY	4	NULL	1	5.00	Using where
```

BTW, the fix at https://github.com/yiisoft/yii2/pull/17125, worked for me on Aurora mysql5.6

**Comment by rob006** [comment] 2019-09-04 17:50
> I'm on `5.6.10a` and it's Amazon RDS Aurora MySQL

BTW: why it is `5.6.10a`? MySQL `5.6.10` was released 6 years ago.

**Comment by adamwinn** [comment] 2019-09-04 18:02
That's the default when you create an Aurora instance.  I see it now supports 5.7 so I will look into upgrading.  Thanks for your help!

**Comment by samdark** [comment] 2019-09-04 21:39
Closing the issue since that seems to be Aurora specific and one we cannot fix.

**Closed by samdark** 2019-09-04 21:39 UTC
Labels: MySQL
