### ISSUE TITLE
[2.0.13] Logger occasionally crashes due to integer microtime

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii2#15107] opened 2017-11-06 16:02 UTC
Sometimes on rare occasions `microtime(true)` will return a pure integer (without a decimal separator '.' character) which causes the new Yii 2.0.13 logger to crash.

### What steps will reproduce the problem?
Logging. It happens randomly due to [this line](https://github.com/yiisoft/yii2/blob/d0bf3cfeb4813cefbaa2e3ac0b6cbf0cbfa931c0/framework/log/Target.php#L364).

Try it yourself:
```
do {
    $string = StringHelper::floatToString(microtime(true));
} while (strpos($string),'.') !== false);
```

### What do you get instead?

>Unable to send log via yii\log\FileTarget: PHP Notice 'yii\base\ErrorException' with message 'Undefined offset: 1' in ****/vendor/yiisoft/yii2/log/Target.php:364

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.0.22
| Operating system | Ubuntu

**Comment by cebe** [comment] 2017-11-06 16:04
duplicate of https://github.com/yiisoft/yii2/issues/15081, we'll release a patch soon.

**Closed by cebe** 2017-11-06 16:04 UTC
