### ISSUE TITLE
Correction for multiple values in filters with select2 jquery

### ISSUE THREAD

**Issue by ebisbe** [yiisoft/yii2#8708] opened 2015-06-08 15:51 UTC
I've found that the filter is not working for multiple values with a select. I'm currently using the kartik/gridview that has implemented select2 jquery plugin. 

The issue is with the file yii.gridView.js. The way it handles the name:value inputs make that selects with ending _[]_ for the name like _MessageSearch[language][]=fi-FI&MessageSearch[language][]=sv-SE_ are not working. 
I'm not sure if this issue corresponds to here but I think that the modification doesn't affect other behaviors so it's better here.
My change is :
```javascript
var cont = 0;
$.each($(settings.filterSelector).serializeArray(), function () {
    if(this.name.indexOf('[]') !== false) {
        this.name = this.name.replace('[]', '[' + cont++ + ']');
    }
    data[this.name] = this.value;
});

$.each(yii.getQueryParams(settings.filterUrl), function (name, value) {
    if(name.indexOf('[]') !== false) {
        name = name.replace('[]', '[' + cont++ + ']');
    }
    if (data[name] === undefined) {
        data[name] = value;
    }
});
```
from :
```javascript
$.each($(settings.filterSelector).serializeArray(), function () {
    data[this.name] = this.value;
});

$.each(yii.getQueryParams(settings.filterUrl), function (name, value) {
    if (data[name] === undefined) {
        data[name] = value;
    }
});
```

**Comment by ebisbe** [comment] 2015-07-01 11:55
Somebody fix it. 

Thanks!

**Comment by samdark** [comment] 2015-07-06 13:27
@ebisbe is there an issue that's reproduceable on Yii w/o kartik/gridview?

**Comment by ebisbe** [comment] 2015-07-06 13:51
Yes I have the issue in my project. I can set up something for share. How can I do it?

**Comment by samdark** [comment] 2015-07-06 19:30
Take basic application template, use Yii's own widgets with minimum amount of customizations. Then zip it or put it into github repo.

**Comment by ebisbe** [comment] 2015-07-07 09:07
@samdark You can checkout this repo https://github.com/ebisbe/yii2-issue-8708 . 
Install composer and run migrations. 
Then you'll need to go to /index.php?r=message%2Findex. In the language filter column you'll see that you can choose one language but whenever you try to choose another one ( after reloading page ) there is always one.

**Comment by samdark** [comment] 2015-07-07 19:39
@ebisbe I mean w/o kartik extension, not with them so it's clear it's Yii problem and not kartik's.

**Comment by ebisbe** [comment] 2015-07-08 07:11
The problem is in how the post is made and that is made by Yii2. I update without Kartik GridView

**Comment by ebisbe** [comment] 2015-07-08 10:15
I can't set up the Gridview with the \kartik\select2\Select2.  The reasion is that K/gridview lets you add data to the collumn and filter them with a select. 
The problem I found was that yii is not submitting the form because there is no form at the filter tables. Instead it creates and object with the values and then creates the form and inserts hidden inputs ( if I remember well ) with the values that has taken from the filters. 
How else I can try to show that the error is from yii? 
With the version I made if you comment the line 113 (_$form.submit();_)  from the file _yii.gridView.js_ you will see that the form doesn't get submited and the script has appended the inputs to the form.

**Comment by ebisbe** [comment] 2015-07-13 09:12
Any news @samdark ?

**Comment by samdark** [comment] 2015-07-13 10:06
Not yet.

**Comment by Faryshta** [comment] 2015-07-15 23:07
@samdark I think the issue can be replicated more easily like this

```php
echo GridView([
    'dataProvider' => ...,
    'filterModel' => $model,
    'columns' => [
        'name[]',
        'name[]',
   ],
]);
```
When you make a request the ideal would be that it generates an url like this: `&name[]=name1&name[]=name2`

But when you execute it, it just generates a `&name[]=name2` because https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.gridView.js#L89 this line deletes the first value.

The patch I would propose would be to change the line 89 to

```javascript
applyFilter: function () {
    var $grid = $(this), event;
    var settings = gridData[$grid.attr('id')].settings;
    var data = {};
    var dataForm[];

    // get the query params from the request url
    $.each(yii.getQueryParams(settings.filterUrl), function (name, value) {
        data[name] = value;
    });

    $.each($(settings.filterSelector).serializeArray(), function () {
        if (data[this.name] !== undefined) {
            //unset all the values that appear on the url to avoid setting them twice.
            delete data[this.name];
        }
        if (this.value !== '') { // only add to the url values that are not empty strings
            dataForm[] = [this.name, this.value];
        }
    });

    $.each(data, function (name, value) {
        // add the values from the url that doesn't appear on the form.
        dataForm[] = [name, value];
    });

    var pos = settings.filterUrl.indexOf('?');
    var url = pos < 0 ? settings.filterUrl : settings.filterUrl.substring(0, pos);

    $grid.find('form.gridview-filter-form').remove();

    var $form = $('<form action="' + url + '" method="get" class="gridview-filter-form" style="display:none" data-pjax></form>').appendTo($grid);

    $.each(dataForm, function (i, value) {
        // add the values from dataForm to the form.
        $form.append($('<input type="hidden" name="t" value="" />').attr('name', value[0]).val(value[1]));
    });

   event = $.Event(gridEvents.beforeFilter);
   $grid.trigger(event);
   if (event.result === false) {
        return;
    }

    $form.submit();
            
    $grid.trigger(gridEvents.afterFilter);
},
```

@ebisbe your solution has an issue, which is that it doesn't let you erase a filter.

if your url contains `&name[0]=name1&name[1]=name2` then when you try to unselect those values the next request will keep them anyway.

**Comment by ebisbe** [comment] 2015-07-16 08:42
Hello @Faryshta,
I've tried your code and got an error with the definition of dataForm. So I made the following changes:
```
applyFilter: function () {
            var $grid = $(this), event;
            var settings = gridData[$grid.attr('id')].settings;
            var data = {};
           **var dataForm = [];**

            // get the query params from the request url
            $.each(yii.getQueryParams(settings.filterUrl), function (name, value) {
                data[name] = value;
            });

            $.each($(settings.filterSelector).serializeArray(), function () {
                if (data[this.name] !== undefined) {
                    //unset all the values that appear on the url to avoid setting them twice.
                    delete data[this.name];
                }
                if (this.value !== '') { // only add to the url values that are not empty strings
                   **dataForm.push([this.name, this.value]);**
                }
            });

            $.each(data, function (name, value) {
                // add the values from the url that doesn't appear on the form.
                **dataForm.push([name, value]);**
            });

            var pos = settings.filterUrl.indexOf('?');
            var url = pos < 0 ? settings.filterUrl : settings.filterUrl.substring(0, pos);

            $grid.find('form.gridview-filter-form').remove();

            var $form = $('<form action="' + url + '" method="get" class="gridview-filter-form" style="display:none" data-pjax></form>').appendTo($grid);

            $.each(dataForm, function (i, value) {
                // add the values from dataForm to the form.
                $form.append($('<input type="hidden" name="t" value="" />').attr('name', value[0]).val(value[1]));
            });

            event = $.Event(gridEvents.beforeFilter);
            $grid.trigger(event);
            if (event.result === false) {
                return;
            }

            $form.submit();

            $grid.trigger(gridEvents.afterFilter);
        },
```
All is working fine except that you can't delete the last one value. ( I had the same problem and my code resolved that issue leaving the issue @Faryshta mentioned ). 
Here the problem is that when yii creates a select option ( single or multiple ) creates a hidden input aswell. The select created  in our example is **MessageSearch[language][]** because has multiple value selectors but the input hidden created **MessageSearch[language]**. In order to make it work with your code we have to delete an if statement in line 811 from file yiiBaseHtml.php that deletes the ending [] from the name. 

```
if (!empty($name) && substr_compare($name, '[]', -2, 2) === 0) {
    $name = substr($name, 0, -2);
}
```
I'll update the PR with your code ( @Faryshta ) and the fixes I made once we all agree

**Comment by ebisbe** [comment] 2015-08-19 07:54
I have updated the PR @samdark @Faryshta

**Comment by svok** [comment] 2015-08-20 09:28
The issue can be reproduced with the checkbox list (for example from $form->field($record, 'attribute')->checkboxlist($list)) in the form. I do not use kartik, so the problem is in yii.gridView.js. In the case of checkbox list inputs have names like Class[attribute][]=value1&Class[attribute][]=value2... etc.

The suggestion from @ebisbe shows the correct problem part of the code, but does not work for me.

**Comment by ebisbe** [comment] 2015-08-20 09:55
Hello @svok,
Have you tried both changes ( js and php ) or just one? I'll try your example today or tomorrow so we can figure the real problem.

**Comment by svok** [comment] 2015-08-20 12:21
I have tested only js. I do not think php concerns this issue because it (problem) is related to the url formation. Namely, I see that after the GridView filter url loses all the "Class[attribute][]=value" parameters except the last. So, instead of multiple checked items I get only one last checked item.

I think about a bit different algorithm. May be it is worth just filtering out the variables from url-GET which are the same in GridView.

Another interesting solution I found in web:
       $("#SomeForm").on("beforeSubmit", function (e) {
            $(this).append($("#w0").clone().hide());
            return true;
        });

This code makes working SomeForm together with GridView. But right now such code is not applicable for the reverse case: GridView to work with SomeForm.

**Comment by ebisbe** [comment] 2015-08-21 11:06
@svok the last one is not lost because when yii2 creates the multiple select they create a hidden input with the same name as the multiple select but without the ending []. And having that difference makes always adding one input from the url. Can look what I'm saying here https://github.com/yiisoft/yii2/pull/9016/files
```
<input type="hidden" value="" name="MessageSearch[language]">
<select size="4" multiple="" name="MessageSearch[language][]" class="form-control select2-hidden-accessible" id="messagesearch-language" tabindex="-1" aria-hidden="true">
<option value="fi-FI">Finlandes</option>
<option selected="" value="sv-SE">Svenska</option>
<option value="ru-RU">Russian</option>
</select>
```

**Comment by svok** [comment] 2015-08-24 11:15
@ebisbe, the code you are proposing is not working. I have tested it on both FF and Chromium and the result is the same. There are no error messages but no action is performed after one changes a filter option. So, submit() method is not invoked. I have no idea why.

It seems to me that the current approach has an algorithmic problem. There are two types of ulrs in the form. One type is by sorting a-tags and onther one is by filtering form elements. And they both work separately and do not interconnect. If there are one more form on the page, applyFilter method would handle it, but the sorting a-hrefs wouldn't.

I would think about something following.
view:

<form id="user-form" action="<?=Url::base()?>" data-slave=gridview-form>
<input ...>
// The following script send all submit requests to the gridview form
$("#user-form").on("beforeSubmit", function (e) {
$("#gridview-form").submit();
return false;
});
</form>


<form id="gridview-form" action="<?=Url::base()?>">
<input type=hidden name=sort>
<a onclick="$('#gridview-form input[name=sort]').val('field').submit();">Sort field</a>
</form>
// The following script collects copies of fields of all other forms inside the GridView form and sends it in one request.
$("#gridview-form").on("beforeSubmit", function (e) {
$(this).append($("form [data-slave=gridview-form]").clone().hide());
return true;
});

In this case no duplication of the fields in the GET string happen, sort string works together with the filter form and all other user forms are well handled by the filter script. And no manipulation with the address is required.

**Comment by ebisbe** [comment] 2015-09-02 09:59
@svok I tested my own code again to understand why was not working for you. I've found that my test where not with the same code I PR so I get it working but the PR as you said is not working. 

The errors where that where missing the form html and the hidden input. Still not sure why happened. But looking in my comment about @Faryshta I see that they are empty there already...
```
var $form = $('').appendTo($grid);
...
$form.append($('').attr('name', value[0]).val(value[1]));
```
to 
```
var $form = $('<form action="' + url + '" method="get" class="gridview-filter-form" style="display:none" data-pjax></form>').appendTo($grid);
...
$form.append($('<input type="hidden" name="t" value="" />').attr('name', value[0]).val(value[1]));
```
Now is working. Can you check it? I don't think we have to change anything else.

**Comment by ebisbe** [comment] 2015-09-02 11:54
Still some error

**Comment by ebisbe** [comment] 2015-09-03 07:27
Now it's working again. I've found that the pagination writes the url like this:
```
/messages?MessageSearch[language][0]=ru-RU&MessageSearch[language][1]=hu-HU&page=14&per-page=30
```
So I made a replace with a regexp to delte all numbers within brackets.

**Comment by ebisbe** [comment] 2015-09-29 11:08
Any one can test or verify? @samdark ? What do I need to do?

**Comment by samdark** [comment] 2015-09-29 11:59
#9016

**Comment by nineinchnick** [comment] 2015-10-30 11:21
Same as #8089, #6923, #4431.

**Comment by ebisbe** [comment] 2015-11-03 12:18
@samdark  @nineinchnick I've made some updates based on your comments.

**Comment by SilverFire** [comment] 2015-12-05 18:24
Resolved by https://github.com/yiisoft/yii2/commit/d3cfb87ba67a328d197d1a9e52dbb12a7bf8476b, #10302

**Closed** 2015-12-05 18:24 UTC
Labels: type:bug
