### ISSUE TITLE
InitDbFixture pgsql problem

### ISSUE THREAD

**Issue by rad8329** [yiisoft/yii2#10885] opened 2016-02-17 15:04 UTC
When TestCase setup the DbFixtures check the integrity, for that, get all the table names, and execute a command like this `ALTER TABLE "public"."auth_assignment" DISABLE TRIGGER ALL; ` is a problem, because the method `findTableNames` [https://github.com/yiisoft/yii2/blob/master/framework/db/pgsql/Schema.php](https://github.com/yiisoft/yii2/blob/master/framework/db/pgsql/Schema.php) get all the objects names (including the views), them, when execute the statement for check integrity fail.

**Comment by rad8329** [comment] 2016-02-17 15:10
I do not know why this query is used , but I would suggest something simpler: 

```
SELECT
  tablename as table_name
FROM
  pg_tables  
WHERE schemaname = :schemaName
```

**Comment by cebe** [comment] 2016-02-17 15:12
duplicate of #8644

**Closed by cebe** 2016-02-17 15:12 UTC
