### ISSUE TITLE
Support for running JS tests in both NodeJS and browser

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#13275] opened 2016-12-26 10:05 UTC
Before switching to NodeJS the JS tests were intended to run in the browser (#12840).

Should we additionally add support for running it in the browser? It requires creation and maintaining of separate application and modifying code, because currently some things are coupled with NodeJs and adapted to work with it properly.

While it would not be very hard to do this, do we really need this? We had some discussion starting from https://github.com/yiisoft/yii2/pull/12936#issuecomment-259602257. Please see my opinion in https://github.com/yiisoft/yii2/pull/12936#issuecomment-259649061 and https://github.com/yiisoft/yii2/pull/12936#issuecomment-260259830.

Personally I think this is not needed anymore. For something very complex or when I need to understand code flow better, I just load basic app that is easy to deploy on local server (it ships as a part of dev tools). Then I use native browser's JS console and debugger. For situations when I need to write some HTML, I'm using views of the same basic app I mentioned.

Please vote - 👍 (should be implemented) or 👎 (should not be implemented).

**Comment by cebe** [comment] 2016-12-26 20:24
What about testing browser compatibility?

**Comment by cebe** [comment] 2016-12-27 04:25
related/duplicate of https://github.com/yiisoft/yii2/issues/13276

**Comment by arogachev** [comment] 2016-12-27 04:34
@cebe It's related, but not a duplicate. This is about adding web application and running tests in the browser of user's choice to get a better view of executed tests and access to browser debugging tools etc. #13276 is about automated run in multiple browsers to catch and prevent browser compatibility issues.

**Comment by dynasource** [comment] 2017-02-21 17:54
> Should we additionally add support for running it in the browser? Personally I think this is not needed anymore.

Agree. The new JS tests are a great improvement and should give enough insight into the inner workings. It should be our intention to make test-code great so that the use of a browser is obsolete.

**Closed by dynasource** 2017-02-21 17:54 UTC
Labels: JS
