### ISSUE TITLE
UrlManager caching issue

### ISSUE THREAD

**Issue by particleflux** [yiisoft/yii2#11231] opened 2016-03-30 08:45 UTC
The Yii2 UrlManager _sometimes_ throws `unserialize` errors.

### What steps will reproduce the problem?

Unfortunately I don't have a way to reproduce yet. Maybe it's concurrency or aborted requests - happens only on our live server. And on second request on a faulting URL it works again.

### What is the expected result?

Urlmanager should be able to successfully write and read it's cached UrlRules everytime

### What do you get instead?

Unserialize() errors when UrlManager tries to read from cache:

- https://gist.github.com/particleflux/7ca5266e1b798858a4818ade4f97ee35
- https://gist.github.com/particleflux/598a4730319e1a758439b1db8c448332
- https://gist.github.com/particleflux/d6b2d6667a3b81f56d59e3272e981243

### Additional info

Running a nginx + php-fpm setup. Caching backend is APCU:

        'cache' =>
            YII_DEBUG ?
                [
                    'class' => 'yii\caching\FileCache',
                ] :
                [
                    'class' => 'yii\caching\ApcCache',
                    'useApcu' => true,
                ]
        ,

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.0.4-1~dotdeb+8.1 and 7.0.5-1~dotdeb+8.1
| Operating system | Debian jessie
| Nginx version | 1.8.1

**Comment by particleflux** [comment] 2016-05-17 13:30
Still occurring in Yii 2.0.8

**Comment by SilverFire** [comment] 2016-05-20 10:35
The issue is assigned to the 2.0.9 milestone and maintained by @cebe. 
Unfortunately, you did not provide any exact way to reproduce the problem, therefore unlikely we can not fix it.
Maybe, you have something helpful to add to your issue?

**Comment by cebe** [comment] 2016-05-20 10:40
are you somehow able to provide the cache data that makes it crash?

**Comment by rob006** [comment] 2016-05-20 10:49
@particleflux Are you sure you get this errors when using `ApcCache`?

**Comment by particleflux** [comment] 2016-05-20 15:54
So, I added a custom de-serializing function, which logs the cached value when failing. Now waiting for the next error to come up^^


> @particleflux Are you sure you get this errors when using ApcCache?

Pretty sure, yes

**Comment by particleflux** [comment] 2016-06-06 15:43
Problems are not showing up when using a custom de-serialization function that tries to log on error case: https://gist.github.com/particleflux/967b4ea8d85d0765e5517464044c1b69

Just commented that out again to see if errors still happening under normal conditions :-/

**Comment by mikehaertl** [comment] 2016-06-06 18:05
@particleflux Searching for the error brings up many workarounds for serialized UTF-8 data that went through some system that is not using UTF-8 (e.g. saving/retrieving to/from a MySQL DB with wrong charset). While I can't really see how this could happen in UrlManager, maybe it gives you some more ideas.

It definitely sounds like a charset issue to me.

**Comment by particleflux** [comment] 2016-06-08 12:37
No re-occuring issues so far. (default code again, without custom serializers)

Maybe the PHP Updates from 7.0.5 to 7.0.7 fixed it.

**Comment by cebe** [comment] 2016-07-04 09:42
closing this as there is no way to reproduce and it may also be a php bug.

**Closed by cebe** 2016-07-04 09:42 UTC
Labels: status:need more info, status:to be verified, type:bug
