### ISSUE TITLE
https request port

### ISSUE THREAD

**Issue by andrtechno** [yiisoft/yii2#19493] opened 2022-07-29 21:36 UTC
https return getServerPort() 80

![gdfgsf](https://user-images.githubusercontent.com/6948026/181846839-0e00d5bf-24b1-40ed-9186-17c5237d7c14.png)

**Comment by samdark** [comment] 2022-07-30 10:46
What's the URL?

**Comment by andrtechno** [comment] 2022-07-30 10:58
https://homfund.pixelion.com.ua/ вывожу Yii::$app->request->getServerPort()

**Comment by andrtechno** [comment] 2022-07-30 12:29
ссылку могу обрать?

**Comment by WinterSilence** [comment] 2022-08-11 18:09
@andrtechno вангую что ты используешь nginx и не можешь нормально его сконфигурировать
@samdark close issue, error in server config

**Comment by samdark** [comment] 2022-08-11 20:20
Closing since wasn't able to reproduce it with nginx + php-fpm.

**Closed by samdark** 2022-08-11 20:20 UTC
Labels: type:bug

**Comment by SagePtr** [comment] 2022-08-24 09:14
I think you are misusing getServerPort. It's not robust way to detect your inbound port if you are behind any reverse proxy.
For instance, Cloudflare [doesn't pass this header at all](https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/), you will end up with port on which your nginx is accepting Cloudflare connections instead of translated one.
If you want to just detect http/https, use Yii::$app->request->isSecureConnection instead.
