### ISSUE TITLE
Active record collection object

### ISSUE THREAD

**Issue by dhiman252** [yiisoft/yii2#10806] opened 2016-02-11 08:59 UTC
Hi Team,

I cannot find any collection object in the documentation for the active records.

Do we have any feature like the laravel framework offers : https://laravel.com/docs/5.1/collections ?

If not please refer to the link and if possible please add this feature in the next version release !!

Thanks

**Comment by SilverFire** [comment] 2016-02-11 10:28
Yes, currently Yii has not collection object, we use arrays instead to be lightweight.

In my own development practice it's usually enough except some special cases, that can be solved locally without affecting overall application performance.

Could you describe your use case?

**Comment by adiramardiani** [comment] 2016-02-11 13:30
Interesting :)
Is it possible to reference the link above (collections) as an enhancement for ArrayHelper ?

**Comment by SilverFire** [comment] 2016-02-11 14:31
Could you elaborate your idea, please

**Comment by cebe** [comment] 2016-02-11 14:43
@dhiman252 part of the functionality of the laravel collection is provided by DataProviders in Yii. Another part is directly part of the QueryInterface already. Please describe in detail what you need and why.

**Comment by dhiman252** [comment] 2016-02-13 09:26
For the ease of use I would like this functionality incorporated in the framework, lets say i have table for user reviews and it contains the message and the points, now if i had to display the user rating average and all the reviews on a single page then i need to fire 2 SQL Queries one getting the reviews average and the other all reviews in an array
 so if we have a collection object then 1 Query and ease of use
like
`/*
$reviewsAvg = $user->reviews->avg('points');
$reviewsCount = $user->reviews->count();
froreach($user->reviews as $review){
    //display review
}
*`
There are a lot of functions associated with the collections which makes the development its easy.

**Comment by cebe** [comment] 2016-02-13 13:15
```php
$reviewsAvg = $user->getReviews()->avg('points');
$reviewsCount = count($user->reviews);
froreach($user->reviews as $review){ 
    //display review
}
```

This already works in yii.

**Comment by Alex-Bond** [comment] 2016-06-10 06:18
@cebe here is much more better example:
For example i need to query 1 time and show data in 2 columns, but not more that 10 records per column. First column contains only active elements (`active=1`) and second one showing not active (`active=0`).
In case of not using collections i need to filter it with if's and than show. If i use collections i can use `filter() ` and using closure filter data as i want.
Or lets imagine that i need to show items 3 per row in bootstrap. According to best practice you need to create new row element for each 12 columns, so i need to create some $i and increase it every iteration and based on value print new row element.
In case of collections i can just use `chunk()` method and create loop inside loop.

This is only few of use cases. There are of different ways to use it.

**Comment by Razzwan** [comment] 2016-08-22 18:28
I agree that it is a good idea.

More options use:
1. If you use the collection instead of an array, it is possible to implement the mechanism links are much more logical than done now. Instead of `$object->link('string', $arrayOfObjects)` we can use `$object->relationName->link([$id1,$id2])`. This is good becouse not use string constant. Ofcouse this is for linked relations
2. ActiveDataProvider - this is very good for return responce but not good for use in code. That part of the functionality that exists in AktiveDataProvider also would not prevent. For example, for a particular copying objects when

I would like to take up the implementation of this mechanism in 2.1 version.

**Comment by samdark** [comment] 2016-08-24 10:36
It was discussed multiple times. While it sounds good there are doubts and cons:

1. At the time we were not able to come up with a good use case where collections are significantly better than arrays.
2. Extra overhead.
3. It was likely to break backward compatibility. Back then it was significant enough obstacle to drop proposal. Now, when 2.1 is in development, it's not an issue.

**Comment by juanmacias** [comment] 2016-08-24 15:56
Sometimes you need business logic for a group of ARs. 
This is an example: ShoppingCart and CartLine[].
You usually should create a ShoppingCart and Lines in memory. When you save the ShippingCart, everything is saved. 

```

class CartLineCollection extends ActiveCollection
{
    /**
     * Rules for the collection
     * @return array
     */
    public function rules()
    {
        return [
            ["total", checkMaxTotal()], //makes a custom rule validation over the attribute total of each line
            ["sku", checkMaxItems()]
        ];
    }

    public function addLine($line)
    {
        if ($this->validateAdd($line)) {
            return parent::add($line);
        } else {
            return false;
        }
    }

    /**
     * Returns all lines with the specified TaxId
     * @param $tax_id
     * @return mixed
     */
    public function getLinesByTaxId($tax_id)
    {
        return parent::filter(["tax_id"=>$tax_id]);
    }

    /**
     * Return an array of totals by tax_id
     * @return mixed
     */
    public function getTotal()
    {
        return parent::sum("total")->groupby("tax_id");
    }

    
```

**Comment by samdark** [comment] 2016-08-24 15:58
OK but that's standalone collection, not the one tied to AR. By "tied to AR" I mean when using `Post::find()->all()` you'll get a collection such as `PostCollection` instead of array of `Post` models.

**Comment by juanmacias** [comment] 2016-08-24 16:03
Is not a standard collection, is a collection of ARs. When you call collection->save(), it makes a call to each element->save().
When you call validate, it calls each element->validate().

That's the only case I found, I used once. Although I still prefer Arrays.....

**Comment by dhiman252** [comment] 2016-08-24 16:04
But what is needed is to reduce the common tasks efforts. A collection has common function of filteration, like we fetch active records and the relations via clousure now i want to filter those activic records which have returned null for the relation attribute.

**Comment by samdark** [comment] 2016-08-24 16:22
@dhiman252 common function of filtration is provided via both standard PHP `array_filter()` and [`ArrayHelper::filter()`](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L810). The only difference is syntax:

```php
$posts = array_filter(Post::find()->all(), function($post) {
    return $post->relation === null;
});

// vs 

$posts = Post::find()->all()->filter(function($post) {
    return $post->relation === null;
});
```

Not a big difference. Also the task itself is better to be solved on query level. Retrieving more than needed and filtering afterwards on PHP side is inefficient both CPU and memory-wise.

**Comment by lubosdz** [comment] 2016-08-24 16:48
The functionality seems kind of specific and of rare use, though has attractive syntax. 
Frameworks generally should stick to simple & generic solutions. 
There are also unclear questions: *what's the memory & speed overhead ? *
Most of use cases above can be achieved with existing Yii objects, though sometimes in a clumsy way. 

What about adding an extra option/method `asObject(bool)` that would **return object list** rather than array (default)?

```
Post::find()->asObject()->all();
Post::find()->asArray()->all();

```

**Comment by samdark** [comment] 2016-08-24 17:03
You mean something like the following?

```php
$postsCollection = Post::find()->asCollection(PostCollection::class)->all();
```

**Comment by lubosdz** [comment] 2016-08-24 17:08
Well, yes, but is the argument `PostCollection::class` really necessary ?

**Comment by samdark** [comment] 2016-08-24 17:11
Which collection are you going to fill then?

**Comment by lubosdz** [comment] 2016-08-24 17:47
Post collection, of course. 
What I meant was, that the argument `PostCollection::class` should be optional - if at all actually exposed to a user. May be just adding method to AR model would suffice:

```
public static function collectionName()
{
    return "PostCollection";
}

public static function asCollection(self::collectionName)
{
    // convert array to object list & bound & invoke events/methods
}

```

**Comment by samdark** [comment] 2016-08-24 20:13
1. We don't want to change default behavior. Arrays are sufficient for majority of cases.
2. Generic collections doesn't make much sense except a bit nicer syntax.
3. Collections do make sense for interfaces and type hinting.

**Comment by samdark** [comment] 2016-08-24 20:55
Basic implementation is done. One can either use it with simple collections as in tests or pass something more advanced as a class such as Laravel collections.

**Comment by klimov-paul** [comment] 2016-08-25 09:37
> If you use the collection instead of an array, it is possible to implement the mechanism links are much more logical than done now. Instead of $object->link('string', $arrayOfObjects) we can use $object->relationName->link([$id1,$id2]). This is good becouse not use string constant. Of course this is only for linked relations

For me it is better to put `link()` into a `ActiveRelation` (`ActiveQuery`) method.
Syntax could be:

```php
$object->getRelationName()->link([$id1, $id2]);
```

I can't see how AR collection involved here.

> ActiveDataProvider - this is very good for return response but not good for use in code. That part of the functionality that exists in ActiveDataProvider also would not prevent. For example, for a particular copying objects when

I do not understand this part. Why do you need to copy AR objects? And how it relates to the AR collection?

> Without collections voplne can do, and solutions will be simple. But these solutions will need to compose himself. A collection will have a ready solution in the documentation. I'm here because I see the advantage. In own castom decision, no matter how simple it may be, still it needs more time.

I don't think the feature is general enough. Besides creating collection instance can be easily performed from the array of objects. Thus this feature can be composed into a separated extension outside the scope if 'yiisoft'. You could implemeted it already long ago.

**Comment by samdark** [comment] 2016-08-25 09:57
@klimov-paul top level collections are indeed easy to implement. Relations aren't that easy, as for me.

**Comment by klimov-paul** [comment] 2016-08-25 10:22
One more note about linking improvement: using collections may introduce you a better syntax for 'has-many' relations, but it will entrely unusable for 'has-one' relations.

**Comment by klimov-paul** [comment] 2016-08-25 10:25
See https://github.com/yiisoft/yii2/pull/12304#issuecomment-242339116

For me the nearest thing to 'AR collections' meant here is `yii\db\BatchQueryResult` and `yii\db\DataReader`. Interacting with this functionality is necessary for the AR collection.

**Comment by Razzwan** [comment] 2016-08-25 10:43
> For me it is better to put link() into a ActiveRelation (ActiveQuery) method.
Syntax could be:

~~~php
$object->relationName->link([$id1, $id2]);
~~~
Magic method `__get($relation)` returned a Collection object.

When I use Collection object in current project:
1. Link objects by ids `$object->relationName->link([$id1, $id2]);`
2. Synchronization objects by ids '$object->relationName->sync([$id1, $id3]);' This code delete $id2 relation and add $id3.
3. Named filtering data objects: `$object->relationName->finteringPublic()` - return only public data. `$object->relationName->filteringForUserPerm($userPerm)`
4. Mass saved/updated data `$object->relationName->save()` instead of 
~~~php
foreach ($object->relationName as $obj) {
    if (!$obj->validate()) {
        $object->addErrors('relationName', $obj->getErrors()); // this is simplified example
        if (!$obj->isNewRecord) {
            $obj->delete();
        }
    } else {
         $obj->save(false);   
    }
}
~~~
5. Mass load '$object->relationName->load(Yii::$app->getRequest()->getPost())' instead static method of ActiveRecord which less intuitive. 
6. Copy data from one object to other. `$nonPayedDataObject->relationName = $payedDataObject->relationName->filteringNonPayedData()`

**Comment by klimov-paul** [comment] 2016-08-25 10:46
> $object->relationName->link([$id1, $id2]);
Magic method __get($relation) returned a Collection object.

As I said at https://github.com/yiisoft/yii2/issues/10806#issuecomment-242342046 , it will work for 'has-many' relation, but any attempt to use such syntax against 'has-one' relation will cause PHP fatal error:

```php
$post->comments->link([$id1, $id2]); // will work
$post->owner->link($userId); // PHP fatal error:: call to undefined method `link()` of `ActiveRecord`
```

**Comment by klimov-paul** [comment] 2016-08-25 10:48
> Copy data from one object to other. $nonPayedDataObject->relationName = $payedDataObject->relationName->filteringNonPayedData()

There was a conscious decision agains direct assignment of the relations via magic setters.
You can use `populateRelation()` for this purpose:

```php
$nonPayedDataObject->populateRelation('relationName', array_filter($payedDataObject->relationName, fucntion() {...});
```

**Comment by Razzwan** [comment] 2016-08-25 10:49
@klimov-paul What prevents to fix it? I agree that it must be fixed too.

**Comment by klimov-paul** [comment] 2016-08-25 10:52
> 4. Mass saved/updated data $object->relationName->save() instead of

A horrible example: you propose to delete the records and insert the same one overa again.
The reason why there is `sync` fucntionality provide in the core - is it is not trivial: sometimes you need the algorithm you provided and sometimes - another one like: https://github.com/yii2tech/ar-linkmany/blob/master/LinkManyBehavior.php#L235

**Comment by klimov-paul** [comment] 2016-08-25 10:52
> What prevents to fix it? I agree that it must be fixed too.

Fix what?

**Comment by Razzwan** [comment] 2016-08-25 10:53
@klimov-paul 
> There was a conscious decision agains direct assignment of the relations via magic setters.
You can use populateRelation() for this purpose:
`$nonPayedDataObject->populateRelation('relationName', array_filter($payedDataObject->relationName, fucntion() {...});`

Do you really believe that it's as simple as my example? You do not mind the presence of stringovoy konstynty in the code, which in the case of changing the name of connection stops working?

**Comment by klimov-paul** [comment] 2016-08-25 10:55
> 3. Named filtering data objects: $object->relationName->finteringPublic() - return only public data. $object->relationName->filteringForUserPerm($userPerm)

Navigation-type data processing is not the common for the remote databases. Introduction of it will encourage bad practice of selecting the entire list of records in the memory and processing them afterwards instead of use SQL filtering.

**Comment by Razzwan** [comment] 2016-08-25 10:58
@klimov-paul 
> Navigation-type data processing is not the common for the remote databases. Introduction of it will encourage bad practice of selecting the entire list of records in the memory and processing them afterwards instead of use SQL filtering.

And who said that data filtering will not take place at the database level? Collection - class for work with data base.

**Comment by klimov-paul** [comment] 2016-08-25 10:58
> the presence of stringovoy konstynty in the code

String constants are use wide eough around the Yii. I can't see a crucial problem here. There are many examples which may cause just the same kind of trouble.

Besides as I already said here: https://github.com/yiisoft/yii2/issues/10806#issuecomment-242331322
We can improve `ActiveRelation` (`ActiveQuery`) to remove this problem:

```
$object->getRelationName()->populate([...]);
```

**Comment by klimov-paul** [comment] 2016-08-25 11:02
> And who said that data filtering will not take place at the database level? Collection - class for work with data base.

So what is wrong to create a separated `ActiveQuery` in the related AR class and introduce an internal method inside for the same purpose:

```php
class RelationNameQuery extends \yii\db\ActiveQuery
{
    public function finteringPublic()
    {
        return $this->andWherePublic()->all();
    }
    ...
}
```

And what is wrong of general code:

```php
$filteredRelatedData = $object->getRelationName()->andWhereActive()->all();
```

for the same purpose?

**Comment by klimov-paul** [comment] 2016-08-25 11:09
Over this entire discussion I can't find any example, which indicates the feature is necessary or at least general.
All arguments provided relate to minor improvements and creating of the 'pretty' code for the rare use cases.

Note: Yii follows the pronciple 'simplicity over complexity', that is why Yii ActiveRecord is relatively simple. It can not compete with Doctrine and other major Database AR layer, lacking many features - this is by design. It is done in this way in order to keep it simple and roboost.

That is why I am against of introduction of such functionality in the Yii core.
However as I said in the my initial comment: https://github.com/yiisoft/yii2/issues/10806#issuecomment-242331322 , you can create your own extension, which will provide this functionality for you, if you need it so badly.

**Comment by samdark** [comment] 2016-08-25 11:25
@klimov-paul your suggestions about improving `ActiveQuery` are very interesting.

**Comment by klimov-paul** [comment] 2016-08-25 11:27
> your suggestions about improving ActiveQuery are very interesting.

Personally I do not consider usage of the string constants to be an issue - it is @Razzwan's concern.
Still this matter should be discussed at separated issue.

**Comment by samdark** [comment] 2016-08-25 11:39
Closing the issue. Decision is not to create collections from ARs. It's not final so if you have strong arguments for returning collections from ARs, post these please.

For standalone collections, either [implement your own](https://github.com/samdark/yii2-cookbook/blob/master/book/structure-collections.md) or use any existing implementation such as Laravel's.

**Closed by samdark** 2016-08-25 11:39 UTC
Labels: status:under discussion, type:enhancement

**Comment by juanmacias** [comment] 2016-08-29 17:21
Although is closed, here is a real example.

This is a Kanban view. 
There is two approach of doing this:
1. Call find() for each column. In this cases 5 times.
2. Call find() one, get all rows and filter in memory.

Also, I have to get a sum for each column.

What I have now is:
    $opCol=new ActiveCollection(Opportunities::find()->somefilter()->all();
    $total=$opCol->sum('annual_contract_value'); 
    $column_rows=filter(["status_id"=>$status->id]);

I've more elaborated functions like filters by json values inside attributes.

But... there is a third solution in the AR, something like:

Opportunities::find()->transformby("status_id")->all();
will return an array of arrays with a key for each status_id.


![screen shot 2016-08-29 at 19 13 42](https://cloud.githubusercontent.com/assets/4797797/18060132/eb7e72b0-6e1c-11e6-9183-6a79b84dae0e.png)

**Comment by klimov-paul** [comment] 2016-08-29 18:31
Same as here: https://github.com/yiisoft/yii2/issues/10806#issuecomment-242350062

Why do not introduce a special method inside `ActiveQuery` for your goal?

```php
class OpportunityQuery extends \yii\db\ActiveQuery
{
    public function transformby($field)
    {
        $rows = $this->indexBy($field)->all();
        $result = [];
        foreach ($rows as $row) {
            //...
        }
        return $result;
    }
    ...
}
```

**Comment by juanmacias** [comment] 2016-08-29 18:48
Good idea!

**Comment by cebe** [comment] 2017-07-10 13:19
see https://github.com/yiisoft/yii2-model-collection/issues/6
