### ISSUE TITLE
http caching always return  status 200

### ISSUE THREAD

**Issue by abdil1234** [yiisoft/yii2#18371] opened 2020-11-09 08:52 UTC
<h3>What steps will reproduce the problem?</h3>
use http cache etag 

```php
[
                'class' => 'yii\filters\HttpCache',
                'only' => ['show', 'pdf', 'show-video', 'show-doc'],
                'etagSeed' => function ($action, $params) {
                    $file = UploadedFile::findOne(['id' => \Yii::$app->request->get('id')]);
                    if($file){
                        return serialize([$file->id, $file->created_at]);
                    }
                },
                'sessionCacheLimiter' => 'public',
            ],

```
<h3>What's expected?</h3>
Next request should cache return http status 304(not modified)

<h3>What do you get instead?</h3>

![Screen Shot 2020-11-09 at 15 49 55](https://user-images.githubusercontent.com/31970269/98519409-4fdf9b00-22a3-11eb-8935-8bba32bd2a12.png)

return http status 200 each request

<h3>Additional info</h3>
<table role="table">
<thead>
<tr>
<th>Q</th>
<th>A</th>
</tr>
</thead>
<tbody>
<tr>
<td>Yii version</td>
<td>2.0.38</td>
</tr>
<tr>
<td>PHP version</td>
<td>7.3</td>
</tr>
<tr>
<td>Web Server</td>
<td> Apche 2.4.6 http 1.1</td>
</tr>
<tr>
<td>Operating system</td>
<td>Centos 7</td>
</tr>
</tbody>
</table>

**Comment by samdark** [comment] 2020-11-09 10:56
What's the full URL you're requesting with?

**Comment by abdil1234** [comment] 2020-11-09 11:00
http://cms.test/files/show?id=584

**Comment by abdil1234** [comment] 2020-11-09 11:05
> What's the full URL you're requesting with?
http://cms.test/files/show?id=584

**Comment by abdil1234** [comment] 2020-11-09 11:05
> What's the full URL you're requesting with?


http://cms.test/files/show?id=584

**Comment by samdark** [comment] 2020-11-09 11:11
I don't see ETag in the response.

**Comment by bizley** [comment] 2020-11-09 11:12
I don't see `Etag` in your response headers. Is it possible that your `etagSeed` function does not return anything?

**Comment by abdil1234** [comment] 2020-11-10 03:36
yes i didn't see etgag response in header.
this return value of my etagseed function
```php
a:2:{i:0;i:584;i:1;i:1604648448;}
```

**Comment by abdil1234** [comment] 2020-11-10 03:59
but its work fine in my another server centos8 (apache/2.4.37 http2)


![Screen Shot 2020-11-10 at 10 53 29](https://user-images.githubusercontent.com/31970269/98626185-b3210a00-2343-11eb-9363-a5111259a407.png)

**Comment by abdil1234** [comment] 2020-11-10 06:54
after investigate , it looks like that header never send after set 
```php
 $response->getHeaders()->set('Etag', $etag);
```

 at yii\filters\HttpCache line 141 (beforeAction).
when i add 
```php
$response->send();
```

its work , i dont know this is a solution for that problem ( sorry for bad english)

<img width="800" alt="Screen Shot 2020-11-10 at 13 51 09" src="https://user-images.githubusercontent.com/31970269/98638097-07d07f00-235c-11eb-8b9a-7313003eda66.png">

**Comment by bizley** [comment] 2020-11-10 09:06
Are you using `return` or `echo` in your controller for output?

**Comment by abdil1234** [comment] 2020-11-10 09:23
<code>echo</code> just for debug purpose that make sure etagSeed have a value

**Comment by bizley** [comment] 2020-11-10 10:08
Check few things:
1. If your controller properly `return`s the result.
2. If `$cacheValid` is `true` (see code you pasted earlier).
3. If it's `false` - if there are headers `If-None-Match` and/or `If-Modified-Since` (see `validateCache()` method in the same part of the code).

**Comment by samdark** [comment] 2020-11-10 10:12
`echo` automatically makes PHP to send headers. After that, no more headers could be sent including ETag.

**Comment by abdil1234** [comment] 2020-11-10 10:47
i recently test on my localhost `http://cms.test/files/show?id=585`

![Screen Shot 2020-11-10 at 17 45 29](https://user-images.githubusercontent.com/31970269/98664148-905f1780-237c-11eb-862f-352671f5cdc1.png)


> 1. If your controller properly `return`s the result.

```php
            [
                'class' => 'yii\filters\HttpCache',
                'only' => ['show', 'pdf', 'show-video', 'show-doc'],
                'etagSeed' => function ($action, $params) {
                    $file = UploadedFile::findOne(['id' => \Yii::$app->request->get('id')]);
                    return serialize([$file->id, $file->created_at]);
                    
                },
                'sessionCacheLimiter' => 'public',
            ],
```
yes my controller return value such as `id:585`, `created_at : 1605003958`

> 2\. If `$cacheValid` is `true` (see code you pasted earlier).

`$cacheValid` always return false


> 3\. If it's `false` - if there are headers `If-None-Match` and/or `If-Modified-Since` (see `validateCache()` method in the same part of the code).

there neither headers `If-None-Match` or `If-Modified-Since`

**Comment by bizley** [comment] 2020-11-10 11:01
`$cacheValid` must be `true` to result in 304. In order for this to be `true` one of the mentioned headers must at least be present.

**Comment by samdark** [comment] 2020-11-10 11:03
Closing since it's more of a usage issue than a framework issue.

**Closed by samdark** 2020-11-10 11:03 UTC
Labels: status:need more info

**Comment by abdil1234** [comment] 2020-11-10 11:10
but after  add
> 
``` php
        if ($cacheValid) {
            $response->setStatusCode(304);
            return false;
        }
        
        $response->send(); //this line

        return true;
 ```

 its work , i see `ETag` in response headers

### Request Header
```json
GET /files/show?id=585 HTTP/1.1
Host: cms.test
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: _identity-backend=62f1151a76ffeac56c607c5a0ed1d6f1f82fae8b83a3e7b521565a00c630af40a%3A2%3A%7Bi%3A0%3Bs%3A17%3A%22_identity-backend%22%3Bi%3A1%3Bs%3A57%3A%22%5B%221603348142%22%2C%22TgA81wATa3yuywrEw3d9rmZbbBKRnvwB%22%2C2592000%5D%22%3B%7D; advanced-session=5svm2lbok46mq95qpeapahvle8; _csrf-frontend=2dc37109a5e2a277cc330071df28314c3a35b90cfe46245c7a66c929dfedd745a%3A2%3A%7Bi%3A0%3Bs%3A14%3A%22_csrf-frontend%22%3Bi%3A1%3Bs%3A32%3A%22-822aF-HanzpK5g0bgOjwOuPMKaRgmXJ%22%3B%7D; _csrf-user=339cf82a3c8b53998291cd51468ab9252137a63071ebf6a9387e6ea3ce65a45aa%3A2%3A%7Bi%3A0%3Bs%3A10%3A%22_csrf-user%22%3Bi%3A1%3Bs%3A32%3A%22oeyOB-le2erTx-RtG6ukNSeU3mrmbgPd%22%3B%7D; _csrf-exam=546c3956310e6ca7150b74c9a692ff2c56d9817682eb8bc0514034e1f938ac0ba%3A2%3A%7Bi%3A0%3Bs%3A10%3A%22_csrf-exam%22%3Bi%3A1%3Bs%3A32%3A%22I91xqPSt36k5DZChNoXMsOdVAzrr844i%22%3B%7D; _csrf-backend=2acc277798e65493167aa675a29aab52be0b4b5078af19c85324be51dd5858b8a%3A2%3A%7Bi%3A0%3Bs%3A13%3A%22_csrf-backend%22%3Bi%3A1%3Bs%3A32%3A%22Ca08kFbiJvmsxw-UWLS_uuGO8gDfMJeV%22%3B%7D; _csrf-pos=b1e2539af89b25a5c65719b7ed9ca07648f08735d8a03a90793f900677172f98a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_csrf-pos%22%3Bi%3A1%3Bs%3A32%3A%222JJNNMpsIcuTF-eWX1UeyKRuJZKVIHPp%22%3B%7D
If-None-Match: "n2Svst1V7r7cjSGPzSpL2gtO74o"
If-Modified-Since: Wed, 10 Jun 2020 03:56:43 GMT

```

### Response Header

```json
HTTP/1.1 200 OK
Date: Tue, 10 Nov 2020 10:59:59 GMT
Server: Apache/2.4.46 (Unix) PHP/7.3.23
Expires: Tue, 10 Nov 2020 13:59:59 GMT
Cache-Control: public, max-age=3600
Set-Cookie: advanced-session=5svm2lbok46mq95qpeapahvle8; path=/; HttpOnly
Set-Cookie: _identity-backend=62f1151a76ffeac56c607c5a0ed1d6f1f82fae8b83a3e7b521565a00c630af40a%3A2%3A%7Bi%3A0%3Bs%3A17%3A%22_identity-backend%22%3Bi%3A1%3Bs%3A57%3A%22%5B%221603348142%22%2C%22TgA81wATa3yuywrEw3d9rmZbbBKRnvwB%22%2C2592000%5D%22%3B%7D; expires=Thu, 10-Dec-2020 10:59:59 GMT; Max-Age=2592000; path=/; HttpOnly
X-Powered-By: PHP/7.3.23
Pragma: no-cache
Last-Modified: Wed, 10 Jun 2020 03:56:43 GMT
Etag: "n2Svst1V7r7cjSGPzSpL2gtO74o"
X-Debug-Tag: 5faa7213658ba
X-Debug-Duration: 47
X-Debug-Link: /debug/default/view?tag=5faa7213658ba
Content-Length: 4688
Content-Type: image/jpg


```

**Comment by bizley** [comment] 2020-11-10 11:49
It still 200, not 304.

**Comment by abdil1234** [comment] 2020-11-10 12:37
> It still 200, not 304

Can you please test in your localhost?, is there your response headers contain `ETag`?

**Comment by bizley** [comment] 2020-11-10 12:46
I cannot reproduce your case. I told you what might be a reason based on the code flow. I have found this [issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=45023) - maybe this is the reason.

**Comment by abdil1234** [comment] 2020-11-10 13:09
> I cannot reproduce your case. I told you what might be a reason based on the code flow. I have found this [issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=45023) - maybe this is the reason.

Will check, thank you
