### ISSUE TITLE
Using join with ActiveQuery causes quoting of the second column in ON condition

### ISSUE THREAD

**Issue by arogachev** [yiisoft/yii2#9293] opened 2015-08-03 10:30 UTC
Example:

```php
$query->leftJoin(
    'procedural_tasks_bases_positions',
    ['procedural_tasks.base_id' => 'procedural_tasks_bases_positions.base_id']
);
```
Generated SQL:

```sql
ON "procedural_tasks"."base_id"='procedural_tasks_bases_positions.base_id'
```
Why this `'procedural_tasks_bases_positions.base_id'` is quoted? It shouldn't be like so.

As the result I have the error:

```
ERROR: invalid input syntax for integer: "procedural_tasks_bases_positions.base_id"
```

**Comment by arogachev** [comment] 2015-08-03 10:35
As a workaround we can wrap right part with `yii\db\Expression` or write it as string, but array is more readable and cleaner IMO.

**Comment by SDKiller** [comment] 2015-08-03 11:18
Can confirm, always had to do something like
`$query->leftJoin(['r' => $subquery], ['r.id' => new Expression('[[b]].[[id]]')]);`

**Comment by cebe** [comment] 2015-08-03 14:57
why do you think that this array syntax should work? the documentation states that it is the same syntax as used in WHERE where you have `column => value` relation and not `column => column`...?
If you want to have a column to column comparison, you have to use a simple string.

**Comment by cebe** [comment] 2015-08-03 15:00
this is a duplicate of #7549 btw

**Closed by cebe** 2015-08-03 15:00 UTC
Labels: feature:db, type:docs

**Comment by arogachev** [comment] 2015-08-04 05:17
It's weird. Why not to use array syntax as an alternative as it's done in where condition, etc.?

**Comment by arogachev** [comment] 2015-08-04 06:32
And most of the times with join we need `column => column` association, not `column => value`.

**Comment by cebe** [comment] 2015-08-04 09:17
how would you decide whether `'somestring' => 'somestring'` is column => column or column => value?

**Comment by unclead** [comment] 2015-08-04 11:40
@cebe i've never seen sql where `column => value` condition has been used in `ON`. Have you?
I agree with @arogachev in this case.
Can you give more detailed explanation?

**Comment by cebe** [comment] 2015-08-04 11:45
this is quite common:

```sql
JOIN sometable s ON s.type = 'whatever' AND s.id = otherid
```

**Comment by unclead** [comment] 2015-08-04 11:51
ohhh, sorry, you're right :smile:
