### ISSUE TITLE
widget's CSS is not inserted with pjax

### ISSUE THREAD

**Issue by hastalavista-baby** [yiisoft/yii2#13155] opened 2016-12-07 15:17 UTC
When I use Pjax, widget's CSS is not inserted in the page

registerCssFile

//page1.php
```php
<?php Pjax::begin(['timeout' => 5000]); ?>
       <a href="/page2.php">Page 2</a>
<?php Pjax::end(); ?>
```

//page2.php
```php
<?php Pjax::begin(['timeout' => 5000]); ?>
       <?php echo MyWidget::widget(); ?>

       <a href="/page1.php">Page 1</a>
<?php Pjax::end(); ?>
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.1
| Operating system | Windows

**Comment by dynasource** [comment] 2016-12-07 15:27
this is expected behavior as the Pjax widget exits directly after execution durign the ajax call. If you want to have the CSS inserted, you have to output it directly between the opening and closing tag of the Pjax widget (and not use registerCssFile).

**Closed by dynasource** 2016-12-07 15:27 UTC
Labels: feature:pjax

**Comment by hastalavista-baby** [comment] 2016-12-07 15:32
how do it?
so that my widget with pjax is not working. right?

**Comment by dynasource** [comment] 2016-12-07 15:34
echo your CSS between the `Pjax::begin` and  `Pjax::end`

**Comment by hastalavista-baby** [comment] 2016-12-07 15:37
this is not correct. 
and if a lot of widgets. all styles write?
why registerJsFile working fine with pjax?

**Comment by dynasource** [comment] 2016-12-07 15:59
the current Pjax widget only supports endPage scripts, as can be seen at https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L148

CSS is not loaded, I guess because it could change the pages representation

**Comment by hastalavista-baby** [comment] 2016-12-07 16:06
why I think it's a bug

**Comment by dynasource** [comment] 2016-12-07 16:24
the Pjax widget in Yii is to be used for pjax widgets which are already loaded in the current page. For this usecase, the CSS would also already have been loaded. 

If you are using Pjax for more complex scenario's with many more Pjax widgets, please understand that this not what Pjax is created for. A lot on this subject has already been said in this issue tracker and the Pjax issue tracker. Please do some searches to find more information.

**Comment by hastalavista-baby** [comment] 2016-12-08 13:09
Thanks

**Comment by derekisbusy** [comment] 2017-02-09 07:41
@dynasource the pjax widget does include the head...

https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L126

I added a fix for the stylesheets issue.

yiisoft/jquery-pjax/pull/49

@hastalavista-baby You need to add an id to the Pjax widget options and make sure they are the same on both pages..

```php
<?php Pjax::begin(['id' => 'main-container', 'timeout' => 5000]); ?>
       <a href="/page2.php">Page 2</a>
<?php Pjax::end(); ?>
```

And use same ID in second page:

<?php Pjax::begin(['id' => 'main-container', 'timeout' => 5000]); ?>
       <?php echo MyWidget::widget(); ?>

       <a href="/page1.php">Page 1</a>
<?php Pjax::end(); ?>
