### ISSUE TITLE
appendTimestamp of assetManager does not work in 2.0.39

### ISSUE THREAD

**Issue by wenjiehu** [yiisoft/yii2#18402] opened 2020-11-22 00:47 UTC
### What steps will reproduce the problem?

1. create a project from basic template;
2. add 
`        'assetManager' => [
            'appendTimestamp' => true,
        ],` to config/web.php

### What is the expected result?
There should be a "v=........."behind href="/basic/web/css/site.css"
### What do you get instead?
no "v=..." append  to the .css or .js

### Additional info
On Yii 2.0.38, this issue can not be reproduced.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.2
| PHP version      | 7.4.10
| Operating system | Windows 10

**Comment by bizley** [comment] 2020-11-22 10:42
@Baleen-Y could you take a look at this?

**Comment by Baleen-Y** [comment] 2020-11-24 01:40
@wenjiehu  
I followed your process and did not reproduce the same version and environment. 
Is it convenient to create a demo?

**Comment by alex-code** [comment] 2020-11-24 08:39
How are you adding the CSS file to the page?

**Comment by wenjiehu** [comment] 2020-11-25 10:33
@Baleen-Y Sorry, I don't have a host now. But I attached 2 images here. At the bottom of each images, you can see the difference of the site.css link, and you can also see the corresponding Yii versions in these images.
<img width="401" alt="yii2 0 38" src="https://user-images.githubusercontent.com/1329378/100215262-bf17e900-2f4b-11eb-9423-aec21c96de73.png">
<img width="357" alt="yii2 0 39 2" src="https://user-images.githubusercontent.com/1329378/100215278-c3dc9d00-2f4b-11eb-9b2c-936398f472d4.png">

**Comment by wenjiehu** [comment] 2020-11-25 10:39
and here are my config files:
[config.zip](https://github.com/yiisoft/yii2/files/5596141/config.zip)

**Comment by Baleen-Y** [comment] 2020-11-26 08:52
> and here are my config files:
> [config.zip](https://github.com/yiisoft/yii2/files/5596141/config.zip)

Sorry, it is normal to use your configuration
![](https://s3.ax1x.com/2020/11/26/D0sw0P.png)

**Comment by samdark** [comment] 2020-11-26 09:13
Closing since we can't reproduce it. @Baleen-Y thanks for trying it out.

**Closed by samdark** 2020-11-26 09:13 UTC
Labels: status:to be verified, type:bug
