### ISSUE TITLE
Yii debug path incorrectly being set causing invalidParamException

### ISSUE THREAD

**Issue by cyphix333** [yiisoft/yii2#11411] opened 2016-04-23 13:56 UTC
I have Yii2 running fine locally but then when I uploaded everything to a staging server I got the below error:

> The file or directory to be published does not exist:/home/example_site/public_html/common/vendor/yiisoft/**yii2/debug**/assets

This path that is getting set is incorrect, it should be:

> /home/majesticstaging/public_html/common/vendor/yiisoft/**yii2-debug**/assets

...which is how it is set on my local server.

I am not sure why the hyphen is getting replaced with a forward slash - they are the same files. I even deleted everything in the vendor directory and ran composer on the server but no change.

### What steps will reproduce the problem?

Loading any page.

### What is the expected result?

Page loads application.

### What do you get instead?

InvalidParamException and error message as above.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 5.4.38
| Operating system | CENTOS 6.7

**Comment by cyphix333** [comment] 2016-04-23 16:38
Ok fixed.

I ran:

`php composer.phar global require "fxp/composer-asset-plugin:~1.1.3"`

Then after running that ran:

`php composer.phar update`

...but was getting issues like I didn't have the `composer-asset-plugin` plugin.

So then I deleted everything inside of `vendor` and reran:

 `php composer.phar global require "fxp/composer-asset-plugin:~1.1.3"`

...and then ran:

`php composer.phar install` (this may have been ran _before_ the above command and not _after_, not 100% sure.

...and then lastly ran:

`php composer.phar update`.

**Comment by cyphix333** [comment] 2016-04-23 16:43
Ok, scratch that; not quite fixed. Now I am getting:

> The file or directory to be published does not exist: common\vendor/bower/bootstrap/dist

Reason I didn't notice at first is because the latest version of Yii kinda _hides_ this error within the debug bar and so you don't know right away without opening the error.

**Comment by cyphix333** [comment] 2016-04-23 16:58
Ok, another update....... the error mentioned above doesn't show as an error in the debug bar, that wasn't caused by something else; however the error I am seeing above shows when I open up the debug bar, so it is trying to load the debug info in the debug bar window when you expand it and then it shows that error.

**Comment by samdark** [comment] 2016-04-23 18:59
Closing since it's not clear what is the issue and how to reproduce it.

**Closed by samdark** 2016-04-23 18:59 UTC
