### ISSUE TITLE
FilterValidator | trim doesn't work on client side

### ISSUE THREAD

**Issue by ageeweb** [yiisoft/yii2#8882] opened 2015-06-24 06:35 UTC
see also : #7361

if you check email with :

```php
return [
  // ...
  ['email', 'trim'],
  ['email', 'required'],
  ['email', 'email'],
  // ...
];
```

on mobile (android and iphone) when you start typing email you can auto fill your email address, but it adds a space to type second word. that space gives an error that email is not valid. (you can simulate this to type email, and add a space) for the email check it will not trim first. After enter you can not see the space, (Trim is working) but for the check its not gone? if you check te value in javascript trace, you can see there is a space, that you cannot remove (its not in your fill in box).

test this and you see what I mean:
"fill in email address and add a space and then enter"

**Comment by nkovacs** [comment] 2015-07-08 13:10
Looks like a duplicate of #7707
@ageeweb could you check with master please?

**Comment by ageeweb** [comment] 2015-07-09 06:26
looks the same

**Comment by nkovacs** [comment] 2015-07-09 07:15
Are you sure? I just checked on Android: google keyboard doesn't insert a space after auto-completing a word (I may have turned it off, but I can't find the setting if there is one), samsung keyboard does, but the trim works. This is exactly the bug that I fixed in #8403.

**Comment by ageeweb** [comment] 2015-07-09 07:28
I mean issue #7707 looks exact like my problem, and I see its for next release solved

**Comment by SilverFire** [comment] 2015-12-27 07:55
Failed to reproduce on latest dev version using the following envs:

 - Android 4.4 Chrome
 - iOS 9.2 Safari
 - iOS 9.2 Chrome

**Closed by SilverFire** 2015-12-27 07:55 UTC
Labels: status:to be verified
