### ISSUE TITLE
Breadcrumbs don't find message category 'yii'.

### ISSUE THREAD

**Issue by twinni** [yiisoft/yii2#8131] opened 2015-04-19 17:39 UTC
After changing the sourceLanguage and rendering a view the message file for category 'yii'  is not found. The log has following entry:
```
yii\i18n\PhpMessageSource::loadMessages
```
```
The message file for category 'yii' does not exist: D:\WebRoot\adv\vendor\yiisoft\yii2/messages/en-En/yii.php Fallback file does not exist as well: D:\WebRoot\adv\vendor\yiisoft\yii2/messages/en/yii.php
```
Example view:
```php
<?php
$this->params['breadcrumbs'][] = 'Can not find message file';

$oldSourceLanguage = Yii::$app->sourceLanguage;
echo  '<br>Yii::$app->sourceLanguage: ' . Yii::$app->sourceLanguage;  // en-US

Yii::$app->sourceLanguage = 'de-DE';
 
$languages = [
    'it-IT',
    'it',
    'de-DE',
    'de',
    'en-US',
    'en-EN'     // only this one makes trouble 
];

foreach ($languages as $lang) {
    Yii::$app->language = $lang;
    echo '<br>' . Yii::$app->language . ' = ' . Yii::t('app', 'Test');
}
// Yii::$app->language = $oldSourceLanguage;
?>
```

There are two things of special interest:
1) The problem occurs only when ```Yii::$app->language``` is set to 'en-EN'. All other languages are ok.
2) The problem doesn't occur when the default ```Yii::$app->language``` is set back before the main.php layout file is rendered. That's strange as I wouldn't expect breadcrumbs acessing message files.

**Comment by cebe** [comment] 2015-04-19 17:48
duplicate of #7964

**Closed by cebe** 2015-04-19 17:48 UTC
