### ISSUE TITLE
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by EbrahimPYK** [yiisoft/yii2#17543] opened 2019-09-05 06:19 UTC
Hi,
i have this error in run **composer update** command in all projects ,recently .
**Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.**

how to resolve this problem?

**Comment by demonking** [comment] 2019-09-05 07:15
![github](https://user-images.githubusercontent.com/1106771/64319139-f0f60600-cfbb-11e9-91d3-c3ee2e331149.png)


> The color coding is as such:
> 
>     green (=): Dependency is in the latest version and is up to date.
>     yellow (~): Dependency has a new version available that includes backwards compatibility breaks according to semver, so upgrade when you can but it may involve work.
>     red (!): Dependency has a new version that is semver-compatible and you should upgrade it.
>

**Comment by EbrahimPYK** [comment] 2019-09-05 07:20
> ![github](https://user-images.githubusercontent.com/1106771/64319139-f0f60600-cfbb-11e9-91d3-c3ee2e331149.png)
> 
> > The color coding is as such:
> > ```
> > green (=): Dependency is in the latest version and is up to date.
> > yellow (~): Dependency has a new version available that includes backwards compatibility breaks according to semver, so upgrade when you can but it may involve work.
> > red (!): Dependency has a new version that is semver-compatible and you should upgrade it.
> > ```

thank's for your descriptions.
but , i don't understand how to resolve my problem .
how to update composer that don't have any error

**Comment by rob006** [comment] 2019-09-05 08:00
Duplicate of https://github.com/yiisoft/yii2-app-basic/issues/210

**Closed by rob006** 2019-09-05 08:00 UTC
