### ISSUE TITLE
Caching TagDependency TTL

### ISSUE THREAD

**Issue by YellowPony** [yiisoft/yii2#17119] opened 2019-02-09 12:33 UTC
Hello, TagDependency never expires and if default cache duration is set, tag can be deleted earlier than cached entry. I think simplest way to fix this is to add $duration property to TagDependency.

```diff
diff --git a/framework/caching/TagDependency.php b/framework/caching/TagDependency.php
index 9e484e9dd..53b621f0a 100644
--- a/framework/caching/TagDependency.php
+++ b/framework/caching/TagDependency.php
@@ -33,6 +33,11 @@ class TagDependency extends Dependency
      */
     public $tags = [];

+    /**
+     * @var int $duration default duration in seconds before the tag will expire.
+     */
+    public $duration;
+

     /**
      * Generates the data needed to determine if dependency has been changed.
@@ -93,7 +98,7 @@ class TagDependency extends Dependency
         foreach ($keys as $key) {
             $items[$key] = $time;
         }
-        $cache->multiSet($items);
+        $cache->multiSet($items, $this->duration);
         return $items;
     }
```

**Comment by samdark** [comment] 2019-03-21 09:19
@yiisoft/reviewers would you please take a look at this one?

**Comment by schmunk42** [comment] 2019-03-21 12:20
Should tag *dependencies* be able to expire?

**Comment by samdark** [comment] 2019-03-21 12:43
No. It's not the job of the dependency.

**Comment by samdark** [comment] 2019-03-21 12:44
Thanks for the right question, @schmunk42. @YellowPony won't be changed since it is like it is by design.

**Comment by YellowPony** [comment] 2019-03-26 18:12
@schmunk42 why not? It is a cache entry, and it's life must be no longer than its related data (if supported by backend). Otherwise we need to build other system to track expired tags to flush them, if we want to keep our cache optimized ofc.

**Comment by schmunk42** [comment] 2019-03-27 12:19
But tags itself can not expire, AFAIK they are not cache entries, it's rather a group or selector with which you can invalidate.

See https://www.yiiframework.com/doc/api/2.0/yii-caching-tagdependency - you can invalidate all cache entries with `user-123` but not `user-123` itself. Please correct me if I am wrong.

**Comment by YellowPony** [comment] 2019-03-27 19:21
Hm..

> and it's life must be no longer than its related data
> But tags itself can not expire

I think we are partially wrong, this expiration can be developer's choice. 
Like all items that stored in cache (whatever it is, but they are store in cache backend and use Cache component) can/must/should have TTL (unlimited or not). Currently we can't set it. May be we can class it like enhancement?

`$tag = new TagDependency([
     'duration' => 100, // by default unlimited
     'tags' => ['a', 'b', 'c'],
]);`

Offtopic:
As i write in first message 
>   if default cache duration is set, tag can be deleted earlier than cached entry. 

This statements is wrong. I check it, look into code, and found that $defaultDuration affects only single set method (found it later in property details).

**Comment by schmunk42** [comment] 2019-03-27 21:08
> There are many cases when orphan tags stay in cache.

Are tags itself really in the cache?

Can you provide a test case which fails in the current setup?

**Comment by YellowPony** [comment] 2019-03-27 22:06
```
<?php

namespace app\commands;

use yii\caching\TagDependency;

class TestController extends \yii\console\Controller
{
    public function actionIndex()
    {
        $cache = \Yii::$app->cache; // \yii\redis\Cache

        $tag = new TagDependency([
            'tags' => ['A_' . rand(1, 10)],
        ]);

        $key = 'test';
        $data = $cache->get($key);
        if ($data === false) {
            $cache->set($key, ['test_data'], 10, $tag);
        }
    }
}
```
![image](https://user-images.githubusercontent.com/30048252/55114259-21bb4080-50ea-11e9-8f5e-e0b72e77c678.png)
Record with key "0d4d0a98d6fded2013b1b5773556c29e" is "tag data" and its never expires.

I stop to use tags A_* by any reason, but "tag data" stay in cache untill redis flush.

**Comment by samdark** [comment] 2019-03-28 08:49
> Are tags itself really in the cache?

Yes, tags are there without expiration. And that's for a reason you cannot rely on native TTL:

1. You set a cache key `A` with tag `tag1` and TTL till 30.03.2019.
2. You set a cache key `B` with tag `tag1` and TTL till 29.03.2019.
3. You set a cache key `C` with tag `tag1` and TTL till 28.03.2019.

Above you can do in totally separate processes so if you just set a TTL for `tag1` to one of the values (except by accident it's value from `1.`), tag will be invalidated before its associated items are.

**Comment by shushenghong** [comment] 2020-01-08 12:17
hope this will be fixed, since tags cache will continuously generate, these will exhaust the cache space, see #17784 . 
Or can we add a max_tags property, after max_tags reached, the oldest tags will be deleted.

**Comment by samdark** [comment] 2020-01-09 10:38
Thought more about it. The problem of cache space pollution is a real one so yes, an option is needed.

**Comment by samdark** [comment] 2020-01-09 13:46
@YellowPony, applying diff as in original post won't work because `touchKeys` is static.

**Comment by samdark** [comment] 2020-01-09 13:51
@shushenghong there's no guarantee that oldest tags aren't valid.

**Comment by samdark** [comment] 2020-01-09 13:52
Please share ideas on how to fix it in a reliable way.

**Comment by My6UoT9** [comment] 2020-01-09 16:29
When the same tag gets cached again, would it be possible to update all references with the "highest" expiration?

**Comment by samdark** [comment] 2020-01-09 16:34
What's the "highest" expiration?

**Comment by shushenghong** [comment] 2020-01-10 01:40
I would suggest add a maxDependencyTags to Cache component, and use LRU algorithm to invalid tags cache.
```php
abstract class Cache extends Component implements CacheInterface {
   /**
     * @var int max tag dependency tags num. After maximum tags reached, invalid tags cache with LRU algorithm. Default value is 0, meaning infinity.
     */ 
    public $maxDependencyTags = 0;
```

**Comment by My6UoT9** [comment] 2020-01-10 07:48
> What's the "highest" expiration?
I mean the  expiration time which is furthest in future, e.g. the maximum.

I have no idea if its possible, is just an idea.

**Comment by samdark** [comment] 2020-01-10 08:05
@My6UoT9 +1 year or so? That won't be different in result. Cache would be polluted with tag data.

@shushenghong that doesn't sound right design-wise. Tags is just one of the dependencies and Cache knowing about it creates another dependency.

**Comment by shushenghong** [comment] 2020-01-10 10:39
@samdark the problem is tags dependency itself also used cache to determine whether related content changed or not, and the these caches never expire. We need a solution to control the scale.

**Comment by samdark** [comment] 2020-01-10 10:49
Thanks for variants. 1,2 doesn't sound right. For example, I'll have to install Redis if I just want to cache data using memcached.

max_tags_num may be OK though.

**Comment by shushenghong** [comment] 2020-01-10 10:54
I will try to code :)
Hope more advices.

**Comment by rob006** [comment] 2020-01-10 11:08
We could pass `null` as duration for `multiSet()`:

https://github.com/yiisoft/yii2/blob/ad83952197315072124027bf39263eabc1979e1a/framework/caching/TagDependency.php#L96

Then `$defaultDuration` from cache component will be used, so you can set expiry time for tags at component level.

**Comment by shushenghong** [comment] 2020-01-10 11:23
> We could pass `null` as duration for `multiSet()`:
> 
> https://github.com/yiisoft/yii2/blob/ad83952197315072124027bf39263eabc1979e1a/framework/caching/TagDependency.php#L96
> 
> Then `$defaultDuration` from cache component will be used, so you can set expiry time for tags at component level.

sounds good :)

**Comment by OscarBarrett** [comment] 2021-09-02 12:42
There is currently an inconsistency between `set` and `multiSet`: `set` has a default duration of `null` (which falls back to `$defaultDuration`) whereas `multiSet` has a default duration of 0.

@samdark Would it be acceptable to update `multiSet` to also default to null? If this was done, TagDependency would then also use the default duration.

Looking at the history, `multiSet` [was added 6 years ago](https://github.com/yiisoft/yii2/commit/5a47692e64938a937b653040527360f6cadd116c).    
`set` [was updated 5 years ago](https://github.com/yiisoft/yii2/commit/9a1c168939a5534c9dc8c881c6933b616ecc5de3) to use the default duration if no value was passed, rather than 0.

**Comment by samdark** [comment] 2021-09-02 14:22
Yes. I think that's a good thing to do.

**Closed** 2021-09-03 07:02 UTC
Labels: status:ready for adoption, type:enhancement, help wanted
