### ISSUE TITLE
yiiActiveForm unexpected behavior

### ISSUE THREAD

**Issue by pana1990** [yiisoft/yii2#11177] opened 2016-03-23 12:37 UTC
### What steps will reproduce the problem?
I create a single form : 
```php
<?php $form = ActiveForm::begin(['id' => 'productForm', 'options' => ['enctype' => 'multipart/form-data']]); ?>

        <?= $form->field($product, 'title', ['inputOptions' => ['class' => 'form-control', 'autofocus' => 'autofocus']]) ?>

        <?= $form->field($product, 'description') ?>

        <?= $form->field($product, 'prize')->input('number', ['step' => '0.01']) ?>

        <?= $form->field($product, 'quantity')->input('number', ['value' => 99]) ?>

        <?= $form->field($image, 'imageFiles[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

        <div class="form-group">
            <?= Html::submitButton('Crear', ['class' => 'btn btn-success', 'id' => 'productFormBtn']) ?>
        </div>

        <?php ActiveForm::end(); ?>
```
and i want to send form by AJAX with the following code : 
```javascript
$(document).ready(function() {
        $("#productForm").submit(function (e) {
            e.preventDefault();
            e.stopImmediatePropagation();
            var options = {
                clearForm: true,
                success: function(data) {
                    if (data == 1) {
                        $.pjax.reload({container: '#productsGrid'});
                        $("form#productForm").yiiActiveForm("resetForm");
                        $("#product-quantity").val(99);
                        $("#product-title").first().focus();
                    } else {
                        alert("Ha habido un error. Intentalo más tarde.");
                        console.log(data);
                    }
                }
            };
            $(this).ajaxSubmit(options);
            return false;
        })
    });
```
### What is the expected result?

yiiActiveform.js not trigger validation when i focus in input with jquery

### What do you get instead?

When input is focus with ```$("#product-title").first().focus();``` yiiActiveform trigger validate and it leave focus.
![screenshot_1](https://cloud.githubusercontent.com/assets/6630197/13985238/d8045ec8-f0fb-11e5-818c-f94fd20c7708.png)

### Additional info
if i remove ```$("form#productForm").yiiActiveForm("resetForm");``` yiiActiveForm validate all inputs together.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8-dev
| PHP version      | 5.6.12
| Operating system | Windows 7 - XAMPP 3.2.1

**Comment by cebe** [comment] 2016-03-23 23:52
not sure if this is caused by your hacking into submit method but it is better to extend activeform by using the events provided by yii instead of original submit:

```js
var $form = $('#formId');
$form.on('beforeSubmit', function() {
    var data = $form.serialize();
    $.ajax({
        url: $form.attr('action'),
        type: 'POST',
        data: data,
        success: function (data) {
...
        },
        error: function(jqXHR, errMsg) {
            alert(errMsg);
        }
     });
     return false; // prevent default submit
});

```

**Comment by SilverFire** [comment] 2016-09-11 18:24
I'm closing the issue unless further information provided.

**Closed by SilverFire** 2016-09-11 18:24 UTC
