### ISSUE TITLE
Pjax widget - submit by get

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii2#6688] opened 2014-12-29 12:12 UTC
###### Code
The menu
```php
Pjax::begin();
//A link here loads the form
Pjax::end();
```

The form
```php
Pjax::begin();
$form = ActiveForm::begin(['method' => 'get', 'options' => ['data' => ['pjax' => 1]]]);
Pjax::end();
```

###### The problem
When you click in the link who has that form, Pjax widget executes [this](https://github.com/yiisoft/yii2/blob/master/framework/widgets/Pjax.php#L175) line.
Any other click in the menu link, returns the content of Pjax again, making another event on submit. Checking it on firebug gives an error which takes time.

###### The possible solution
Add at the beginning of that line this: `jQuery(document).off('submit', $formSelector).on(...);`

Perhaps this is specific or not (but this make possible multiple pjax widgets).

**Comment by SilverFire** [comment] 2015-11-23 21:41
Seems to be fixed in upstream: https://github.com/defunkt/jquery-pjax/commit/6e2c7e5b123b2b3a0521d9cfda9ef802e20563ab

**Comment by SilverFire** [comment] 2016-09-10 18:27
Failed to reproduce

**Closed by SilverFire** 2016-09-10 18:27 UTC
Labels: feature:pjax, status:to be verified
