### ISSUE TITLE
API documentation search not functional

### ISSUE THREAD

**Issue by zpin** [yiisoft/yii2#16572] opened 2018-07-28 13:21 UTC
### What steps will reproduce the problem
Go to the official API documentation, search for "beforeSave":
![image](https://user-images.githubusercontent.com/9852384/43356853-b6d45f16-9278-11e8-8ce2-1df07bfb6381.png)

### What is the expected result?
It should point you to all available "beforeSave" functions in the API. See for example:
http://stuff.cebe.cc/yii2docs/index.html
Where it delivers useful results:
![image](https://user-images.githubusercontent.com/9852384/43356879-09e80a0e-9279-11e8-85ed-4949bb9b635b.png)

### What do you get instead?
No results at all in the dropdown and a wrong "yii\db\AfterSaveEvent" result on pressing enter.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | All
| PHP version      | -
| Operating system |-

Similarly, searching the forums always searches the whole site, there doesn't seem to be a forums only search functionality.

**Comment by cebe** [comment] 2018-07-28 14:59
to search for methods and properties, prefix the search with `.` or `::`.

**Comment by cebe** [comment] 2018-07-28 14:59
duplicate of https://github.com/yiisoft-contrib/yiiframework.com/issues/379

**Closed by cebe** 2018-07-28 14:59 UTC
