### ISSUE TITLE
ActiveQuery method 'one()' not add 'limit(1)'

### ISSUE THREAD

**Issue by igorveremsky** [yiisoft/yii2#16223] opened 2018-05-04 14:40 UTC
Hi, as notice at [performance guide](https://www.yiiframework.com/doc/guide/2.0/en/tutorial-performance-tuning#optimizing-databases) is good to use `LIMIT` at sql queries, so i decided maybe method [one() in ActiveQuery](https://github.com/yiisoft/yii2/blob/6960eb67d9e03baf6ebc68045014011739519191/framework/db/ActiveQuery.php#L290) will add `limit(1)` to builded sql query?

**Comment by samdark** [comment] 2018-05-04 14:43
Duplicate of https://github.com/yiisoft/yii2/issues/13875

**Closed by samdark** 2018-05-04 14:43 UTC
