### ISSUE TITLE
Add ActiveQuery::getAlias() as pair of alias()

### ISSUE THREAD

**Issue by sasha-ch** [yiisoft/yii2#10909] opened 2016-02-19 11:07 UTC
How do you about add:
```php
class ActiveQuery ...
{
...
    public function getAlias()
    {
        list(, $alias) = $this->getQueryTableName($this);
        return $alias;
    }
```
or make `ActiveQuery::getQueryTableName()` function not `private`?

**Comment by samdark** [comment] 2016-02-19 11:26
Why do you need it to be non-private? What's your use case?

**Comment by sasha-ch** [comment] 2016-02-19 13:25
About getAlias():
I need to create ActiveQuery in one "service" class and add andWhere() for its primary table in another "service".
Cutted code is:
```php
/* @var \app\models\ObjectQuery */
$query = $modelClass::findForUser($userId);    //may be contain several joins
$searchService = SearchService::createFromQuery($query);
$query = $searchService->search($params);   //apply filters inside
return new ActiveDataProvider([
            'query' => $query
        ]);
```
```php
class ObjectQuery extends ActiveQuery
{
    public function filterBySomeThing($params)
    {
        $whereCondition = ...;   //some logic
        $tableAlias = $this->getAlias();
        $field = "{{$tableAlias}}.[[my_attr_id]]";
        return $this->andWhere([$field => $whereCondition]);
    }
}
```

**Comment by samdark** [comment] 2016-02-19 14:20
@cebe sounds related your recent alias changes, would you please check it?

**Comment by cebe** [comment] 2016-02-19 15:24
duplicate of #7263

**Closed by cebe** 2016-02-19 15:24 UTC
Labels: feature:db, status:need more info

**Comment by sasha-ch** [comment] 2016-03-21 07:49
Any news?
I hate code copy-pasting, but have no other way now.

**Comment by cebe** [comment] 2016-03-21 16:44
@sasha-ch the topic is discussed in #7263 by evaluating several use cases. we need to find a common api for different cases. comments are welcome in that issue.
