### ISSUE TITLE
batchInsert incorrectly quotes SQL query with values, containing [[xxx]] symbols

### ISSUE THREAD

**Issue by tphanx** [yiisoft/yii2#14848] opened 2017-09-19 09:20 UTC
### What steps will reproduce the problem?
$this->db->createCommand()->batchInsert('table', ['column1'], [["input [[123]]"]])->execute();

### What is the expected result?
Value "input [[123]]" inserted into a table

### What do you get instead?
<pre>"input `123`"</pre>

Raw SQL 
<pre>INSERT INTO `table` (`column1`) VALUES ('input `123`')</pre>

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.0
| Operating system | Windows 10 64bit

**Comment by cebe** [comment] 2017-09-19 09:26
duplicate of #11242

**Closed by cebe** 2017-09-19 09:26 UTC
