### ISSUE TITLE
Flash is always lost when using DbSession (postgresql)

### ISSUE THREAD

**Issue by yakninja** [yiisoft/yii2#17623] opened 2019-10-21 13:01 UTC
### What steps will reproduce the problem?

1. Create a new application, basic template
2. Create a database and a session table:
```sql
CREATE TABLE session
(
    id CHAR(64) NOT NULL PRIMARY KEY,
    expire INTEGER,
    data BYTEA
)
```
3. Edit config/db.php:
```php
<?php

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=127.0.0.1;dbname=dbname',
    'username' => 'dbuser',
    'password' => 'dbpassword',
];
```
4. Edit config/web.php:
```php
<?php
...

$config = [

    'components' => [
...
        'session' => [
            'class' => 'yii\web\DbSession',
        ],
...
    ],
];
...
```
5. Edit controllers/SiteController.php:
```php
...
class SiteController extends Controller
{
...
    public function actionTest1()
    {
        Yii::$app->session->setFlash('foo', 'bar');
        return $this->redirect(['/site/test2']);
    }

    public function actionTest2()
    {
        var_dump(Yii::$app->session->getAllFlashes());
    }
...
}
```
6. `./yii serve`
7. open `http://localhost:8080/index.php?r=site%2Ftest1`

### What is the expected result?

`array(1) { ["foo"]=> string(3) "bar" }`

### What do you get instead?

`array(0) { }`

### Additional info

Works ok if:

- Database is mysql
- `yii\web\Session` is used instead of DbSession

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.26
| PHP version      | 7.3.8
| Operating system |macOS 10.15, Centos 7
| PostgreSQL version | 11.3

**Comment by samdark** [comment] 2019-10-21 14:12
Is your session written correctly into database table?

**Comment by yakninja** [comment] 2019-10-21 15:12
Yes. Oddly enough, this happens only to flash, the rest of the sessions work just fine.

The flash data is correctly written to the db as well, you can see it if you comment out the redirect in site/test1.

If you call site/test2 just after that, the flash data disappears BEFORE the controller method is called. So my guess is that it is lost somewhere during the session initialization, but I'm not sure where exactly.

**Comment by samdark** [comment] 2019-10-21 18:41
And you're sure that if you switch to file sessions it works?

**Comment by yakninja** [comment] 2019-10-21 19:13
Yes. It works after commenting out `'class' => 'yii\web\DbSession'` line in config as well as after switching to mysql.

**Comment by HenryVolkmer** [comment] 2019-12-30 17:12
No psql problem rather then a \yii\web\Session Problem. Fixed with [PR](https://github.com/yiisoft/yii2/pull/17775)

**Comment by samdark** [comment] 2020-01-09 14:04
See https://github.com/yiisoft/yii2/pull/17775#issuecomment-572574923

**Comment by samdark** [comment] 2020-02-19 16:40
Closing since no use-case was provided to reproduce the issue.

**Closed by samdark** 2020-02-19 16:40 UTC
Labels: PostgreSQL, type:bug

**Comment by yakninja** [comment] 2020-02-19 16:45
Isn't the first message in this thread the use-case? Not trying to reopen the issue, just not sure what I should have done to provide that use-case.

**Comment by samdark** [comment] 2020-02-19 16:48
@yakninja see https://github.com/yiisoft/yii2/pull/17775#issuecomment-572574923
