### ISSUE TITLE
FileTargetTest::testRotate produced errors

### ISSUE THREAD

**Issue by bscheshirwork** [yiisoft/yii2#15072] opened 2017-11-02 12:30 UTC
### What steps will reproduce the problem?
I can see it **again** in https://travis-ci.org/yiisoft/yii2/jobs/296156475

```sh
Time: 6.63 minutes, Memory: 162.00MB

There was 1 failure:

1) yiiunit\framework\log\FileTargetTest::testRotate with data set #0 (true)

Failed asserting that file "/home/travis/build/yiisoft/yii2/tests/runtime/log/filetargettest.log.1" exists.

/home/travis/build/yiisoft/yii2/tests/framework/log/FileTargetTest.php:88

/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:52

--

There was 1 incomplete test:

1) yiiunit\framework\i18n\GettextMessageSourceTest::testLoadMessages

/home/travis/build/yiisoft/yii2/tests/framework/i18n/GettextMessageSourceTest.php:19

/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:52
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev
| PHP version      | trevis 7.1

**Comment by rugabarbo** [comment] 2019-01-03 14:50
Here we are talking about a rare situation where tests fail with an error:
```
There was 1 failure:
1) yiiunit\framework\log\FileTargetTest::testRotate with data set #0 (true)
Failed asserting that file "/home/travis/build/yiisoft/yii2/tests/runtime/log/filetargettest.log.1" exists.
/home/travis/build/yiisoft/yii2/tests/framework/log/FileTargetTest.php:88
/home/travis/build/yiisoft/yii2/vendor/phpunit/phpunit/phpunit:52
```

**Note that:**
1. This test usually fails on changesets that are not directly related to it.
2. This test fails very rarely and randomly (I could not find any such fail of this test over the past year).

@samdark I assume that the causes of these fails lie somewhere at the level of Travis (for example, memory limits or file operations in a specific test container). Purposefully diagnose the exact cause is very difficult. That's why I propose to move this issue to the [Infrastructure milestone](https://github.com/yiisoft/yii2/milestone/10).

**Comment by samdark** [comment] 2019-01-03 16:39
Moved. Thanks for checking.

**Comment by samdark** [comment] 2020-03-26 22:06
We're not using travis anymore and I haven't seen the error for a while. Closing.

**Closed by samdark** 2020-03-26 22:06 UTC
Labels: status:ready for adoption, type:test
