### ISSUE TITLE
Missing vendor/bower

### ISSUE THREAD

**Issue by lazarevicivica** [yiisoft/yii2#15821] opened 2018-03-02 14:32 UTC
After upgrade to 2.0.14 i got error message 

> The file or directory to be published does not exist: /var/www/businessday/vendor/bower/jquery/dist

I solved the problem by creating symbolic link _bower_ that points to _bower-assets_

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14?
| PHP version      | 5.6 
| Operating system |Ubuntu Linux 14.04

**Comment by schmunk42** [comment] 2018-03-02 15:22
Duplicate of https://github.com/yiisoft/yii2/issues/14324?

**Closed** 2018-03-02 16:25 UTC
