### ISSUE TITLE
Validator don`t working with extension webp

### ISSUE THREAD

**Issue by semiromid** [yiisoft/yii2#15155] opened 2017-11-14 20:34 UTC
### What steps will reproduce the problem?

            ['img_x1', 'image', 'extensions' => 'webp'
            ],

### What is the expected result?
I want to load image with extension "webp"
### What do you get instead?

if i load image with extension 'webp', that i get error what - images can will be loading only with extension 'webp'.

And validator return me - myimage.webp - is not image

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.13.
| PHP version      |  5.6
| Operating system | Win 8.1

**Comment by Alex-Code** [comment] 2017-11-15 08:22
Are you validating in the client (browser) or on the server?
If it's the browser it might not support `webp`, https://caniuse.com/#feat=webp

**Comment by semiromid** [comment] 2017-11-18 08:54
it is working:
When i load image with extentions "jpeg, png, jpg"
```
            ['img_x1', 'image', 'extensions' => 'jpeg, png, jpg',
              'minWidth' => 696, 'maxWidth' => 696,
              'minHeight' => 309, 'maxHeight' => 309,
            ],
```
When i loading image with extension "webp" I get error from validator, what i try load image with other extension, but i load image with "webp" extension.
```
            ['img_x1', 'image', 'extensions' => 'webp',
              'minWidth' => 696, 'maxWidth' => 696,
              'minHeight' => 309, 'maxHeight' => 309,
            ],
```




If i load any images with extension: jpg, png, gif, svg, that It is working!
`            [['img_x1'], 'file', 'skipOnEmpty' => false, 'maxFiles' => 1, 'maxSize' => 1000000],`


If i load image with extension "webp", than It is not working! I get error from validation, that it image is not image.



I use Google Chrome and FF last version.

**Comment by samdark** [comment] 2017-11-18 09:49
Likely it's caused by issues when determining mime type for webp image. Yii expects PHP's `finfo()` to return `image/webp`.

You can help us to debug a bit by executing the following code:

```php
echo FileHelper::getMimeType($yourFilePath);
```

**Comment by semiromid** [comment] 2017-11-18 10:33
return -   application/octet-stream

**Comment by samdark** [comment] 2017-11-18 23:30
Means PHP can't obtain mime for it correctly at all... not sure if we can deal with that at framework level.

**Comment by semiromid** [comment] 2017-11-19 07:58
PHP 7 returned `"image/webp"`

**Comment by samdark** [comment] 2017-11-19 15:39
Yes, it depends on PHP version as well. I don't think we can affect that from the framework so closing the issue.

**Closed by samdark** 2017-11-19 15:39 UTC
Labels: status:need more info

**Comment by cozumel424** [comment] 2019-12-08 05:43
```
$model->file = UploadedFile::getInstance($model, 'file');
print_r($model->file);
yii\web\UploadedFile Object ( [name] => Image1225.webp [tempName] => /tmp/phpcBSkZP [type] => image/webp [size] => 40089 [error] => 0 ) 
```

```
echo FileHelper::getMimeType($_FILES['CommentImage']['tmp_name']['file']);
image/png
```
It looks like the Yii file validator isn't actually checking the file at all and just going by the extension?

Putting `'checkExtensionByMimeType' => false` in the rules then checking it manually works. Using Yii 2.0.31

**Comment by kamarton** [comment] 2019-12-08 06:00
> echo FileHelper::getMimeType($_FILES['CommentImage']['tmp_name']['file']);
> image/png

are you sure webp is the image format? It is possible that the uploaded image is a png and only the file extension is webp. 
For example `image.png` renamed to `image.webp`.
