### ISSUE TITLE
Console application logging always writes messages of category 'application' even if exempt

### ISSUE THREAD

**Issue by c-schmitz** [yiisoft/yii2#12957] opened 2016-11-09 12:40 UTC
### What steps will reproduce the problem?
Create a console application and use logging. We use logging to a database table.

        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning','info'],
                    'except' => [
                       'yii\db\*',
                       'yii\swiftmailer\*',
                       'application'
                     ],
                ],
            ],
        ],

As you can see the category 'application' is exempt from logging.

### What is the expected result?
Messages of category 'application' should not be written to the log table/file.

### What do you get instead?
Messages of category 'application ' and log level 4 which look like this 

   $_SERVER = [
       'LANGUAGE' => 'en_US:en'
       'HOME' => '/root'
       'LOGNAME' => 'root'
       'PATH' => '/usr/bin:/bin'
       'LANG' => 'en_US.UTF-8'
       'SHELL' => '/bin/sh'
       'PWD' => '/root'
       'PHP_SELF' => '/service/engine/yii'
       'SCRIPT_NAME' => '/service/engine/yii'
       'SCRIPT_FILENAME' => '/service/engine/yii'
       'PATH_TRANSLATED' => '/service/engine/yii'
       'DOCUMENT_ROOT' => ''
       'REQUEST_TIME_FLOAT' => 1478694601.0434
       'REQUEST_TIME' => 1478694601
       'argv' => [
           0 => '/service/engine/yii'
           1 => 'webserver/process-action-queue'
       ]
       'argc' => 2
   ]

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.5.9ubuntu
| Operating system | Linux

**Comment by samdark** [comment] 2016-11-09 12:56
Is it the same for non-console?

**Comment by c-schmitz** [comment] 2016-11-09 13:38
I only have a console application in Yii2 so I couldn't tell, sorry.

**Comment by samdark** [comment] 2016-11-09 22:24
I've verified it works as expected with the config provided i.e. when `application` is in `except` logs aren't added to database. Otherwise they are.

**Comment by cebe** [comment] 2016-11-09 22:35
@c-schmitz the message you see is created by `logVars` property of the log target. set that to an empty array to avoid logging this message.

**Comment by c-schmitz** [comment] 2016-11-10 08:33
@cebe Setting logVars to en empty array works just fine as a workaround, thank you.
@samdark So you are saying this is fixed in the latest version?

**Comment by samdark** [comment] 2016-11-10 09:18
@c-schmitz what was your `logVars` before you changed it as @cebe suggested?

**Comment by asamats** [comment] 2022-11-17 22:48
By default it logs in web/console/everywhere.
The cause is 
https://github.com/yiisoft/yii2/blob/64adbd73c626b66e13208a11a0456157954915b4/framework/log/Target.php#L151
This line is called after filtration messages.
`$this->messages[] = [$context, Logger::LEVEL_INFO, 'application', YII_BEGIN_TIME, [], 0];`

So, this message is always will put in a log file even if you only want to log errors. Nightmare for devops)
 
The quick fix is `logVars = []`

**Comment by samdark** [comment] 2022-11-18 10:06
Seems it is configurable so closing the issue. Nothing we need to fix.

**Closed by samdark** 2022-11-18 10:06 UTC
Labels: status:to be verified
