### ISSUE TITLE
No data extracted when using join or renaming

### ISSUE THREAD

**Issue by BartMitTyp** [yiisoft/yii2#18331] opened 2020-10-14 09:35 UTC
### What steps will reproduce the problem?
```
$test1 = TableA::find()
        ->select('TableB.id')
        ->joinWith('TableB')
        ->all();
trigger_error(var_export(($test1), true));
```
and
```
$test2 = TableA::find()
        ->select('id as idtest')
        ->all();
trigger_error(var_export(($test2), true));
```

### What is the expected result?
$test1 should contain TableB.id (when removing the select statement, I'm able to find the ID of TableB), but contains no Data at all.
$test2 should contain a renamed version of its id, but also contains no Data at all.

### What do you get instead?
No data in both cases.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.38
| PHP version      | 7.2.31
| Operating system | Windows 10

**Comment by bizley** [comment] 2020-10-14 10:43
1. IIRC `joinWith` requires relation name as the first argument, and relation names can only start lowercased. Anyway, my test is not showing what you claims:

`tab_a` columns: `id` | `data` -> model `TabA` -> one row inserted with 1 | 3.
`tab_b` columns: `id` | `a_id` | `data` -> model `TabB` -> one row inserted with 1 | 1 | 6.

`TabA` model with relation `tabB`

    $test1 = TabA::find()->select('tab_b.id')->joinWith('tabB')->all();
    $test1[0]->id === 1
    $test1[0]->data === null
    $test1[0]->tabB->id === 1

2. This works as intended, no attribute is hydrated since you aliased `id` in query.

You must remember that you are operating on Active Record objects and these are not the same as SQL queries. I hope I cleared the doubts (please close the issue in that case) or maybe I misunderstood something or did wrong, clarify it for me then.

**Comment by BartMitTyp** [comment] 2020-10-14 11:13
>     1. IIRC `joinWith` requires relation name as the first argument, and relation names can only start lowercased. Anyway, my test is not showing what you claims:

You're right, my code was lowercase, but I changed the Names to make it easiert to understand. The relations were created with gii. So the 'real' code would be
```
$test1 = TableA::find()
        ->select('tableB.id')
        ->joinWith('tableB')
        ->all();
trigger_error(var_export(($test1), true));
```
But I still don't get and values back, even though when I add a little mistake in the select statement (so the error message displays the sql statement), and I execute the sql statement, I get the values I was expecting.


>     1. This works as intended, no attribute is hydrated since you aliased `id` in query.
So is it not possible to alias data to use in the resulting variable? I also tried the following statements, which also caused no data to be extracted:
```
->select(['id as idtest'])
->select(['idtest'=>'id'])
```

**Comment by bizley** [comment] 2020-10-14 11:27
> So is it not possible to alias data to use in the resulting variable?

It is but you need to have AR property named like the alias. Or not use AR and just work on Query object.

**Comment by BartMitTyp** [comment] 2020-10-14 11:57
The Problem is that even when using groupby I can't seem to get any data out of the query (when using join with it).
I also still don't know how to fix the first issue, maybe there's an error that will fix the rest. As I said the produced SQL query is correct, but the resulting data in $test1 is not. Am I doing something fundamentally wrong?

**Comment by alex-code** [comment] 2020-10-14 12:51
If you want to select a specific column in a join you need to select it in a sub function.
```php
$test1 = TableA::find()
  ->select('tableB.id')
  ->joinWith(['tableB' => function(ActiveQuery $q) {
    $q->select(['id']);
  })
  ->all();

$test1[0]->tableB->id;
```

**Comment by BartMitTyp** [comment] 2020-10-14 14:06
Thank you! I will be able to try that on Friday, then I can hopefully close the issue

**Comment by BartMitTyp** [comment] 2020-10-16 07:33
I am able to select the id (and another attribute, when I also select the id - presumably because that's what is used for the join), but as soon as I add the outer select statement, the result is empty again or contains wrong results

```
$test1 = TableA::find()
  ->select(['tableA.id', 'tableB.id'])
  ->joinWith(['tableB' => function(ActiveQuery $q) {
    $q->select(['id']);
  }])
  ->all();
```
results in only `tableA.id` being shown.

```
$test1 = TableA::find()
  ->select(['max(tableB.id)'])
  ->joinWith(['tableB' => function(ActiveQuery $q) {
    $q->select(['id']);
  }])
  ->all();
```
results in nothing being returned, even though
```
$test1 = TableA::find()
  ->joinWith(['tableB' => function(ActiveQuery $q) {
    $q->select(['id']);
  }])
  ->all();
```
contains the info I need and I would work with that, but this way I can't use aggregation functions, which would make everything a lot easier.

**Comment by alex-code** [comment] 2020-10-16 09:01
If you want to use AR you need the properties on the model too. e.g.
```php
class TableA extends ActiveRecord
{
  public $max;
  //...
}

$test1 = TableA::find()
  ->select(['max' => 'max(tableB.id)'])
  ->joinWith(['tableB'], false)
  ->all();
```

Or if you use `asArray()` you won't need the properties.
```php
$test1 = TableA::find()
  ->select(['max' => 'max(tableB.id)'])
  ->joinWith(['tableB'], false)
  ->asArray()
  ->all();
```

**Comment by bizley** [comment] 2020-10-16 09:05
As far as I see there is no error in Yii 2 here, you are just not using Active Record properly. Please move the discussion to [forum](https://forum.yiiframework.com/).

**Closed by bizley** 2020-10-16 09:05 UTC
Labels: status:need more info
