### ISSUE TITLE
Wrong behavior of Json helper.

### ISSUE THREAD

**Issue by misq007** [yiisoft/yii2#17913] opened 2020-03-10 06:20 UTC
### What steps will reproduce the problem?

```php
<?php
$data = [
    0 => 'test'
];
$data = (object)$data;

echo \yii\helpers\Json::encode($data); // ["test"]
// echo json_encode($data); // {"0":"test"}
exit;
```

I have a custom API that is using `Yii::$app->response->format = \yii\web\Response::FORMAT_JSON` and returns a list with groups where the group_id was a key.
Note that in my case the 0 was the ID of a group and only one group was returned.

### What is the expected result?

`{"0":"test"}`

### What do you get instead?

`["test"]`

`json_encode($data);` works fine.
The problem occurs because you foreach it and convert it to array here:
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseJson.php#L171

I think it should check if:
```php
($data instanceof stdClass) {
    return $data;
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.32
| PHP version      | 5.6
| Operating system | centos

**Comment by kamarton** [comment] 2020-03-10 06:31
For incremental numeric keys (0, 1, 2 ...) in PHP is interpreted as a JSON array.

Incremental, started from zero, string type keys:
```bash
$ php -r 'var_dump(json_encode(["0" => "a","1" => "b"]));'
string(9) "["a","b"]"
```

not incremental:
```
$ php -r 'var_dump(json_encode([1 => "a",0 => "b"]));'
string(17) "{"1":"a","0":"b"}"
$ php -r 'var_dump(json_encode(["0" => "a","2" => "b"]));'
string(17) "{"0":"a","2":"b"}"
```

**Comment by misq007** [comment] 2020-03-10 06:38
Please see that I cast it to object in purpose:
`$data = (object)$data;` and node that json_encode works fine.

In my case, it was a filter that returns only a special group with ID 0.
But without filter - it returns 0 and 13 which is fine.

The Yii Json helper cannot break the behavior of `json_encode` because people do not expect it and it causing hard to find bugs.

I think this should be fixed.

**Comment by rob006** [comment] 2020-03-10 09:00
Duplicate of https://github.com/yiisoft/yii2/issues/16621

**Closed** 2020-03-12 15:26 UTC
