### ISSUE TITLE
Response "HTTP 200 OK" on exception in layout

### ISSUE THREAD

**Issue by gugglegum** [yiisoft/yii2#7571] opened 2015-03-04 13:38 UTC
If layout of web application gets an exception and current environment is "Production" (i.e. `YII_DEBUG=false`) the Yii2 generates empty response and HTTP status "200 OK". HTTP status on error must be 5xx.

**How to reproduce**

Add `throw new \Exception('test');` in `views/layout/main.php`. Also it can be reproduced if `web/assets` directory is empty and not writable and layout contains `AppAsset::register($this);`. This throws `yii\base\InvalidConfigException` which results in 200 OK and blank page too. YII_DEBUG must be false (as on Production).

Yii version 2.0.2

This bug is very dangerous in some kind of web APIs because "200 OK" response with empty body can be interpreted as normal response if API request is executed successfully. This may result in loss of data.

**Comment by SDKiller** [comment] 2015-03-05 10:00
Could not reproduce it in any place of layout.
`500 Internal Server Error` is thrown even with `'errorHandler'` commented in config.

For actions which require authorisation - `302` redirect at first and then `500`.
The same is with assets folder.

The only situation when I received `200 Ok` - when  I forgot to remove debug toolbar from `bootstrap` in config.

**Comment by gugglegum** [comment] 2015-03-05 10:05
Is `200 OK` correct answer for situation when assets folder is not writable but some components need to write into it?

**Comment by SDKiller** [comment] 2015-03-05 10:05
Ah, sorry
In case of assets folder `200 Ok` when
```
'errorHandler' => [
            'errorAction' => 'site/error',
        ],
```

**Comment by SDKiller** [comment] 2015-03-05 10:08
And you receive `500` when you disable it in config

```
        'errorHandler' => [
            //'errorAction' => 'site/error',
        ],
```

**Comment by gugglegum** [comment] 2015-03-05 10:09
So, is this a bug of Yii or bug of SiteController?

**Comment by samdark** [comment] 2015-03-05 10:15
Looks like bug in ErrorAction.

**Comment by SDKiller** [comment] 2015-03-05 10:24
Seems that view rendering errors are not handled by `\yii\web\ErrorAction`

**Comment by gugglegum** [comment] 2015-03-05 10:48
Here is full list of steps to reproduce a bug from clean Yii project.

`composer create-project --prefer-dist yiisoft/yii2-app-advanced ~/yii2-advanced`
`~/yii-advanced/init`
(Press "1", Enter, "y")
`sudo su`
`nano /etc/nginx/sites-enabled/yii2-advanced.conf`

Add following lines:
```
server {
    server_name yii2-advanced;
    root /home/USERNAME/yii2-advanced/frontend/web;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include fastcgi_params;

        fastcgi_pass unix:/var/run/home-fpm.socket;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
    }
}
```
`/etc/init.d/nginx restart`
`echo "127.0.0.1 yii2-advanced" >> /etc/hosts`
`exit`

Try to open http://yii2-advanced/ -- everything sould be OK. Now let's add Exception to main layout and disable YII_DEBUG:

`nano ~/yii2-advanced/frontend/views/layouts/main.php`
Add to begining after `<?php`:
```
throw new \Exception('test');
```

Now try to open http://yii2-advanced/ again. You'll see blank page and HTTP status `200 OK`.

**Comment by gugglegum** [comment] 2015-03-06 06:31
Is this bug was confirmed? Can you reproduce it with my steps above?

**Comment by samdark** [comment] 2015-03-06 16:44
Confirmed if exception is in the layout.

**Comment by samdark** [comment] 2015-03-06 16:47
The issue is that exception is in layout which should be used to render the exception.

**Comment by gugglegum** [comment] 2015-03-06 16:55
Yes. But if HTML page with error message cannot be rendered due to layout problem I will prefer that at least HTTP status be `500`. No care of blank page. Or as gracefull degradation it may be plain-text message without any decoration.

**Comment by samdark** [comment] 2015-03-06 16:56
Could be fixed in hacky way in `yii\base\ErrorHandler::handleException()`:

```php
            $msg .= "\n\$_SERVER = " . VarDumper::export($_SERVER);
            error_log($msg);

            if (PHP_SAPI !== 'cli') {  // <---- like that
                http_response_code(500);
            }
            exit(1);
        }

        $this->exception = null;
    }
```

Not sure it's a good solution though since HTTP details got into base handler class. Probably `yii\web\renderException::renderException()` should be modified instead...

**Comment by samdark** [comment] 2015-03-06 16:57
It is plain message in case of `YII_DEBUG = true`.

**Comment by samdark** [comment] 2015-03-06 17:11
Thanks for reporting.

**Closed** 2015-03-06 17:11 UTC
Labels: status:to be verified
