### ISSUE TITLE
Invalid JSON in API responses

### ISSUE THREAD

**Issue by wcjr** [yiisoft/yii2#13841] opened 2017-03-23 15:59 UTC
### What steps will reproduce the problem?
`DEBUG=true`
 Generate any error response from an API.
Notice the unescaped string in the `type` field.

### What is the expected result?
```
{
    "name": "Unprocessable entity",
    "message": "...some validation message...",
    "code": 0,
    "status": 422,
    "type": "yii\\web\\UnprocessableEntityHttpException"
}
```
### What do you get instead?
```
{
    "name": "Unprocessable entity",
    "message": "...some validation message...",
    "code": 0,
    "status": 422,
    "type": "yii\web\UnprocessableEntityHttpException"
}
```

Maybe this could be json encoded to ensure those namespace backslashes are escaped.  https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L147

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0
| Operating system | N/A

**Comment by samdark** [comment] 2017-03-23 16:27
How do you throw exception? I've tried throwing `BadRequestHttpException` and the response was escaped properly:

```json
{"name":"Bad Request","message":"test","code":0,"status":400,"type":"yii\\web\\BadRequestHttpException"}
```

**Comment by wcjr** [comment] 2017-03-23 23:39
Thanks for checking that out.  Yours looks right, I must be doing something wrong then...

I'm writing an API and wanted to ensure the only type of error response that ever came out the API was a JSON response, so I customized and configured my own and I suppose this means my implementation is not using the same as Yii's built-in.

Here's the config that I use to point to my error handler:  https://github.com/silinternational/idp-id-broker/blob/feature/initial-features/application/frontend/config/main.php#L8-L10

And here's my implementation:  https://github.com/silinternational/idp-id-broker/blob/feature/initial-features/application/frontend/web/ErrorHandler.php

I thought I was doing the same thing as the built-in: https://github.com/yiisoft/yii2/blob/master/framework/web/ErrorHandler.php#L78-L125

Especially on line 121, however that's obviously not the case, becuase it seems yours **is** being run through a json encoder...do you have any advice on where I might find the logic that is handling your response?

**Comment by samdark** [comment] 2017-03-23 23:57
Getting the same proper encoding with your code.

**Comment by samdark** [comment] 2017-03-24 00:00
Closing the issue since I'm unable to reproduce it.

**Closed by samdark** 2017-03-24 00:00 UTC
Labels: feature:rest, status:to be verified, type:bug

**Comment by wcjr** [comment] 2017-03-24 00:10
In reading the docs, I don't think I ever needed to write my own custom error handler in the first place, I added the following config:

```
        'response' => [
          'format' => yii\web\Response::FORMAT_JSON,
          'charset' => 'UTF-8',
        ],
```

and it's turning all responses into JSON, even compile problems.  However it's still not encoding properly so I'm wondering if there's some configuration involved with escaping the JSON or not?  I thought I'd seen something about it in the JsonResponseFormatter...I'll keep looking, if you happen to notice you have some config that might be controlling it on your end, would you  mind letting me know?  Thanks for your time, I appreciate as always!

**Comment by samdark** [comment] 2017-03-24 00:23
I haven't touched anything about response formatting. Config is pretty much the same as the one in the basic app.

Could it be that your browser is eating double slashes? Can you try something like curl?

**Comment by wcjr** [comment] 2017-03-24 00:29
well, that was a fantastic idea, I **DO** see the proper encoding via `curl`...sorry to have wasted your time like that :-|  I also see now within my XHR plugin there is a "Raw" and  "JSON" tab, I see the additional backslashes in the "RAW" tab...

Well, one great thing from all this is I learned I don't need to write custom error handler, I can simply configure the `'response'` properly!  Thank you again, hope you have a great rest of your day.
