### ISSUE TITLE
pjax aborting reload if 2nd reload comes in / expected?

### ISSUE THREAD

**Issue by ItsReddi** [yiisoft/yii2#5443] opened 2014-10-09 08:20 UTC
following after a successful ajax call:
```js
success  : function(response) {
                    $.pjax.reload({container: '#magazineCalcWithoutField-grid-pjax', timeout: 3000});
                     console.log('okay');
                    $.pjax.reload({container: '#magazineCalc-grid-pjax', timeout: 3000});
                }
```

networking:
```
GET barfoo......=12&_pjax=%23magazineCalcWithoutField-grid-pjax
	
Aborted

okay

GET barfoo......=12&_pjax=%23=12&_pjax=%23magazineCalc-grid-pjax
	
200 OK
```

is this expected or a bug that the 2nd reload is aborting the first reload.

**Comment by SilverFire** [comment] 2015-11-23 21:34
Seems to be fixed in https://github.com/yiisoft/jquery-pjax/pull/29
Try to set `skipOuterContainers` option for both of your Pjax blocks.

As the issue is very old, I'm closing it. When the problem is still alive - please, feel free to post a comment here.
Thank you

**Closed by SilverFire** 2015-11-23 21:34 UTC
Labels: feature:pjax, status:to be verified, status:under discussion

**Comment by Erkebulan69** [comment] 2017-11-30 11:55
I'm facing the same issue.. Would be glad for your help to overcome it

**Comment by SilverFire** [comment] 2017-12-01 07:03
What framework version do you use?

**Comment by Erkebulan69** [comment] 2017-12-02 18:01
bower-asset/yii2-pjax : 2.0.7.1
yiisoft/yii2 : 2.0.13.1
