### ISSUE TITLE
MSSQL rbac/init rule INSERT Query Generator error

### ISSUE THREAD

**Issue by Schwoebel** [yiisoft/yii2#13674] opened 2017-02-27 13:18 UTC
### What steps will reproduce the problem?
I am using SQL Server 13.0.4001.  I am writing in some rules and roles to be added into the database.
When I try rbac/init I run into several problems.  None of which I can conclude whether or not they are my databases settings problems OR a MSSQL Yii2 DB migration problem.
I do know that it isn't code related because if I run the code on a MySql database it works 100%.
### What is the expected result?
When I write a rule and insert it into my RbacController it looks like this:
    $rule = new \app\rbac\EditProfileRule;
    $auth->add($rule);
I expect the result to be a rule inserted into the Database auth_rule table
### What do you get instead?
I get this error: 
    The SQL being executed was: INSERT INTO [auth_rule] ([name], [data], [created_at
    ], [updated_at]) VALUES (**'O:24:"app\rbac\EditProfileRule":3:{s:4:"name";s:14:"ca
    nEditProfile";s:9:"createdAt";i:1488200387;s:9:"updatedAt";i:1488200387;}'**, CONV
    ERT(VARBINARY, 'O:24:"app\rbac\EditProfileRule":3:{s:4:"name";s:14:"canEditProfi
    le";s:9:"createdAt";i:1488200387;s:9:"updatedAt";i:1488200387;}'), 1488200387, 1
    488200387)'

### Additional info
It appears that your MSSQL Query generator is trying to insert the 'data' field into the 'name' field instead of using the rule name. (the bolded text above should be 'editProfileRule')

If I copy that query and put the right value in the name field the query goes through.

doing this manually mangles the converted data, result in a unserialize(): Error at offset 0 of 60 bytes error for the data field, but that is an entirely other ticket.
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 5.5
| Operating system | MS Server 2013 MSSQL Driver 11

**Comment by samdark** [comment] 2017-02-27 20:45
Could you post error title as well?

**Comment by samdark** [comment] 2017-02-27 20:46
Seem you're right about wrong columns order. At least in your output.

**Comment by Schwoebel** [comment] 2017-02-28 08:51
This is the error output in its entirety
Exception 'yii\db\Exception' with message 'SQLSTATE[07002]: [Microsoft][ODBC Driver 11 for SQLServer]COUNT field incorrect or syntax error The SQL being executed was: INSERT INTO [auth_rule] ([name], [data], [created_at], [updated_at]) VALUES ('O:25:"app\rbac\IsYourSchoolRule":3:{s:4:"name";s:26:"performActionsInThisSchool";s:9:"createdAt";i:1488271665;s:9:"updatedAt";i:1488271665;}', CONVERT(VARBINARY, 'O:25:"app\rbac\IsYourSchoolRule":3:{s:4:"name";s:26
:"performActionsInThisSchool";s:9:"createdAt";i:1488271665;s:9:"updatedAt";i:148
8271665;}'), 1488271665, 1488271665)' in C:\inetpub\wwwroot\folder\vendor\yiisoft\yii2\db\Schema.php:636
Error Info:
Array
(
    [0] => 07002
    [1] => 0
    [2] => [Microsoft][ODBC Driver 11 for SQL Server]COUNT field incorrect or sy
ntax error
)

**Comment by Schwoebel** [comment] 2017-02-28 09:19
If I run that query manually, with the correct fields in the correct places the data comes out mangled and I get a 
    unserialize(): Error at offset 0 of 60 bytes
When it tries to decode the rule data so it can look up and access the rule class file.

**Comment by samdark** [comment] 2017-02-28 13:41
Yeah. Looks like a bug and needs digging into it. Can do that after 2.0.12 release. Feel free to fixing it yourself and sending a pull request with tests. It could be merged into 2.0.12 then.

**Comment by Schwoebel** [comment] 2017-03-01 10:36
Is there any way we could broadcast this bug to some developers who might know how to fix it?  I don't have the slightest clue on even where to begin.

**Comment by samdark** [comment] 2017-03-01 10:47
It's already tagged with MSSQL.

**Comment by tsdogs** [comment] 2017-05-03 15:43
IMHO the problem is the use of varbinary in the data field.
Changing varbinary(MAX) to nvarchar(MAX) for the data field seems to be fixing the problem.

**Comment by dabkhazi** [comment] 2017-06-28 21:01
I confirm this problem. I fixed it in my project, later i will post the reason of this problem.

**Comment by samdark** [comment] 2020-06-04 20:53
@darkdef checked it. Seems to be working fine with current master.

**Closed** 2020-06-04 20:52 UTC
Labels: MSSQL, status:ready for adoption, type:bug
