### ISSUE TITLE
Tried to allocate 18446744071594489720 bytes of ram BaseFileHelper.php

### ISSUE THREAD

**Issue by N0ps32** [yiisoft/yii2#17048] opened 2019-01-17 09:59 UTC
### What steps will reproduce the problem?
Load a page with Yii2 and PHP 7.3-fpm

### What is the expected result?
A working setup

### What do you get instead?
`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 18446744071594489720 bytes) in /app/vendor/yiisoft/yii2/helpers/BaseFileHelper.php on line 59`
That's about 16384 terrabytes of ram.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.3
| Operating system | Debian Linux (Docker)

**Comment by Thoulah** [comment] 2019-01-17 20:05
That is 16384 Petabytes! Are you trying to load the internet into your Yii app?

**Comment by samdark** [comment] 2019-01-17 22:17
No, that should not behave like that and is, indeed, unlikely Yii issue. If you'll find out it is because of Yii, please open new issue. Thanks.

**Comment by khalwat** [comment] 2019-01-27 15:50
The code in question is here:

```
    public static function normalizePath($path, $ds = DIRECTORY_SEPARATOR)
    {
        $path = rtrim(strtr($path, '/\\', $ds . $ds), $ds);
```
^ line 59

Why `rtrim` and/or `strtr` would be an issue on 7.3, I don't know. I couldn't find any issues logged against PHP 7.3 that seemed relevant: https://bugs.php.net/search.php?cmd=display&search_for=&x=0&y=0

**Comment by rob006** [comment] 2019-01-27 16:17
@khalwat It may be related to xdebug. Is it still broken if you disable xdebug or change `$ds = DIRECTORY_SEPARATOR` to `$ds = '/'`?

**Comment by rob006** [comment] 2019-01-27 16:31
Hmm, it is actually bug in PHP 7.3, it should be fixed in PHP 7.3.2.

**Comment by bertoost** [comment] 2019-01-27 17:14
Yes. I can confirm when not having xdebug it is working fine! Thanks for pointing this out. Hopefully it's fixed soon

**Comment by brandonkelly** [comment] 2019-01-27 17:46
I do have xdebug enabled as well.

**Comment by N0ps32** [comment] 2019-01-27 18:42
I can confirm that I also had xdebug enabled. Thanks for solving the mistery!

**Comment by rob006** [comment] 2019-01-27 18:49
Closing for now. Please reopen if upgrading to PHP 7.3.2 (after it gets released) does not resolve this issue.

**Closed by rob006** 2019-01-27 18:49 UTC
Labels: php7

**Comment by brandonkelly** [comment] 2019-01-28 17:14
Considering Yii 2 is scheduled for a new release on Feb 1, and who knows how long it will take for an official fix + the PHP update to be readily available by popular dev environments like Homestead, doesn’t it make sense to work around the issue in Yii?

**Comment by rob006** [comment] 2019-01-28 17:36
@brandonkelly How?

**Comment by samdark** [comment] 2019-01-28 17:59
@brandonkelly if you have solution, please pull request.

**Comment by brandonkelly** [comment] 2019-01-28 21:55
Hm, maybe easier said than done. I’m getting inconsistent results with different versions of the code, and even when I can get PHP to get past that one line, it’ll end up hitting the same bug in other dependencies, and even Composer class loader files. So probably not worth a workaround.

**Comment by rob006** [comment] 2019-01-28 21:58
If you want a workaround, you should change opcache settings for your PHP: https://bugs.xdebug.org/view.php?id=1583#c4820
