### ISSUE TITLE
php7的开发者们是家里有事儿？

### ISSUE THREAD

**Issue by kaikaige** [yiisoft/yii2#17499] opened 2019-08-07 05:43 UTC
### What steps will reproduce the problem?
php7.2的开发者们是怎么想的！ 一个object定义为关键字，使我我们的项目升级如此困难，谁知道他们是怎么想的，针对yii2.0 ?
### What is the expected result?
Cannot use 'Object' as class name as it is reserved
### What do you get instead?
Cannot use 'Object' as class name as it is reserved
### Additional info
Cannot use 'Object' as class name as it is reserved

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.23
| PHP version     | 7.24|
| Operating system | Mac os

**Comment by alex-code** [comment] 2019-08-07 06:59
https://github.com/yiisoft/yii2/issues/7936 What version are you using? this has been in since 2.0.13 November 03, 2017

**Comment by rob006** [comment] 2019-08-07 08:03
Duplicate of https://github.com/yiisoft/yii2/issues/14823. See https://github.com/yiisoft/yii2/issues/14823#issuecomment-394314404

**Closed by rob006** 2019-08-07 08:03 UTC
