### ISSUE TITLE
Create 2.0.16 release

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2#16885] opened 2018-11-13 08:01 UTC
Latest stable release is from March.
There have been quite some bugfixes.

2.0.16 was scheduled for 3rd quarter 
- https://github.com/yiisoft/yii2/blob/master/ROADMAP.md
- https://github.com/yiisoft/yii2/milestone/25
  Issues should be moved to 2.0.17

I think it also makes sense to have a `2.x` branch.

https://github.com/orgs/yiisoft/projects/14

**Comment by samdark** [comment] 2018-11-13 09:19
There are some critical issues to be fixed. I've already moved some to next milestone but there are still plenty to check. If you have some time to burn, help is really appreciated.

**Comment by schmunk42** [comment] 2018-11-14 14:12
Which ones are the critical ones ... "ready for adoption" + "bug"?

**Comment by schmunk42** [comment] 2018-11-15 07:18
Can you post a link to a filtered view for triaged issues?

**Comment by samdark** [comment] 2018-11-16 11:40
https://github.com/yiisoft/yii2/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.16+label%3A"status%3Aready+for+adoption"

**Comment by schmunk42** [comment] 2018-11-16 11:53
I think it would be good to adjust the release policy for 2.x slightly.
When looking at the [changelog](https://github.com/yiisoft/yii2/blob/master/framework/CHANGELOG.md#2016-under-development) there are almost 80(!) bugs fixed for `2.0.16` - why keep them back? Issuing a patch release is perfectly fine.

The remaining open ones are looking rather hard and complicated to me (half of them are for PgSQL, MSSQL and Oracle), IMHO there's no need to wait until all of them are fixed to get a new release.

We're having a much greater flexibility regarding version numbers now.

**Comment by samdark** [comment] 2018-11-16 12:40
> Issuing a patch release is perfectly fine

**Comment by schmunk42** [comment] 2018-11-16 12:46
I'd at least at a "critical" label then.

**Comment by samdark** [comment] 2018-11-16 14:21
We haven't triaged all issues for the milestone so haven't applied labels yet.

**Comment by machour** [comment] 2019-01-14 23:11
I went carefully over all issues with milestone 2.0.16 and postponed all non-critical issues to 2.0.17.

My definition of "non-critical" being: *issue was already present for more than two 2.0.X releases, doesn't look like a 2.0.15 regression and isn't vital to 2.0.16.*

We're down to 7 issues, including this one:

- #16959: Related to sessions, awaiting feedback from reporter
- #16703: Important change introduced in 2.0.14. Should be documented.
- #15931: Should have been fixed in 2.0.15.1, but there are still some problems.
- #15876: Weird thing noticed by @cebe while reviewing #15871, might be worth checking carefully before next release
- #15552: Non critical but a PR is provided. Can be postponed.
- #15482: Old problem with a recent PR. Can be postponed.

**Comment by samdark** [comment] 2019-01-16 09:51
Another thing: https://github.com/yiisoft/yii2/issues/16891. Regression.

**Comment by samdark** [comment] 2019-01-17 14:34
Need to release ElasticSearch before doing core release. See #16891

**Comment by machour** [comment] 2019-01-21 09:31
So far so good 🏅 aside from this issue (and I'm covering a load of Yii features)

**Comment by schmunk42** [comment] 2019-01-21 09:47
Also related to 2.0.16 - https://github.com/yiisoft/yii2/issues/17049

**Comment by bizley** [comment] 2019-01-21 10:01
@machour this looks like a mistake - I'll prepare fix.

**Comment by SilverFire** [comment] 2019-01-21 13:39
It seems that we are ready to release?

**Comment by machour** [comment] 2019-01-21 14:12
There's still #16780, but not sure it's a regression or if it can be postponed.

I think we need to test the release a bit more with basic/advanced & devs apps, seeing that we just fixed two "nasty" regressions today. Feb 1 seems like a good release date.

**Comment by samdark** [comment] 2019-01-21 18:10
@SilverFire we need to review issues of basic/advanced apps. I'm starting to write announcement meanwhile.

**Comment by samdark** [comment] 2019-01-27 18:53
Seems all the preparation things in this repo are completed. Closing. Will track things in a project: https://github.com/orgs/yiisoft/projects/14

**Closed by samdark** 2019-01-27 18:53 UTC

**Comment by s1lver** [comment] 2019-01-28 07:41
> Seems all the preparation things in this repo are completed. Closing. Will track things in a project: https://github.com/orgs/yiisoft/projects/14

This link is not available

**Comment by samdark** [comment] 2019-01-28 10:54
Fixed.
