### ISSUE TITLE
How to check user can access controller/action in yii2

### ISSUE THREAD

**Issue by noppakun** [yiisoft/yii2#7232] opened 2015-02-11 09:49 UTC
In yii v.1.x can use Yii::app()->user->checkAccess('customer/list') ,
but it not work in yii2,
I try to use Yii::app()->user->can() it work only for permission , not work for cortroller/action

**Comment by samdark** [comment] 2015-02-11 09:52
Duplicate of https://github.com/yiisoft/yii/issues/3749

**Closed by samdark** 2015-02-11 09:52 UTC
