### ISSUE TITLE
Error while sending QUERY packet.

### ISSUE THREAD

**Issue by cleippi** [yiisoft/yii2#12680] opened 2016-10-05 16:55 UTC
### What steps will reproduce the problem?
I'm not sure. It seems to happen intermittently. From what I can tell from my researching, it sounds like there's a MYSQL limit that's being broken to get a query packet error. However, my queries are nowhere near the max limit. See below query, it's just running a basic select.

### What do you get instead?

I'm getting occasional errors. An example is below:

exception 'yii\base\ErrorException' with message 'Error while sending
QUERY packet. PID=6401' in
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Command.php:900
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Error
while sen...', '/home/bookspro/...', 900, Array)
#1
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Command.php(900):
PDOStatement->execute()
#2
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Command.php(376):
yii\db\Command->queryInternal('fetch', NULL)
#3 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Query.php(247):
yii\db\Command->queryOne()
#4
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/ActiveQuery.php(295):
yii\db\Query->one(NULL)
#5
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/BaseActiveRecord.php(107):
yii\db\ActiveQuery->one()
#6 /home/bookspro/booksproutapp/common/models/User.php(426):
yii\db\BaseActiveRecord::findOne(Array)
#7 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/User.php(665):
common\models\User::findIdentity(2507)
#8 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/User.php(188):
yii\web\User->renewAuthStatus()
#9 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/User.php(340):
yii\web\User->getIdentity()
#10
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Component.php(130):
yii\web\User->getIsGuest()
#11
/home/bookspro/booksproutapp/frontend/controllers/ReviewRequestController.php(72):
yii\base\Component->__get('isGuest')
#12 [internal function]:
frontend\controllers\ReviewRequestController->actionView('11',
'totally-coached...')
#13
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/InlineAction.php(55):
call_user_func_array(Array, Array)
#14
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Controller.php(154):
yii\base\InlineAction->runWithParams(Array)
#15
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Module.php(454):
yii\base\Controller->runAction('view', Array)
#16
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/Application.php(87):
yii\base\Module->runAction('review-request/...', Array)
#17
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Application.php(375):
yii\web\Application->handleRequest(Object(yii\web\Request))
#18 /home/bookspro/public_html/index.php(18):
yii\base\Application->run()
#19 {main}

Next exception 'yii\db\Exception' with message 'Error while sending
QUERY packet. PID=6401
The SQL being executed was: SELECT * FROM `user` WHERE (`id`=2507) AND
(`status`=10)' in
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Schema.php:633
Stack trace:
#0
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Command.php(915):
yii\db\Schema->convertException(Object(yii\base\ErrorException),
'SELECT * FROM `...')
#1
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Command.php(376):
yii\db\Command->queryInternal('fetch', NULL)
#2 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/Query.php(247):
yii\db\Command->queryOne()
#3
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/ActiveQuery.php(295):
yii\db\Query->one(NULL)
#4
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/db/BaseActiveRecord.php(107):
yii\db\ActiveQuery->one()
#5 /home/bookspro/booksproutapp/common/models/User.php(426):
yii\db\BaseActiveRecord::findOne(Array)
#6 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/User.php(665):
common\models\User::findIdentity(2507)
#7 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/User.php(188):
yii\web\User->renewAuthStatus()
#8 /home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/User.php(340):
yii\web\User->getIdentity()
#9
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Component.php(130):
yii\web\User->getIsGuest()
#10
/home/bookspro/booksproutapp/frontend/controllers/ReviewRequestController.php(72):
yii\base\Component->__get('isGuest')
#11 [internal function]:
frontend\controllers\ReviewRequestController->actionView('11',
'totally-coached...')
#12
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/InlineAction.php(55):
call_user_func_array(Array, Array)
#13
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Controller.php(154):
yii\base\InlineAction->runWithParams(Array)
#14
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Module.php(454):
yii\base\Controller->runAction('view', Array)
#15
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/web/Application.php(87):
yii\base\Module->runAction('review-request/...', Array)
#16
/home/bookspro/booksproutapp/vendor/yiisoft/yii2/base/Application.php(375):
yii\web\Application->handleRequest(Object(yii\web\Request))
#17 /home/bookspro/public_html/index.php(18):
yii\base\Application->run()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      | 5.5.37
| Operating system | Linux of some kind

**Comment by cebe** [comment] 2016-10-05 20:33
which MySQL version are you using? also please provide the table definition of the table you are selecting from.
Also please show the output of `SHOW VARIABLES LIKE 'max_allowed_packet'` in mysql. See http://stackoverflow.com/questions/30753674/error-while-sending-query-packet

**Comment by cleippi** [comment] 2016-10-05 21:06
MYSQL version is:
`mysql  Ver 14.14 Distrib 5.6.33, for Linux (x86_64) using  EditLine wrapper`

The table doesn't seem to be related (I've seen this error happen on other tables as well). For reference though, here's the user table (should be fairly un-modified from the advanced application):

```
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `auth_key` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password_reset_token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` smallint(6) NOT NULL DEFAULT '10',
  `created_at` int(11) NOT NULL,
  `updated_at` int(11) NOT NULL,
  `activation_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=2509 ;
```

And finally,
```
mysql> SHOW VARIABLES LIKE 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 16777216 |
+--------------------+----------+
```

Let me know if there's anything else you need!

**Comment by cebe** [comment] 2016-10-05 21:15
thanks for providing this information, unfortunately I can not see any Yii related issue here and I am not able to reproduce it.

**Comment by cleippi** [comment] 2016-10-05 21:38
Yeah, it happens quite infrequently. Mostly in my backend running cron jobs, so I haven't been too worried about it until today when this happened on the user facing side.

Do you have any recommendations that might point me in the right direction in finding a fix for this problem?

**Comment by cebe** [comment] 2016-10-05 21:51
no idea, sorry. closing this issue unless we found it is yii related.

**Closed by cebe** 2016-10-05 21:51 UTC
Labels: status:need more info

**Comment by cleippi** [comment] 2017-01-20 06:14
Hi again cebe,

I believe I've narrowed down the issue as to what was causing this problem. My host has a very short mysql wait_timeout (30 seconds). It seems that if I use the db connection, do some operations that last longer than 30 seconds, then try and update the database, I get the above error.

For example:

```
$arcsToFollowUpOn = Arc::find()->all();
```

Do operations that last more than 30 seconds, such as sending a bunch of emails with swiftmailer in my case.

```
Arc::updateAll(['follow_up_sent_at' => time()], ['id' => $arc->id]);
```

Is there any way that a person can automatically reopen the connection to the database if it's closed by mysql's wait_timeout?

**Comment by cebe** [comment] 2017-01-20 23:14
this has been discussed in https://github.com/yiisoft/yii2/issues/12634 and https://github.com/yiisoft/yii2/issues/10168
I have no good solution to that right now but you could measure the time and manually reconnect if your script has run longer than 30sec.
