### ISSUE TITLE
Authenticator behavior should always try to authenticate 

### ISSUE THREAD

**Issue by invaderhd** [yiisoft/yii2#7776] opened 2015-03-18 13:04 UTC
I am creating a restful service and I'm using QueryParamAuth.

An example:
```php
public function behaviors() {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticator' => [
                'class' => QueryParamAuth::className(),
                //'only' => ['subscrever', 'noticias', 'noticia', 'categorias'],
                'only' => ['subscrever'],
            ],
            'contentNegotiator' => [
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                ],
            ],
        ]);
    }
```

As you can see only "subscrever" required authentication, if I access "noticias" and provide an access token, the access token is ignored and the user not authenticate. I think this class should have an option to always try to authenticate. 

In my case the action "noticias" return all the news, but for registered users return only the news from the categories that the user subscribe.

**Comment by glagola** [comment] 2015-03-18 18:23
It seems I've similar problem: part of my REST API is accessible to guests. I think authenticator should silently try to authenticate, and ActiveController::checkAccess() / Access Control Filter / RBAC should decide throw UnauthorizedHttpException or not.

**Comment by jpodpro** [comment] 2015-11-18 03:20
this is essentially a duplicate of issue #7405 - an issue i'm surprised has not been addressed. once logged in a user should remain logged in until they logout. yii treats them as if they logged out when they access a public page. strange behavior.

**Closed** 2015-11-18 10:29 UTC
Labels: feature:rest

**Comment by SilverFire** [comment] 2015-11-19 17:01
Fixed https://github.com/yiisoft/yii2/commit/035a9ce0a8642dc1218f4b5d587dfde4daa382f2
