### ISSUE TITLE
\yii\helpers\ArrayHelper::getValue() can't read non existing object property

### ISSUE THREAD

**Issue by IStranger** [yiisoft/yii2#11244] opened 2016-03-31 09:12 UTC
### What steps will reproduce the problem?
Enable max php reporting level `error_reporting(E_ALL);`

##### example 1:
```php
$object         = new \stdClass();
$object->first  = 'firstValue';
$object->second = 'secondValue';

var_dump(\yii\helpers\ArrayHelper::getValue($object, 'first', 'defaultValue'));
var_dump(\yii\helpers\ArrayHelper::getValue($object, 'third', 'defaultValue')); // Throws PHP Notice – yii\base\ErrorException - Undefined property: stdClass::$third
```

##### example 2:
```php
class TestObject
{
    public $first  = 'firstValue';
    public $second = 'secondValue';
}

// ...
$object = new TestObject();
var_dump(\yii\helpers\ArrayHelper::getValue($object, 'first', 'defaultValue'));
var_dump(\yii\helpers\ArrayHelper::getValue($object, 'third', 'defaultValue')); // Throws PHP Notice – yii\base\ErrorException - Undefined property: TestObject::$third
```

### What is the expected result?
For the non existing properties method should return default value without any notices ( `'defaultValue'` for the described examples).

### What do you get instead?
example 1: Throws PHP Notice – yii\base\ErrorException - Undefined property: stdClass::$third
example 2: Throws PHP Notice – yii\base\ErrorException - Undefined property: TestObject::$third

### Additional info
Should be added checking using `property_exists()` into this method.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6
| PHP version      | 5.5.30
| Operating system | MacOSX 10.11 El Capitan

**Comment by SilverFire** [comment] 2016-03-31 11:59
I'm afraid property_exists or reflection will affect `asArray()` performance.
Would you like to take care of this issue and provide a PR with benchmarks?

**Comment by cebe** [comment] 2016-04-02 18:01
duplicate of https://github.com/yiisoft/yii2/issues/7193#issuecomment-73287156, see https://github.com/yiisoft/yii2/pull/10590 for more details and reasoning about it.

**Closed by cebe** 2016-04-02 18:01 UTC
Labels: type:bug
