### ISSUE TITLE
MARS issues with SQLSRV driver

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#9454] opened 2015-08-18 09:04 UTC
I'm using Yii 2.0.4 with MSSQL 2012 database (Microsoft sqlsrv driver). MSSQL has a feature called "Multiple Active Result Sets" (MARS). This can be either enabled or disabled. When enabled, transactions in Active Record classes do not work as expected (see #8523). When disabled, batching of query results does not work as expected:

```php
		$query = Incident::find()->where([">", "last_update_date", $lastRun]);
		foreach ($query->with("inspections")->each() as $incident) { ... }
```
```
2015-08-18 04:35:51 [-][-][-][info][yii\db\Command::query] SELECT * FROM [x].[Y] WHERE [last_update_date] > '17-Aug-2015'
2015-08-18 04:36:45 [-][-][-][info][yii\db\Command::query] SELECT * FROM [X].[Z] WHERE [id] IN (...)
2015-08-18 04:37:15 [-][-][-][error][yii\db\Exception] exception 'PDOException' with message 'SQLSTATE[IMSSP]: The connection cannot process this operation because there is a statement with pending results.  To make the connection available for other queries, either fetch all results or cancel or free the statement.  For more information, see the product documentation about the MultipleActiveResultSets connection option.' in C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Command.php:825
Stack trace:
#0 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Command.php(825): PDOStatement->execute()
#1 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Command.php(349): yii\db\Command->queryInternal('fetchAll', NULL)
#2 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Query.php(206): yii\db\Command->queryAll()
#3 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveQuery.php(130): yii\db\Query->all(NULL)
#4 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(237): yii\db\ActiveQuery->all()
#5 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveQueryTrait.php(170): yii\db\ActiveQuery->populateRelation('inspections', Array)
#6 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveQuery.php(223): yii\db\ActiveQuery->findWith(Array, Array)
#7 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BatchQueryResult.php(147): yii\db\ActiveQuery->populate(Array)
#8 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BatchQueryResult.php(112): yii\db\BatchQueryResult->fetchData()
#9 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BatchQueryResult.php(102): yii\db\BatchQueryResult->next()
#10 C:\inetpub\sites\qtool\commands\InspectionsController.php(36): yii\db\BatchQueryResult->rewind()
#11 [internal function]: app\commands\InspectionsController->actionRun()
#12 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#13 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#14 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('run', Array)
#15 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('run', Array)
#16 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Module->runAction('inspections/run', Array)
#17 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\console\Application.php(137): yii\console\Application->runAction('inspections/run', Array)
#18 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 C:\inetpub\sites\qtool\yii(23): yii\base\Application->run()
#20 {main}

Next exception 'yii\db\Exception' with message 'SQLSTATE[IMSSP]: The connection cannot process this operation because there is a statement with pending results.  To make the connection available for other queries, either fetch all results or cancel or free the statement.  For more information, see the product documentation about the MultipleActiveResultSets connection option.
The SQL being executed was: SELECT * FROM [X].[Z] WHERE [id] IN (...)' in C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Schema.php:595
Stack trace:
#0 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Command.php(840): yii\db\Schema->convertException(Object(PDOException), 'SELECT * FROM [...')
#1 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Command.php(349): yii\db\Command->queryInternal('fetchAll', NULL)
#2 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\Query.php(206): yii\db\Command->queryAll()
#3 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveQuery.php(130): yii\db\Query->all(NULL)
#4 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveRelationTrait.php(237): yii\db\ActiveQuery->all()
#5 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveQueryTrait.php(170): yii\db\ActiveQuery->populateRelation('inspections', Array)
#6 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\ActiveQuery.php(223): yii\db\ActiveQuery->findWith(Array, Array)
#7 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BatchQueryResult.php(147): yii\db\ActiveQuery->populate(Array)
#8 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BatchQueryResult.php(112): yii\db\BatchQueryResult->fetchData()
#9 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\db\BatchQueryResult.php(102): yii\db\BatchQueryResult->next()
#10 C:\inetpub\sites\qtool\commands\InspectionsController.php(36): yii\db\BatchQueryResult->rewind()
#11 [internal function]: app\commands\InspectionsController->actionRun()
#12 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#13 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#14 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\console\Controller.php(91): yii\base\Controller->runAction('run', Array)
#15 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Module.php(455): yii\console\Controller->runAction('run', Array)
#16 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\console\Application.php(161): yii\base\Module->runAction('inspections/run', Array)
#17 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\console\Application.php(137): yii\console\Application->runAction('inspections/run', Array)
#18 C:\inetpub\sites\qtool\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#19 C:\inetpub\sites\qtool\yii(23): yii\base\Application->run()
#20 {main}
Additional Information:
Array
(
    [0] => IMSSP
    [1] => -61
    [2] => The connection cannot process this operation because there is a statement with pending results.  To make the connection available for other queries, either fetch all results or cancel or free the statement.  For more information, see the product documentation about the MultipleActiveResultSets connection option.
)
```

One way to sort this out seems to be to have MARS enabled (default behavior) and execute all AR transaction's statement in a single command like described here: http://blogs.msdn.com/b/cbiyikoglu/archive/2006/11/21/mars-transactions-and-sql-error-3997-3988-or-3983.aspx 

This would require rework in AR MSSQL classes so that Yii2 would queue all SQL commands and execute them in one go.

Maybe you could suggest other solutions, as I need both - transactions support and batching functionality.

**Comment by daliran** [comment] 2015-08-21 08:15
The problems is present also with MSSQL 2008R2 (Yii2 2.0.6, php 5.6.11 x86)

Enabling the MARS feature (default behavior) allows the batch (and each) functions of the ActiveRecord to work as expected, however any attempt of use transactions causes an exception:

```
SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back.
```

Disabling MARS instead, allows the transactions to work, but the batch (and each) functions of the ActiveRecord stop working.

Checking the Yii1 repository I found an interesting issue: https://github.com/yiisoft/yii/issues/112

The problem seems that Yii1 was using old PDO transaction api.
The code has been fixed in the commit: https://github.com/resurtm/yii/commit/62d0119cce4817fd11736d23b4c6b7f72793c3cd

Last version of Yii1 Connection class (createPdoInstance function, row 435):
https://github.com/yiisoft/yii/blob/master/framework/db/CDbConnection.php

I checked also the code of Yii2 and I found that the same issue is also present of the current code (createPdoInstance, row 574):
https://github.com/yiisoft/yii2/blob/master/framework/db/Connection.php

The code:

```php
if (isset($driver) && ($driver === 'mssql' || $driver === 'dblib' || $driver === 'sqlsrv')) {
	$pdoClass = 'yii\db\mssql\PDO';
}
```

needs to be changed to:

```php
if(isset($driver)){
	if($driver === 'mssql' || $driver === 'dblib'){
		$pdoClass = 'yii\db\mssql\PDO';
	} else if($driver === 'sqlsrv'){
		$pdoClass = 'yii\db\mssql\SqlsrvPDO';
	}
}
```

This fix will make the MARS and transactions work together.

**Comment by samdark** [comment] 2015-08-21 09:59
Got it. Do you have time to prepare a pull request?

**Comment by daliran** [comment] 2015-08-21 10:10
Yes, I'm going to do it today.

**Comment by dryu** [comment] 2015-08-21 11:34
How is that using ```SqlsrvPDO``` instead of ```PDO``` going to solve MARS problem? The only different between those classes is ```lastInsertId``` implementation which is slightly different in ```SqlsrvPDO```.

I doubt this will fix the actual issue.

**Comment by daliran** [comment] 2015-08-21 11:40
The problem is that the ```yii\db\mssql\PDO``` class overrides the standard PDO transaction api.
The ```yii\db\mssql\SqlsrvPDO``` class override only the code required for fix the ```lastInsertId``` leaving the standard PDO transaction logic.

Using the correct PDO class both the transaction and the batching works fine for me.

**Closed** 2015-09-28 14:40 UTC
Labels: feature:db, MSSQL

**Comment by adiramardiani** [comment] 2015-11-30 08:43
I still got some issue in v.2.0.6 [PHP: 5.4.22]

`SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back.`

```php
'dsn'			=> 'sqlsrv:Server=192.168.x.x;Database=dbxxx',
```

**Comment by samdark** [comment] 2015-11-30 09:10
If you know how to reproduce it, create a separate issue.

**Comment by adiramardiani** [comment] 2015-11-30 09:28
I write here because i think this issue is related :)
This issue when I use [dynamic form](https://github.com/wbraganca/yii2-dynamicform), running well in mysql, but not in mssql

I write sample code from this plugin (generally same with my current code)
The Controller (sample code)
```php
<?php

namespace app\controllers;

use Yii;
use app\models\Customer;
use app\models\CustomerSearch;
use app\models\Address;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\base\Model;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends Controller
{
    ...

    /**
     * Creates a new Customer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $modelCustomer = new Customer;
        $modelsAddress = [new Address];
        if ($modelCustomer->load(Yii::$app->request->post())) {

            $modelsAddress = Model::createMultiple(Address::classname());
            Model::loadMultiple($modelsAddress, Yii::$app->request->post());

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelsAddress),
                    ActiveForm::validate($modelCustomer)
                );
            }

            // validate all models
            $valid = $modelCustomer->validate();
            $valid = Model::validateMultiple($modelsAddress) && $valid;

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $modelCustomer->save(false)) {
                        foreach ($modelsAddress as $modelAddress) {
                            $modelAddress->customer_id = $modelCustomer->id;
                            if (! ($flag = $modelAddress->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $modelCustomer->id]);
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        return $this->render('create', [
            'modelCustomer' => $modelCustomer,
            'modelsAddress' => (empty($modelsAddress)) ? [new Address] : $modelsAddress
        ]);
    }

    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $modelCustomer = $this->findModel($id);
        $modelsAddress = $modelCustomer->addresses;

        if ($modelCustomer->load(Yii::$app->request->post())) {

            $oldIDs = ArrayHelper::map($modelsAddress, 'id', 'id');
            $modelsAddress = Model::createMultiple(Address::classname(), $modelsAddress);
            Model::loadMultiple($modelsAddress, Yii::$app->request->post());
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsAddress, 'id', 'id')));

            // ajax validation
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ArrayHelper::merge(
                    ActiveForm::validateMultiple($modelsAddress),
                    ActiveForm::validate($modelCustomer)
                );
            }

            // validate all models
            $valid = $modelCustomer->validate();
            $valid = Model::validateMultiple($modelsAddress) && $valid;

            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $modelCustomer->save(false)) {
                        if (! empty($deletedIDs)) {
                            Address::deleteAll(['id' => $deletedIDs]);
                        }
                        foreach ($modelsAddress as $modelAddress) {
                            $modelAddress->customer_id = $modelCustomer->id;
                            if (! ($flag = $modelAddress->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $modelCustomer->id]);
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        return $this->render('update', [
            'modelCustomer' => $modelCustomer,
            'modelsAddress' => (empty($modelsAddress)) ? [new Address] : $modelsAddress
        ]);
    }

    ...
}
```

Model Class
```php
<?php

namespace app\base;

use Yii;
use yii\helpers\ArrayHelper;

class Model extends \yii\base\Model
{
    /**
     * Creates and populates a set of models.
     *
     * @param string $modelClass
     * @param array $multipleModels
     * @return array
     */
    public static function createMultiple($modelClass, $multipleModels = [])
    {
        $model    = new $modelClass;
        $formName = $model->formName();
        $post     = Yii::$app->request->post($formName);
        $models   = [];

        if (! empty($multipleModels)) {
            $keys = array_keys(ArrayHelper::map($multipleModels, 'id', 'id'));
            $multipleModels = array_combine($keys, $multipleModels);
        }

        if ($post && is_array($post)) {
            foreach ($post as $i => $item) {
                if (isset($item['id']) && !empty($item['id']) && isset($multipleModels[$item['id']])) {
                    $models[] = $multipleModels[$item['id']];
                } else {
                    $models[] = new $modelClass;
                }
            }
        }

        unset($model, $formName, $post);

        return $models;
    }
}
```

**Comment by samdark** [comment] 2015-11-30 10:04
New issue please. Here it will be lost.
