### ISSUE TITLE
yiisoft/yii2-authclient facebook deprecated

### ISSUE THREAD

**Issue by iMihael** [yiisoft/yii2#7250] opened 2015-02-12 09:47 UTC
Facebook client is using deprecated protocol. Here what i see, when trying to auth via facebook:
>You must upgrade this app to Graph API v2.x
>v1.0 will be deprecated on April 30, 2015
>Learn how to upgrade

Screenshot: https://qsnapnet.com/snaps/cf27bwuajshjv2t

P.S. Sorry for what I write it here, but I do not found issue tracker on yiisoft/yii2-authclient repo.

**Comment by cebe** [comment] 2015-02-15 00:22
> P.S. Sorry for what I write it here, but I do not found issue tracker on yiisoft/yii2-authclient repo.

This is the correct issue tracker, yii2-authclient is a submodule of this repo.

**Comment by klimov-paul** [comment] 2015-02-16 11:03
Unable to reproduce: authentication and attribute feting works fine.
Also `yii\authclient\clients\Facebook` does not specify version for the Graph API explicetly.

I am closing this untill more particular information arrives.

**Closed by klimov-paul** 2015-02-16 11:03 UTC
Labels: feature:authclient
