### ISSUE TITLE
Call to a member function getRequest() on a non-object in XXX/vendor/yiisoft/yii2/log/Target.php

### ISSUE THREAD

**Issue by vinpel** [yiisoft/yii2#6803] opened 2015-01-08 21:55 UTC
i don't understand why i get this error .... seem random and after all codeception tests

You can view the complete log in this page : https://travis-ci.org/vinpel/gaspSync/builds/46372199

error :
<code>
PHP Fatal error: Call to a member function getRequest() on a non-object in /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/Target.php on line 269

PHP Stack trace:
PHP 1. {main}() /home/travis/.composer/vendor/codeception/codeception/codecept:0
PHP 2. Symfony\Component\Console\Application->run() /home/travis/.composer/vendor/codeception/codeception/codecept:27
PHP 3. yii\log\Logger->flush() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/Logger.php:0
PHP 4. yii\log\Dispatcher->dispatch() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/Logger.php:170
PHP 5. yii\log\Target->collect() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/Dispatcher.php:183
PHP 6. yii\log\FileTarget->export() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/Target.php:111
PHP 7. array_map() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/FileTarget.php:99
PHP 8. yii\log\Target->formatMessage() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/FileTarget.php:99
PHP 9. yii\log\Target->getMessagePrefix() /home/travis/build/vinpel/gaspSync/vendor/yiisoft/yii2/log/Target.php:250
</code>

**Comment by qiangxue** [comment] 2015-01-09 01:14
Duplicate of https://github.com/yiisoft/yii2/pull/6739

**Closed by qiangxue** 2015-01-09 01:14 UTC
