### ISSUE TITLE
Dependencies Injection : register class with configuration problems

### ISSUE THREAD

**Issue by lherry** [yiisoft/yii2#6922] opened 2015-01-19 11:47 UTC
I'm using Yii 2.0.3 and I have an issue when I register dependencies configurations :

I register my dependency in my base controller the following:
```php
\Yii::$container->set(\kartik\widgets\DepDrop::className(), [
            'pluginOptions'=>[
                'loadingText' => Yii::t('app','Loading...'),
            ],        
        ]);
```

And in my form I use the following code:
```html+php
<?= $form->field($model, 'activity_ID')->widget(\kartik\widgets\DepDrop::classname(), [
        'data' => [], // No data before initialization
        'pluginOptions'=>[
            'depends'=>[
                Html::getInputId($model, 'school_year_ID')
            ],
            'placeholder'=>Yii::t('app', '-- Select --'),
            'url'=>Url::to(['list-activities']),
            //'initialize' => true,
        ]
 ]); ?>
```

And when I inspect my widget's configuration, I loose my 'pluginOptions' registered dependency...

If I debug my code, I find the use of `array_merge()` in the `get()` method of the `\yii\di\Container` class which overrides all existant keys (like my array 'pluginOptions')...

Should I use it differently ?
Could  it be pertinent to use the `array_merge_recursive()` function that fix the problem ?

**Comment by lynicidn** [comment] 2015-01-19 11:58
kartik !== yii core

**Comment by lherry** [comment] 2015-01-19 12:04
Yes, I know, it's only for my example... But the Container class is...

**Comment by qiangxue** [comment] 2015-01-19 13:02
Duplicate of https://github.com/yiisoft/yii2/pull/4154

**Comment by cebe** [comment] 2015-01-23 12:16
https://github.com/yiisoft/yii2/pull/4154#issuecomment-70509620

I think we could provide some enhancements to this in the core. Will check the details later.

**Comment by qiangxue** [comment] 2015-01-23 14:18
What kind of enhancements are you thinking about?

**Comment by thejahweh** [comment] 2015-09-18 11:07
Are there plans to support this?
If not, then it should be documented as an expected behavior.

**Comment by samdark** [comment] 2016-02-07 08:17
It's expected that properties are overridden. @thehereward do you have an idea on where to document it best?

**Comment by thehereward** [comment] 2016-02-07 15:17
@samdark I think you meant to reference @thejahweh, not me.
For the record, I have no strong opinions on where best to document this behaviour. ;-)

**Comment by samdark** [comment] 2016-02-07 20:47
Yeah. Sorry :)

**Comment by thejahweh** [comment] 2016-02-09 15:18
@samdark hmm I don't know, but definietly somewhere at:
http://www.yiiframework.com/doc-2.0/guide-concept-di-container.html

**Closed** 2016-04-30 18:45 UTC
Labels: type:docs
