### ISSUE TITLE
message/extract ignores Yii::t calls when the message is using params returned from method calls

### ISSUE THREAD

**Issue by fl0v** [yiisoft/yii2#17098] opened 2019-02-03 13:49 UTC
The update to yii 2.0.16 contains commit [5208ef761ed0552d1a4144589b1b7dff4c6fe3e7](https://github.com/yiisoft/yii2/commit/5208ef761ed0552d1a4144589b1b7dff4c6fe3e7) which tries to fix  issue [#16828](https://github.com/yiisoft/yii2/issues/16828).

The code at row [559](https://github.com/yiisoft/yii2/commit/5208ef761ed0552d1a4144589b1b7dff4c6fe3e7?diff=unified#diff-c4a5086d29e4d4b9309010d8f4a58e01R559) creates a bug regarding messages using params passed as a result from another method call:
```php
Yii::t('app', 'Message with param from method call {val}', [
    'val' => \Yii::$app->formatter->asDecimal(23, 4),
]);
```
The above message and all others following in the same file are ignored.

### What steps will reproduce the problem?

Having the following code in your application:
```php
echo PHP_EOL, Yii::t('app', '1. Simple message');
echo PHP_EOL, Yii::t('app', '2. Message with simple param {val}', [
    'val' => 'today',
]);
echo PHP_EOL, Yii::t('app', '3. Message with param from function call {val}', [
    'val' => date('Y-m-d'),
]);

// the next call creates the bug:
echo PHP_EOL, Yii::t('app', '4. Message with param from method call {val}', [
    'val' => \Yii::$app->formatter->asDecimal(23, 4),
]);

// after the bug:
echo PHP_EOL, Yii::t('app', '5. Simple message');
echo PHP_EOL, Yii::t('app', '6. Message with simple param {val}', [
    'val' => 'today',
]);
echo PHP_EOL, Yii::t('app', '7. Message with param from function call {val}', [
    'val' => date('Y-m-d'),
]);
```

Run message/extract with default translator:
```bash
./yii message/extract --source-path=@app --except='/vendor' --languages='en-US' --message-path=@app/messages --mark-unused=1 --overwrite=1 --remove-unused=0 --sort=1 --translator=Yii::t
```

### What is the expected result?

In messages/en-us/app.php:
```php
return [
    '1. Simple message' => '',
    '2. Message with simple param {val}' => '',
    '3. Message with param from function call {val}' => '',
    '4. Message with param from method call {val}' => '',
    '5. Simple message' => '',
    '6. Message with simple param {val}' => '',
    '7. Message with param from function call {val}' => '',
];
```

### What do you get instead?

```php
return [
    '1. Simple message' => '',
    '2. Message with simple param {val}' => '',
    '3. Message with param from function call {val}' => '',
];
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.1
| Operating system | Linux

**Comment by uran1980** [comment] 2019-02-05 21:23
Have the same problem after update to 2.0.16 from 2.0.15.1

**Comment by samdark** [comment] 2019-02-06 20:46
@uran1980, @fl0v would you please try fix @rugabarbo did?

**Comment by fl0v** [comment] 2019-02-06 22:58
it works in my scenario, 
great job @rugabarbo,
10x

PS: imho the code complexity in there is pretty high, i wouldn't be surprised if other scenarios will still uncover bugs in the future.

**Comment by samdark** [comment] 2019-02-07 16:00
@fl0v I agree. The complexity there is quite bad.

**Comment by samdark** [comment] 2019-02-07 17:44
Agree.

**Comment by uran1980** [comment] 2019-02-08 11:11
Worked for me. Thaks folks.

**Comment by Thoulah** [comment] 2019-02-13 19:04
What doesn't work for me is extracting the following strings:

```
echo $form->field($model, 'action')->dropDownList([
	'renew' => Yii::t('app', 'Renewing Licenses'),
	'add' => Yii::t('app', 'Adding Licenses'),
]);
```

**Comment by samdark** [comment] 2019-02-13 21:01
@rugabarbo would you please check this extra case?

**Comment by rugabarbo** [comment] 2019-02-13 21:08
@samdark yes, I'm already exploring it ;)

**Comment by rugabarbo** [comment] 2019-02-14 00:14
@Thoulah I could not reproduce your problem.
See PR #17128 and travis build https://travis-ci.org/yiisoft/yii2/builds/492982953

Can you provide a complete source file for research? If it contains private data, you can send it to me at rugabarbo@gmail.com

**Comment by rugabarbo** [comment] 2019-02-14 08:50
@Thoulah I checked the file you sent me by email. This is also handled correctly.
Are you sure that you use the `master` branch? The problem is fixed only in master.

**Closed** 2019-02-14 09:16 UTC
Labels: status:ready for adoption, type:bug
