### ISSUE TITLE
Session ID changing during login process

### ISSUE THREAD

**Issue by thkillert** [yiisoft/yii2#17259] opened 2019-04-10 13:50 UTC
### What steps will reproduce the problem?
I can not give exact steps of how to reproduce the system without getting in too deep into our application.
Presumably the problem should occur with every session access in a login process which checks session id between cookie and database.
With the login the session id is regenerated and does not fit to the id in database. 

### What is the expected result?
Functional login due to correct comparison between session ids.

### What do you get instead?
Failed login as session id in cookie has changed after login and will not fit to session id in database, therefore second session is created.

### Additional info
We changed the writeCallback in our configuration as follows:
```
'session' => [
    'writeCallback' => function($session){
        return [
                    'created_at' => new \MongoDB\BSON\UTCDateTime(),
                    'actions'=>++$actions,
                    'startsession'=>$startsession,
                    'expire'=>$session->get('expire',time()+1440)
         ];
    }
],
```

to

```
'session' => [
    'writeCallback' => function($session){
       return [
                    'created_at' => new \MongoDB\BSON\UTCDateTime(),
                    'actions'=>++$actions,
                    'startsession'=>$startsession,
                    'id'=>$session->id, //added for Yii 2.0.17.1
                    'expire'=>$session->get('expire',time()+1440),
                    'pid'=>Yii::$app->params['pid']
          ];
    }
],
```

We had to take care of preserving session id in our writeCallback now, which was taken care of in `MultiFieldSession::composeField()` before (ll. 111-115) - commented correspondingly.

In Version 2.0.15.1 everything was working fine, problem aroused after update to version 2.0.17.1.

As we already found a solution/workaround for this problem we only wanted to point to this fact assuming this change was not made intentionally...!?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17.1
| PHP version      | 7.1
| Operating system | Windows 7 / Linux Mint 18.3

**Comment by samdark** [comment] 2019-04-12 13:20
Is it possible to do `git bisect` to find a commit that broke it for your case? I see no other way to solve it since there's no clear way reproducing it for us.

**Comment by rob006** [comment] 2019-04-13 11:07
It may be related to https://github.com/yiisoft/yii2/pull/17188

**Comment by thkillert** [comment] 2019-04-29 09:04
Not explicitly determined by `git bisect` but using github history revealed that the change was made in commit 8bb334b9ae5760f5ad3548f449bf4fe5b9d98d22 to file `yii/web/MultiFieldSession.php`

**Comment by samdark** [comment] 2019-04-30 16:16
@lubosdz any idea?

**Comment by lubosdz** [comment] 2019-05-02 21:11
@thkillert Your implementation was relying on buggy implementation. Method `$this->composeFields($id, $data);` was originally called **after** closing the session, which threw errors if populating custom session DB column with some session value, e.g. UserIdentity->id. 
Since unit tests are passing and nobody else reports similar issue, I reckon you are using your own custom DB session handler .. ? You may possibly need to adjust your code in session `close()`.

Could you check if you call `composeFields()` before closing the session - [like here](https://github.com/yiisoft/yii2/commit/8bb334b9ae5760f5ad3548f449bf4fe5b9d98d22#diff-6f6a191d70c6d117086ec1873e231af5R152)? Eventually check your code where you call `composeFields()` and make sure it is called **before** session closed.

Session `id` is automatically passed into closing handler argument and merged with other custom fields. With proper implementation it works fine, no workarounds needed.

**Closed** 2019-05-09 21:13 UTC
Labels: status:to be verified
