### ISSUE TITLE
Rbac : getUserIdsByRole() returns wrong results when assign role as a nested

### ISSUE THREAD

**Issue by hirenbhut93** [yiisoft/yii2#14103] opened 2017-05-03 07:28 UTC
### What steps will reproduce the problem?
I have created two role one is **Admin** and another is **Author**.

Then i can add **Author role** in **Admin Role** as a child items.

Then i can get which user where assign **Author** role, but **Admin** role user is not return. 

The `getUserIdsByRole()` is not return which user where assign `Admin` role, It's only return those user where role/permission is directly assign.

```php
$auth = Yii::$app->authManager;

$rule = new \app\rbac\UserGroupRule;
$auth->add($rule);

$author = $auth->createRole('author');
$author->ruleName = $rule->name;
$auth->add($author);
// ... add permissions as children of $author ...

$admin = $auth->createRole('admin');
$admin->ruleName = $rule->name;
$auth->add($admin);
$auth->addChild($admin, $author);

$userId = Yii::$app->authManager->getUserIdsByRole('Author'); //only return those user where assign role directly not return admin role of user.
```
### What is the expected result?
Check nested/inherited permissions for given role/permission then return userid.
### What do you get instead?
Only return those user where directly assign role/permission. not check nested.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12-dev
| PHP version      | 7.1
| Operating system | Ubuntu 16

**Comment by samdark** [comment] 2017-05-04 21:55
Yes, indeed currently it returns only directly assigned roles.

**Comment by samdark** [comment] 2017-05-04 21:56
Will dig into it after 2.0.12 release.

**Comment by Kolyunya** [comment] 2017-05-17 13:03
Isn't this a duplicate of https://github.com/yiisoft/yii2/issues/11895?

**Comment by samdark** [comment] 2017-05-17 14:00
It is. Thanks!

**Closed by samdark** 2017-05-17 14:00 UTC
Labels: status:under discussion, type:enhancement
