### ISSUE TITLE
\yii\base\Model::loadMultiple + save() generate redundant queries

### ISSUE THREAD

**Issue by gephaest** [yiisoft/yii2#5375] opened 2014-10-06 10:26 UTC
I was trying to use Multiple models with single form and found strange behavior.
For example: I've form with many load models for edit. I'm changing one row (one model) and saving form. Yii in theory it should execute **one** UPDATE query, but it update **all** models (if page include 100 models will be 100 UPDATES).
![screenshot_34](https://cloud.githubusercontent.com/assets/1038708/4524244/b332d8e0-4d41-11e4-999c-7410d613f617.png)

My code similar to [this](http://www.yiiframework.com/doc-2.0/guide-input-forms.html#handling-multiple-models-with-a-single-form) (Handling multiple models with a single form section).

I think Yii can be smarter and update only changed rows.

**Comment by Erik-r** [comment] 2015-01-03 11:43
@samdark @cebe The issue is failing dirty attributes in AR has been discussed in #5911 and #2790 already.

I personally think it's not done by a documentation. The framework should be able to handle it correctly out of the box because all necessary information is available for the framework. See my thoughts:

Dirty attributes works only if numeric attributes are type casted with rules and strings, texts, dates, times, datetimes are nulled if form delivers an empty string. So each developer has to write rules for all attributes. This is the proposal of samdark. My comment: a) the framework has all knowledge about the attribute type in database. b) Even if you document this most developers would forget this rules.

Often it's not an issue if one record is stored with same values. But then Yii doesn't need dirty attributes. In the above case the storage is inefficient. In case of my app I use an inherited ActiveRecord class which stores data temporal (see http://en.wikipedia.org/wiki/Temporal_database). if a user push save button without a change and if dirty attributes fails the same record is written again with new valid from date.

As qiangxue wrote in #2790 the comparison of new and old attributes can't be done by unprecise comparator (0 != null for numeric values) what is correct from my opinion. Therefore I have overridden the method `getDirtyAttributes`. I use the column type of table schema to decide if the comparison is strict or not. smallint with one character (= bool) is handled unstrict. I know it's an unbeautiful hack, but it works. see part of code:

```php
        $attributes = [];
        $checkAttributes = $this->getAttributes();
        if ($this->getOldAttributes() === null) {
            foreach ($checkAttributes as $name => $value) {
                if (isset($names[$name])) {
                    $attributes[$name] = $value;
                }
            }
        } else {
            $schema = static::getTableSchema();
            $unpreciseTypes = ['void', 'string', 'date', 'datetime', 'time', 'text'];
            foreach ($checkAttributes as $name => $value) {
                $attrType = $schema->columns[$name]->type;
                $attrSize = $schema->columns[$name]->size;
                if (isset($names[$name]) && isset($checkAttributes[$name])){
                    if (array_search($attrType, $unpreciseTypes) || ($attrType === 'smallint' && $attrSize === 1) ){
                        if ($value != $this->getOldAttribute($name)){
                            $attributes[$name] = $value;
                        }
                    } else 
                        {
                        $value = $value === '' ? null : $value;
                        if ($value !== $this->getOldAttribute($name)){
                            $attributes[$name] = $value;
                        }
                        
                    }
                }
            }
        }
```

Probably it would be better to override `setAttributes`of Model in ActiveRecord. Then set values of empty strings to null and type cast all numeric values according to its table schema column type. Afterwards call the parent method. I expect that in this `attributes`and `oldAttributes`will have exactly same values and type without a change. Dirty attributes will work as planned.

**Comment by mohdqasim98** [comment] 2018-07-18 10:30
I am also having the same issue ?
What's the fix for this ?

**Comment by Enrica-r** [comment] 2018-07-18 11:02
@mohdqasim98 Unfortunately nothing changed because in most cases you won't see it and an update with same content isn't remarkable normally.

In my case I have inherited AR and have overridden the method getDirtyAttributes as you can see above. Then I use AR with my namespace but only for these cases in which the bug has an impact.

**Closed** 2021-03-08 13:45 UTC
Labels: type:docs

**Comment by bizley** [comment] 2021-03-10 20:51
Closing due to inactivity. If this should be reopen please write here.
