### ISSUE TITLE
Allowed memory exhausted When use find()->one()

### ISSUE THREAD

**Issue by 2lovecode** [yiisoft/yii2#16401] opened 2018-06-14 10:51 UTC
### What steps will reproduce the problem?
1.My database is Mysql, it's version is 5.7.18.
2.The amount of data that meet the conditions  is about 190000.
3.When I use "ActiveRecord::find()->where(['name' => 'value'])->one()" to find. A yii\base\ErrorException will throw

[yii\base\ErrorException:1] yii\base\ErrorException: Allowed memory size of 134217728 bytes exhausted(tried to allocate 4096 bytes) in ..../vendor/yiisoft/yii2/db/Command.php:842
Stack trace:
\#0 [internal function]: yii\base\ErrorHandler->handleFataError()
\#1 {main}

### What is the expected result?

For find()->one(), yii2 use PDOStatement::execute() to execute a sql and use PDOStatement::fetch() to get a raw. But when execute(), the result set has returned to server. If there is too much data meet the conditions, memory will exhausted. So, can you optimize this situation?

### What do you get instead?
To avoid this situation, we add limit(1) after where() artificially.

ActiveRecord::find()->where(['name' => 'value'])->limit(1)->one()

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.7
| PHP version      | 7.1.7
|Mysql version | 5.7.18
| Operating system |Ubuntu16.04(x86_64)

**Comment by rob006** [comment] 2018-06-14 11:14
Duplicate of #13875

**Closed by rob006** 2018-06-14 11:14 UTC
