### ISSUE TITLE
Guide menu item "Advanced Project Template" has a wrong link

### ISSUE THREAD

**Issue by Vatruha** [yiisoft/yii2#9697] opened 2015-09-16 05:24 UTC
Here http://www.yiiframework.com/doc-2.0/guide-index.html on the left menu we have "Special Topics" item and "Advanced Project Template" subitem with a link "./guide-README.html".

It looks something is wrong with that link...

**Comment by cebe** [comment] 2016-01-24 14:33
duplicate of https://github.com/yiisoft/yii2-apidoc/issues/43

**Closed by cebe** 2016-01-24 14:33 UTC
Labels: ext:apidoc, type:bug
