### ISSUE TITLE
Definitive Guide: Links to Widgets incorrect

### ISSUE THREAD

**Issue by bluezed** [yiisoft/yii2#9233] opened 2015-07-28 08:54 UTC
In the "Definitive Guide" the links to the Bootstrap and jQuery UI widget documentations are incorrect.
They link to the Guide main page rather than the widget pages.

Here's a screenshot:
![Screenshot](http://s19.postimg.org/c5v5gp55v/Yii2_Guide.png)

**Comment by samdark** [comment] 2016-04-30 14:58
Duplicate of #9922

**Closed by samdark** 2016-04-30 14:58 UTC
Labels: type:docs
