### ISSUE TITLE
DB Json field not decoded in asArray() method

### ISSUE THREAD

**Issue by finnan444** [yiisoft/yii2#15999] opened 2018-03-28 15:14 UTC
### What steps will reproduce the problem?
I have a table called 'Menu' in PostgreSQL, data field has json type. Then I populate one row
```PHP
$a = Menu::findOne(110);
$b = Menu::find()->where(['id' => 110])->asArray()->one();
```
```$a->data``` returns an array
```$b['data']``` returns a string with json inside

### What is the expected result?
In my humble opinion, most users expect an Array when they call asArray() method, but somehow it is not decoded as in populate method

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.0.28
| Operating system |CentOs

**Comment by berosoboy** [comment] 2018-03-28 17:19
Duplicate of #15803 ?

**Comment by samdark** [comment] 2018-03-28 19:21
Yes.

**Closed** 2018-03-28 19:20 UTC
Labels: status:under discussion
