### ISSUE TITLE
Add mutators from laravel

### ISSUE THREAD

**Issue by ShNURoK42** [yiisoft/yii2#10063] opened 2015-10-31 05:38 UTC
Hi,

can we add [mutators](http://laravel.com/docs/5.1/eloquent-mutators#accessors-and-mutators) from laravel in our AR?

To get virtual property `frist_name` use:
```
public function getFirstNameAttribute($value)
{
    return ucfirst($value);
}
```

to set virtual property `frist_name` use:

```
public function setFirstNameAttribute($value)
{
    $this->setAttribute('first_name') = strtolower($value);
}
```

**Comment by pana1990** [comment] 2015-10-31 07:26
check this https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md#data-transformation-

**Comment by ShNURoK42** [comment] 2015-10-31 07:32
@pana1990 I know about this. The difference in the name of property.
I think better use $model->created_at than $model->createdAtFormmatedByTimeAgo

**Comment by pana1990** [comment] 2015-10-31 09:02
It sounds good for me and it is easy implement.

**Comment by samdark** [comment] 2015-10-31 11:19
@ShNURoK42 you can define:

```php
public function getCreated_at() { ... }
```

and then use it as:

```php
echo $model->created_at;
```

It's already supported.

**Comment by samdark** [comment] 2015-10-31 11:20
http://www.yiiframework.com/doc-2.0/guide-concept-properties.html

**Comment by kidol** [comment] 2015-10-31 11:53
But if `created_at` is actual db field, it won't call __get of Component: https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L239

So in Laravel it's different.
```php
    public function setFirstNameAttribute($value)
    {
        $this->attributes['first_name'] = strtolower($value);
    }
```

Now when doing

```php
// first_name is db field
$model->first_name = "test";
```
Laravel will automatically call `setFirstNameAttribute($value)` (by method name convention).

So in Yii it's kind of the other way around.

The good thing about Laravel approach seems to be that you can keep accessing the actual field name instead of doing `$firstName` or `getFirstName()`. In the accessor/mutator methods one could then use scenarios to vary return value.

**Comment by samdark** [comment] 2015-10-31 12:09
Duplicate of https://github.com/yiisoft/yii2/issues/9656

**Closed by samdark** 2015-10-31 12:09 UTC
Labels: status:under discussion
