### ISSUE TITLE
Integrity constraint violation (#23000)

### ISSUE THREAD

**Issue by yujiandong** [yiisoft/yii2#11532] opened 2016-05-10 12:00 UTC
Table's column is not null. And form field's value is blank.
When excute '$model->save()', v2.0.7 is OK, but v2.0.8 is ERROR.(Integrity constraint violation (#23000) : the column can not be null)

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8
| PHP version      | 7
| Operating system | centos

**Comment by cebe** [comment] 2016-05-10 12:01
please give more context for reproducing the problem.

**Comment by yujiandong** [comment] 2016-05-10 12:05
v2.0.8's error is:

> Integrity constraint violation – yii\db\IntegrityException
> 
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tags' cannot be null
> The SQL being executed was: INSERT INTO `simpleforum_topic` (`user_id`, `title`, `node_id`, `tags`, `created_at`, `updated_at`, `replied_at`) VALUES ('1', 'asfdasdf', 16, NULL, '1462881723', '1462881723', '1462881723')
> Error Info: Array
> (
>     [0] => 23000
>     [1] => 1048
>     [2] => Column 'tags' cannot be null
> )
> ↵
> Caused by: PDOException
> 
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tags' cannot be null

**v2.0.7 will excute sql:**

> INSERT INTO `simpleforum_topic` (`user_id`, `title`, `node_id`, `tags`, `created_at`, `updated_at`, `replied_at`) VALUES ('1', 'asfdasdf', 16, '', '1462881723', '1462881723', '1462881723')

**Comment by samdark** [comment] 2016-05-10 12:31
Need code of your model. How do you process / validate `tags` field?

**Comment by yujiandong** [comment] 2016-05-10 12:55
```
    public function rules()
    {
        return [
            [['title', 'node_id'], 'required'],
            [['invisible', 'comment_closed', 'alltop', 'top'], 'boolean'],
            ['node_id', 'integer'],
            ['node_id', 'exist', 'targetClass' => '\app\models\Node', 'targetAttribute' => 'id'],
            ['title', 'trim'],
            ['title', 'string', 'length' => [4, 120]],
            ['tags', 'default', 'value' =>''],
        ];
    }

```

**Comment by samdark** [comment] 2016-05-10 13:03
Any other extra processing? Behaviors? beforeSave?

**Comment by yujiandong** [comment] 2016-05-10 13:08
No behaviors, no beforeSave.

Controller's codes
```
        if ( $topic->load($request->post()) && $topic->validate() ) {
                $topic->save(false);
                return $this->redirect(['view', 'id' => $topic->id]);
        }
```

**Comment by yujiandong** [comment] 2016-05-10 13:11
```
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at', 'replied_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }
```

**Comment by klimov-paul** [comment] 2016-05-10 13:12
1) Provide DDL for your problematic table.

2) Print out model attributes before save. Which values it shows?

```php
if ( $topic->load($request->post()) && $topic->validate() ) {
    var_dump($topic->attributes);
    exit;
    $topic->save(false);
    return $this->redirect(['view', 'id' => $topic->id]);
}
```

**Comment by yujiandong** [comment] 2016-05-10 13:17
**1) Provide DDL for your problematic table.**

DROP TABLE IF EXISTS simple_topic;
CREATE TABLE simple_topic (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `created_at` int(10) unsigned NOT NULL,
  `updated_at` int(10) unsigned NOT NULL,
  `replied_at` int(10) unsigned NOT NULL,
  `node_id` smallint(6) unsigned NOT NULL,
  `user_id` mediumint(8) unsigned NOT NULL,
  `reply_id` mediumint(8) unsigned NOT NULL default 0,
  `alltop` tinyint(1) unsigned NOT NULL default 0,
  `top` tinyint(1) unsigned NOT NULL default 0,
  `invisible` tinyint(1) unsigned NOT NULL default 0,
  `closed` tinyint(1) unsigned NOT NULL default 0,
  `comment_closed` tinyint(1) unsigned NOT NULL default 0,
  `comment_count` mediumint(8) unsigned NOT NULL default 0,
  `favorite_count` smallint(6) unsigned NOT NULL default 0,
  `views` mediumint(8) unsigned NOT NULL default 0,
  `title` char(120) NOT NULL,
  `tags` char(60) NOT NULL default '',
  PRIMARY KEY id(`id`),
  KEY alllist(`node_id`, `alltop`, `replied_at`, `id`),
  KEY nodelist(`node_id`, `top`, `replied_at`, `id`),
  KEY hottopics(`node_id`, `created_at`, `comment_count`, `replied_at`),
  KEY updated(`updated_at`),
  KEY node_updated(`node_id`,`updated_at`),
  KEY allcount(`node_id`, `id`),
  KEY user_id(`user_id`,`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**2) Print out model attributes before save. Which values it shows?**

array(16) { ["id"]=> NULL ["node_id"]=> string(1) "9" ["user_id"]=> string(1) "1" ["reply_id"]=> NULL ["created_at"]=> NULL ["updated_at"]=> NULL ["replied_at"]=> NULL ["views"]=> NULL ["comment_count"]=> NULL ["favorite_count"]=> NULL ["alltop"]=> NULL ["top"]=> NULL ["comment_closed"]=> NULL ["invisible"]=> NULL ["title"]=> string(8) "asfdasfd" ["tags"]=> string(0) "" }

**Comment by klimov-paul** [comment] 2016-05-10 13:23
Are you able to save empty string into `tags` column using DAO layer?

```php
Yii::$app->db->schema->insert('simple_topic', [...]);
```

**Comment by yujiandong** [comment] 2016-05-10 13:40
**The code:**
`Yii::$app->db->schema->insert('simpleforum_topic', ['node_id'=> 9, 'user_id'=> 1, 'title'=> 'asfdasfd', 'tags'=>'', 'created_at'=> 1462887122, 'updated_at'=> 1462887122, 'replied_at'=> 1462887122]);`

**The result**

> Integrity constraint violation – yii\db\IntegrityException
> 
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tags' cannot be null
> The SQL being executed was: INSERT INTO `simpleforum_topic` (`node_id`, `user_id`, `title`, `tags`, `created_at`, `updated_at`, `replied_at`) VALUES (9, '1', 'asfdasfd', NULL, '1462887122', '1462887122', '1462887122')
> Error Info: Array
> (
>     [0] => 23000
>     [1] => 1048
>     [2] => Column 'tags' cannot be null
> )
> ↵
> Caused by: PDOException
> 
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tags' cannot be null
> 
> in E:\website\simplebbs\basic\core\vendor\yiisoft\yii2\db\Command.php at line 844

**Comment by klimov-paul** [comment] 2016-05-10 13:53
Please provide which output produces following code:

```php
var_dump(Yii::$app->db->schema->getTableSchema('simpleforum_topic')->getColumn('tags'));
```

**Comment by yujiandong** [comment] 2016-05-10 13:56
object(yii\db\ColumnSchema)#154 (14) { ["name"]=> string(4) "tags" ["allowNull"]=> bool(false) ["type"]=> string(4) "char" ["phpType"]=> string(6) "string" ["dbType"]=> string(8) "char(60)" ["defaultValue"]=> NULL ["enumValues"]=> NULL ["size"]=> int(60) ["precision"]=> int(60) ["scale"]=> NULL ["isPrimaryKey"]=> bool(false) ["autoIncrement"]=> bool(false) ["unsigned"]=> bool(false) ["comment"]=> string(0) "" }

**Comment by klimov-paul** [comment] 2016-05-10 14:12
Now, it is obvious the source of the problem is here:
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchema.php#L116

This check success in your case.
The reason for this is you are using `char` type, which somehow does not recognized as `Schema::TYPE_STRING`.

**Comment by klimov-paul** [comment] 2016-05-10 14:13
The issue caused by commit eaeb9267687b7ea567b460a026a3172461b760de

**Comment by klimov-paul** [comment] 2016-05-10 14:15
Source Pull Request: #9617

**Comment by klimov-paul** [comment] 2016-05-10 14:16
Either condition at `Schema::typecast()` should be updated, or changes at `Schema::typeMap` should be reverted.

**Comment by yujiandong** [comment] 2016-05-10 14:26
why v2.0.7 is ok but v2.0.8 is ng？
please tell me how can i do now？ do not upgrade to v2.0.8 and wait bug fix？
thanks .

**Comment by klimov-paul** [comment] 2016-05-10 14:36
PR #9617 was merged into 2.0.8, thus your bug appears only with this version and later one.
I am unsure, which is the way for proper fix. @samdark and @SilverFire should look into this since they were guiding that PR. @df2 's opinion is also welcome.
Until any patch provided it is obvious solution for you to use 2.0.7.

**Comment by df2** [comment] 2016-05-12 20:31
@klimov-paul can you please provide a summary of what the issue is here?

**Comment by samdark** [comment] 2016-05-12 20:40
@df2 empty string is casted to `null` before model is saved causing problems for not null columns.

**Comment by df2** [comment] 2016-05-13 08:07
Ok, thanks Alex. So previously `char` columns would be parsed as `TYPE_TEXT`. Now they have their own type (`TYPE_CHAR`), but this new string type was missed from the typecast check https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchema.php#L116

**Comment by spaceman9** [comment] 2016-05-13 08:34
FWIW:  I have just come across this bug, when doing a  (ActiveRecord) $model->refresh(). 
Using MySQL the DB column is a 'ccode CHAR(2) NOT NULL', with a value of "", 
After calling the $model->refresh(), calling $model->ccode returns NULL.
I traced the error back to the line above. (https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchema.php#L116)

**Closed** 2016-05-13 12:39 UTC
Labels: feature:db, type:bug
