### ISSUE TITLE
QueryBuilder not building proper UNION with SQLite DB

### ISSUE THREAD

**Issue by petzo** [yiisoft/yii2#9790] opened 2015-09-29 11:26 UTC
`QueryBuilder` in its `build()` method builds SQL which looks like:
```
(SELECT ...) UNION (...)
```
Which doesn't work in SQLite. What works is:
```
SELECT ... UNION ...
```
That is without the parentheses.

What fixes the problem for me is to create custom `build()` and `buildUnion()` methods in the [db/sqlite/QueryBuilder.php](https://github.com/yiisoft/yii2/blob/master/framework/db/sqlite/QueryBuilder.php) that doesn't add the parentheses. 

We stumbled across the issue when following your [Internationalization guide](http://www.yiiframework.com/doc-2.0/guide-tutorial-i18n.html). There we've selected the [yii\i18n\DbMessageSource](http://www.yiiframework.com/doc-2.0/yii-i18n-dbmessagesource.html) and the problem became apparent.

Best regards.

**Comment by nineinchnick** [comment] 2015-09-29 11:30
Possible duplicate of #7992

**Comment by nineinchnick** [comment] 2015-09-29 11:31
Duplicate of #8053.

**Comment by petzo** [comment] 2015-09-29 11:39
Yes, indeed. I tried to search for similar issue but obviously I missed those...

**Comment by nineinchnick** [comment] 2015-09-29 11:45
But reporting that DbMessageSource is not working with SQLite is important. I think actually #8053 may be closed in favor of this one as the description here is better.

**Comment by samdark** [comment] 2015-09-29 11:57
https://github.com/yiisoft/yii2/pull/8054

**Comment by petzo** [comment] 2015-09-29 13:26
@samdark , this solution looks nice, but I'm not sure how it reflects the discussion in #7992 , and its raised questions regarding ORDER and LIMIT. Nevertheless I think it is important that core framework features like i18n work with all of the supported DB drivers, SQLite in this particular case.

**Comment by petzo** [comment] 2015-10-19 12:34
I think that this is important #8054 to be implemented as soon as possible, because without it UNION in SQLite simply does not work at all. Topics raised in #8054 are obviously important for other DBs but SQLite UNIONs should be working, even if not perfect.

**Comment by samdark** [comment] 2015-10-19 12:57
@petzo have you tested solution from #8054?

**Comment by petzo** [comment] 2015-11-10 15:07
Yes, I've tested it and it fixes the issue.

**Closed** 2015-11-11 18:06 UTC
Labels: feature:db, type:bug
