### ISSUE TITLE
javascript form validation trigger the form submition

### ISSUE THREAD

**Issue by massimans** [yiisoft/yii2#13105] opened 2016-12-01 10:52 UTC
trying to validate a form with javascript with
```
$('#order-form').data('yiiActiveForm').submitting = true;
$('#order-form').yiiActiveForm('validate');
```
when form is 
```
<?php $form = ActiveForm::begin(['id' => 'order-form', 'layout' => 'horizontal']); ?>
// somme fields
<?php ActiveForm::end() ?>
```
i expect the form to just validate the fields show error messages if any, but instead the form is submited
| Yii version      | 2.0.10
| PHP version      | 7.0.4
| Operating system | Windows

**Comment by samdark** [comment] 2016-12-01 11:23
@massimans can you try code from current master branch?

**Comment by massimans** [comment] 2016-12-01 11:34
same behavior in master for me, i will try to see whats going on in the javascript code

**Comment by massimans** [comment] 2016-12-01 13:06
apparently `yiiActiveForm.validate()` calls `updateInputs()` witch will submit the form if you you set submitting to true an no error found in the form

**Comment by samdark** [comment] 2016-12-01 13:35
What if you'll set it to false or omit it?

**Comment by massimans** [comment] 2016-12-01 14:07
both cases no validation at all, input dont turn red or green an no event triggred
checked with
```
$('#order-form').on('afterValidate', function(e) {
console.log('afterValidate')
})
$('#order-form').on('beforeValidate', function(e) {
console.log('beforeValidate')
})
$('#order-form').on('beforeValidateAttribute', function(e) {
console.log('beforeValidateAttribute')
})
```

**Comment by SilverFire** [comment] 2016-12-11 19:05
Thank you for the report, fixed

**Comment by SilverFire** [comment] 2017-07-29 18:10
The issue is reopened now because the fix contained a regerssion

**Comment by DarthLegiON** [comment] 2017-09-20 09:01
The bug appears again, I use dev-master version. In 2.0.12, 'validate' method not work instead. Anyway, correct using of this method is impossible right now, isn't it?

**Comment by Shaeldon** [comment] 2018-05-14 10:52
Mabye soon™ ?

**Comment by samdark** [comment] 2018-05-14 11:47
@Shaeldon do you know how to fix it properly?

**Comment by ptolomaues** [comment] 2021-11-07 20:22
Fixed with the crunch, since without
`$(this).data('yiiActiveForm').submitting = true;`
the validation does not work


`diff --git a/~yii.activeForm.js b/yii.activeForm.js
index ab44e0c..5bb8a11 100755
--- a/~yii.activeForm.js
+++ b/yii.activeForm.js
@@ -757,7 +757,9 @@
                 if (data.submitObject) {
                     applyButtonOptions($form, data.submitObject);
                 }
-                $form.submit();
+                if (!data.validate_only) {
+                    $form.submit();
+                }
                 if (data.submitObject) {
                     restoreButtonOptions($form);
                 }
`

**Comment by samdark** [comment] 2021-11-07 21:17
@ptolomaues do you have some time for a pull request?

**Comment by ptolomaues** [comment] 2021-11-08 08:22
@samdark 
I'll try to find a time, but it seems the mentioned fix should be rechecked carefully.
Seems it does not help with the issue as expected.

**Comment by samdark** [comment] 2021-11-11 21:28
@ptolomaues does https://github.com/yiisoft/yii2/pull/19003 help?

**Comment by ptolomaues** [comment] 2021-11-16 10:03
@samdark yes, the auto-submission is skipped in this case

**Closed** 2021-11-26 07:19 UTC
Labels: type:bug, JS
