### ISSUE TITLE
Request a subquery ActiveQuery

### ISSUE THREAD

**Issue by evgenmil** [yiisoft/yii2#9720] opened 2015-09-18 06:03 UTC
Hi.
Why does not the subquery with sql-query?
```
ThisModel::find()
   ->select('id, name, count(*) as count')
   ->from(['u' => ThisModel::findBySql('SELECT * FROM `this_model` WHERE [any condition] LIMIT 10')])
   ->all();
```
Result query in debugger:
```
SELECT `id`, `name`, count(*) as count FROM (SELECT * FROM `this_model`) `u`
```
Thanks.

**Comment by arogachev** [comment] 2015-09-18 06:43
Possible duplicate of #9266. Also title here is not so detailed.

**Comment by cebe** [comment] 2015-09-19 15:41
see https://github.com/yiisoft/yii2/issues/9266#issuecomment-141681362

**Closed by cebe** 2015-09-19 15:41 UTC
