### ISSUE TITLE
Action executed Twice while redirecting

### ISSUE THREAD

**Issue by mmezzawi** [yiisoft/yii2#15920] opened 2018-03-18 19:30 UTC
### What steps will reproduce the problem?

```php
public function actionLaunch()
 {
   return $this->redirect(['site/index']);
 }
	
public function actionIndex()
    {
       if(!empty($_SESSION['basic']))
			$_SESSION['basic']++;
		else
			$_SESSION['basic']= 1;

		echo $_SESSION['basic'];
    }
```

### What is the expected result?
Session will be incremented by one while redirect
which mean the action is executed once

### What do you get instead?
Session will be incremented by two ( not always )
which mean the action is executed twice

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.14.2
| PHP version      |  7.0
| Operating system |  windows

**Comment by FabrizioCaldarelli** [comment] 2018-03-18 21:51
Who is calling actionLaunch? Maybe is the caller make two time the same call?

**Comment by mmezzawi** [comment] 2018-03-19 05:48
@FabrizioCaldarelli 
we are calling the launch action manually in the browser.

@samdark 
we have test it in different cases and it's still reproducible

Thanks.

**Comment by Alex-Code** [comment] 2018-03-19 15:54
Are you clearing the sessions between each test so it's reset?

**Comment by berosoboy** [comment] 2018-03-20 04:04
@mmezzawi are you testing it on Google Chrome?
I faced something similar to this case. But I realized that the problem is caused by Google Chrome.
It only happens when I enter the url manually in the address bar. 
I suspect that Google Chrome launch a anticipated request while you are typing the address.

**Comment by samdark** [comment] 2018-03-20 16:15
Try Firefox. It's the only browser that behaves strictly according to standards nowadays. If it doesn't work in FF then it's something in Yii. If it does and it's a Chrome thing then I'm not surprised. The way it maintains sessions when closing-opening browser is totally against standards but well, it is how it is.

**Comment by mmezzawi** [comment] 2018-03-20 19:57
@berosoboy ,  @samdark 
The issue is only occurring on google chrome, another request is made without been logged in the dev tools , i have used wireshark to monitor this behavior.
The following issue [https://bugs.chromium.org/p/chromium/issues/detail?id=64810](url) and other issue related to the same topic were reported but none has a solution.

Any advice about this  ? 
Thanks in advance

**Comment by berosoboy** [comment] 2018-03-20 20:29
I suspect that is caused by one of these Chrome default settings:
 
![screen shot 2018-03-20 at 17 27 02](https://user-images.githubusercontent.com/7874200/37680896-fdec4baa-2c63-11e8-8565-09df2a197f95.png)

My only advice is to not rely on GET method if you want to change sensitive data in your application.

**Comment by mmezzawi** [comment] 2018-03-20 20:38
Dear @berosoboy ,

That right seems those two features are responsible of this issue.
Currently the issue appear while redirecting to another action ( note no params are sent )

Thanks.

**Comment by berosoboy** [comment] 2018-03-20 20:52
I guess that the issue will happen regardless of redirection.

**Comment by samdark** [comment] 2018-03-20 20:57
Since it's Chrome issue and not Yii issue, closing.

**Closed by samdark** 2018-03-20 20:57 UTC
Labels: status:to be verified

**Comment by mmezzawi** [comment] 2018-03-20 20:58
@samdark @berosoboy, 

Appreciated !!!

**Comment by berosoboy** [comment] 2018-03-20 21:00
You're welcome ;)
