### ISSUE TITLE
limit statement fetch less fows from db than specified

### ISSUE THREAD

**Issue by NewBalanse** [yiisoft/yii2#16519] opened 2018-07-15 14:46 UTC
### What steps will reproduce the problem?
Simple limit statement in query which has lot of 'with' statements.
I see it when i try to fetch rows from db with six nested relations
Here excerpt of my code:
self::find()->with([`users`, function($query) {
        $query->with([
            // here i specify remainded relations
        ])
    }])
    ->where(['mentor_id' -> $mentorId, 'status' => $status])
    ->offset(0) // in firsh query this parameter will be null
    ->limit(10)
    ->all()
### What is the expected result?
I wanr to fetch ten rows from db
### What do you get instead?
I derive only five fows, and when i specify limit(20) i derive only ten rows. In another words i always derive only half of total count which i need.

### Additional info
I fix this problem with orderBy(['id' => SORT_DESC]).
When i try to specify SORT_ASC this lead to getting only half rows of total count which i need 
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.6?
| PHP version      |  7.0.3
| Operating system | 16.04.01 Ubuntu

**Comment by rob006** [comment] 2018-07-15 22:04
Probably duplicate of #13800. See https://github.com/yiisoft/yii2/issues/13800#issuecomment-287726753

**Closed** 2018-11-02 23:06 UTC
Labels: expired, status:need more info
