### ISSUE TITLE
i18n strange behaviour

### ISSUE THREAD

**Issue by turalsprofile** [yiisoft/yii2#10649] opened 2016-01-24 10:26 UTC
# Here is actual problem:

i18n parser completely ignores example below:
```
  <?
            $html = "";
            if ($vacancies) {
                $html .= Html::tag("h2", Yii::t("vacancies", "We have following vacancies:"));

            } else {
                $html .= Html::tag("h2", Yii::t("vacancies", "Currently we have no active vacancies. But you can send your CV to our email address:"));
            }
            echo $html;
            ?>
```

I'm using command below to generate messages:

```
 ./yii message/extract messages-config.php
```

And here is `messages-config.php`'s contents

```
<?php

return [
    'sourcePath' => __DIR__,
    'languages' => ['az', 'en', 'ru', 'tr'],
    'translator' => 'Yii::t',
    'sort' => true,
    'removeUnused' => false,
    'only' => ['*.php'],
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/vendor',
        '/backend',
        '/environments',
        '/tests'
    ],

    'format' => 'db',
    'overwrite' => true,
    'sourceMessageTable' => 'TranslationSourceMessage',
    'messageTable' => 'TranslationMessage',
];
```

I'm trying to figure out why this problem happen, when I'm doing everything based on Yii documentation?

**Comment by samdark** [comment] 2016-01-24 10:28
`@@` means outdated.

**Comment by turalsprofile** [comment] 2016-01-24 10:29
@samdark so AFAIK it's because of removeUnused turned off?

**Comment by samdark** [comment] 2016-01-24 10:32
Yes.

**Comment by samdark** [comment] 2016-01-24 10:33
So the issue is about ignoring the piece of code you've provided. It looks OK so I think parse has a bug.

**Comment by turalsprofile** [comment] 2016-01-24 10:35
@samdark oh god, don't make us wait for 2.0.8, man. :) it's for project which is in production currently. Please fix it ASAP. Hope for understanding

**Comment by samdark** [comment] 2016-01-24 10:46
You can speed it up by fixing it yourself and providing a pull request. Or at least by providing extra unit test with your example that fails.

**Comment by andrewnester** [comment] 2016-01-25 08:42
Hi guys! I've found why the issue is happened, looks like @turalsprofile is using short php tags `<?` instead of `<?php`. That's why parser does not work. I am gonna fix this

**Comment by turalsprofile** [comment] 2016-01-25 08:48
@andrewnester yes you're right, changing <? to <?php fixed problem. @samdark please fix based on Andrew's suggestion. Thank you all, guys.

**Comment by andrewnester** [comment] 2016-01-25 08:53
@turalsprofile I am not sure that it could be fixed in framework. Because you are using `short_open_tag` you need to enable it in php configuration. here is described why http://stackoverflow.com/a/684752

**Comment by andrewnester** [comment] 2016-01-25 09:37
I've tested it with `short_open_tag` enabled, issue appears anyway. That's why I sent PR with fix and test for it

**Comment by klimov-paul** [comment] 2016-01-25 10:01
The source of the problem `token_get_all()` does not support short tags. See:
http://php.net/manual/ru/function.token-get-all.php#92653

> This function not support :
- Old notation :  "<?  ?>" and "<% %>"
- heredoc syntax
- nowdoc syntax (since PHP 5.3.0)

**Comment by andrewnester** [comment] 2016-01-25 10:28
@klimov-paul yes, it's true, then I guess we have no chance to fix it because parsing and replacing short tags is not an option, right?

**Comment by turalsprofile** [comment] 2016-01-25 10:41
Maybe, we can report this issue into php developer community?

**Comment by SilverFire** [comment] 2016-01-25 11:14
I think this issue must be closed as `wontfix` because PHP short tags are not recommended by PSR and probably would be deprecated.

**Closed** 2016-01-25 11:16 UTC
Labels: status:to be verified, type:bug
