### ISSUE TITLE
Assets not updating

### ISSUE THREAD

**Issue by wangchj** [yiisoft/yii2#8197] opened 2015-04-26 21:00 UTC
I am experiencing a very odd issue regarding publishing assets (`.js`, `.css`). For some reason, Yii has stopped publishing updated `.js` files to the `web/assets` directory. I have to manually remove everything from `web/assets` for the updated version to show up. The reason this issue is odd is because the asset manager was working perfectly until last couple of days.

On my system I can see that my `.js` file was modified on a certain time, and the version of the same file in the assets directory has an earlier modification time; so I don't think this is a browser caching issue. It's an issue that updated assets are not being published.

I don't have a clue where to start to finding out what is causing this. Does anyone have any idea on how to fix this?

**Comment by wangchj** [comment] 2015-04-26 21:11
Related to #8190?

**Comment by cebe** [comment] 2015-04-26 21:39
> The reason this issue is odd is because the asset manager was working perfectly until last couple of days.

have you upgraded yii recently? which version are you using?

**Comment by wangchj** [comment] 2015-04-26 21:53
Hi cebe,

To rule out file corruption, I just removed everything from `app/vendor` directory and performed `composer update`.  However, updating did not solve the problem. The last entry in the `CHANGELOG.md` is `2.0.3 March 01, 2015`, so I assume that is the version I am using.

I'm using Ubuntu 14.04.

A workaround for this that I am using is to `forceCopy` on the asset manager.

**Comment by cebe** [comment] 2015-04-26 22:00
you can run `composer show -i` to see installed versions.

**Comment by wangchj** [comment] 2015-04-26 22:11
@cebe I keep the dependencies updated regularly so it is possible that it was working before an update but I cannot say for certain. Also like I said, I just noticed this problem since maybe 1 or 2 days ago. I've been coding on the back-end recently and just recently switch back to front-end; so it could be broken a while back without me noticing.

Or maybe it's just mine computer that's going crazy. Let me set up another instance of my project on another machine. I'll get back to you with my observation.

**Comment by cebe** [comment] 2015-04-27 08:08
you may also try different versions of yii by setting composer.json to require exact version.

**Comment by wangchj** [comment] 2015-04-30 06:30
Tried it with another Linux box and assets seems to be published just fine.

Also just tried it again on my dev machine by removing `forceCopy` and still doesn't update my asset. Something is funky going on here on my computer. Maybe some convention that I am not following causing Yii to freak out. Other than that my app seems to work fine though.

**Comment by wangchj** [comment] 2015-07-18 03:44
I think this is definitely a problem. I'm having the same issue with another Yii2 project. Is nobody else having this issue?

**Comment by Tomino2112** [comment] 2015-11-11 22:01
Same issue here.

My Assets bundle:

```
class AppAsset extends AssetBundle
{
    public $sourcePath = '@frontend/web/assets_src';
    public $jsOptions = array(
        'position' => \yii\web\View::POS_HEAD
    );
    public $css = [
        '//fonts.googleapis.com/css?family=Raleway:100,400,700',
        'css/layout.css',
        'css/ui.css',
        'css/typography.css',
        'css/icons.css',
        'css/main.css',
    ];
    public $js = [
        'js/html5.image.preview.js'
    ];
    public $depends = [
        'yii\bootstrap\BootstrapPluginAsset',
        'yii\web\JqueryAsset',
        'frontend\assets\DotDotDotAsset'
    ];

    /*public function __construct($config = [])
    {
        $this->publishOptions['forceCopy'] = (YII_ENV_DEV || YII_ENV_DEV);

        parent::__construct($config);
    }*/
}
```

As you can see I tried to add the `publishOption` to force copy assets, which works but slows down the website about 10 times. 

It seems its not picking up the change only when you use `sourcePath`

**Comment by SilverFire** [comment] 2015-12-15 21:21
The only way I succeeded to reproduce the problem was setting `chmod` that disallows reading of source `.js` file. Unfortunately, I think that's not the problem @Tomino2112 and @wangchj are talking about, right, guys?

**Comment by SilverFire** [comment] 2016-01-03 15:45
Removing the issue from the milestone 2.0.7 because it does not have the exact way to reproduce and @Tomino2112 with @wangchj are inactive.

**Comment by antoniom** [comment] 2016-01-21 15:01
Same issue for me. My assets bundle looks like this:
```php
class AppAsset extends AssetBundle {

    public $sourcePath = '@webroot';
    public $css = [
        'css/site.css',
    ];
    public $js = [
        'js/keycloak.js',
        'js/app.js',
        'js/app-mocks.js',
        'js/app-directives.js',
        'js/config.js',
        'js/utils.js',
        'js/services/ProfileService.js',
        'js/services/FarmService.js',
        'js/services/ProductService.js',
        'js/services/ProductCategoryService.js',
        'js/services/WeatherService.js',
        'js/controllers/MainController.js',
        'js/controllers/DashboardController.js',
        'js/controllers/FarmIndexController.js',
        'js/controllers/FarmFormController.js',
        'js/controllers/LoginController.js',
        'js/controllers/LogoutController.js',
        'js/controllers/ProductCodeController.js',
        'js/controllers/ProductDetailsController.js',
        'js/controllers/ProductEditController.js',
        'js/controllers/ProductIndexController.js',
        'js/controllers/ProductInitController.js',
        'js/controllers/ProductNewController.js',
        'js/controllers/ProfileController.js',
    ];
    
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
        'frontend\assets\AngularAsset',
        'frontend\assets\PolymerAsset',
    ];

}
```
It seems that the [publish()](https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L443) function in `AssetManager` is treating the bundle as a directory not as a list of separate files. Consequently, `publishDirectory` is called which does not look up for the latest modified file.

**Comment by rubenjleon** [comment] 2016-04-29 20:47
I'm having the same issue where the changes I write to the assets (js or css) do not appear right away.  Eventually they'll take effect.  I noticed is the css file referenced in my AssetBundle was completely empty even though it was registered on the web page.   I'm on a Mac, apache 2 and php 7.

```bash
Composer show -i
bower-asset/bootstrap          v3.3.5  The most popular front-end framework for developing responsive, mobile first projects on the web.
bower-asset/jquery             2.2.3   
bower-asset/jquery.inputmask   3.2.7   jquery.inputmask is a jquery plugin which create an input mask.
bower-asset/punycode           v1.3.2  
bower-asset/typeahead.js       v0.11.1 
bower-asset/yii2-pjax          v2.0.6  
cebe/markdown                  1.1.0   A super fast, highly extensible markdown parser for PHP
ezyang/htmlpurifier            v4.7.0  Standards compliant HTML filter written in PHP
fzaninotto/faker               v1.6.0  Faker is a PHP library that generates fake data for you.
kartik-v/yii2-krajee-base      v1.8.4  Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-widget-typeahead v1.0.1  Enhanced Yii2 wrapper for the Twitter Typeahead plugin (sub repo split from yii2-widgets).
phpspec/php-diff               v1.1.0  A comprehensive library for generating differences between two hashable objects (strings or arrays).
swiftmailer/swiftmailer        v5.4.1  Swiftmailer, free feature-rich PHP mailer
yiisoft/yii2                   2.0.8   Yii PHP Framework Version 2
yiisoft/yii2-bootstrap         2.0.6   The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-codeception       2.0.5   The Codeception integration for the Yii framework
yiisoft/yii2-composer          2.0.4   The composer plugin for Yii extension installer
yiisoft/yii2-debug             2.0.6   The debugger extension for the Yii framework
yiisoft/yii2-faker             2.0.3   Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii               2.0.5   The Gii extension for the Yii framework
yiisoft/yii2-swiftmailer       2.0.5   The SwiftMailer integration for the Yii framework
```

```php
<?php

namespace frontend\components\matrix;

use yii\web\AssetBundle;

class MatrixWidgetAsset extends AssetBundle
{
    public $js = [
        'js/matrix.js',
        'js/jetColorMap.min.js',
    ];

    public $css = [
        'css/matrix.css'
    ];

    public $depends = [
        'yii\web\JqueryAsset'
    ];

    public function init()
    {
        // Tell AssetBundle where the assets files are
        $this->sourcePath = __DIR__ . "/assets";
        parent::init();
    }
}
```

**Comment by temirfe** [comment] 2016-05-02 10:22
I have the same problem, as I noticed this problem occurs when the source is `$sourcePath`. But when the source is `$basePath` and `$baseUrl` there is no problem.

**Comment by rubenjleon** [comment] 2016-05-02 16:40
@temirfe you led me to the answer but I used $sourcePath though:

I learned that `$sourcePath` has precedence over `$basePath` and `$baseUrl` 
```php
    public $sourcePath = '@app/components/matrix/assets';
```

My problem was I created an AssetBundle as part of a custom widget and stored the AssetBundle under the Widget directory tree and didn't know how to properly register the path to the assets.  It's all working perfectly now and no need to delete any of the generated assets to refresh.

Here's the whole code of my AssetBundle:
```php
<?php

namespace frontend\components\matrix;

use yii\web\AssetBundle;

class MatrixWidgetAsset extends AssetBundle
{
    
    public $sourcePath = '@app/components/matrix/assets';
    
    public $js = [
        'js/matrix.js',
        'js/jetColorMap.min.js',
    ];

    public $css = [
        'css/matrix.min.css'
    ];

    public $depends = [
        'yii\web\JqueryAsset'
    ];

    public function init()
    {
        parent::init();
    }

}
```

**Comment by temirfe** [comment] 2016-05-05 04:04
@rubenjleon I did exactly the same, but problem remained. I learned there is another solution:

```
class Asset extends AssetBundle
{
    public $sourcePath = '...';
    public $js = [..];
    public $css = [...];
    public $depends = [...];

    public $publishOptions = [
        'forceCopy' => true,
         //you can also make it work only in debug mode: 'forceCopy' => YII_DEBUG
    ];
}
```
forceCopy forces files to be published in assets folder each time.

**Comment by mmdtl** [comment] 2016-07-30 06:41
I believe reason is the default hash function of AssetManager, It looks like below:
protected function hash($path)
    {
        if (is_callable($this->hashCallback)) {
            return call_user_func($this->hashCallback, $path);
        }
        $path = (is_file($path) ? dirname($path) : $path) . filemtime($path);
        return sprintf('%x', crc32($path . Yii::getVersion()));
    }

The value of $path is $sourcePath of an AssetBundle. When $sourcePath is a directory who has sub directory ,after some files are modified in the sub directory, the last modified time of the sub directory is changed ,but the directory 's last modified time is not change. The hash function only contain the directory's last modified time, so publish js skipped.

**Comment by tunecino** [comment] 2016-07-30 18:13
same here. i fixed it by adding this to my config file:

```php
if (YII_ENV_DEV) {
    ...
    $config['components']['assetManager']['forceCopy'] = true;
}
```

**Comment by Patricy** [comment] 2016-10-28 10:17
> I believe reason is the default hash function of AssetManager, It looks like below:

Thanks, @mmdtl . You right.

As temporary solution I propose put in config:
`    
        $config['components']['assetManager']['hashCallback'] = function($path){
        $mostRecentFileMTime = 0;
        $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path), RecursiveIteratorIterator::CHILD_FIRST);
        foreach ($iterator as $fileinfo) {
            if ($fileinfo->isFile() && $fileinfo->getMTime() > $mostRecentFileMTime) {
                $mostRecentFileMTime = $fileinfo->getMTime();
            }
        }
        $path = (is_file($path) ? dirname($path) : $path) . $mostRecentFileMTime;
        return sprintf('%x', crc32($path . Yii::getVersion()));
    };
`

It works for me.
When you updating css/js in subdirectory of assets sourcePath it does not visible for filemtime function of parent directory.

I will prepare pull request to update AssetsManager with recursive check of assets sourcePath soon

**Comment by dynasource** [comment] 2016-10-31 15:23
@Patricy, to what extent would a recursive check go at cost of performance?

**Comment by samdark** [comment] 2016-11-28 16:17
Yes, the issue is there: http://stackoverflow.com/questions/3620684/directory-last-modified-date

> The mtime (modification time) on the directory itself changes when a file or a subdirectory is added, removed or renamed.
> 
> Modifying the contents of a file within the directory does not change the directory itself, nor does updating the modified times of a file or a subdirectory. If you change the permissions on the directory, the ctime changes but the mtime does not.

**Comment by samdark** [comment] 2016-11-28 16:21
The performance cost may be significant since getting proper mtime mean recursively walking over everything in a directory.

**Comment by brandonkelly** [comment] 2017-02-13 15:12
We are able to reliably reproduce this whenever a nested file has a modification date that is greater than the parent directory – especially easy to reproduce when the file is in a subdirectory of the asset bundle’s root path.

For Craft CMS, we’ve fixed this by [overriding `AssetManager::hash()`](https://github.com/craftcms/cms/blob/4b86957674abe11ac427248a7bcf8beed3607c8e/src/web/AssetManager.php#L68-L78), replacing the `filemtime()` call with a call to our [`craft\helpers\FileHelper::lastModifiedTime()`](https://github.com/craftcms/cms/blob/4b86957674abe11ac427248a7bcf8beed3607c8e/src/helpers/FileHelper.php#L343-L360) method, which recursively loops through all sub-files/directories and returns the true latest modified time.

Performance impact is negligible. For an asset bundle with 10 nested directories and 128 nested files, I’m seeing about an 0.2-second performance hit on average when calling `getPublishedUrl()` 1,000,000 times.

@cebe @samdark @qiangxue Let me know if you’d like me to submit these changes in a PR.

**Comment by cebe** [comment] 2017-02-13 19:16
@brandonkelly this seems similar to what is being discussed in #608. I think adding such an algorithm as an option would be a good addition.

**Comment by schmunk42** [comment] 2017-02-13 19:58
I also think that's the way to go. The performance cost is negligible, IMHO - for development - compared to other solutions.

Can't we just use `FileHelp::findFiles()` on the `$path` during "`deepHashing`" (maybe even filter css,js,less,... files) - and call `max()` for all `mtime()` on the list? ... Will try this via `hashCallback` and report.

**Comment by samdark** [comment] 2017-02-13 20:54
I don't think it should be optional. Current behavior is basically not reliable. Clearly a bug.

**Comment by Patricy** [comment] 2017-02-14 08:06
Maybe would be good to implement some exclude directories list from everytime hash checking.
I.e. to have possibility  to exclude vendors assets from checks, I will clean assets manually after composer updates,

**Comment by rob006** [comment] 2017-02-14 08:43
> Performance impact is negligible. For an asset bundle with 10 nested directories and 128 nested files, I’m seeing about an 0.2-second performance hit on average when calling getPublishedUrl() 1,000,000 times.

Are you testing this by calling `getPublishedUrl()` in a single loop? Do you call `clearstatcache()` after each cycle?

**Comment by brandonkelly** [comment] 2017-02-21 20:01
@rob006 Yes, I just made a for-loop for 1-1000000, and called `getPublishedUrl()` for the source directory path within it, and compared the microtime before/after the loop. Did not call `clearstatcache()` within the loop as I was looking for the real-world performance hit.

**Comment by rob006** [comment] 2017-02-21 20:13
@brandonkelly But this makes your test useless. PHP caches results of `filemtime()` for better performance, so only first call of `getPublishedUrl()` shows real performance hit, rest of calls uses cached data which makes this test completely unreliable.

**Comment by brandonkelly** [comment] 2017-02-21 20:26
Well, there's still all the recursive directory scanning that had to happen on each iteration, which I don't believe PHP caches.

**Comment by schmunk42** [comment] 2017-02-24 12:43
I tried this for local development with good results:

```
     'hashCallback' => getenv('APP_ASSET_FORCE_PUBLISH') ? function ($path) {
                $files = \yii\helpers\FileHelper::findFiles(
                    $path, 
                    ['only' => ['*.js', '*.css', '*.less']]
                );
                foreach ($files as $file) {
                    $max = max(0, filemtime($file));
                }
                return hash('sha256', $path.$max);
            } : null,
```

**Comment by sqiva** [comment] 2017-03-15 09:27
`<?php
namespace app\assets;
use yii\web\AssetBundle;

class AppAsset extends AssetBundle
{
	public $basePath = '@webroot';
	public $baseUrl = '@web';
	public $css = [
		// 'css/bootstrap.min.css',
		// 'css/normalize.css',
		// 'css/bootstrap-datetimepicker.min.css',
		// 'css/bootstrap-table.min.css',
		// 'css/bootstrap-select.css',
		// 'css/font-awesome.min.css',
		// 'css/sm-core-css.css',
		// 'css/jquery.smartmenus.bootstrap.css',
		// CUSTOM
		'css/freestyle.css',
		'css/theme1.css',
		'fonts/open-sans/opensans.css',
	];
	public $js = [
		// 'js/bootstrap.min.js',
		// 'js/moment.min.js',
		// 'js/bootstrap-datetimepicker.min.js',
		// 'js/bootstrap-table.min.js',
		// 'js/bootstrap-select.min.js',
		'js/bootstrap-maxlength.js',
		'js/jquery.number.min.js',
		'js/Chart.bundle.min.js',
		'js/jquery.smartmenus.min.js',
		'js/jquery.smartmenus.bootstrap.min.js',
		// CUSTOM
		'js/freescript.js',
		'js/list_menu.js',
	];
	public $depends = [
		'yii\web\YiiAsset',
		'app\assets\SqivaAsset'
	];
	public $jsOptions = [
		'position' => \yii\web\View::POS_HEAD
	];
}
`

`<?php
namespace app\assets;

class SqivaAsset extends \yii\web\AssetBundle
{
    public $sourcePath = '@vendor';
    // public $basePath = '@vendor';
    // public $baseUrl = '@webroot';
    public $js = [
        // 'components/jquery/jquery.min.js',
        'twbs/bootstrap/dist/js/bootstrap.min.js',
        // 'moment/moment/moment.js',
        // 'bootstrap-select/bootstrap-select/dist/js/bootstrap-select.min.js',
        // 'eonasdan/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js',
        // 'wenzhixin/bootstrap-table/dist/bootstrap-table.min.js',
        // 'moment/moment/moment.js',
    ];
	public $css = [
        'twbs/bootstrap/dist/css/bootstrap.min.css',
        'components/font-awesome/css/font-awesome.min.css',
        // // 'bootstrap-select/bootstrap-select/dist/css/bootstrap-select.min.css',
        // // 'eonasdan/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css',
        // 'wenzhixin/bootstrap-table/dist/bootstrap-table.min.css',
	];
	// public $jsOptions = [
	// 	'position' => \yii\web\View::POS_HEAD
	// ];

    public function init()
    {
        parent::init();

        // $this->js[] = 'i18n/' . Yii::$app->language . '.js'; // dynamic file added
    }
}
`

buy my assets is not publish to assets folder ? how ?

**Comment by sqiva** [comment] 2017-03-15 09:28
`asd`

**Comment by sqiva** [comment] 2017-03-15 09:29
`<?php
namespace app\assets;

class SqivaAsset extends \yii\web\AssetBundle
{
    public $sourcePath = '@vendor';
    // public $basePath = '@vendor';
    // public $baseUrl = '@webroot';
    public $js = [
        // 'components/jquery/jquery.min.js',
        'twbs/bootstrap/dist/js/bootstrap.min.js',
        // 'moment/moment/moment.js',
        // 'bootstrap-select/bootstrap-select/dist/js/bootstrap-select.min.js',
        // 'eonasdan/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js',
        // 'wenzhixin/bootstrap-table/dist/bootstrap-table.min.js',
        // 'moment/moment/moment.js',
    ];
	public $css = [
        'twbs/bootstrap/dist/css/bootstrap.min.css',
        'components/font-awesome/css/font-awesome.min.css',
        // // 'bootstrap-select/bootstrap-select/dist/css/bootstrap-select.min.css',
        // // 'eonasdan/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css',
        // 'wenzhixin/bootstrap-table/dist/bootstrap-table.min.css',
	];
	// public $jsOptions = [
	// 	'position' => \yii\web\View::POS_HEAD
	// ];

    public function init()
    {
        parent::init();

        // $this->js[] = 'i18n/' . Yii::$app->language . '.js'; // dynamic file added
    }
}
`

**Comment by samdark** [comment] 2017-03-15 09:59
I still think we should have something like that by default.

**Comment by schmunk42** [comment] 2017-03-15 15:30
@samdark So, regarding your https://github.com/yiisoft/yii2/issues/8197#issuecomment-279519022

I also don't like the code very much, but how to solve this?

**Comment by samdark** [comment] 2017-03-15 15:38
Same as you did. Traversing files, collecting mtimes.

**Comment by SilverFire** [comment] 2017-10-08 04:52
> I still think we should have something like that by default.

Disagreed. `filemtime()` gets cached by stat-cache and then works without FS reads.
Any approach with FS traversing will not be cached and will affect performance.

```php
$path = Yii::getAlias('@bower/typeahead.js/src');

$op1 = function () use ($path) {
    $files = \yii\helpers\FileHelper::findFiles(
        $path,
        ['only' => ['*.js', '*.css', '*.less']]
    );
    $max = time();
    foreach ($files as $file) {
        $max = max(0, filemtime($file));
    }
    return hash('sha256', $max);
};

$op2 = function () use ($path) {
    return hash('sha256', filemtime($path));
};

$res = '';
foreach ([$op1, $op2] as $op => $callback) {
    $start = microtime(true);
    for ($i = 0; $i < 100; $i++) {
        $callback();
    }
    $res .= 'Option ' . $op . ': ' . (microtime(true) - $start) . '<br />';
}

return $res;
```

Out with SSD:

```
Option 0: 0.16192412376404
Option 1: 0.043011903762817
Option 2: 0.00028610229492188
```


Out with HDD:

```
Option 0: 0.29494607925415
Option 1: 0.082420864105225
Option 2: 0.0003058910369873
```

I don't even want to enable this as a default for dev env, because we have `linkAssets`.
Closing this issue.

**Closed by SilverFire** 2017-10-08 04:52 UTC
Labels: status:ready for adoption, type:bug
