### ISSUE TITLE
Pagination::totalCount  initialized incorrectly

### ISSUE THREAD

**Issue by taobig** [yiisoft/yii2#16891] opened 2018-11-16 10:21 UTC
### What steps will reproduce the problem?
```
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'totalCount' => $totalCount,//the value is difference from $query->count()
            'pagination' => [
            ],
        ]);
        echo $dataProvider->pagination->page;//always 0
```

### What is the expected result?
 $dataProvider->pagination->page == $_GET['page']
### What do you get instead?
$dataProvider->pagination->page;//always 0
### Additional info
correct code：
```
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'totalCount' => $totalCount,//the value is difference from $query->count()
            'pagination' => [
                totalCount' => $totalCount,// add this line
            ],
        ]);
```
or
```
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'totalCount' => $totalCount,//the value is difference from $query->count()
            'pagination' => [
            ],
        ]);
        $dataProvider->getModels();// add this line
```
I found yii\data\Pagination::getPageCount()  to use `totalCount` without initialized.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1
| PHP version      | 7.2
| Operating system |

**Comment by samdark** [comment] 2018-11-19 22:05
Yes. That's how it is currently. Any idea on how to fix it?

**Comment by samdark** [comment] 2019-01-16 09:39
@GHopperMSK would you please check regression that's caused by solving this task? https://github.com/yiisoft/yii2-elasticsearch/issues/201 Thanks!

**Comment by samdark** [comment] 2019-01-17 14:33
Fixed in in ElasticSearch. Probably a good idea to release it first.

**Closed by samdark** 2019-01-17 14:33 UTC
Labels: severity:important, type:bug
