### ISSUE TITLE
Case sensitivity for Active record relations

### ISSUE THREAD

**Issue by dryu** [yiisoft/yii2#11193] opened 2016-03-25 12:58 UTC
### What steps will reproduce the problem?

1. Have a database with a case-insensitive collation
2. Define a relation between two AR classes using a string primary key
3. Have the data used in the relation link to be in different case in the database
4. Try to pull the related records with AR functionality

### What is the expected result?

AR successfully pulls related records and match them to the primary model using a case-sensitive or case-insensitive match of a string key (whether automatically determined from a database or by complying with configuration option of Yii).

### What do you get instead?

AR successfully pulls related records but not able to match those with primary model because case-sensitive match is always used.

### Additional info

PHP is case-sensitive, but databases can be both: case-sensitive and case-insensetive. This affects working with relations that have the link defined with a string field - sometimes the relation records are not matched because they are in different case in corresponding tables.

```php

class User extends \yii\db\ActiveRecord {
    public static function tableName() { return "Users"; }
    public function primaryKey() { return ["username"]; }
    public function getOrders() {
        $this->getMany(Order::className(), ["username" => "username"];
    }
}

class Order extends \yii\db\ActiveRecord {
    public static function tableName() { return "Orders"; }
    public function primaryKey() { return ["order_id"]; }
    public function getUser() {
        $this->getOne(User::className(), ["username" => "username"];
    }
}
```

Table Users

| username | Name
| ---------------- | ---
| johnsmith | John Smith

Table Orders

| order ID | username | Item
| ---------------- | --- | ---
| 1 | JohnSmith | 12

```$user->orders``` will be empty.

| Q                | A
| ---------------- | ---
| Yii version      | Yii 2.0.7
| PHP version      | 5.5
| Operating system | Windows

**Comment by SilverFire** [comment] 2016-03-25 13:52
Probably related to https://github.com/yiisoft/yii2/issues/9077

**Comment by cebe** [comment] 2016-03-28 03:05
duplicate of #9077

**Closed by cebe** 2016-03-28 03:05 UTC
Labels: feature:db
