### ISSUE TITLE
Dependency Injection and yii\data\ActiveDataProvider

### ISSUE THREAD

**Issue by zharnikov** [yiisoft/yii2#11575] opened 2016-05-17 08:12 UTC
When I use a constructor injection in some ActiveRecord class:

```php
class SomeRecord extends \yii\db\ActiveRecord 
{
    private $obj;

    public function __construct(SomeInterface $obj, $config = []) {
        $this->obj = $obj;
        parent::__construct($config);
    }
}
````

and in the entry script i have:

```php
Yii::$container->set('SomeInterface', 'SomeClass');
```

I got an error on the line 176 in yii\data\ActiveDataProvider:

PHP Recoverable Error – yii\base\ErrorException

Argument 1 passed to SomeRecord::__construct() must implement interface SomeInterface, none given, called in ~/vendor/yiisoft/yii2/data/ActiveDataProvider.php on line 176 and defined

`
$model = new $this->query->modelClass;
`

Looks like here must be the \Yii::createObject($this->query->modelClass) call? and new instance of SomeClass will be injected in the SomeRecord object.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.8 
| PHP version      | 5.5.9
| Operating system | Linux Mint 17.2

**Comment by SilverFire** [comment] 2016-05-20 10:12
Looks like that. Would you like to submit a PR?

**Comment by klimov-paul** [comment] 2016-05-20 10:16
Fixing data provider unlikely will help. See #5786

**Comment by SilverFire** [comment] 2016-05-20 10:23
Yeah, I didn't know that it was discussed earlier. As far as I see, @cebe already tried to fix it, but it is impossible without BC.

Closing as a duplicate of #5786

Thank you @klimov-paul for noticing!

**Closed by SilverFire** 2016-05-20 10:23 UTC
Labels: status:ready for adoption, type:bug
