### ISSUE TITLE
ActiveRecord attributes not array friendly

### ISSUE THREAD

**Issue by razvanphp** [yiisoft/yii2#8098] opened 2015-04-15 21:54 UTC
I needed in my application to have some attributes defined as arrays, but I found that the framework is really against it.

My hacky solution:
````php
public function behaviors()
{
    return [
        [
            'class' => AttributeBehavior::className(),
            'attributes' => [
                ActiveRecord::EVENT_BEFORE_INSERT => 'thumbnails',
                ActiveRecord::EVENT_BEFORE_UPDATE => 'thumbnails',
                ActiveRecord::EVENT_AFTER_FIND => 'thumbnails',
            ],
            'value' => function ($event) {
                $value = $event->sender->thumbnails;
                switch ($event->name) {
                    case ActiveRecord::EVENT_BEFORE_INSERT:
                    case ActiveRecord::EVENT_BEFORE_UPDATE:
                        return json_encode(is_array($value) ? $value : []);
                    case ActiveRecord::EVENT_AFTER_FIND:
                        return json_decode(is_string($value) ? $value : '[]');
                }
            }
        ],
    ];
}
````

If I don't do this, and try to save an array, I get a nasty error deep inside yii:
````
 PHP Notice – yii\base\ErrorException
Undefined offset: 0

    1. in /var/www/current/vendor/yiisoft/yii2/db/Command.php at line 318
    2. in /var/www/current/vendor/yiisoft/yii2/db/ActiveRecord.php – yii\db\Command::update() at line 208
    3. in /var/www/current/vendor/yiisoft/yii2/db/BaseActiveRecord.php – yii\db\ActiveRecord::updateAll() at line 711
    4. in /var/www/current/vendor/yiisoft/yii2/db/ActiveRecord.php – yii\db\BaseActiveRecord::updateInternal() at line 539
    5. in /var/www/current/vendor/yiisoft/yii2/db/BaseActiveRecord.php – yii\db\ActiveRecord::update() at line 584
    6. in /var/www/current/app/controllers/ImageController.php – yii\db\BaseActiveRecord::save() at line 87
````

Another case is when you try to append new items to the array attribute, before saving it:
````php
//  PHP Notice – yii\base\ErrorException – Indirect modification of overloaded property app\models\Image::$thumbnails has no effect
$this->thumbnails[] = $value;

// workaround
$temp = $this->thumbnails;
$temp[] = $value;
$this->thumbnails = $temp;
````

I'm using Yii 2.0.3. Any elegant way of improving this? Native support, via serializing or json_encode would be great, maybe something similar with `yii\rbac\DbManager::addRule()`?

Thank you!

**Comment by cebe** [comment] 2015-04-15 23:31
first of all the solution is not hacky but normal workflow for converting data that needs different representation in php and db. I do not think Yii should dictate a way of how arrays should be transformed when written to DB. Some DBMS may even support getting an array value.
I am closing this as a duplicate of https://github.com/yiisoft/yii2/issues/7481

**Closed by cebe** 2015-04-15 23:31 UTC

**Comment by mdmunir** [comment] 2015-04-29 01:22
https://github.com/mdmsoft/yii2-format-converter/blob/master/SerializeConverter.php
Usage:
```php
public function behaviors()
{
    return [
        [
            'class' => 'mdm\converter\SerializeConverter',
            'format' => 'json',
            'attributes' => [
                'Thumbnails' => 'thumbnails', // 
            ]
        ],
        ...
    ]
}

// *****************
$model = MyModel::findOne($id);

$temp = $model->Thumbnails;
$temp[] = 'xxx';
$model->Thumbnails = $temp;
$model->save();
```
