### ISSUE TITLE
RBAC DbManager::getChildRoles() 

### ISSUE THREAD

**Issue by KengCui** [yiisoft/yii2#13412] opened 2017-01-20 03:24 UTC
### What steps will reproduce the problem?
Call `DbManager::getChildRoles()`
### What is the expected result?
array_key_exists() expects parameter 2 to be array, null given
### What do you get instead?
initialize `$result = [];`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.6.15
| Operating system | win 7

**Comment by samdark** [comment] 2017-01-20 09:40
Duplicate of #12810 which is already fixed in master. Will be there with next release.

**Closed by samdark** 2017-01-20 09:40 UTC
Labels: status:to be verified, type:bug
