### ISSUE TITLE
pjax in layout file clears view file's registered assets 

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8227] opened 2015-04-29 15:20 UTC
I have a pjax widget inside my layout file. The pjax widget calls `\yii\web\View::clear()` in its init. Unfortunately this also clears the view's registered assets, link tags etc., since the view is rendered before the layout.

**Comment by nunomaduro** [comment] 2015-05-19 17:53
For my project I had to remove that line. Can someone explain to me the disadvantages of remove that lane ?

**Comment by nkovacs** [comment] 2015-05-20 07:49
When in pjax mode, the widget is supposed to only output the html content inside itself, that means only assets and meta tags registered inside the widget should be outputted. If you clear it, it means everything goes out. For example, if you register JQueryAsset in your layout file, your pjax page loads will include jquery.js (the js code will prevent the loading of any script files if they're already loaded though).

The problem is that the layout file is rendered after the view file. So the view file is inside the pjax widget (i.e. the assets registered by the view file should be included in the pjax output), but since it has already been rendered (it has registered its assets), the pjax widget will clear its assets.

**Comment by nunomaduro** [comment] 2015-05-20 08:06
After I remove \yii\web\View::clear() my problem is this issue: #6917 . The 3rd party apps don't have is asset's to run.

**Comment by cbepxpa3ym** [comment] 2016-01-25 09:52
Any news? Pjax is useless with that issue.

**Comment by SilverFire** [comment] 2016-01-25 11:07
No, the problem is still unsolved and we don't have any good ideas how to fix it.
However, there is a

### Workaround

Put all your assets to your main application asset and let the client download them on first page load. Ofc, it will eat much traffic on first load, but the problem will be solved.

**Comment by SilverFire** [comment] 2016-01-25 11:09
@nkovacs could we do with CSS files the same, as we've done to JS files, ha? :)

The idea is don't call `View::clear()`, pass it to client side and handle with ajax prefiler. I guess it should word. What do you think?

**Comment by nkovacs** [comment] 2016-01-25 11:22
Yes, the ajax prefilter can also be extended to css files (and it could handle updating title and meta tags, not sure how those are handled currently).
A proper fix would be for a view to commit its assets once it has finished rendering, so the pjax widget would not clear them, only uncommitted assets (e.g. if the pjax widget is in a view, all assets before it are not committed, so they'll be cleared).

**Comment by cbepxpa3ym** [comment] 2016-01-25 13:25
Simple example with standard template. Let's say I want to wrap whole site into Pjax. So, I wrap the inner body in main layout. It works great if I navigate through Hom page, About Us. It looks like a Single Page Application. Very cool! But when I come to Contact Us page I get a problem: pjax do not return inline scripts. So, validation do not work. I can still submit a form and validation will happen on the server-side, and pjax will return html with marked fields. So, in theory I could deal with that. But this is just one simple example, as I said. There could be more situations when inline script is required to be executed.

**Comment by SilverFire** [comment] 2016-01-25 14:22
@cbepxpa3ym the use case you've provided is fixed in current dev version on https://github.com/yiisoft/jquery-pjax
You can check it

**Comment by cbepxpa3ym** [comment] 2016-01-25 14:37
Nope, and this is why: http://c2n.me/3toCnOh.png

**Comment by cbepxpa3ym** [comment] 2016-01-31 19:56
Any ideas?

**Comment by SilverFire** [comment] 2016-01-31 19:58
You're on 2.0.6 stable release, the behavior is changed in the dev-version and will be included in 2.0.7 stable release.

**Comment by cbepxpa3ym** [comment] 2016-01-31 20:05
I used the jquery.pjax.js code from 2.0.7 to test, and provided that screenshot.
Did I something wrong?

**Comment by SilverFire** [comment] 2016-01-31 20:06
Did you clear the cache?

**Comment by cbepxpa3ym** [comment] 2016-01-31 20:07
Well, for real that file cannot do anything with the problem. Because that problem happens here: \yii\web\View::clear()

**Comment by cbepxpa3ym** [comment] 2016-01-31 20:10
In Pjax.php is the line which removes the scripts: http://c2n.me/3tGA04v.png

**Comment by SilverFire** [comment] 2016-01-31 20:16
You show the Pjax::init() method. When you register the JS inside the Pjax block, it will not be removed by pjax init.

**Comment by cbepxpa3ym** [comment] 2016-01-31 20:37
Reproduce:
1. Add Pjax inside div with "wrap" class of main.php: http://c2n.me/3tGCYrx.png
2. Go to home page and open dev tools.
3. Click Contact link in the header.
4. View the source code of ajax request: http://c2n.me/3tGDoXP.png
5. Compare to the page loaded in non-ajax mode: http://c2n.me/3tGDM08.png

**Comment by cbepxpa3ym** [comment] 2016-01-31 20:57
Am I doing something unexpected?

**Comment by cbepxpa3ym** [comment] 2016-02-02 08:47
So, I register scripts inside a pjax block. But they are still removed.

**Comment by SilverFire** [comment] 2016-02-02 09:44
I'm assigned to this issue and will check it asap

**Comment by vistart** [comment] 2016-04-25 05:30
@cbepxpa3ym You should use `renderAjax()` instead of `render()` or `renderPartial()`.
the `renderAjax()` method will register all assets of `Yii::$app->assetManager->bundles`, yes, it also includes assets which were loaded in main layout.
See details in [`yii\web\View::renderAjax()`](https://github.com/yiisoft/yii2/blob/master/framework/web/View.php#L200)
But we should resolve the problem that how to avoid load the assets which have been loaded.

**Comment by cbepxpa3ym** [comment] 2016-04-25 07:56
I should not do anything. PJAX should do all for me. This why it was developed. It loads the same content as regular browser request, and then extracts the required content from there to update some specific part of the page.

**Comment by cbepxpa3ym** [comment] 2016-04-25 08:09
Also, what you explained tells me you do not understand what we are talking about here. So, you can simply implement what you suggested into the pjax to see why you was wrong.

**Comment by vistart** [comment] 2016-04-25 08:20
@cbepxpa3ym Do you really think I was wrong?
The following result is rendered by `renderPartial()` method:
![qq 20160425161501](https://cloud.githubusercontent.com/assets/864657/14777630/eac0104c-0b00-11e6-94ed-dcf0205dc32a.png)
Obviously, the style sheets were not loaded.

then, the following result is rendered by `renderAjax()` method:
![qq 20160425161636](https://cloud.githubusercontent.com/assets/864657/14777663/1d6e7b82-0b01-11e6-9c80-dd521acd3ad6.png)

If I did not do, I dare say it?

**Comment by vistart** [comment] 2016-04-25 08:29
The correct way to use AJAX (also PJAX) is load contents only, not related to any styles, js or any other asset files. If you want to register js, css, or any other assets, please use `renderAjax()`, otherwise reload whole page.

**Comment by nkovacs** [comment] 2016-04-25 08:34
No, it's not. pjax was designed to seamlessly ajax-ify a page, so you don't have to use renderAjax.
It also does load styles and js correctly (and is designed to do that), the only issue is that the Yii pjax widget clears the styles and js files, because it only wants to output the styles and js files that are registered inside the pjax widget.
This works fine if the pjax widget is in the view. It does not work when the widget is in the layout, because of the way Yii renders views and layouts.

**Comment by Alex-Code** [comment] 2016-10-03 12:44
Would this work? Having the layout render the view.

Your controller
```php
$view = 'my-view-file-name';
$this->renderContent($view);
```

Your layout
```php
//....
Pjax::begin()
echo $this->render($content);
Pjax::end();
//....
```

The layout would be loaded first then so the views scripts would come after `Pjax::begin()`

**Comment by dynasource** [comment] 2016-10-31 15:50
we are planning to drop Pjax support with the next Yii2 release 2.1. Many of us know why. Pjax is a time crusher. When it works, its fantastic. But if it doesnt work, the evaporation of our time begins. Many hours of all of us have been wasted on debugging or by making a complex usecase work. It is simply not designed for complex usecases. And we all are ambitious. So we will continue to run into troubles, proven by our 200 subjects in our forum https://github.com/yiisoft/yii2/issues?utf8=%E2%9C%93&q=pjax. 

We are thinking about creating a solution as a complete Yii extension ourselves. We think that making our own extension will cost less time in the end, than to give support on the state of pjax. If there are people eager to contribute, please let us now.

**Closed by dynasource** 2016-10-31 15:50 UTC
Labels: feature:pjax
