### ISSUE TITLE
CAPTCHA is not displayed if the first character in the parameter foreColor is equal to zero

### ISSUE THREAD

**Issue by disasterovich** [yiisoft/yii2#8904] opened 2015-06-25 16:40 UTC
Example:

    public function actions()
        {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'foreColor'=>0x059ED7, //bad
                //'foreColor'=>0x159ED7, //ok
            ],
        ];
        }

**Comment by SilverFire** [comment] 2015-12-23 20:33
Failed to reproduce. Both of the lines work the same.

PHP 5.6.11

**Comment by SilverFire** [comment] 2015-12-23 20:34
I'm closing the issue since it is old and I failed to reproduce it.

@disasterovich is the problem still appears - feel free to text here and show your PHP version.

**Closed by SilverFire** 2015-12-23 20:34 UTC
Labels: status:to be verified
