### ISSUE TITLE
When i use dirtyAttributes after update event it gives drop down field values as dirty attrbute?

### ISSUE THREAD

**Issue by sivabalan02** [yiisoft/yii2#12739] opened 2016-10-13 11:57 UTC
### What steps will reproduce the problem?
When i am using the select tag on the form without changing the select tag value and submit the form means in the dirty attributes select tag attribute was coming. But i doesn't change its value. But i found the problem in db it was stored as the integer field, on the load() function it was loaded as the string. Here how can change its value from string to integer, When i type cast the select tag value from string to integer it was working fine in the dirty attributes. This problem occurs for without the selecting any option on the select tag also

### What is the expected result?
For integer fields the load() function automaticlly change the value from string to integer

### What do you get instead?
Currently i am manually typecast each attribute value into integer

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

**Comment by samdark** [comment] 2016-10-13 19:30
Duplicate of https://github.com/yiisoft/yii2/issues/11741

**Closed by samdark** 2016-10-13 19:30 UTC
