### ISSUE TITLE
ActiveForm odd behavior with GET action

### ISSUE THREAD

**Issue by damirka** [yiisoft/yii2#8729] opened 2015-06-09 19:29 UTC
Well, I've got this default form generated via Gii:

```php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SearchForm */
/* @var $form ActiveForm */
?>
<div class="site-search">
    <?php $form = ActiveForm::begin(['method' => 'GET']); ?>
        <?= $form->field($search, 'search') ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Submit'), ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>
</div><!-- site-search -->
```

If I submit the form URL will look like this:
```
// Submitting first time
example.com/search?SearchForm[search]=testone
// Submitting second time
example.com/search?SearchForm[search]=testone&SearchForm[search]=testtwo
// etc...
```

Then I add 'action' to the options array:
```
    <?php $form = ActiveForm::begin(['method' => 'GET', 'action' => '/search']); ?>
```

And when I submit this one URL contains only last parameter:
```
// Submitting first time
example.com/search?SearchForm[search]=testone
// Submitting second time
example.com/search?SearchForm[search]=testtwo
// etc...
```

**Important:** in both situations 'form' tag contains action attribute and value does not change.

One more note:  it's quite predictable - multiple get params add this elements into form:
```html
<form id="w0" action="/search" method="GET">
  <!-- What are they doing here if it's a single value - non-array parameter -->
  <input type="hidden" name="SearchForm[search]" value="asdasd">
  <input type="hidden" name="SearchForm[search]" value="asdasd">
  <input type="hidden" name="SearchForm[search]" value="asdasd">
  <input type="hidden" name="SearchForm[search]" value="asdasd">
  <div class="form-group field-searchform-search">
     <label class="control-label" for="searchform-search">Search</label>
    <input type="text" id="searchform-search" class="form-control" name="SearchForm[search]">
    <div class="help-block"></div>
  </div>    
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button> 
  </div>
</form>
```

What's wrong with this?

**Comment by cebe** [comment] 2015-06-11 11:05
duplicate of #5985

**Closed by cebe** 2015-06-11 11:05 UTC
Labels: status:to be verified
