### ISSUE TITLE
Bug: Rbac PhpManager delay saving and load

### ISSUE THREAD

**Issue by mdmunir** [yiisoft/yii2#11106] opened 2016-03-13 15:49 UTC
How to reproduce
```php
use yii\web\View;
use yii\rbac\PhpManager;
use yii\helpers\VarDumper;

/* @var $this View */
mt_srand(time());
$name = mt_rand(1111, 9999);
$auth1 = new PhpManager([
    'itemFile' => '@runtime/rbac-items.php'
    ]);

$auth1->removeAll();
$item = $auth1->createRole($name);
$auth1->add($item);

// load from other manager
$auth2 = new PhpManager([
    'itemFile' => '@runtime/rbac-items.php'
    ]);

VarDumper::dump([
    'auth1' => $auth1->getRoles(),
    'auth2' => $auth2->getRoles()
    ], 10, true);
```

Both `authManager` have a different value.
![screenshot from 2016-03-13 22 42 39](https://cloud.githubusercontent.com/assets/5828252/13729673/35adf872-e96d-11e5-84d5-891a267d2d82.png)

Even after redirecting. When redirect to other page, latest item added can not be loaded at first time.

**Comment by Alex-Code** [comment] 2016-03-14 09:10
http://php.net/manual/en/function.file-put-contents.php#82934
According to that comment `file_put_contents` is not atomic.

**Comment by flowip** [comment] 2016-05-17 07:37
It's probably because of caching: https://github.com/yiisoft/yii2/issues/9948.

**Comment by samdark** [comment] 2016-05-17 09:36
Most probably it's duplicate of #9984 as @flowip mentioned.

**Closed by samdark** 2016-05-17 09:36 UTC
