### ISSUE TITLE
innerJoin / innerJoinWith in AR relation

### ISSUE THREAD

**Issue by joe-meyer** [yiisoft/yii2#9047] opened 2015-07-08 18:17 UTC
I have a use case where I want to filter my relation based on that relation's related records such that the order of hierachy is `Dispatch` => `OrdMthdResList` => `Resource`

```
public function getOrdMthdResList()
    {
        return $this->hasMany(
            OrdMthdResList::className(),
            [
                'ord_id' => 'ord_id',
                'opr_seq_no' => 'opr_seq_no'
            ]
        )

            ->andOnCondition('is_actv = 1')
            ->andOnCondition(['>', 'ord_mthd_res_list.user_dec2', 0]);
    }

Results in the following SQL:
SELECT * 
FROM ord_mthd_res_list 
WHERE ((("ord_id" = 'S05691628' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05542558' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05542576' AND "opr_seq_no" = 100) OR ("ord_id" = 'S03797047' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05773189' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05773190' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05773191' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05773192' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05773193' AND "opr_seq_no" = 100) OR ("ord_id" = 'S05773194' AND "opr_seq_no" = 100))) 
AND ((is_actv = 1)
AND (ord_mthd_res_list."user_dec2" > 0))
```

However, I actually need to filter these results down based on the related resource table like so, the problem is that the `Dispatch` attributes for my `ord_id` and `opr_seq_no` are all coming across as null as soon as I try to add my `innerJoinWith()`

```
    public function getOrdMthdResList()
    {
        return $this->hasMany(
            OrdMthdResList::className(),
            [
                'ord_id' => 'ord_id',
                'opr_seq_no' => 'opr_seq_no'
            ]
        )
            ->andOnCondition('is_actv = 1')
            ->andOnCondition(['>', 'ord_mthd_res_list.user_dec2', 0])
            ->innerJoinWith('resource')
            ->andOnCondition(
                'res.res_type = :materialType',
                [':materialType' => 'MATERIAL']
            );
    }
 
 
 
//resulting sql
SELECT ord_mthd_res_list.*
FROM ord_mthd_res_list
INNER JOIN res ON ord_mthd_res_list."plnd_res_id" = res."res_id"
WHERE (((ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL)))
AND (((is_actv = 1)
AND (ord_mthd_res_list."user_dec2" > 0))
AND (res.res_type = 'MATERIAL'))
```

**Comment by lynicidn** [comment] 2015-07-08 18:25
change andOnCondition to andWhere

**Comment by MeyerJL** [comment] 2015-07-08 18:30
@lynicidn these have no effect and as you can see are working properly based on the query that is generated. 

Result after changing `andOnCondition` to `andWhere`
```
SELECT ord_mthd_res_list.* FROM ord_mthd_res_list INNER JOIN res ON ord_mthd_res_list."plnd_res_id" = res."res_id" WHERE (((is_actv = 1) AND (ord_mthd_res_list."user_dec2" > 0)) AND (res."res_type" = 'MATERIAL')) AND (((ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL) OR (ord_mthd_res_list."ord_id" IS NULL AND ord_mthd_res_list."opr_seq_no" IS NULL)))
```

The problem isn't the added conditionals, the problem is that as soon as a join is introduced into the mix, the primary model no longer seems to pass values into the query.

**Comment by lynicidn** [comment] 2015-07-08 18:32
it's new model ?

**Comment by joe-meyer** [comment] 2015-08-03 15:49
@lynicidn I don't understand what you're asking. My problem is that I am unable to use `innerJoinWith` as part of my relation and filter related records, by records related to themselves. 

Another example...

Each `Course` can have many `CourseInstance`, and each `CourseInstance` can have many `ClassStudent`, and finally `ClassStudent` can have a single `Student` record linked to them.

Now lets say that I want to get course 'abc' and all of it's CourseInstances with all Active Students only.

I would expect that from my "Course" model I could have something like..

```
public function getCourseInstance()
{
    return $this->hasMany(
        CourseInstance::className(),
        ['course_id' => 'course_id']
    );
}

public static function getCourseInstructorsAndActiveStudents()
{
    return static::find()
       ->with('courseInstance.activeStudents')
       ->where(['course_title' => 'abc'])
       ->all();
}
```

And in my CourseInstance model I could define my `activeStudents` relation as such:

```
public function getStudent()
{
    return $this->hasOne(Student::className, ['student_id' => 'student_id']);
}

public function getActiveStudents()
{
    return $this->hasMany(
        ClassStudent::className(),
        ['class_id' => 'class_id']
    )->innerJoinWith('student')
    ->andWhere('student.status' => 'A');
}
```

In this case, the problem would occur on the `getActiveStudents()` function because the innerJoinWith student would fail.

**Comment by Faryshta** [comment] 2015-08-03 20:39
on the  OrdMthdResList model modify the getResource method and put the 

            ->andOnCondition(
                'res.res_type = :materialType',
                [':materialType' => 'MATERIAL']
            );

There

**Comment by joe-meyer** [comment] 2015-08-03 21:55
@Faryshta sorry if I wasn't clear the `getResource` method is in the `OrdMthdResList` model. I can't put it in the model that calls `OrdMethodResList` because there's not a logic join there other than via OrdMthdResList and if I do via I've essentially eliminated the benefit of the inner join itself.

**Comment by Faryshta** [comment] 2015-08-03 22:25
how are you invoking the joinWith?

**Comment by joe-meyer** [comment] 2015-08-03 23:21
@Faryshta I need the relation to be independent of the `joinWith` that's the problem. Essentially I want to do 2 left joins, and then an inner join on one of my left joins. I don't have the code in front of me but I  believe it looks something like:

```
Dispatch::find()->with('orders.ordMthdResList.resource')->all();
```

Which I expect to give me ALL related orders, and then `ordMthdResList` being my intermediate table between my resources and my orders, I want to filter these results so that I am ONLY getting a specific resource type ("MATERIAL"). And then I want to additionally get all MATERIAL resource records that qualify.

**Comment by Faryshta** [comment] 2015-08-04 02:06
Dispatch::find()->with('orders.ordMthdResList' => function ($query) {
    $query->joinWith('resources')->andWhere('res.res_type = "MATERIAL"');
} )->all();

**Comment by givisok** [comment] 2015-08-13 11:01
I have the same issues. 

In courses file.
```php
 public function getOffersValues() {
        return $this->hasMany(OffersValues::className(), [ 'good_id' => 'id' ])
            ->andOnCondition([OffersValues::tableName() . '.type' => 'course']);
    }
```
Try to call:
```php
$courses = Courses::find()->joinWith('offersValues')->where( [ '<' , OffersValues::tableName().'.price', 1000] )->all();
```
I got:
```mysql
SELECT `courses`.* FROM `courses` LEFT JOIN `offers_values` ON (`courses`.`id` = `offers_values`.`good_id`) AND (`offers_values`.`type`=:qp0) WHERE `offers_values`.`price` < :qp1
```
```php
 var_dump($courses[0]->id, $courses[0]->offersValues);
```
I got all offers related to courses wihtout filter by price.

If I add select('*') mysql query is change to 
```mysql
SELECT * FROM `courses` LEFT JOIN `offers_values` ON (`courses`.`id` = `offers_values`.`good_id`) AND (`offers_values`.`type`=:qp0) WHERE `offers_values`.`price` < :qp1
```
Nothing change. I got all offers related to courses without filter by price.

**Comment by Faryshta** [comment] 2015-08-13 17:08
@givisok you are confusing the query used to find the courses and the query used to find the offer_values associated to each course.

The first query is fine, it finds you all the courses that has at least one offer_value costing 1000 or less.

then you have to do something similar to the query used to find the offer_values associated to each course. Check http://www.yiiframework.com/doc-2.0/yii-db-activequery.html#joinWith%28%29-detail when a call back is used.

```php
$courses = Courses::find()->innerJoinWith(['offersValues' => function ($query) {
    $query->andWhere( [
        '<' ,
        OffersValues::tableName() . '.price',
        1000
    ]);
}])->all();
```

**Comment by joe-meyer** [comment] 2015-10-12 14:32
@Faryshta what you proposed with the callback produces the exact same results as simply adding the innerJoinWith to my `->hasMany()` relation.

@samdark I really think this is a bug, not a feature (if you have a distinction between the two). I'm not exactly sure why it's doing this, but it's using `NULL` instead of the actual values. The joins themselves are working as they should be, it's the filtering values that don't seem to be making it over.

```
SELECT "ord_mthd_res_list".* 
FROM "ord_mthd_res_list" 
    INNER JOIN "res" ON "ord_mthd_res_list"."plnd_res_id" = "res"."res_id" 
WHERE (
    (is_actv = 1) 
    AND ("ord_mthd_res_list"."user_dec2" > 0)
)
    AND (
    ("ord_mthd_res_list"."ord_id" IS NULL AND "ord_mthd_res_list"."opr_seq_no" IS NULL) 
    OR 
    ("ord_mthd_res_list"."ord_id" IS NULL AND "ord_mthd_res_list"."opr_seq_no" IS NULL)
)
```

**Comment by joe-meyer** [comment] 2015-10-12 15:34
Ok so I tracked this down some more... the problem occurs in the [`buildCompositeInCondition`](https://github.com/yiisoft/yii2/blob/master/framework/db/sqlite/QueryBuilder.php#L346).

Essentially what I'm seeing happen is that the `$values` array keys don't match up with the `$columns` values because when the relation builder sends the columns list forward it prepends it with the table name, this causes a mismatch for for the `isset($value[$column])` 

![image](https://cloud.githubusercontent.com/assets/1292766/10431777/f8335778-70d4-11e5-870b-93e2ba7772a0.png)

Not sure what the best way to fix this would be... perhaps when the filterByRelation is built it should build the values by prepending the table names as well so there's a match? Or perhaps it's safe enough to just grab the last part of the `$columns` values so that the columns match up?

**Comment by cebe** [comment] 2016-04-22 13:39
Having a hard time to reproduce the issue, could someone come up with relation definitions and queries on the records defined in Yii2 unit tests: https://github.com/yiisoft/yii2/tree/master/tests/data/ar ?

**Comment by cebe** [comment] 2016-04-22 14:32
closing this as duplicate of #10201

**Closed by cebe** 2016-04-22 14:32 UTC
Labels: feature:db
