### ISSUE TITLE
extension in the apache (intl) and i18n translations problem

### ISSUE THREAD

**Issue by spiritdead** [yiisoft/yii2#11767] opened 2016-06-16 18:30 UTC
### What steps will reproduce the problem?

install the extension in the apache (intl) and translate this (i18n)

### What is the expected result?

the translate result

### Additional info

Formatting message for language 'es' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ARGUMENT_TYPE_MISMATCH. The message being formatted was: {notificationCount} {notificationCount, plural, =1{New} other{News}}.

```php
'{notificationCount} {notificationCount, plural, =1{New} other{News}}' => '{notificationCount} {notificationCount, plural, =1{New} other{News}}',
```

| Q                | A
| ---------------- | ---
| Yii version      |  2.0.8
| PHP version      | 5.6.*
| Operating system | win / linux / centOS

i see this https://github.com/yiisoft/yii2/issues/1072

and i have passed in the requirements yii2 (is rare)

**Comment by spiritdead** [comment] 2016-06-16 18:35
@samdark help plz or is a bug in the extension apache extension=php_intl.dll

**Comment by spiritdead** [comment] 2016-06-16 18:59
@samdark  well the error is a mayus, plz can add in the documentation this...
http://php.net/manual/en/timezones.php

**Comment by spiritdead** [comment] 2016-06-16 19:05
but the i18n is broken hehe

Formatting message for language 'es' failed with error: Message pattern is invalid: msgfmt_create: message formatter creation failed: U_ARGUMENT_TYPE_MISMATCH. The message being formatted was: {notificationCount} {notificationCount, plural, =1{New} other{News}}.

**Comment by lynicidn** [comment] 2016-06-16 19:50
what is version intl ?

**Comment by lynicidn** [comment] 2016-06-16 19:51
try change
`{notificationCount, plural, `
to
{notificationCount,plural,`

**Comment by spiritdead** [comment] 2016-06-16 20:08
@lynicidn nothing change and the version is our current ICU version is 54.1.

**Comment by lynicidn** [comment] 2016-06-16 20:35
ah, try use
'{notificationCount, plural, =1{# New} other{# News}}'

**Comment by spiritdead** [comment] 2016-06-16 20:36
@lynicidn  nothing :( but if i remove the extension intl work perfectly :S

**Comment by lynicidn** [comment] 2016-06-16 20:36
use `#` instead duplicate variable name

**Comment by spiritdead** [comment] 2016-06-16 20:37
work!

**Comment by spiritdead** [comment] 2016-06-16 20:37
but is rare if i have the {notificationCount} not work and when i remove this and add the # work ?

**Comment by lynicidn** [comment] 2016-06-16 20:37
:clap:

**Comment by spiritdead** [comment] 2016-06-16 20:37
@samdark  plz can add this in the documentations when use INTL ?

**Comment by samdark** [comment] 2016-06-18 14:00
So how the line looks in the end?

**Comment by pstddc** [comment] 2016-06-24 10:35
@samdark строка содержащая 2 раза одну переменную не будет работать
т.е.
{a} {a, plural, =1{One}} - не работает
{a, plural, =1{# One}} - работает

**Comment by cebe** [comment] 2016-06-25 17:24
can you check `{a, number} {a, plural, =1{One}}`? seen this in some versions of intl which have a type mismatch as they first thread a as a string and are then unable to use that string as plural rule input anymore.

**Comment by SilverFire** [comment] 2016-08-05 11:34
@cebe's option works fine. The problem is out of Yii scope, closing

**Closed by SilverFire** 2016-08-05 11:35 UTC
Labels: status:need more info

**Comment by phdcoder** [comment] 2019-11-20 17:05
This error occurs because  of old ICU version on intl module on PHP.  There is some scenarios that is hard to fix it, host servers for example, and a solution is to use the fallback function to format the message provided by Yii itself.   Remove the if enclosing the fallbackformat call  on MessageFormartter::formart .
