### ISSUE TITLE
User can login by cookie only once when `autoRenewCookie` is set to false

### ISSUE THREAD

**Issue by oyyq99999** [yiisoft/yii2#11825] opened 2016-06-26 18:00 UTC
### What steps will reproduce the problem?
1. set `enableAutoLogin` to `true` and `autoRenewCookie` to false
2. Login with a duration set(e.x. 86400), close browser, open the site again, user will auto login.
3. close browser again, and open the site once more, user won't be logged in.
### What is the expected result?

User should be logged in before `duration` has expired.
### Additional info

It switches identity with a `duration` value 0.
https://github.com/yiisoft/yii2/blob/2.0.8/framework/web/User.php#L309

And now, it removes the old cookie.
https://github.com/yiisoft/yii2/blob/2.0.8/framework/web/User.php#L587-L589

And finaly, it doesn't add a new cookie here because the `duration` is set to 0.
https://github.com/yiisoft/yii2/blob/2.0.8/framework/web/User.php#L606-L608

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 7.0.7 |
| Operating system | OS X 10.11.4 |

**Comment by samdark** [comment] 2016-06-26 18:34
What's initial duration?

**Comment by oyyq99999** [comment] 2016-06-27 03:18
In my case I set it to one day(86400)

**Comment by klimov-paul** [comment] 2016-09-06 14:29
Unable to reproduce: user remains logged in after second browser re-open.

> And finaly, it doesn't add a new cookie here because the duration is set to 0.

Being logged in by cookie duration is picked up from this cookie and thus is it not `0`:
https://github.com/yiisoft/yii2/blob/2.0.8/framework/web/User.php#L309

**Comment by oyyq99999** [comment] 2016-09-06 14:37
No, actually I said, **set `autoRenewCookie` to `false`**, and when it is false, it will be 0 in [line 309](https://github.com/yiisoft/yii2/blob/2.0.8/framework/web/User.php#L309).

**Comment by klimov-paul** [comment] 2016-09-06 14:39
I am still unable to reproduce the issue by your description.
Which the correct steps to reproduce it then?

**Comment by oyyq99999** [comment] 2016-09-06 14:44
> 1. set `enableAutoLogin` to `true` and `autoRenewCookie` to false
> 2. Login, close browser, open the site again, user will auto login.
> 3. close browser again, and open the site once more, user won't be logged in.

The actual steps, I think @samdark has reproduced it before. 
And it's a bug in 2.0.8, I haven't checked for 2.0.9 yet.

**Comment by klimov-paul** [comment] 2016-09-06 14:44
Reproduced in IE

**Comment by SilverFire** [comment] 2017-01-22 20:29
If anybody knows how to fix this bug - we will be happy to see your pull request. Thank you in advance

**Comment by SilverFire** [comment] 2017-08-13 18:17
Fixed by 03299e8870eaaeb2714e53452078ca3ba2c86800

**Closed by SilverFire** 2017-08-13 18:17 UTC
Labels: status:ready for adoption, type:bug
