### ISSUE TITLE
Default url parsing logic does not enforce trailing slash or not

### ISSUE THREAD

**Issue by nkovacs** [yiisoft/yii2#8370] opened 2015-05-12 08:56 UTC
If you have actionIndex in SiteController, `site/index` and `site/index/` both work. But if you create a url rule, e.g.:

`'foo/<action:\w+>' => 'site/<action>'`

then only `foo/index` will work, because of #1807.

**Comment by cebe** [comment] 2015-05-12 19:24
duplicate of #7670?

**Comment by nkovacs** [comment] 2015-05-12 19:38
No. `site/index/` should not work either, for the same reasons as #1807, but that would break BC.

**Closed** 2016-08-30 20:54 UTC
