### ISSUE TITLE
Memory usage leak when long operation

### ISSUE THREAD

**Issue by cvelasco88** [yiisoft/yii2#20113] opened 2024-02-10 09:53 UTC
### What steps will reproduce the problem?
Execute many operations on script

### What is the expected result?
script executed

### What do you get instead?
error because Memory limit

### Additional info
Info about PHP inside docker container:
PHP version: 8.3.0
PHP 8.3.0 (cli) (built: Dec 16 2023 02:31:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.0, Copyright (c), by Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
    
| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 8.3.0
| Operating system | Ubuntu [info_system.txt](https://github.com/yiisoft/yii2/files/14228756/info_system.txt)

Using docker "Current version: 4.27.0 (135262)".
![Captura desde 2024-02-10 10-51-09](https://github.com/yiisoft/yii2/assets/2356962/6a0ee8f1-51fb-4ef4-adde-9f3bb59aaff7)

from repo: 
https://github.com/cvelasco88/azerothcore-wotlk/tree/main/apps/web-app

Memory usage on different points (without executing callback & executing callback). Number of records ~50k.

![Captura desde 2024-02-10 10-37-39](https://github.com/yiisoft/yii2/assets/2356962/765a25c9-d887-4dd6-a402-069398299095)

![Captura desde 2024-02-10 10-40-30](https://github.com/yiisoft/yii2/assets/2356962/1c1ae201-530e-4561-bd15-a38cb1b0bb2f)
![Captura desde 2024-02-10 10-40-42](https://github.com/yiisoft/yii2/assets/2356962/dba3afb9-d4c7-4ad5-8f25-317a63da40ec)

**Comment by samdark** [comment] 2024-02-10 11:38
Are you sure it's caused by framework and not the application itself?

**Comment by rob006** [comment] 2024-02-10 14:19
By default `Logger::flush()` does not flush all messages from memory - it only dispatches messages from logger to log targets (that will keep these messages in memory). You need to pass `true` as argument to this method if you want to flush messages completely. 

Also, make sure you don't have debug module active, it will keep all debug info in memory.

**Comment by cvelasco88** [comment] 2024-02-17 12:34
> Are you sure it's caused by framework and not the application itself?

There is where i'm aiming my searching. As it can be seen i tried to free all the variables on the function, so my first suspicious it was some Log system from Yii or whatever. Then i'm wasting time searching and understanding if there is any issue with the PHP itself releaseing memory, and the last point would be the "application" setting the queries in cache, but i don't really know. The point is that on each loop that memory consumption grows too much despite  wanting to force the GC.

I debugged the Logger and the "messages" inner array was empty, so won't be that in my case

**Comment by Webkadabra** [comment] 2024-02-25 00:45
wow dude, learn how to write code for what you're working with. I have Yii rurnning scripts for HOURS without any issues. No point in giving you absolutely any further advice, you have a journey ahead of you. Close this issue, it's ridiculous.

**Comment by bizley** [comment] 2024-02-25 10:35
While I don't like this snarky comment I agree that we should close it. @cvelasco88 feel free to write here if anything new develops regarding the issue.

**Closed by bizley** 2024-02-25 10:35 UTC
Labels: status:need more info

**Comment by Webkadabra** [comment] 2024-02-26 17:40
@bizley I just checked to see what kind of issues are on Yii tracker, and most of them are absolutely ridiculous, like this one. 
To the point that it seems like an opensource terrorism: make a Yii controller with an infinie `while(true)...` and complain Yii has mem leaks
