### ISSUE TITLE
Scalar Relations for Active Record

### ISSUE THREAD

**Issue by Faryshta** [yiisoft/yii2#12491] opened 2016-09-08 06:03 UTC
Lets imagine you need a report for the sales, employees, restockngs and aisles for all the shops in a determined city. The query would look something like this.

```php
Shop::find()->select([
    'shop.*',
    'salesCount' => 'count(distinct sale.id)',
    'soldAmount' => 'sum(sale.amount)',
    'employeesCount' => 'count(distinct employee.id)',
    'aislesCount' => 'count(distinct aisle.id)',
    'restocksCount' => 'count(distinct restock.id)',
])->joinWith([
    'sales',
    'employees',
    'aisles',
    'restocks',
    'address',  
])->andWhere(['address.city_id' => $city_id])
->groupBy('shop.id');
```

It will be a huge and slow query with a total of 6 simultaneous tables and consuming a lot of resources. On top of that 'salesAmount' will produce a wildly different result than expected due to the repetition of data implicit with every join. So that data can't be eagerloaded and needs to be calculated with a new query for every shop in the report.

To solve this issue the best approach is to segmentate the results into multiple relational queries per table. I propose a new type of relations that can take advantage of this.

```php
public funciton getSalesCount()
{
    return $this->getSales()->asScalar('count(*)');
}

public funciton getSalesAmount()
{
    return $this->getSales()->asScalar('sum(amount)');
}

public funciton getRestocksCount()
{
    return $this->getRestocks()->asScalar('count(*)');
}

// etc
```

Which would be used very similar to the existing relations.

```php
Shop::find()->with([
    'salesCount',
    'salesAmount',
    'employeesCount',
    'aislesCount',
    'restocksCount',
    'addressCount',
])->innerJoinWith('address')
->andWhere(['address.city_id' => $city_id]);
```

Which would produce queries

```sql
SELECT shop.*
FROM shop
  INNER JOIN address on shop.address_id = address.id
WHERE address.city_id = 1;

SELECT count(*), shop_id
FROM sales
WHERE shop_id in (1, 2, ..., 100)
GROUP BY shop_id;

SELECT sum(amount), shop_id
FROM sale
WHERE shop_id in (1, 2, ..., 100)
GROUP BY shop_id;

SELECT count(*), shop_id
FROM restock
WHERE shop_id in (1, 2, ..., 100)
GROUP BY shop_id;

/* etc */
```

The number of queries will increment but the execution time will be reduced drastically and the `saleAmount` parameter will be calculated properly.

The proposition would be to add a new method `yii\db\ActiveQuery::asScalar()` which would take an string parameter to determine how to calculate the scalar value. Relations marked as scalar won't produce instances of `yii\db\ActiveRecord` and will only save the scalar result.

**Comment by SilverFire** [comment] 2016-09-08 09:00
You can achieve pretty much the same:

```php
    public function getSalesCount()
    {
        return $this->getSales()->select(['shop_id', 'count(*)'])->groupBy('shop_id');
    }
```

```php
Shop::find()->with(['salesCount', ...])
    ->innerJoinWith('address')
    ->andWhere(['address.city_id' => $city_id]);
```

I'm closing the issue for now because to can not find a good reason to introduce new API. The issue is not locked, so feel free to continue discussion if you have something on mind. Thank you

**Comment by Faryshta** [comment] 2016-09-08 09:24
@SilverFire have you tried that snippet? it will simply not save the 'count(*)' anywhere on the ActiveRecord.

I would need to create a new class for each scalar relation to add it a getter/setter attribute.

And I would have to use it like this

```php
$model->salesCount->count;
$model->salesAmount->sum;
```

So for the example I wrote above I would require at least 4 new classes just to make one report.

**Comment by SilverFire** [comment] 2016-09-08 09:55
> have you tried that snippet?

Nah, it was a concept that does something similar :octocat:

> it will simply not save the 'count(*)' anywhere on the ActiveRecord

Well, you can say `->asArray()` but then model does not look so shiny.

**Comment by SilverFire** [comment] 2016-09-08 09:57
Then looks useful and could be implemented, as for me. 
Let's wait for more thoughts from @yiisoft/core-developers

**Comment by klimov-paul** [comment] 2016-09-08 10:00
This topic has already been disscussion several times in several contexts.
See #2179, #8316, #10459

**Comment by Faryshta** [comment] 2016-09-08 18:02
@klimov-paul i have read them all and none of them offers a solution for eager loading. On the example I provided its meant to find several shops and extra data for each shop which would be be executed by several individual queries per row or by one humongous query. Both approaches are not optimal and would consume lots of resources.

@SilverFire then the snippet would look something like this

```php
public funciton getOrdersCount()
{
      return $this->getOrders()->select(['shop_id', 'count' => 'count(*)'])->asArray()->groupBy('shop_id');
      // usage $this->ordersCount['count']
}
```

Which is what I am doing at the moment but its not practical, intuitive or easy to maintain and loses some functionalities such as `attributeLabels` on gridviews.

My propsal is to use it like this

```php
public funciton getOrdersCount()
{
      return $this->getOrders()->asScalar('count(*)');
      // usage $this->ordersCount
      // extra select and group by are added by array_keys($query->link) and only for eager-loading.
}
```

which can take advantage of `attributeLabels`, `attributeHints` and similar functionalities

**Comment by klimov-paul** [comment] 2016-09-08 18:14
> i have read them all and none of them offers a solution for eager loading.

Is that really so? What about this comment then?

https://github.com/yiisoft/yii2/issues/10459#issuecomment-181971912

I will even re-post it here:

```php
class WhateverCount extends \yii\db\ActiveRecord
{
    public function query()
    {
        return (new \yii\db\Query())
            ->select(['related_id', 'counted' => 'count(*)'])
            ->from('tablename')
            ->groupBy('related_id')
            ->asArray(true);
    }
}

class WhateverModel extends \yii\db\ActiveRecord
{
    public function tablename()
    {
        return 'sometable';
    }

    public function getWhateverCount()
    {
        $this->hasOne(WhateverCount::class,['id'=>'related_id']);
    }
}

$rows = WhateverModel::find()->with('whateverCount')->all();
foreach ($rows as $row) {
    echo $row->whateverCount['counted'];
}
```

Here is your **eager** loading without **one humongous query**.

**Comment by Faryshta** [comment] 2016-09-08 20:50
@klimov-paul that approach is very similar to the one I am using already except that it produces the requirement for a class for every relational data. In the provided example I would need  to create 5 new classes just to handle one grid view.

The number of classes on the system would bloat and will be hard to mantain/debug. Will be specially difficult as I start to need more relation data such as classes like would need stuff like `ShopSalesCount` `ShopTotalAmount`, `ShopBiggestSale`, `ShopAverageSaleAmount` and it would lose functionalities like `attributeLabels`, `attributeHints`.

And finally it offers no benefit than making the query like this

```php
public funciton getOrdersCount()
{
      return $this->getOrders()->select(['shop_id', 'count' => 'count(*)'])->asArray()->groupBy('shop_id');
      // usage $this->ordersCount['count']
}
```

**Comment by mdmunir** [comment] 2016-09-09 02:15
similar this #12025 
```php
class OrderCount extends QueryRecord
{
    public static function query()
    {
        return (new Query())
            ->select(['shop_id', 'count'=>'count(*)'])
            ->from('order');
    }
}

class Shop extends ActiveRecord
{
    public function getOrderCount()
    {
        return $this->hasOne(OrderCount::className(), ['shop_id' => 'id']);
    }
}

foreach(Shop::find()->with('orderCount')->all() as $shop)
{
    echo $shop->orderCount->count;
}
```

**Comment by Faryshta** [comment] 2016-09-09 07:06
@mdmunir the main issue i have with that approach is that it will increase the number of class models inmensely for every time you need new data.

Example  `OrdersCount`, `MaxOrderAmount`, `TotalOrderAmount`, `AverageOrderAmount`, etc just to give examples, most will be for a very particular use and not very reusable.

Plus its not intuitive/aesthetical to use `$shop->orderCount->count` instead of `$shop->orderCount`

**Comment by SilverFire** [comment] 2016-09-09 10:15
Kind of workaround:

```php
use yii\db\BaseActiveRecord;

/**
 * @property integer aggregate
 * @property string aggregate
 */
class DynamicAggregate extends \yii\db\ActiveRecord
{
    public static function find()
    {
        return new DynamicAggregateQuery(static::class);
    }

    public function attributes()
    {
        return ['id', 'aggregate'];
    }

    public static function primaryKey()
    {
        return ['id'];
    }

    public function __toString()
    {
        return $this->aggregate;
    }

    public static function populateRecord($record, $row)
    {
        BaseActiveRecord::populateRecord($record, $row);
    }
}
```

```php
class DynamicAggregateQuery extends \yii\db\ActiveQuery
{
    public function forModel($modelClass, $alias = null)
    {
        $this->from = [$modelClass::tableName()];
        if ($alias !== null) {
            $this->alias($alias);
        }

        return $this;
    }
}
```

```php
class Shop extends ActiveRecord
{
    public function getOrdersCount()
    {
        return $this->hasOne(DynamicAggregate::class, ['shop_id' => 'id'])
            ->forModel(Order::class)
            ->select(['shop_id', 'aggregate' => 'count(*)'])
            ->groupBy('shop_id');
    }
}
```

```php
foreach(Shop::find()->with('ordersCount')->all() as $shop)
{
    echo $shop->ordersCount; // or $shop->ordersCount->aggregate;
}
```

**Comment by klimov-paul** [comment] 2016-09-09 10:20
The simpliest way is using a getter:

```php
class WhateverModel extends \yii\db\ActiveRecord
{
    public function tablename()
    {
        return 'sometable';
    }

    public function getWhateverRelation()
    {
        $this->hasOne(WhateverRelation::class,['id'=>'related_id'])
            ->select(['related_id', 'counted' => 'count(*)'])
            ->from('tablename')
            ->groupBy('related_id')
            ->asArray(true);
    }

    public function getWhateverCount()
    {
        return $this->whateverRelation['counted'];
    }
}

$rows = WhateverModel::find()->with('whateverCount')->all();
foreach ($rows as $row) {
    echo $row->whateverCount;
}
```

**Comment by SilverFire** [comment] 2016-09-09 10:26
:+1: 

Enough ways to solve problem. Suggest to close the issue
@Faryshta ?

**Comment by Faryshta** [comment] 2016-09-09 14:22
@SilverFire the last solution you wrote sounds interesting, can we have a shortcut or standarized way to use it?

```php
public function getOrdersCount()
{
     return $this->agregateRelationalField($this->getOrders()->select('count(*)'));
}
```

or something like that to get it on the core.

@klimov-paul i think thats not intuitive and has many requirements but seems good enough. Can we get proper documentation on that proposal?

**Comment by Faryshta** [comment] 2016-09-09 18:38
I think we can standarize it with a very small PR.

```php

class ActiveQuery
{
     /**
       * @param string|array the added select
       * @return $this
       */
     public function asRelationalData($select)
     {
         $linkKeys = array_keys($this->link);
         $this->multiple = false;

         return $this->select(array_merge((array) $select, $linkKeys))
             ->groupBy($linkKeys)
             ->asArray(true);;
     }
}

// usage

class Shop extends ActiveRecord
{
     public function getOrders()
     {
          return $this->hasMany(Order::class, ['shop_id' => 'id']);
     }

     public function getOrdersData()
     {
          return $this->getOrders()->asRelationalData([
             'count' => 'count(*)',
             'totalAmount' => 'sum(amount)'
          ]);
    }
          /* this would be the equivalent of
         return $this->hasOne(Order::class, ['shop_id' => 'id'])
               ->select([
                    'count' => 'count(*)',
                    'totalAmount' => 'sum(amount)'
                    'shop_id',
               ])->groupBy('shop_id')
               ->asArray(true);
          */

     public function getOrdersCount()
     {
           return $this->ordersData['count'];
     }

     public function getOrdersTotalAmount()
     {
           return $this->ordersData['totalAmount'];
     }
}
```

@klimov-paul @SilverFire shall i make a pr?

**Comment by klimov-paul** [comment] 2016-09-09 19:36
Docs updated 2250612cb861947c3fcaab91f0d60d116978a88e

**Closed by klimov-paul** 2016-09-09 19:36 UTC
Labels: feature:db, status:under discussion, type:docs

**Comment by paradox80** [comment] 2016-09-16 13:44
В документации ошибка, нужно менять `getOrders` на `hasOne(Order::className(), ['customer_id' => 'id'])`, иначе на выходе двойной массив и `getOrdersCount` ничего не возвращает
```php
public function getOrdersAggregation()
{
        return $this->hasOne(Order::className(), ['customer_id' => 'id'])
            ->select(['customer_id', 'counted' => 'count(*)'])
            ->groupBy('customer_id')
            ->asArray(true);
}
```

Или как вариант править  `getOrdersCount`

**Comment by klimov-paul** [comment] 2016-09-16 13:47
It is already fixed: 34aeb019e51978f8f9982d9dd8bd3ed8798e7217

**Comment by wartur** [comment] 2017-02-01 07:35
Магия в запросе какая-то.
```php
            ->select(['customer_id', 'counted' => 'count(*)'])
            ->groupBy('customer_id')
```
Я конечно понимаю, что 2 раза повторить customer_id нужно для того, что бы activeRecords подхватила и связала это внутри себя, но хотелось бы более явной команды на это.

Собственно именно из-за того что это встретил
```php
return $this->ordersAggregation[0]['counted'];
```
Мне показалось, что здесь кроется какой-то костыль и поэтому я специально нашел этот баг что бы почитать в чем прикол

Что-то не то с API, слишком сложно. Мое мнение, что надо исправлять это.

**Comment by wartur** [comment] 2017-02-01 07:52
@klimov-paul Требуется еще расширить документацию, так как данных может не найдено, тогда будет ошибка "Undefined offset: 0"

Правильнее всего.
```php
return empty($this->ordersAggregation) ? 0 : $this->ordersAggregation[0]['counted'];
```

ЗЫ: не красивый код, хотелось бы скрыть подобное поведение за фассадом...

**Comment by samdark** [comment] 2017-02-02 17:48
https://github.com/yiisoft/yii2/commit/93fbc55b23e816e906c667f84e7258c0719bc35c

**Comment by samdark** [comment] 2017-02-02 17:48
Спасибо.
