### ISSUE TITLE
Javascript Causing internal server error

### ISSUE THREAD

**Issue by twob-shahid** [yiisoft/yii2#13972] opened 2017-04-12 08:15 UTC
When I put the following js in my html, nothing displays:
```javascript
function getNewsFeed(which) {
        var _this = this;
        if (typeof which == 'undefined' || which == 'first') {
            $.ajax({
                url: '<?= Yii::$app->urlManager->createUrl('site/news-feed')?>',
                type: 'post',
                data: {
                    country: <?=$country['id']?>,
                    _csrf: '<?=Yii::$app->request->csrfToken?>',
                    news_type: 1,
                    offset: $("#country-news-breaking li").length
                },
                success: function (data) {
                    append_html(data, $('#country-news-business'));
                },
                complete: function () {
                    $("#wp1").html("");
                    waypointNews1();
                }
            });
        }
        if (typeof which == 'undefined' || which == 'second') {
            $.ajax({
                url: '<?= Yii::$app->urlManager->createUrl('site/news-feed')?>',
                type: 'post',
                data: {country: <?=$country['id']?>, _csrf: '<?=Yii::$app->request->csrfToken?>', news_type: 2}, // breaking
                success: function (data) {
                    append_html(data, $('#country-news-breaking'));
                }
            });
        }
    }
```

**Comment by Faryshta** [comment] 2017-04-12 18:40
are you just putting it directly on the html or are you following the page view life cycle?

are you using http://www.yiiframework.com/doc-2.0/yii-web-view.html#registerJs()-detail ?

**Comment by cebe** [comment] 2017-04-12 20:31
This could be caused by a lot of things, unless it turns out to be a framework issue I'll close this issue. please seek help in other places:

**Closed** 2017-04-12 20:31 UTC
Labels: question, status:need more info
