### ISSUE TITLE
yii2 rest api db oracle

### ISSUE THREAD

**Issue by faradoxuz** [yiisoft/yii2#9415] opened 2015-08-14 08:37 UTC
Hello! I have such problem. I'm building REST API on yii2 and my database on ORACLE. I can't authenticate. I got an error "Undefined index: CONSTRAINT_TYPE".
what's problem?

**Comment by samdark** [comment] 2015-08-14 08:50
Need more info:

1. Stacktrace.
2. A way to reproduce the issue.

**Comment by faradoxuz** [comment] 2015-08-14 09:08
Our team build mobile application on android, rest api on yii2, I'm wrtiting API, client must authenticate via mobile application. simple 'select' queries work excellent, but authentication doesn't work.
Error:
1. PHP NOTICE: "Undefined index: CONSTRAINT_TYPE","code":8,"type":"yii\\base\\ErrorException","file":"/var/www/stapi.uz/vendor/yiisoft/yii2/db/oci/Schema.php","line":283
"stack-trace":
["#0 /var/www/stapi.uz/vendor/yiisoft/yii2/db/oci/Schema.php(283),
"#1 /var/www/stapi.uz/vendor/yiisoft/yii2/db/oci/Schema.php(88): yii\\db\\oci\\Schema->findConstraints(Object(yii\\db\\TableSchema))",
"#2 /var/www/stapi.uz/vendor/yiisoft/yii2/db/Schema.php(146): yii\\db\\oci\\Schema->loadTableSchema('POINTS')"
"#3 /var/www/stapi.uz/vendor/yiisoft/yii2/db/ActiveRecord.php(294): yii\\db\\Schema->getTableSchema('POINTS')"

**Comment by faradoxuz** [comment] 2015-08-14 09:31
Problem with oracle?

**Comment by samdark** [comment] 2015-08-14 09:52
Which version it is?

**Comment by faradoxuz** [comment] 2015-08-14 09:55
Oracle 11g R2

**Comment by faradoxuz** [comment] 2015-08-14 10:05
Sasha! I tried with deleting the string 'D.CONSTRAINT_TYPE' on line 266 in the file yii\db\oci\Schema.php and it worked. It's weird.

**Comment by samdark** [comment] 2015-08-14 10:10
Looks like a bug in our `\oci\Schema`.

**Comment by faradoxuz** [comment] 2015-08-14 10:13
What should I do now? What will you advice

**Comment by cebe** [comment] 2015-08-14 10:16
`CONSTRAINT_TYPE` is part of the select that is done before, why is it not part of the result set?

**Comment by cebe** [comment] 2015-08-14 10:17
have you cleared all caches after update to 2.0.6?

**Comment by cebe** [comment] 2015-08-14 10:18
the code in question has been introduced in #8844 btw.

**Comment by faradoxuz** [comment] 2015-08-14 10:19
Until that moment, I use yii1.1.16, this is my first step to yii2. in yii1 we have another rest application, and it works very excellent.

**Comment by faradoxuz** [comment] 2015-08-14 10:20
I wrote another rest on yii2 advanced with mysql, angular, it works well

**Comment by cebe** [comment] 2015-08-14 10:20
so this happends on a fresh install of the basic app?

**Comment by faradoxuz** [comment] 2015-08-14 10:20
yep

**Comment by cebe** [comment] 2015-08-14 10:22
I see what could be wrong, will prepare a fix

**Comment by cebe** [comment] 2015-08-14 10:28
should be fixed by 34d5b45, can you verify that it works?

**Closed** 2015-08-14 10:28 UTC
Labels: feature:db, Oracle, type:bug

**Comment by faradoxuz** [comment] 2015-08-14 10:35
Thanks guys, it works now
