### ISSUE TITLE
ActiveForm in 2.0.4

### ISSUE THREAD

**Issue by olessavluk** [yiisoft/yii2#8993] opened 2015-07-03 12:56 UTC
Hi!
When I create `ActiveForm` with option `'enableClientValidation' => false` and create button with name `submit`, like on this minimal code to reproduce issue:
```php
<?php $form = ActiveForm::begin([
    'enableClientValidation' => false,
]); ?>

<?= Html::submitButton('Submit', [
    'name' => 'submit',
]) ?>

<?php ActiveForm::end(); ?>
```
Click on the "submit" button and nothing happened, click second time and form submits.
(Maybe it's because of client validation prevents submitting?)

This issue reproduces only when `'enableClientValidation' => false`  and button name is `submit` and yii2 version is `2.0.4` (with v`2.0.3` no such issue)

**Comment by cebe** [comment] 2015-07-03 15:49
duplicate of #8756?

**Comment by olessavluk** [comment] 2015-07-03 20:16
@cebe yes, you are right, this is the same

**Comment by olessavluk** [comment] 2015-07-03 21:13
@cebe I think this issue is not yet resolved, and here why:

This issue is caused by https://github.com/yiisoft/yii2/commit/3abc07d16cb4f877cdff9e24d97269345a6c8b44 (after reverting that commit, bug disappeared and form get submitted after first click)

According to this https://github.com/yiisoft/yii2/issues/8756#issuecomment-112324639 I cannot use some "reserved" words inside html form (it looks very strange).
 
So I should not use these "reserved" words or maybe there is better way to fix both issues ( #6642 and this one)? I think we need better solution.

**Comment by pana1990** [comment] 2015-07-10 10:12
@olessavluk Jquery jquery suggests not using keywords reserved, as such submit, length, or method

see https://api.jquery.com/submit/ for more details

>Forms and their child elements should not use input names or ids that conflict with properties of a form, such as submit, length, or method. Name conflicts can cause confusing failures

**Comment by pana1990** [comment] 2015-07-10 11:20
related https://github.com/yiisoft/yii2/issues/9048

@cebe maybe it should be documented in https://github.com/yiisoft/yii2/blob/master/docs/guide/input-forms.md?¿

**Comment by cebe** [comment] 2015-08-03 10:57
added a documentation hint to the guide and also the html button methods.

**Closed** 2015-08-03 10:57 UTC
Labels: status:to be verified
