### ISSUE TITLE
Response::sendFile Content-Disposition header with non-ASCII filenames

### ISSUE THREAD

**Issue by PowerGamer1** [yiisoft/yii2#12047] opened 2016-07-29 19:08 UTC
When `$attachmentName` of `Response::sendFile` method contains non-ASCII characters the method creates invalid `Content-Disposition` HTTP header (according to specification HTTP headers cannot contain non-ASCII characters). In such a case the filename must be encoded according to https://tools.ietf.org/html/rfc5987 (also see https://tools.ietf.org/html/rfc6266#section-5).

Example:
```PHP
return \Yii::$app->getResponse()->sendFile('somepath', 'руссо туристо.txt');
```
The file "Save As..." window prompted by IE11 contains invalid file name.

**Comment by shirase** [comment] 2016-07-30 08:36
#12040

**Comment by samdark** [comment] 2016-08-23 23:30
Duplicate of #10563

**Closed by samdark** 2016-08-23 23:30 UTC
Labels: type:bug
