### ISSUE TITLE
Guide: links errors

### ISSUE THREAD

**Issue by CedricYii** [yiisoft/yii2#11050] opened 2016-03-08 08:26 UTC
If you look in the source of the left menu of the guide (http://www.yiiframework.com/doc-2.0/guide-README.html), you will find several links pointing to "./guide-README.html".

For example, Special Topics > Advanced Project Template

Whereas if you look at the same link in the main page, you find a useful link.

Could you correct it?

Yii seems to be missing a good navigation core system.

**Comment by samdark** [comment] 2016-04-30 14:58
Duplicate of #9922

**Closed by samdark** 2016-04-30 14:58 UTC
