### ISSUE TITLE
Cannot use 'Object' as class name

### ISSUE THREAD

**Issue by mogilka** [yiisoft/yii2#14472] opened 2017-07-17 11:52 UTC
Please suggest

### What steps will reproduce the problem?
Update php from 7.0 to 7.1/7.2 via standard Ubuntu app updater

### What is the expected result?
I could run Yii2 console commands successfully as before, for example:
`/var/www/site/yii ctrl/index`

### What do you get instead?

> PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /var/www/zvezdochet.guru/vendor/yiisoft/yii2/base/Object.php on line 77

The error appears even if I run simple command in console (under of any my projects - basic or advanced):
`/var/www/site/yii`

### Additional info
Later I've also updated all Yii2 components via composer but it didn't help.
My web-sites works perfect via browser but I cannot run any console command (controller).
Do I need to doungrade to PHP7.0 or somehow fix the problem?
PHP console works fine, I can execute some php code in it.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | 7.2
| Operating system | Ubuntu 16.04

**Comment by klimov-paul** [comment] 2017-07-17 11:53
Duplicate of #7936

**Closed by klimov-paul** 2017-07-17 11:53 UTC

**Comment by danabyrd** [comment] 2018-01-10 21:16
@mogilka for console commands you can sometimes specify the php version depending on your OS.

Here's an example on Ubuntu 16.04.3 LTS
```php
// Using php 7.1 or 7.2  to run yii (v2.0.13.1) console commands throws an exception.
// A temporary solution is to specify the php version you want to run the command.
// Example: "php yii migrate" will fail on php 7.1 or 7.2 but the line below will work.
php7.0 yii migrate 
```
