### ISSUE TITLE
Invalid Action Object 

### ISSUE THREAD

**Issue by maoneid** [yiisoft/yii2#19665] opened 2022-11-08 12:06 UTC
https://github.com/yiisoft/yii2/blob/22614a5b1fde5902137e3af6a99a7f7ada6b62d4/framework/filters/auth/CompositeAuth.php#L73

This is invalid when the owner of filter behaviors is module; The error is 

Getting unknown property: frontend\modules\moduleName\Module::action

please rollback to code base on doc https://www.yiiframework.com/doc/api/2.0/yii-filters-auth-compositeauth#authenticate()-detail

if (
            $this->owner instanceof Controller
            && (!isset($this->owner->action) || !$auth->isActive($this->owner->action))
        ) {
            continue;
        }

**Comment by maoneid** [comment] 2022-11-11 09:25
> Maybe you can refer to #19581

Thankyou

**Comment by samdark** [comment] 2022-11-15 06:48
Duplicate of #19581

**Closed by samdark** 2022-11-15 06:48 UTC
