### ISSUE TITLE
DateValidator doesn't correctly validate DateTime values

### ISSUE THREAD

**Issue by VirtualRJ** [yiisoft/yii2#10165] opened 2015-11-16 13:02 UTC
I have a model with the following rule:

```PHP
[['start'], 'date', 'timestampAttribute' => 'start'],
````

and the following code in my controller:

```PHP
$curTime = Yii::$app->formatter->asDateTime(new \DateTime('NOW'));
$model->start = $curTime;
```

When I run $model->validate it returns false. If I do the same, but change asDateTime to asDate it validates correctly.

I have even tried setting the formatter to the formatter defined by making the rule in the model like this:
```PHP
[['start'], 'date', 'format' => Yii::$app->formatter->datetimeFormat, 'timestampAttribute' => 'start'],
```

I presume this isn't expected behavior since as far as I can tell the DateValidator also validates DateTime and there is no specific seperate validator for DateTime.

**Comment by SilverFire** [comment] 2015-11-16 17:28
```php
$curTime = Yii::$app->formatter->asDateTime(new \DateTime('NOW')); // gives Nov 16, 2015, 5:18:59 PM
```
As it gives you string formatted in you local settings, it is really hard to guess, what are we expecting.

Create the `$curTime` in specific format and check for the same specific format:

```php
$curTime = Yii::$app->formatter->asDateTime(new \DateTime('NOW'), 'yyyy-MM-dd HH:mm:ss');
$curTime = Yii::$app->formatter->asDateTime(new \DateTime('NOW'), 'php:Y-m-d H:i:s'); // the same as previous, but date format is in PHP date() format
```

Then specify the expected format in the validator:

```php
[['start'], 'date', 'format' => 'php:Y-m-d H:i:s'],
```

**Comment by VirtualRJ** [comment] 2015-11-16 19:20
Yes, that does work, but it is still strange (and unexpected) behavior. Even if I say:

```PHP
$curTime = Yii::$app->formatter->asDateTime('now', Yii::$app->formatter->datetimeFormat);
```
and make the rule like:
```PHP
[['start'], 'date', 'format' => Yii::$app->formatter->datetimeFormat, 'timestampAttribute' => 'start'],
```
It returns false. In that case I don't think there should be any unexpected formatting issue even with localisation.

**Comment by VirtualRJ** [comment] 2015-11-17 14:11
I did some digging. The reason why it does work in the example is in the way parseDateValueIntl($value, $format) works in the DateValidator. I'm not completely sure how to describe it, but if something is unclear please let me know.

```PHP
$format = Yii::$app->formatter->datetimeFormat; //$format = 'medium'
```
When asked to validate and the intl extension is installed it ends up in the function parseDateValueIntl($value, $format). Specifically in this part:
```PHP
if (isset($this->_dateFormats[$format])) {
    $formatter = new IntlDateFormatter($this->locale, $this->_dateFormats[$format], IntlDateFormatter::NONE, 'UTC');
}
```
In the constructor of IntlDateFormatter the third parameter is always IntlDateFormatter::NONE which specifies the format of the time. When the function does try to parse the date using the IntlDateFormatter it will encounter an error as soon as the time part of the $value is reached. Specifically in this line:
```PHP
$parsedDate = @$formatter->parse($value, $parsePos);
```
When IntlDateFormatter::NONE is changed to the same value as the second parameter $this->_dateFormats[$format] (which in my case essential is IntlDateFormatter::MEDIUM) the DateTime value gets parsed succesfully and validation succeeds. Sadly validation of just a date breaks with this change.

I do not hold the coding answer for the solution, but I guess the only way to fix this is detecting the value supplied is a DateTime instead of just a Date. If detection is succesful the line for constructing the formatter could become:
```PHP
$formatter = new IntlDateFormatter($this->locale, $this->_dateFormats[$format], $hasTimeInfo ? $this->_dateFormats[$format] : IntlDateFormatter:NONE, 'UTC');
```
As an end note I'll give a piece of code where I can reproduce the issue:
```PHP
$format = Yii::$app->formatter->datetimeFormat;
$curDate = Yii::$app->formatter->asDate('now', Yii::$app->formatter->datetimeFormat);
$curDateTime = Yii::$app->formatter->asDateTime('now', Yii::$app->formatter->datetimeFormat);
$dateValidator = new DateValidator();

echo "Format: ". $format . "</br>";
echo "<hr/>";
echo "Current date: " . $curDate . "</br>";
echo "Date validation: " . var_export($dateValidator->validate($curDate), true) . "</br>";
echo "<hr/>";
echo "Current date & time: " . $curDateTime . "</br>";
echo "DateTime validation: " . var_export($dateValidator->validate($curDateTime), true) . "</br>";
```
In my case (because of nl-NL localisation) the output is:

```
Format: medium

Current date: 17 nov. 2015
Date validation: true

Current date & time: 17 nov. 2015 14:08:56
DateTime validation: false
```

**Comment by SilverFire** [comment] 2015-11-17 14:42
Thank you for digging in.

Your example looks inconsistent, but as the DateValidator is covered by tests, it's an expected behavior.

Do you have any ideas how to fix this and don't crash anything?

**Comment by VirtualRJ** [comment] 2015-11-17 15:21
Well we could add a property to the DateValidator $type or $intlType and set the default to 'date' or null. And make the parseDateValueIntl as follows:

```PHP
    /**
     * Parses a date value using the IntlDateFormatter::parse()
     * @param string $value string representing date
     * @param string $format the expected date format
     * @return integer|boolean a UNIX timestamp or `false` on failure.
     */
    private function parseDateValueIntl($value, $format)
    {
        if (isset($this->_dateFormats[$format])) {
            if (!isset($this->type) || $this->type === 'date') {
                $formatter = new IntlDateFormatter($this->locale, $this->_dateFormats[$format], IntlDateFormatter::NONE, 'UTC');
            } elseif ($this->type === 'dateTime') {
                $formatter = new IntlDateFormatter($this->locale, $this->_dateFormats[$format], $this->_dateFormats[$format], 'UTC');
            }
        } else {
            // if no time was provided in the format string set time to 0 to get a simple date timestamp
            $hasTimeInfo = (strpbrk($format, 'ahHkKmsSA') !== false);
            $formatter = new IntlDateFormatter($this->locale, IntlDateFormatter::NONE, IntlDateFormatter::NONE, $hasTimeInfo ? $this->timeZone : 'UTC', null, $format);
        }
        // enable strict parsing to avoid getting invalid date values
        $formatter->setLenient(false);
        // There should not be a warning thrown by parse() but this seems to be the case on windows so we suppress it here
        // See https://github.com/yiisoft/yii2/issues/5962 and https://bugs.php.net/bug.php?id=68528
        $parsePos = 0;
        $parsedDate = @$formatter->parse($value, $parsePos);
        if ($parsedDate === false || $parsePos !== mb_strlen($value, Yii::$app ? Yii::$app->charset : 'UTF-8')) {
            return false;
        }
        return $parsedDate;
    }    
```

**Comment by samdark** [comment] 2015-11-17 16:22
@cebe I guess this issue needs your input.

**Comment by VirtualRJ** [comment] 2015-12-15 10:32
I made some unit tests to test the inconsistency (ac4be34) and made proposal enhancement (45c6239).

**Comment by nkovacs** [comment] 2016-02-03 10:45
This is a duplicate of #7177

**Comment by cebe** [comment] 2016-02-06 15:08
closed as duplicate.

**Comment by cebe** [comment] 2016-02-06 15:09
@VirtualRJ can you send a pull request?

**Closed by cebe** 2016-02-06 15:08 UTC
Labels: status:under discussion

**Comment by dhanakumarm** [comment] 2018-08-06 06:37
Test test
