### ISSUE TITLE
Codeception test fails out of the box

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii2#13442] opened 2017-01-25 09:27 UTC
Install fresh yii2 advanced template via composer
Install codeception
Execute codeception run, and get the following error:

cept run
Codeception PHP Testing Framework v2.2.8
Powered by PHPUnit 4.8.32 by Sebastian Bergmann and contributors.

[common\tests]: tests from /var/www/ott/common

Common\tests.unit Tests (3) ---------------------------------------------------------------------------------------
✔ LoginFormTest: Login no user (0.04s)
✔ LoginFormTest: Login wrong password (0.53s)
✔ LoginFormTest: Login correct (0.53s)
-------------------------------------------------------------------------------------------------------------------

[frontend\tests]: tests from /var/www/ott/frontend

Frontend\tests.functional Tests (12) ------------------------------------------------------------------------------
E AboutCest: Check about (0.01s)
- ContactCest: Check contact<pre>PHP User Error &#039;yii\base\ErrorException&#039; with message &#039;Exception (Invalid Configuration) &#039;yii\base\InvalidConfigException&#039; with message &#039;The directory does not exist: ./assets&#039;

in /var/www/ott/vendor/yiisoft/yii2/web/AssetManager.php:211

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 5.4.16
| Operating system | CentOS 7.3

**Comment by stiff-dev** [comment] 2017-01-25 10:34
Have you tried 
`php init`
in your main project directory?
It looks like you don't have your assets directory. Is your project running correctly in browser?
And maybe paste your *ContactCest.php* file here.

**Comment by evil1** [comment] 2017-01-25 14:44
Here is ContactCept contents:
`<?php
namespace frontend\tests\functional;

use frontend\tests\FunctionalTester;

/* @var $scenario \Codeception\Scenario */

class ContactCest
{
    public function _before(FunctionalTester $I)
    {
        $I->amOnPage(['site/contact']);
    }

    public function checkContact(FunctionalTester $I)
    {
        $I->see('Contact', 'h1');
    }

    public function checkContactSubmitNoData(FunctionalTester $I)
    {
        $I->submitForm('#contact-form', []);
        $I->see('Contact', 'h1');
        $I->seeValidationError('Name cannot be blank');
        $I->seeValidationError('Email cannot be blank');
        $I->seeValidationError('Subject cannot be blank');
        $I->seeValidationError('Body cannot be blank');
        $I->seeValidationError('The verification code is incorrect');
    }

    public function checkContactSubmitNotCorrectEmail(FunctionalTester $I)
    {
        $I->submitForm('#contact-form', [
            'ContactForm[name]' => 'tester',
            'ContactForm[email]' => 'tester.email',
            'ContactForm[subject]' => 'test subject',
            'ContactForm[body]' => 'test content',
            'ContactForm[verifyCode]' => 'testme',
        ]);
        $I->seeValidationError('Email is not a valid email address.');
        $I->dontSeeValidationError('Name cannot be blank');
        $I->dontSeeValidationError('Subject cannot be blank');
        $I->dontSeeValidationError('Body cannot be blank');
        $I->dontSeeValidationError('The verification code is incorrect');
    }

    public function checkContactSubmitCorrectData(FunctionalTester $I)
    {
        $I->submitForm('#contact-form', [
            'ContactForm[name]' => 'tester',
            'ContactForm[email]' => 'tester@example.com',
            'ContactForm[subject]' => 'test subject',
            'ContactForm[body]' => 'test content',
            'ContactForm[verifyCode]' => 'testme',
        ]);
        $I->seeEmailIsSent();
        $I->see('Thank you for contacting us. We will respond to you as soon as possible.');
    }
}
`
I did run `init` and initialized the development environment.

Project is running in browser well using both apache webserver and `yii serve` command runnint PHP's internal server.
But `php serve` by default cannot detect the docroot, so I have to manually pass it via `--docroot` parameter.
By default codeception configuration uses localhost:8080 url which (I guess) means that codeception uses `php serve` command for testing?
Anyway, I tried both - chaging the url to the one, served by apache and the defaul one.
The error is still there.

**Comment by samdark** [comment] 2017-01-25 15:56
Try creating assets directory.

**Comment by evil1** [comment] 2017-01-25 17:02
Where? It is present under frontend/assets containing php bundles and also frontend/web/assets containing styles and scripts required for the project. The last one is accessible to the browser.

**Comment by evil1** [comment] 2017-01-25 17:04
chmod 777 - R on the last dir mentioned above also changed nothing.

**Comment by samdark** [comment] 2017-01-25 17:14
Hmm... it looks it searches for assets in `tests` which doesn't seem correct.

**Comment by evil1** [comment] 2017-01-26 01:45
Is the any temporary sution to fix this?

**Comment by evil1** [comment] 2017-01-26 03:07
Creating assets directory in the project root did resolve the issue.

Another thing I faced before is when I was upgrading yii from 2.0.6 to 2.0.10 none of the tests where downloaded. I guess this chould be moved to another issue?
`php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"`
`php composer.phar update yiisoft/yii2 yiisoft/yii2-composer bower-asset/jquery.inputmask` 
did upgrade yii, but the file structure was not upgraded.

**Comment by evil1** [comment] 2017-01-26 07:54
Now the problem is that LoginCest fails with valid login and SignupCest fails.
I tried to add some debug messages to test code.
user erau is actually being added to test DB correctly.
I disabled Fixture unload (so that test DB was not erased after the fixture was used), and manually logged in successfully with the credentials provided in fixture.

**Comment by samdark** [comment] 2017-01-26 08:59
> Creating assets directory in the project root did resolve the issue.

I guess it's a good idea to add empty `assets` directories to both basic and advanced templates by default...

**Comment by samdark** [comment] 2017-01-26 08:59
> but the file structure was not upgraded

It should not. Template is what it is. You start with it and then it's all yours. It's not meant to be updated.

**Comment by evil1** [comment] 2017-01-26 09:09
Update:
After checking user table I found that user `tester` which is added during SignupCest was not removed after the test (should that be done automatically).
After manual removal, SignupCest is fine.
The problem still exists with LoginCest with valid credentials `erau` and password `password_0`.

**Comment by evil1** [comment] 2017-01-27 04:48
It look like Fixture is not working in `_before` function of LoginCest.
I modified the `checkValidLogin` method, to check wether the user exists in database, and found that it's not there.
    ```
public function checkValidLogin(FunctionalTester $I)
    {
        $I->seeRecord('common\models\User', [
            'username' => 'erau',
            'email' => 'sfriesen@jenkins.info',
        ]);
    }
```

**Comment by evil1** [comment] 2017-01-27 04:53
![frontendtest](https://cloud.githubusercontent.com/assets/5018681/22360893/9f6bee2e-e47e-11e6-8cad-b02c34407116.PNG)
Yes, Fixture is not correctly applied in LoginCest _before method.
After manually adding the user to the test database all test are ok.

**Comment by evil1** [comment] 2017-01-27 07:34
Some kind of magic happens.
I investigated ActiveFixture class (put some echo for debug purposes) both methods, `load `and `unload` are called properly, but the user is not added to the database, and `$this->resetTable()` in the load section does not actually deletes any data in table.
@samdark do you have any idea, why this might happen?

**Comment by evil1** [comment] 2017-01-27 15:54
Trying to load fixture with `./yii fixture/load` also not woking:
![fixture2](https://cloud.githubusercontent.com/assets/5018681/22377205/26c1060a-e4db-11e6-826d-38af96eae6ac.PNG)
![fixture](https://cloud.githubusercontent.com/assets/5018681/22377209/296b8510-e4db-11e6-829c-a988435e8931.PNG)

**Comment by evil1** [comment] 2017-01-28 16:09
@samdark I think the problem is related to PostgreSQL only.
I modified the `load` method of `ActiveFixture` and came to some interesting information:
![activefixture](https://cloud.githubusercontent.com/assets/5018681/22397750/c0e148c2-e5a2-11e6-929a-1350507a6d95.PNG)
and here is the output of the echo command:
![echooutput](https://cloud.githubusercontent.com/assets/5018681/22397762/05ef7e48-e5a3-11e6-8852-d56ff720bdfc.PNG)
My PostgreSQL version is postgresql-server-9.2.18-1.el7.x86_64
It seems like `user` is a reserved operator in PostgreSQL.
`SELECT * FROM user` returns current user instead of user table contents.
For sure this is not Yii-caused bug, but should be considered by developers.
Running the command in psql console also led to exactly the same results:
![psql](https://cloud.githubusercontent.com/assets/5018681/22397825/99c7fb80-e5a4-11e6-931e-99d6028371ec.PNG)

**Comment by samdark** [comment] 2017-01-28 16:11
So that's specific to your application?

**Comment by evil1** [comment] 2017-01-28 16:15
That is specific to database used.
I guess I'm not the only person, who uses PostgreSQL as a database server.

**Comment by samdark** [comment] 2017-01-28 17:07
What I've meant is "are you using AR only to access user model or you did exactly that command via plain SQL"?

**Comment by evil1** [comment] 2017-01-28 17:29
As I've mentioned in the begingin of the issue these are the tests out of the box,  so only pure advanced template and codeception are installed.  No coding was made.

**Comment by evil1** [comment] 2017-01-28 17:30
So I believe only AR is used with no plain SQL used

**Comment by samdark** [comment] 2017-01-28 18:08
That's a bit weird then since table names should be escaped properly.

**Comment by evil1** [comment] 2017-01-29 07:31
My fault. When I put table name inside the quotes SELECT query works well
`SELECT * FROM "user" gives propper output`
I tried to enable DB query loggin, and see the following:
```
LOG:  execute pdo_stmt_00000007: INSERT INTO "user" ("username", "auth_key", "password_hash", "password_reset_token",
 "created_at", "updated_at", "email") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
DETAIL:  parameters: $1 = 'erau', $2 = 'tUu1qHcde0diwUol3xeI-18MuHkkprQI', $3 = '$2y$13$nJ1WDlBaGcbCdbNC5.5l4.sgy.OME
KCqtDQOdQ2OWpgiKRWYyzzne', $4 = 'RkD_Jw0_8HEedzLk7MM-ZKEFfYR7VbMr_1392559490', $5 = '1392559490', $6 = '1392559490',
$7 = 'sfriesen@jenkins.info'
LOG:  statement: DEALLOCATE pdo_stmt_00000007
LOG:  statement: ROLLBACK
```
For some reason ROLLBACK is called
I will try to investigate further, and find the cause of the problem.
One more thing I've noticed, when `$this->resetTable()` is called, the following queries being executed:
```
LOG:  execute pdo_stmt_00000003: DELETE FROM "user"
LOG:  statement: DEALLOCATE pdo_stmt_00000003
LOG:  execute pdo_stmt_00000006: SELECT SETVAL('"user_id_seq"',1,false)
LOG:  statement: DEALLOCATE pdo_stmt_00000006
```

According to PostgreSQL docs https://www.postgresql.org/docs/9.2/static/sql-truncate.html it's much more efficient to use truncate to reset table in a single query:
`TRUNCATE TABLE "user" RESTART IDENTITY`
I'm not sure if this information is helpful, and will be used by Yii team, but still at least you will know that this approach also exists.

**Comment by evil1** [comment] 2017-01-29 09:34
Just for testing purposes, I tried to change DB server to MySQL (MariaDB), and all the tests pass without any errors.  So the problem is purely related to PostgreSQL

**Comment by evil1** [comment] 2017-01-31 01:22
Overriding the `load` method in `common\fixtures\User` did solve the problem, but this is just a temporary workaround, not a solution:
```
public function load()
    {
        parent::load();
        $this->db->transaction->commit();
    }
```

**Comment by samdark** [comment] 2017-02-02 00:01
Could be related to https://github.com/Codeception/Codeception/pull/3973

**Comment by samdark** [comment] 2017-02-02 18:14
https://github.com/yiisoft/yii2-app-advanced/issues/221

**Comment by samdark** [comment] 2017-02-03 08:27
Well, the rollback happens within Codeception.

**Comment by evil1** [comment] 2017-02-03 08:41
But it does nothing in case you are using MySQL, and rolls back the transaction in case you are using PostgreSQL

**Comment by samdark** [comment] 2017-02-03 08:58
Well, yes. I can reproduce failures using PostgreSQL but these are actually different than yours so I'm not sure what and why happens in your case.

**Comment by evil1** [comment] 2017-02-03 09:08
I can make a freshly installed vmware image, and upload it somewhere to demonstrate the error presence.

**Comment by evil1** [comment] 2017-02-03 09:23
The steps are as simple as possible:
```
composer global require "fxp/composer-asset-plugin:^1.2.0"
composer create-project --prefer-dist yiisoft/yii2-app-advanced yii-application
cd yii-application
./init

```
select 0 (Development environment
configure database in `common/config/mail-local.php`
configure test database name in `common/config/test-local.php`
```
composer require "codeception/codeception"
alias cept='./vendor/bin/codecept'
cept run
```

**Comment by purocean** [comment] 2017-02-05 09:20
append to test config file.
```php
    'components' => [
        'assetManager' => [
            'basePath' => __DIR__ . '/../web/assets',
        ],
    ],
```

**Comment by Nicolai6120** [comment] 2017-02-05 17:04
I think `purocean` code should be included to next advanced template version. It`s clean and simple!

**Comment by sashsvamir** [comment] 2017-02-14 15:29
Also have same issue after update codeception to 2.2.9:
`[yii\base\InvalidConfigException] The directory does not exist: ./assets`
problem solved after append code with assetManager's basePath like as **purocean** showing above.
**Nicolai6120** this code already have yii2 backend template (checked on 2.0.11.2).

**Comment by dynasource** [comment] 2017-02-17 12:50
as stated above, this problems seems to be resolved by commit https://github.com/yiisoft/yii2-app-advanced/commit/7f58ca1f53aab55bb15f8e8feb11aac4af4991f2#diff-3cc128d31956e25113f3d136ae06fdd0

**Closed** 2017-02-17 12:50 UTC
Labels: Codeception
