### ISSUE TITLE
Autoload Yii.php

### ISSUE THREAD

**Issue by miraage** [yiisoft/yii2#7619] opened 2015-03-07 09:47 UTC
Since we need to load this file in order to perform some initialization - why not to load it via composer?
I suggest some changes in `framework/composer.json`:

```json
"autoload": {
  "psr-4": {"yii\\": ""},
  "files": ["Yii.php"]
}
```

**Comment by samdark** [comment] 2015-03-07 10:34
What's the benefit doing so?

**Comment by cebe** [comment] 2015-03-07 12:01
duplicate of #6908.

**Closed by cebe** 2015-03-07 12:02 UTC
