### ISSUE TITLE
blank page after save with upload while redirect 

### ISSUE THREAD

**Issue by m-wardany** [yiisoft/yii2#10139] opened 2015-11-11 15:39 UTC
this issue only appears after pushing to the server and only in the case of uploading files 
no redirect and no data saved , only blank page 
after search I found it's all about php headers , sometimes ob_start() works and sometimes no 
locally I'm working on ubuntu 14.04 and it works fine .

**Comment by samdark** [comment] 2015-11-11 15:43
Can't get steps to reproduce the issue from the info provided.

**Comment by cebe** [comment] 2015-11-11 15:51
Blank page sounds like undisplayed php error. Check your log files.

**Comment by m-wardany** [comment] 2015-11-11 16:06
I have a form included upload file 
upload operation in beforeSave() function 
if no file attached ,  the data saved into data base and the redirect action work properly  
if there is a file attached , the upload operation done properly , but no data saved to the database and then blank page appears 
I checked validate and no errors in model
this issue Only appears in live server but in the local host it works fine 
sorry for bad description I'm trying to make it clear

**Comment by samdark** [comment] 2015-11-11 16:15
Check log file.

**Comment by m-wardany** [comment] 2015-11-12 08:36
nothing in backend/web/error_log file

**Comment by samdark** [comment] 2015-11-12 09:02
How about backend/runtime?

**Comment by m-wardany** [comment] 2015-11-12 14:29
I don't know why but this was the solution :
in backend/web/index.php 
I changed yii_inv to 'dev' instead of 'prod'
defined('YII_ENV') or define('YII_ENV', 'dev');

**Comment by samdark** [comment] 2015-11-12 15:03
It's not a good idea to run your server like that. Anyway, since it's not Yii issue but something about config, I'm closing the ticket.

**Closed by samdark** 2015-11-12 15:03 UTC
Labels: status:need more info
