### ISSUE TITLE
Migration $this->primaryKey()->unsigned() don't work for MySQL!

### ISSUE THREAD

**Issue by Dromok** [yiisoft/yii2#10889] opened 2016-02-17 22:29 UTC
Showed error "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UNSIGNED'".

Because it generated "`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY UNSIGNED" invalid sql.
Need correct sql like this "`id` int(11) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY".

**Comment by MysteryDragon** [comment] 2016-02-18 08:42
+1
Oracle MySQL v5.7.11

**Comment by samdark** [comment] 2016-02-18 09:58
`primaryKey()` uses schema `pk` type which is `int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY`.

**Comment by samdark** [comment] 2016-02-18 09:59
Same as `'id' => 'pk'` in the old syntax.

**Comment by SilverFire** [comment] 2016-02-18 10:02
So you think it's a wontfix?

**Comment by MysteryDragon** [comment] 2016-02-18 10:48
I noticed some mistakes in my solutions:
1. We can't set the AUTO_INCREMENT attribute this ways. Only alterTable or SQL expression can help us here, I guess.
2. "PRIMARY" isn't good name for PRIMARY index. :) It may be blank string or any correct index name but not the "PRIMARY". Or else we'll receive an MySQL exception.
So, to my mind it's quite nice to set this attribute in some other way.

**Comment by df2** [comment] 2016-02-18 15:28
```php
public function unsignedPrimaryKey();
public function unsignedBigPrimaryKey();
```

**Comment by samdark** [comment] 2016-02-18 21:25
How about `charPrimaryKey()`, `stringPrimaryKey()`?

**Comment by MysteryDragon** [comment] 2016-02-19 07:40
Maybe `ColumnSchemaBuilder::autoIncrement()`?
But in this case such method must define some index type.
Or could Yii replace schema parameters, if we extend it by `unsigned()` methods and so on? This is expected behavior of such methods, I guess.

**Comment by df2** [comment] 2016-02-19 09:00
@samdark It makes sense that ```pk()->unsigned()``` would produce a primary key as defined by Yii, but an unsigned version.

This is an argument about a virtual capacity. It doesn't _really_ matter that we're throwing away half our "pool of resources" in this case. There is perhaps an OCD affection that drives one nuts tho, when you could access that "half" by the UNSIGNED modifier.

**Comment by mdmunir** [comment] 2016-02-21 23:14
Its because the name of `primaryKey()` itself. Should be canged to another name like `serial()`, `autoIncrement()` or something else. Then `primaryKey()` use for real `PRIMARY KEY`.
```php
'id' => $this->serial(), // <- int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY

'coa' => $this->char(8)->primaryKey(), // <- char(8) PRIMARY KEY

[
    'order_id' => $this->integer()->notNull(),
    'product_id' => $this->integer()->notNull(),
    ...
    $this->primaryKey(['order_id','product_id']), // <- PRIMARY KEY ([[order_id]], [[product_id]])
]
```

**Comment by cebe** [comment] 2016-02-22 08:53
> Its because the name of primaryKey() itself. Should be canged to another name like serial(), autoIncrement() or something else. Then primaryKey() use for real PRIMARY KEY.

:+1:

**Comment by df2** [comment] 2016-02-22 08:59
See #10921 it's being fixed. Would you like to add to that @mdmunir . See the changes that have been made so far and how you would like to go ahead based on that.

**Closed** 2016-04-28 11:29 UTC
Labels: feature:db, severity:important, type:bug

**Comment by pptyasar** [comment] 2016-11-09 08:21
Is this solved?

**Comment by MysteryDragon** [comment] 2016-11-09 08:30
@pptyasar , yep.

**Comment by pptyasar** [comment] 2016-11-09 09:00
Then how to create pk without Auto Increment

**Comment by MysteryDragon** [comment] 2016-11-09 13:08
@pptyasar , currently (<=v2.0.10):
```
$this->createTable('tableName', [
    'id' => $this->integer()->unsigned()->notNull(),
    // ...
   'PRIMARY KEY ([[id]])',
]);
```
Or add primary key later, see [Migration::addPrimaryKey()](http://www.yiiframework.com/doc-2.0/yii-db-migration.html#addPrimaryKey()-detail)

**Comment by vercotux** [comment] 2017-05-22 04:12
@MysteryDragon 

> Or add primary key later, see Migration::addPrimaryKey()

This is how you do it:

    $this->createTable('tableName', [
        'id' => $this->integer()->unsigned()->notNull(),
        // ...
    ]);
    $this->addPrimaryKey('pk-id', 'tableName', 'id');

**Comment by MysteryDragon** [comment] 2022-07-01 14:21
@Radon8472 if you seek some easy answer, it'll look like
```
$this->createTable('tableName', [
    // ...
    'field' => 'INT AUTO_INCREMENT NOT NULL',
]);
```
I mean you don't have to use schema builder 'cause it produces string at the end.
Same works for other statements like `$this->addColumn(...)`, etc.

Or if you'd like to you can try to extend builder functionality.

**Comment by Radon8472** [comment] 2022-07-02 06:56
> @Radon8472 if you seek some easy answer, it'll look like
> 
> ```
> $this->createTable('tableName', [
>     // ...
>     'field' => 'INT AUTO_INCREMENT NOT NULL',
> ]);
> ```
> 
> I mean you don't have to use schema builder 'cause it produces string at the end. Same works for other statements like `$this->addColumn(...)`, etc.
> 
> Or if you'd like to you can try to extend builder functionality.

Thank you.
I know, that I could write plain sql, but I try to learn how to work with the builder functions, like it was planned by the devs of yii .
But seems that there are some use cases that are hard to handle with the currently implemented methods.

My final solution what usses the builder as far as possible was:

```
$this->createTable('tableName', [
    'id' => $this->integer()->unsigned()->notNull()->append('AUTO_INCREMENT PRIMARY KEY'),
    // ...
]);
```

**Comment by MysteryDragon** [comment] 2022-07-02 08:07
@Radon8472 that's true. Yii 2 isn't meant to be extremely flexible. It's more about simplicity + power together.
If you wanna do it "right way" then it's about implementing your own additional builder methods I believe.
